### ISSUE TITLE
cli: Watcher client favicon should be red on compile errors

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#10]
like how github has (it's yellow here but it's red when there's an error)

<img width="136" alt="Screen Shot 2023-01-02 at 1 45 55 PM" src="https://user-images.githubusercontent.com/3120367/210280029-8398e0f1-5037-4373-9a3f-e6b1df02b2b8.png">

**Comment by sinyo-matu** [comment]
Hi d2 authors.
I want to contribute to this issue.
And I am already done with my work.
You can check it at [add favicon indicator](https://github.com/sinyo-matu/d2/commit/f9dc6e7595428a2da0e8d4f1e7447f519aadbf61).
Is it Ok to open a PR for this issue?

**Comment by alixander** [comment]
oh wow, please do! thanks @sinyo-matu

**Comment by sinyo-matu** [comment]
@alixander Thanks!
Here it is #1240

**Comment by Nepo26** [comment]
Shouldn't this issue be closed @alixander as it was already merged?

**Comment by alixander** [comment]
good point!
