### ISSUE TITLE
Multi-colored text

### ISSUE THREAD

**Issue by Filip-K** [terrastruct/d2#1001]
Hi! I'm trying to create a legend which explains the colors used in my diagram, but I'm a bit at loss with creating colored text that does not overlap. Here's as far as I could get ([link to the playground](https://play.d2lang.com/?l=&script=pJExCsMwDEV3neJfwIV21NC71K3aqRYIDXZL7h5kg5MhW0bD4z_zNJszLMIQVaQ7GuNPQHdchprxMZFCC1EL5HeEmLwC6O2vjLfqgCIKw6U6AVGSkdVdv-kpxcXm0Ha6na-_b4z8sBNz429rAAAA__8%3D&))
![d2](https://user-images.githubusercontent.com/16614296/223767096-93dbda60-2c10-4b84-ba78-1cfb2416dfc2.png)

Close enough, but the legend entries `foo` and `bar` overlap. Any ideas?

**Comment by alixander** [comment]
@Filip-K ah, yeah multiple `near` set to the same constant will overlap.

The way to do this will be to put both items in a container and then set the `near` on just that container. But that's currently a TODO. We'll get to this in the next week or so. https://github.com/terrastruct/d2/issues/848

https://play.d2lang.com/?l=&script=jJExDsIwDEV3n-Ij5iLB6IGJvUsvQKlpK0EipR5aUO6O7KiwMHRM9Oxvvf91zkgmhmhGdcbCeBPgGYcSzeiTSKBMtBjy-ock6Qx4SC-hK8AezTBOGCfoIGjqS73zX_PJaKNqfFY3CSqJAG_tyLjH6NOAC2WozFreHvireL0LyLQuODHaa9q8wK628UyfAAAA__8%3D&

**Comment by Filip-K** [comment]
I see, thanks! The trick with putting a legend into a container is already pretty good, even if it cannot be set `near` yet. Feel free to close this issue now or when #848 is done.

**Comment by alixander** [comment]
great to hear! I'll close this then in favor of that one
