### ISSUE TITLE
elk: about connectors text

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1004]
https://play.d2lang.com/?l=&script=TMo9CgIxFEXh_q3idFZmASncy8ubKwqSQDLiBHHv4k8x5b3n22zjeGJmzq0V77_pqaTIhNfDypBYLyJar9qBJX_uLq7j2--1KjSG9_m3FN3awzyVzNMgDBYD2cveAQAA__8%3D&layout=elk&

**Comment by alixander** [comment]
corners have been removed
