### ISSUE TITLE
icon: (not utf-8) is not exist error

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1018]
windows (using double byte charactors) file system is not utf-8.
ex. japanese = s-jis(cp932)

ok
```
y{
icon:test.svg
}
```

ng
```
z{
icon:テスト.svg 
}
```

"テスト" is utf-8 in d2 source.
but windows file system is not utf-8.

how do i write the d2 source?

**Comment by alixander** [comment]
i don't quite understand this. @nhooyr do you know what he means?

**Comment by nhooyr** [comment]
I think he's trying to open a file with non UTF-8 characters and it's causing issues because windows uses UTF-16.

I'm surprised to see this though, I believe Go automatically translates between on Windows Syscalls.

**Comment by bo-ku-ra** [comment]
Japanese windows is not UTF-16.

c:> echo x--y >テスト.d2
c:> d2 テスト.d2

テ ス ト = 0x8365 0x8365 0x8367 (S-JIS)

**Comment by bo-ku-ra** [comment]
URL encode
file:///C:/D2/%E3%83%86%E3%82%B9%E3%83%88.svg (UTF-16)

ok
```
y{
icon:test.svg
}
```

ng
```
z{
icon: file:///C:/D2/%E3%83%86%E3%82%B9%E3%83%88.svg
}
```

**Comment by alixander** [comment]
i believe this is solved now that D2 supports utf-16 automatically
