### ISSUE TITLE
Links between sql_table fields

### ISSUE THREAD

**Issue by angela-aura** [terrastruct/d2#1037]
We have a use case where we want to document mappings between data tables. In order to do this, we have multiple links between two tables, each starting from one field and going to another.

Currently, the render draws arrows starting from anywhere along the first data table and landing anywhere along the second data table. Ideally, we would like the arrows to start and end from the right fields. We are aware that this might mean the diagram would look more messy, e.g. if the arrows cross.

Here are an example D2 diagram and its render.
[sql_table links example.txt](https://github.com/terrastruct/d2/files/10979995/sql_table.links.example.txt)
![sql_table links example](https://user-images.githubusercontent.com/126801929/225315114-a86f7305-d8e8-4333-8e7c-a6b33da7e865.png)

**Comment by alixander** [comment]
this is a layout engine constraint.

we can't do this in dagre, but we might be able to add in ELK, and i'll look into it.

TALA currently does this.

looks like there's a bug with targeting that name with backslash... 

if i reorder the columns and change the backslack-dot to an underscore:

https://play.d2lang.com/?script=pJGxDoIwEIb3PsUfdklg7OCgL-DgTgpcTCMUPAoJIby7oVIpDC6OvXx3__enVuUVJRLRRXUk5d09I0wCcE0kuleVOUoIQJcS2lhM289JtKxrxWP2pHEWgFH1smZZAEyD7nRj_LtQlh4Nj9l6KBxte7MQLjHde6X_ebWKrenrnNhHD8ShXMtN2Rf2ugpJ3PaDr1cSL644nfHRjLfTHvDFA2hN88Sud3jrEHrEdfkDfgcAAP__&layout=tala&

**Comment by alixander** [comment]
This is done for ELK and that's the best we can do.
