### ISSUE TITLE
cli:browser=0

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1049]
\>d2.exe --watch ```--browser=0``` (#175)

**Comment by bo-ku-ra** [comment]
\>d2.exe ```--color=false``` (#514)

**Comment by alixander** [comment]
@bo-ku-ra i don't think there's a need to add a flag, the coloring mechanism should just handle windows. is it still broken for you?

**Comment by bo-ku-ra** [comment]
[alixander](https://github.com/alixander)
https://github.com/terrastruct/d2/issues/514#issuecomment-1474823107 and https://github.com/terrastruct/d2/issues/514#issuecomment-1474824335 on Windows
