### ISSUE TITLE
syntax: variables

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#105]
E.g. have $vars.light_primary hold the hex code which you reference as background on a bunch of objects

**Comment by alixander** [comment]
<img width="761" alt="Screen Shot 2022-11-22 at 2 37 15 PM" src="https://user-images.githubusercontent.com/3120367/203435495-9e156fb0-be41-4bff-8567-37e3ff992d69.png">

**Comment by wycats** [comment]
@alixander is there a sketch of a design for this? I'm very interested in the idea (I'm switching from mermaid to d2 in the documentation for https://starbeamjs.com/, and the need to represent common concepts like "invalidation" or "output" in a consistent way is the biggest hurdle so far).

I've created a very simplistic preprocessor in my own codebase for style variables, but I'd also be interested in helping with the overall design.
