### ISSUE TITLE
"origami" theme

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1083]
<img width="717" alt="Screen Shot 2023-03-23 at 11 11 33 AM" src="https://user-images.githubusercontent.com/3120367/227343312-e58445fa-412c-493a-8cc5-deb84f5d894f.png">

**Comment by bo-ku-ra** [comment]
origami?

**Comment by alixander** [comment]
yeah just a cool name. if you have suggestions, plz share! @bo-ku-ra 

the purpose here is to have a cool east-asian aesthetic. 

D2 gets quite a lot of usage from chinese/japanese/korean user base 
e.g. https://www.youtube.com/watch?v=TKFNs0z_ShE 
https://github.com/kookmin-sw/capstone-2023-43/blob/2353354ea5ea26348ac3973702907d665672186e/docs/src/SignUpSequence.d2

**Comment by bo-ku-ra** [comment]
as a Japanese, it may seem strange name, but i understand that this is a strategy.
if you think it's cool, it's good.

fyi.
washi is a material of japanese culture
* washi = 和紙
  * 和 = japan, japanese
  * 紙 = paper

origami is japanese culture
* origami = 折り紙
  * 折り = folding
  * 紙 = paper

at first, i thought
origami? not folded anywhere..

**Comment by alixander** [comment]
@bo-ku-ra we thought of washi, but it's not a recognizable world in English. I had to search up what it meant at first. Origami  is much more recognizable and still related to east asian and paper =). appreciate the input!

**Comment by bo-ku-ra** [comment]
yes. i think it is acceptable for japanese, too.
thank you for respecting japanese culture!
