### ISSUE TITLE
cli: favicon should show D2 icon

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1086]
open watch mode with `d2 --watch input.d2`

currently the favicon in the browser is this

<img width="21" alt="Screen Shot 2023-03-23 at 8 14 35 PM" src="https://user-images.githubusercontent.com/3120367/227415267-015daed4-2803-4e3b-a8fe-c2e1501dc2aa.png">

but it should be

<img width="23" alt="Screen Shot 2023-03-23 at 8 14 39 PM" src="https://user-images.githubusercontent.com/3120367/227415278-0a11f9bf-de1d-4905-8e89-85e7731e113f.png">

Use the same favicon as the docs: https://github.com/terrastruct/d2-docs/blob/master/static/img/favicon.ico

**Comment by bo-ku-ra** [comment]
> currently the favicon in the browser is this
> 
> <img alt="Screen Shot 2023-03-23 at 8 14 35 PM" width="21" src="https://user-images.githubusercontent.com/3120367/227415267-015daed4-2803-4e3b-a8fe-c2e1501dc2aa.png">

edge (windows)
![image](https://user-images.githubusercontent.com/121328398/227416958-8d10c3b0-2e6e-4965-b967-a6b6ba343e7e.png)

firefox (windows)
(none)

**Comment by bo-ku-ra** [comment]
https://raw.githubusercontent.com/terrastruct/d2-docs/master/static/img/favicon.ico

sleep talking..  ( you can make favicons from svg files, there's a dark mode switching function in d2.exe.  )
