### ISSUE TITLE
theme color code off for dark_mauve?

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1092]
Something's wrong with the dark theme color coding I think. The paralellogram shape at 2 levels deep has a color clash. 

![Screen Shot 2023-03-26 at 9 08 57 PM](https://user-images.githubusercontent.com/3120367/227838808-2a7363b2-b4de-4d78-bad2-07693460f6c2.png)

### It's fine on other themes

![Screen Shot 2023-03-26 at 9 09 04 PM](https://user-images.githubusercontent.com/3120367/227838686-89740210-7c32-4e32-8254-af681d221741.png)

![Screen Shot 2023-03-26 at 9 09 15 PM](https://user-images.githubusercontent.com/3120367/227838692-a3c71673-2de3-4334-bece-fe34017f4d2b.png)

**Comment by satishkumarsajjan** [comment]
So u want the parallelogram to have different color or mix of some defined colors??

**Comment by alixander** [comment]
it's color coded to something (https://github.com/terrastruct/d2/tree/master/d2themes#color-coding-guide)

I suspect either the color code is wrong for that, or it just wasn't set correctly. it should be distinct
