### ISSUE TITLE
Label Padding Does Not Account for Bold on Horizontal Paths

### ISSUE THREAD

**Issue by bonesmoses** [terrastruct/d2#1099]
In cases where a label is applied to a horizontal path segment and a bold font is applied, padding does not increase to account for the larger text.

The following code illustrates the issue:

```yaml
direction: right

x -> y: sync

y -> z: sync {
  style {
    bold: true
  }
}
```

![no-padding](https://user-images.githubusercontent.com/719860/228110853-9bd5327f-f3fe-4c95-9bd9-e32bef45afd2.png)

Note that the second label is much harder to read despite the heavier font due to its intersection with the line segment itself.

**Comment by alixander** [comment]
nice find!

https://play.d2lang.com/?script=gseFlUIRKGC4uCoUdO0UKq0Uiivzkrm4KkG8KghPoZpLQQFsrRWYqaAAinUrhZKi0lQuBYVarlouQAAAAP__&layout=dagre&
