### ISSUE TITLE
Unable to compile d2 template when markdown contains pipe inside

### ISSUE THREAD

**Issue by stej** [terrastruct/d2#1127]
It looks like the markdown parser doesn't respect the escape character for pipe.

Example:
```
test: |md
  # What about pipes

  Will escaping \| work?
|

```

Result:
```
4:19: unexpected text after md block string
5:1: block string must be terminated with |
```

Additional info.
Tried `\|`, `` `| ``, `||`, `/|`, nothing worked.

**Comment by alixander** [comment]
ah, it's this: https://d2lang.com/tour/text#advanced-block-strings

this has come up a few times, maybe we should include that link when the error "unexpected text after md block string" shows up? @nhooyr

**Comment by DUPLESSIS46** [comment]
Hulk2Lit_T🔝P_Spin_Hat

**Comment by stej** [comment]
Any hint in error message is welcome :)
Honestly I tried to find the solution, but I didn't find that as I thought it's markdown specific.
