### ISSUE TITLE
Bug: Sequence diagram - multi-row self referential messages overlap arrow

### ISSUE THREAD

**Issue by alexstoick** [terrastruct/d2#1143]
Screenshot of the issue: 
![Screenshot2023-04-05at14 02 58](https://user-images.githubusercontent.com/1664100/230508492-b2748ec5-2276-4204-8672-55994bc4172e.png)

This issue stems from the fact that the arrow size is hardcoded here:
https://github.com/alexstoick/d2/blob/master/d2layouts/d2sequence/sequence_diagram.go#L561

To resolve we could simply update the value of `endY`, so that it would be computed based on how long the self-referential message is.
_However_, changing just the `endY` will potentially end up with overlapping the arrow with the next message due to the fact that `yStep` is hardcoded based on the longest current message in the _whole_ sequence diagram. There is a `TODO` note here: https://github.com/alexstoick/d2/blob/master/d2layouts/d2sequence/sequence_diagram.go#L164

Potential proposed solution would be to line [561](https://github.com/alexstoick/d2/blob/master/d2layouts/d2sequence/sequence_diagram.go#L561) update:

`endY := startY + float64(message.LabelDimensions.Height)*1.5` and then further down on line [576](https://github.com/alexstoick/d2/blob/master/d2layouts/d2sequence/sequence_diagram.go#L576) to update to:
`messageOffset += float64(message.LabelDimensions.Height) + MIN_MESSAGE_DISTANCE*1.5`

With these changes the diagram would look like:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1664100/230509512-1617e66a-38eb-49ad-82b5-427e7770b5a1.png">

---

It would be great to tackle the removal of the `yStep` as a whole and adapt individual `yStep` calculations - but that can be raised as a separate issue.

**Comment by alixander** [comment]
i don't know enough about how the code will affect everything. For this type of bug, I'd review by looking at the test changes and reason backwards to the fix of why it works. Your solution looks promising though, thanks for doing the legwork on that @alexstoick . I'm for it if you wanna open a PR with that as a test

**Comment by alixander** [comment]
Long delay, but that solution was it, thanks again @alexstoick
