### ISSUE TITLE
support edges within grid diagrams

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2#1145]
currently not supported since there is no edge routing mechanism for the grid layout

**Comment by alixander** [comment]
<img width="716" alt="Screen Shot 2023-04-09 at 9 28 14 AM" src="https://user-images.githubusercontent.com/3120367/230784604-b567d266-7506-45ee-8d94-11649b110357.png">

what if we only allow edges for adjacent cells? this could be easy to do and cover the vast majority of desired edges in grid diagrams

**Comment by alixander** [comment]
<img width="575" alt="Screen Shot 2023-04-11 at 7 16 39 AM" src="https://user-images.githubusercontent.com/3120367/231191786-354803a7-2689-4126-ab6f-802e37bacbd2.png">

source: https://txt.cohere.ai/generative-ai-part-5/

**Comment by alixander** [comment]
![Screen Shot 2023-08-20 at 11 08 27 PM](https://github.com/terrastruct/d2/assets/3120367/9e4ad976-be83-4f23-ada3-e285dd3174cc)
