### ISSUE TITLE
customize gap sizes in grid diagram

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2#1146]
currently there is a constant gap size of 40 between rows and columns, but this should be user-configurable. maybe `grid-row-gap`:  and `grid-column-gap`

**Comment by soma-m** [comment]
@gavin-ts Good idea 👍🏽 

Can we also add `grid-gap` as a convenience feature for setting both `grid-row-gap` and `grid-column-gap` at the same time.

**Comment by gavin-ts** [comment]
> @gavin-ts Good idea 👍🏽
> 
> Can we also add `grid-gap` as a convenience feature for setting both `grid-row-gap` and `grid-column-gap` at the same time?

sounds like a good idea to me, I imagine that would be the more common usage
