### ISSUE TITLE
shadow is cut off when 0 padding

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1154]
```
direction: right
classes: {
  load balancer: {
    label: load\nbalancer
    width: 34
    height: 200
    style: {
      stroke-width: 0
      fill: "#44C7B1"
      shadow: true
      border-radius: 5
    }
  }
  unhealthy: {
    style: {
      fill: "#FE7070"
      stroke: "#F69E03"
    }
  }
}

web traffic -> web lb
web lb.class: load balancer

web lb -> api1
web lb -> api2
web lb -> api3

api2.class: unhealthy

api1 -> cache lb
api3 -> cache lb

cache lb.class: load balancer
```

the right side is cut off

<img width="684" alt="Screen Shot 2023-04-07 at 9 34 37 PM" src="https://user-images.githubusercontent.com/3120367/230703281-5d62160b-3e81-4e17-848e-1e9e975c50bd.png">

**Comment by yhorbachov** [comment]
Cannot reproduce.
I run locally with `go run main.go --watch input.d2` and it gives me this picture:
![image](https://user-images.githubusercontent.com/1104209/235689645-3054a9c1-3832-4737-97c6-f92bd130b382.png)

**Comment by alixander** [comment]
my fault for the lack of reproducible steps here. By 0 padding i mean with the flag `--pad 0`. Can you try that @yhorbachov ?
