### ISSUE TITLE
The content is not fully displayed when I used this `Markdown text` template.

### ISSUE THREAD

**Issue by NumberCode** [terrastruct/d2#1162]
Hi, when I using this `Markdown text` template in [Playground](https://play.d2lang.com/?script=TNEhDgJBDEBR31P8BM0FcEiO0dDZQJhpSTsExB6ejFv31Tev_d5dXRffhX2YwIkbd3UsWPuWJQJn-rNmHUrg6kbMR0s8cmhnaL4svk7Nz7bJLv8AAAD__w%3D%3D&layout=dagre&theme=0&sketch=0&) website, the `And other normal markdown stuff` is not display here, I'm not sure this is a bug?

<img width="415" alt="image" src="https://user-images.githubusercontent.com/12987627/230752998-46616547-6550-48f2-a041-52b00c1c68cc.png">

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/12987627/230752985-34321c77-acff-497f-975e-6968b8eb64b3.png">

**Comment by alixander** [comment]
oh strange, it looks like it works in chrome but not firefox or safari. can you confirm you're on firefox or safari? thank for reporting @NumberCode

**Comment by alixander** [comment]
it's definitely something to do with fonts, but i don't think it's to do with blocking. i can reproduce it in a private browsing window on firefox (no extensions)

**Comment by NumberCode** [comment]
@alixander 
Yeah, I'm using Safari on macOS.

**Comment by alixander** [comment]
fixed now. deployed on playground: https://play.d2lang.com/?script=TNEhDgJBDEBR31P8BM0FcEiO0dCZQJhpSTsExB6erFv31Tev_d5DXXe-C9s0gRM37upYsO9blgicGc9adSiBqxuxHi3xyKmDqfmy-Dq1Pr132eQfAAD__w%3D%3D&layout=dagre&theme=0&sketch=0&

will be in next release, thanks again

**Comment by gavin-ts** [comment]
I'm seeing what looks like a cached response (old svg with old styling) on the original prompt specifically, but if I change it to be slightly different (e.g. a few more newlines at the end) it has the updated svg. I assume this will fix itself soon
