### ISSUE TITLE
How to call the method by async to get the svg result when I add some remote images?

### ISSUE THREAD

**Issue by NumberCode** [terrastruct/d2#1163]
Hi, I tried to use d2 in my project(non go), but seems the image didn't  download and render when I got this svg, so I want to know how to use this `Render()` method by async?

```
server: {
  shape: image
  icon: https://icons.terrastruct.com/tech/022-server.svg
}
github: {
  shape: image
  icon: https://icons.terrastruct.com/dev/github.svg
}

server -> github

```

![1681025890](https://user-images.githubusercontent.com/12987627/230760774-c3497a2a-7483-4ead-8c21-75a7f0c2c55e.svg)

**Comment by alixander** [comment]
apologies for the delay @NumberCode , did you find your answer?

**Comment by NumberCode** [comment]
Yeah, it's my network incoming's issue, solved now, thanks.
