### ISSUE TITLE
Recursive classes

### ISSUE THREAD

**Issue by HugoVG** [terrastruct/d2#1165]
in the default implementation you have the normal theme
![image](https://user-images.githubusercontent.com/64896329/230766466-b972a059-1ee7-4c7c-ab07-f4dd9c6160b4.png)
which is
depth 1: #e3e9fd
depth 2: #edf0fd
depth 3: #f7f8fe
depth ....

doing this in the current classes implementation it would be something along the lines of
using classes right now it would be 
class 1: stroke #e3e9fd
class 2: stroke  #edf0fd
to get the same effect

your d2 fill will look like 
```d2
PC: PC Host {
  Consumers: {
    Heartbeat: {
      class: PCClass
    }
    StartApp: Start App {
      class: PCClass
    }

    StopApp: Stop App {
      class: PCClass
    }
    MuteDiscord: Mute Discord {
      class: PCClass
    }
    class: PCClassEven
  }
  Publishers: {
    Heartbeat: {
      class: PCClass
    }
    class: PCClassEven
  }
  Files.class: PCClassEven
  class: PCClass
}
```

it isn't very pleasant to have to specify every single container/object with the class

it would be better to be able to have a ``recursive`` keyword inside classes
so you would have 
```d2
classes: {
  PCClass: {
      style: {
        fill: lightblue
        shadow: true
        stroke: darkblue
        3d: false
      }
      recursive: true
    }
}
```

and being able to supply an array of colours when it is recursive

```d2
classes: {
  PCClass: {
      style: {
        fill: lightblue, "#8fcadd"
        shadow: true
        stroke: darkblue
        3d: false
      }
      recursive: true
    }
}
```
in this implemantion it should look through
depth 1: style[colour % 2] // so we have 0, 1 in this case "lightblue" 
depth 2: style[colour % 2] // so we have 0, 1 in this case "#8fcadd" 
depth 3: style[colour % 2] // so we have 0, 1 in this case "lightblue" 
depth 4: style[colour % 2] // so we have 0, 1 in this case "#8fcadd" 

you could supply an amount of colour to use 
let's say we put 
fill: #cacfd6, #D6E5E3, #9FD8CB, #517664, #2D3319
and stroke to the same array 
stroke: #cacfd6, #D6E5E3, #9FD8CB, #517664, #2D3319
it would keep track of the depth and supply the fill with the length of the array

```go
func getColourByDepth(depth int, colourarray string[]) string {
   return colourarray[depth % colourarray.Length];
}
```

placing a class on a child/descendant object that has the recursive keyword will overide the childeren of that child 

## What does this benefit?

- being able to quickly distinguish different types of containers
   - for example you have an application that has multiple microservices that go very indepth, you can assign them different colours so they are in their same "theme"
- less writing

**Comment by smheidrich** [comment]
I keep having the same issue and opened a feature request for another potential way to solve this (using themes) at https://github.com/terrastruct/d2/issues/2124.

I would be happy with either solution, although I find the array syntax and implicit modulo a bit confusing.

A different idea might be to allow specifying a `child` class definition under a class definition, e.g.:

```d2
classes: {
  PCClass: {
      style: {
        fill: lightblue
        shadow: true
        stroke: darkblue
        3d: false
      }
      child: {
        style: {
          fill: "#8fcadd"
        }
        child: {
          ...
        }
      }
    }
}
```

Although admittedly that would look bad with deeper nesting and make the modulo feature you propose impossible to implement, so I don't know...

**Comment by alixander** [comment]
This is essentially the same ask as https://github.com/terrastruct/d2/issues/2124

I think the cleanest solution is just overriding global variables at each container level. In the other issue, that's the whole theme id. In this, it'd be theme-overrides. (https://github.com/terrastruct/d2/issues/2124#issuecomment-2381022296)
