### ISSUE TITLE
Incorrect width in unicode edge case (map emoji)

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1166]
https://play.d2lang.com/?l=&script=vJW_asJQFMb3-xSH7IodutyCT-JSrJRCsRDaSQJpLhakKgr-SbE0g1BIxULrUElLlr6JJxqy5RFK7k3SRJNu6SI5J8d8v_N95rrTDNe0KLQIwHY22-mGO2AUpI3eRlXd6O1as9aMCwlafHcK9Qu5ftk4AU5YDpKjcCWfNs_jnlhmv_ubJQW5caYQhRBkE2QLZE8Cw7G6hxgFKAdKo6yFo48id3Ys1fl8cKzQemfdSZL8g-VD1F5Qi5JvL5PyaQJ-WRiJ25l5y5Hbv98a_cgLlgWTvizKlhEyE9k4IlGTJMVoijcQSlWI34OgiH8g4k4YV1AkHRM3Q-ig8OweQe0Z2ReyJbJV1PPsHpRKgNorsjmyRTl4JFshu0NtTqEl-KK_AwrX8k1DIdnjXDShkft1LlqFrX27e-yVnfXEHXcpfE-j-fgUp3BUqeSYtO_oQYsfoxSOFUKEEgXf0N94glk6PFiBIvnG1JKycXg4ns2fNnjPm0n74BuDj_zJ0MtgbGj-hZfOxjfMXHmF_AQAAP__&layout=dagre&

![image](https://user-images.githubusercontent.com/121328398/230779211-98a3b1bb-60d6-4fee-ba07-49ce7a27f510.png)

**Comment by alixander** [comment]
beautiful diagram hahah.

are you talking about this emoji? it renders like this for me. perhaps it's different on each OS:

<img width="273" alt="Screen Shot 2023-04-09 at 7 49 27 AM" src="https://user-images.githubusercontent.com/3120367/230779753-dd59934f-03fc-4e05-8c4f-a45a86090968.png">

**Comment by bo-ku-ra** [comment]
yes. i am slow and unuseful but could improve it  on v.4.0 by myself.

https://play.d2lang.com/?l=&script=jFTPi9NQEL7nrxjqOSG7uJcXCLiusDfF815kt4ggFYJ6CQsxjwqL22UXuttIxRwKQiwVbA-WKLn4n3TShtzyJ8i8_PC1ScRDSzJv5vu-mS_z7p3tw1tdu6_pSmGurQAcHTJbNMng9IV1-rJrCCUaOcTglfWs97wM5Zp3gn8dY2B1zwxBxfYO9HMF4OHxg6fMlhLJRwZ7um7Q8fHjJ49ajiHHgf0ilX4KwMb1kyAk3evxeOP5yTVnnZXXR8dZef2T3kmveunYokt2dCgDIL9DPkX-mTDi8LKGsVMWh8MGmvLvX0xx6MQ_P8ahUBsvLySY_1B5g-5XdPNO-zOpdrtcPLbCJBfjdDZMrj6s_atcBW9A2n5sEzREHiC_zWEcCaa5oPJKNauRq2Y1E4oWLaqmLJMOCirVTKMBcbtfkP9CPkO-KGNpNFBVdL8hnyCfagTGF8jfozspvqfyumPw2nrTFdKa81VTJmivJkpzHb3bfBpo8fIuub1kv0fNH29tM2gxYGuJahFxQzA4MKQJ5mws873vNPd8zrRThnBBaOhk_igsPaCFkl1II6q-nttS6fnOSCnhRz2hGBXL_JugTi4PkGV-MG8RoPwJAAD__w%3D%3D&

i want write

classes{
DB:{shape: circle;style.fill: orange;style.stroke: orange;style.font-color: red;width:150}
CHAR:{style.font-size: 100;}
HOPE:{```class: CHAR;``` width: 200;}
}
