### ISSUE TITLE
export: PDF

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#120]
straightforward with gopdf, will dedicate time to do it when there's enough demand

**Comment by alixander** [comment]
this will complement scenarios/layers very well. PDF is unique in multi-page support. We should work on this when scenarios/layers is ready

**Comment by TSSlade** [comment]
Is this the current state of the software w.r.t. PDF export? (To wit: not currently supported, but on the roadmap, pending completion of the scenarios/layers bit?)

Current best approach to PDFing presumably just pandoc'ing our SVG output, or something?

**Comment by alixander** [comment]
yes. unless someone else picks up the task before then, our plan is to implement support for it when that part is done.
