### ISSUE TITLE
How to convert the svg file to png? Sorry, I didn't not found this method, could you share with me?

### ISSUE THREAD

**Issue by NumberCode** [terrastruct/d2#1208]

**Comment by bo-ku-ra** [comment]
[inkscape](https://inkscape.org/)

d2
c:>d2.exe foobar.d2 (foobar.svg)
c:>d2.exe foobar.d2 foobar.png
c:>d2.exe foobar.d2 foobar.pdf

**Comment by NumberCode** [comment]
Sorry, I have no windows enviroment, and just want to use golang to implement this logic to conver some svg files to png.

**Comment by bo-ku-ra** [comment]
https://github.com/gographics/imagick/blob/master/README.md

**Comment by alixander** [comment]
you don't convert svg to png -- D2 isn't an image converting library.

But you can output PNG directly from a `.d2` file: https://d2lang.com/tour/exports/

**Comment by NumberCode** [comment]
Thanks so much! I will try again later.

**Comment by bo-ku-ra** [comment]
@alixander 
it seems that d2 is the image converter. 

foobar.svg (embeded d2 source:https://github.com/terrastruct/d2/issues/1000#issue-1615066981)

c:>d2.exe foobar.svg foobar.png
