### ISSUE TITLE
Diamond shape change default bg color

### ISSUE THREAD

**Issue by rkgarcia** [terrastruct/d2#1210]
We have an issue creating a diagram without styles, when we use the diamond shape the color is changed to gray

![imagen](https://user-images.githubusercontent.com/1530429/232338576-d1ea4d76-8ae2-475b-81ef-4d7fe1fe9ead.png)

```d2
ll: Proxy {
    shape: square
}
if: It works? {
    shape: diamond
}
```

My current version:
```bash
$ d2 --version
v0.4.0-HEAD
```

**Comment by alixander** [comment]
hey @rkgarcia , it's not a bug. Some shapes just get a different default color according to the theme. https://github.com/terrastruct/d2/tree/master/d2themes#color-coding-guide

**Comment by rkgarcia** [comment]
@alixander thanks for your support! You have a really good project here!
