### ISSUE TITLE
array for class

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1218]
please see this d2 source.
https://play.d2lang.com/?l=&script=bJZLbuMwEET3PEXgWWfA5p_KaoAI2TmAbzCL5BKG7h5YthTK9bYFkdQrdjdrd3Oy4ka7Jwtus3zyzj2K4-rOn-d5uq5_-fdh2PTi3xZ3md8f8p1pOv35-vLe-9Pby12_lcCgLu7jMs_n50W1lK6LNnVxn5d_54_5edX3939YtamLW5yz8mrT6XRdUaYbx3LTAmgRtPSrXeb3VcoqFZWqSk2lDkeaJ5EgTCicZcDNgJtH3PvvZKXNSpuVNittVto80m7SCLtrBhqgJkBNgJpG1LX6VjGRmEkcgO91uKoV1UYbdPwULjrRRSekj0AfR_rt-Dji78dH4o8j__ApGRDRgEgGRDQgHgwYZWMZTAhgQiATApoQyIRARRDQg4AehNGDQe20LXoQ2INw8GCTnRm4YOSCUSfYaMJ-lmEpGNpgaINRKRi5YAcXBtVQhTrw4ICHUeBhyHvk98jvkd8jv8cy8NgLnuvA0zjw5EBXA7ryd7j_Dj3QZez3EXz_qoKml971mesw_DrAdmJtytqg2hvANoBtAtsAtgFsk0euQXk3qu5Gxd2Itr7qhxVwK-BWwK2CW-VFr_KgV0GtgFoJtRJqPaA-ROcOYW1rg0Na-xUVV-NaoS7WvKZxrVDzFkkwhYALTu_CwzsTcSbiTE-YZjaNbJrYNLBpXtO4lnFIZaTNTJuINhFtknyaBDUJahLUJKhJUJOgJg2mCTkTc0I4izqOozBGYYzCeIhj20ZVpWfKKJRRKSMMYYxekLwoeAVoU0pdh9C1bSecQTkPYWuTdDIFatRAkylgwIAhjAmLAhaFTMU1xTXFNcXFSIWJCgMVDeKfAAAA__8%3D&

 i want to be able to write like this
```
#array
(
16-4,
16-5,
16-6,
16-7,
16-8,
15-3,
15-4,
15-5,
15-6,
15-7,
15-8,
15-9,
15-10,
15-11,
9-5,
8-5,
8-8,
7-5,
7-6,
7-7,
7-8,
6-4,
6-6,
6-7,
6-9,
5-4,
5-5,
5-6,
5-7,
5-8,
5-9,
4-3,
4-4,
4-5,
4-6,
4-7,
4-8,
4-9,
4-10,
3-3,
3-4,
3-5,
3-8,
3-9,
3-10
):"" {class:RED}
```

**Comment by bo-ku-ra** [comment]
bonus (d2 v0.4.1)
![d2_mario-run](https://user-images.githubusercontent.com/121328398/232710675-e4f0aa7b-2c55-4d4e-beb9-5f1c1bb02155.svg)

**Comment by alixander** [comment]
![giphy (4)](https://user-images.githubusercontent.com/3120367/232851571-5204ad56-d0ce-4293-9b5d-e79c21c06207.gif)

**Comment by alixander** [comment]
can i get the source code for that hahah

**Comment by bo-ku-ra** [comment]
https://github.com/terrastruct/d2/issues/1000#issuecomment-1511161790

**Comment by bo-ku-ra** [comment]
d2.exe (windows)

---

\> d2 d2_mario-run.d2 d2_mario-run.gif

[31merr[0m: bad usage: ```-animate-interval``` must be greater than 0 for .gif outputs.
[31merr[0m: You provided: 0
[31merr[0m: Run with --help to see usage.

correct : ```--animate-interval```

---

\>d2 --animate-interval=120 d2_mario-run.d2 d2_mario-run.gif
(no message & don't output gif-file) 

---

\>d2 --animate-interval=120 d2_mario-run.d2 d2_mario-run.svg
[32msuccess[0m: successfully compiled d2_mario-run.d2 to d2_mario-run.svg in 181.8273ms
ok

---

\>d2 d2_mario-run.d2 d2_mario-run.pdf
success: successfully compiled d2_mario-run.d2 to d2_mario-run.pdf in 2.2247553s
ok (also ansi escape sequences)
