### ISSUE TITLE
I was told to share this error link

### ISSUE THREAD

**Issue by moshethebeadle** [terrastruct/d2#1220]
https://play.d2lang.com/?script=nFKxrhMxEOz3K0ZKnYYOF0hHTidoOAkHpaGxzpuLpYt9so0CIvl3tI5zAV7ee9IrvTPj2dnd7PLECh9NcgM2v4aJ8ZsAGYpCDvNaxkZAia8gTvKSHlVhAsu2FN69LxW5NYUcf3B5Lu5L7UIXouWyFGw4eSL-OU_Gm2vpfLQErEBnol6h3--pU-jcNFGjFRproYOZqVFoRpdNZmoVWrlb0gp6dp6ox_oDOoVviSO20Y0jx4TvHjqbmBe4vLB1R44Cds67dOBEK3SVIb53wpeQ8ZXNcGBLN8bOZI74VG5SOMbb11TNU1WI_4n-FWiFzwkGO5MOgpaFUaNrD23wLOXGWufHklNGVGM8sLv9fme84N7WOW6MH3hKf_lXtO6hyqWZBXosbAXVdWtI7FMotj5gCn7kWGpcFKfSuhWm8yPpZ6QpS4AqK5ortX-7S3-9JuQSy0qsPwEAAP__&layout=tala&

**Comment by bo-ku-ra** [comment]
ok
https://play.d2lang.com/?script=quBKrSjIScxLBEWxlUJNbgqXgkKMMlcNFyAAAP__&layout=tala&

ng
https://play.d2lang.com/?script=quBKrSjIScxLBEWxlUJNbgqXgoIyVw0XIAAA__8%3D&layout=tala&

**Comment by alixander** [comment]
seems it's tala only

**Comment by gavin-ts** [comment]
this looks like a bug with an empty markdown render, also seeing strange results in dagre and elk. fixing

https://play.d2lang.com/?script=SuRKslKoyU3h4uKq4UrmSuFKVNC1U0gCEclcgAAAAP__&layout=dagre&
