### ISSUE TITLE
Panic when `class` used improperly

### ISSUE THREAD

**Issue by murphyke** [terrastruct/d2#1222]
This will cause a panic: `myobj.class.style.stroke-dash: 3`

For comparison, `myobj.subobj.style.stroke-dash: 3` correctly creates subobj within myobj.

But ... `myobj.style.style.stroke-dash: 3` seems to just ignore the extra `style`. I would expect that to generate a parsing error.

**Comment by alixander** [comment]
appreciate the report @murphyke ! fixed and will be in the next release
