### ISSUE TITLE
`font-color` should apply to markdown

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1229]
```
c: |md
  colored
| {
  style.font-color: blue
}
```

**Comment by parthvnp** [comment]
Happy to work on this issue!

**Comment by bo-ku-ra** [comment]
"colo" = blue
https://play.d2lang.com/?l=&script=SrZSqMlN4VJQAMWAjZu_XwiYVWSrpOzmZmBgYKBkV5SaYqMPkrHjqlGo5lJQALtQDxFvVgpJOaWpXLVcgAAAAP__&

**Comment by alixander** [comment]
hi @parthvnp were you still interested in trying this? will assign to you if so, otherwise, no worries!

**Comment by parthvnp** [comment]
@alixander Please assign this issue to me as I would like to contribute a fix.

**Comment by alixander** [comment]
@parthvnp all yours!
