### ISSUE TITLE
Allow custom fonts

### ISSUE THREAD

**Issue by VladKopanev** [terrastruct/d2#1233]
I want to be able to configure my custom font. 
If the font is not found, I want the tool to use the default font.

**Comment by alixander** [comment]
You can do it =)

https://d2lang.com/tour/fonts/

**Comment by VladKopanev** [comment]
Ohh, I was looking at the old version!! Sorry for disturbing you!

**Comment by alixander** [comment]
not at all, let me know if you make any cool diagrams in public!
