### ISSUE TITLE
[feature request] container with text in it

### ISSUE THREAD

**Issue by bokunodev** [terrastruct/d2#1241]
is it possible to create a box with text in it? and maybe style the text.
like left/right/justify alignment, monospace font and colour.
also add text box in a relation arrow. 
something like a code block, example bellow.
![tmp](https://user-images.githubusercontent.com/54968427/233795434-f08c1e41-0eb0-432d-bab4-8036f372df7f.png)

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=vJLBysIwEITv-xTD3vPTX_CyAaG-SdoEFatCEKSkeXfZxmpz8eglhIHMTvabN16Juk1LbZoD_H2wSDe4_mxR9JJXYvCLomDlcTzdg109VXyC_6Z5iVXdBJvGZtr_cFZ_80GYU23dj-5aeQ-6hUN04xcrao1RO2N2yw9WcAVbW82A5s80J0iE0hmZLp6QAALYsXDHes96TImQKdMzAAD__w%3D%3D&

and  #1167
