### ISSUE TITLE
Fonts sometimes have an incorrect cmap subtable

### ISSUE THREAD

**Issue by eiswind** [terrastruct/d2#1252]
I found that when fonts are embedded, they are not always embedded the same way.
Sometimes the font is correct, sometimes it has an incorrect cmap subtable.

Browsers seem to ignore that but other tools I use to render the svg cannot handle that.

I'll attach two files, one (injection) has the font correctly, the other (boot)  one is broken.

![01_boot_d2](https://user-images.githubusercontent.com/1238044/234815306-d902f3eb-58f9-4ef4-9d16-ebda12ebe5dd.svg)
![01_injection_d2](https://user-images.githubusercontent.com/1238044/234815331-054e72c2-cfbc-4fa6-9c24-0c75dcb66106.svg)

**Comment by mikeday** [comment]
The issue here appears to be that the cmap subtable (format 4) has an odd length count?

**Comment by alixander** [comment]
oh interestingg, we do roll out own cmap font thing for optimized subsetting. very possible to have missed something. 

will test with the "Allsorts" that @mikeday mentioned in his other issue.

> other tools I use to render the svg cannot handle that

@eiswind what's a tool we can test on to confirm we have the right fix?

**Comment by mikeday** [comment]
I think it might be this line 611 of `generateCMAPTable` in utf8fontfile.go in gofpdf:
```go
length := 16 + (8 * segCount) + (numSymbols + 1)
```
The `length` field is the size in bytes of the `cmap` format 4 subtable as defined here:

https://learn.microsoft.com/en-us/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values

Since this subtable is entirely comprised of 16-bit values it is impossible for it to be odd; the `16 + (8 * segCount)` part is correct but the `numSymbols + 1` is highly suspect!

**Comment by mikeday** [comment]
It appears that the original PHP fpdf does not have this bug, it just takes the length of the subtable in bytes directly:
```php
$data .= pack('nnn', 4, 6+strlen($cmap), 0); // format, length, language
```

**Comment by eiswind** [comment]
@alixander please try prince xml https://www.princexml.com/
@mikeday thanks for your assistance!

**Comment by eiswind** [comment]
Are there chances that this will get fixed? Sadly I don't get what going on there, so I can't provide a patch.

**Comment by alixander** [comment]
@berniexie can you look into this on Tuesday please?

**Comment by berniexie** [comment]
@eiswind can you give me the exact d2 code of the failed Spring Boot example

**Comment by alixander** [comment]
can you not reproduce with some simple "asdf" text? @berniexie

**Comment by berniexie** [comment]
@alixander not with the latest version of d2. I suspect the issue may already fixed but I wanted to confirm with the exact case that can generate an invalid subset.

**Comment by alixander** [comment]
how would it have been fixed? i don't think there's any PR that touched this part since the issue was created

**Comment by berniexie** [comment]
Nevermind. I was able to reproduce the issue with an example.
