### ISSUE TITLE
making layers on watch-mode

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1262]
i want to write x.d2 y.d2 and z.d2 on watch-mode.

z.d2
```
x{
icon:"x.svg"
}

layers:{
 1{
  y{
  icon:"y.svg"
  }
 }
}
```

i can write x.d2 on watch-mode and conpile it.
next
i can write y.d2 on watch-mode and conpile it.
next
i can write z.d2 on watch-mode.

# new feature

\>d2 -w ```--animate-interval=600``` z.d2

z.d2
```
x{
import:"x.d2" #<------------------------------not svg
}

layers:{
 1{
  y{
  import:"y.d2" #<------------------------------not svg
  }
 }
}
```

**Comment by alixander** [comment]
thanks @bo-ku-ra , it's on our radar! https://github.com/terrastruct/d2/issues/1176
