### ISSUE TITLE
elk layout seems to misplace edges on the playgroung

### ISSUE THREAD

**Issue by ymolists** [terrastruct/d2#1267]
I have not confirmed if this is an actual issue with the latest code. Howver, when i do the below code and select elk layout on the playground this seems to be a bug somewhere.

My expectation was that edges will be properly drawn. The TALA layout does not seem to be affected by this issue.

```
main: {
  x -> y
  y <- z
}

root: {
  x -> y
  y <- z
}
```

output:

![image](https://user-images.githubusercontent.com/6591993/235331604-f2b7ee39-ae81-4e6b-8df3-74c77da5410f.png)

**Comment by alixander** [comment]
oh good find, strange. will look into it asap, thanks @ymolists
