### ISSUE TITLE
Opening D2 SVGs with Inkscape and Krita 

### ISSUE THREAD

**Issue by yuce** [terrastruct/d2#1273]
Hello,

I'm trying to convert the "hello world" sample with D2 (compiled from master; and using release 0.4.1) and opening it with Inkscape / Krita:
```
$ cat hello.d2 
x -> y: hello world 
$ d2 hello.d2 hello.svg
success: successfully compiled hello.d2 to hello.svg in 43.594504m
```
Firefox and Chrome can display the generated SVG just fine, but Krita and Inkscape cannot. This is on Kubuntu 23.04, Krita 5.1.5, Inkscape 1.2. I couldn't find an open/closed issue in this repo. Did anyone encounter this issue before?
 
I've attached the generated SVG, screenshots from how Krita and Inkscape displays the generated SVG and Inkscape output.

* Krita: ![image](https://user-images.githubusercontent.com/513114/235362394-7962d167-07a5-45a5-b641-c242e0c100f4.png)
* Inkscape: 
![image](https://user-images.githubusercontent.com/513114/235362470-e1d28541-ac47-49a6-b1c9-9bdbf03fd95d.png)
* Inkscape log: https://gist.github.com/yuce/856b56fb92a275bb549ba0281b34d918
* Generated SVG: 
![hello](https://user-images.githubusercontent.com/513114/235363388-63179bf8-1964-4ac1-ae0f-ea910f9f2f17.svg)

**Comment by alixander** [comment]
yeah unfortunately the issue is in svg renderers that don't support CSS: https://d2lang.com/tour/troubleshoot/#markdown-svgs-wont-render-in-certain-svg-viewers

**Comment by alixander** [comment]
too tough to support everything we want to do with pure CSS-less SVG, so I'll close as it's unlikely to change. but useful to have this in the history so others can find it in github, thanks @yuce !

**Comment by yuce** [comment]
@alixander  Thanks for the explanation.

**Comment by Craeckie** [comment]
The svg generated by d2 doesn't follow the svg specification, that's why inkscape can't open it correctly. You can convert all the shapes to paths with rsvg-convert:
`rsvg-convert -f svg -o output.svg input.svg`

Inkscape can open it and it seems to work for everything except markdown content. You can also use rsvg-convert to convert to a vectorized pdf.

**Comment by yuce** [comment]
@Craeckie Thanks for this information.
