### ISSUE TITLE
Bug: --animate-interval not generating svg for steps

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#1280]
I'm testing out `--animate-interval` from this [doc](https://d2lang.com/tour/composition-formats) and am finding that it is silently dying and not generating the animated svg at all.

/tmp/test.d2:
```d2
steps: {
  1: {
    code
  }
  2: {
    code -> git commit
  }
  3: {
    git commit -> git push
  }
}
```
```shell
$ d2 --animate-interval 1200 /tmp/test.d2 /tmp/test.svg
<no output>
```
```
$ ls -l /tmp/test.svg
ls: /tmp/test.svg: No such file or directory
```
If I remove the `--animate-interval 1200` switch then it generates 3 svgs:
```shell
$ d2 /tmp/test.d2 /tmp/test.svg
success: successfully compiled /tmp/test.d2 to /tmp/test/1.svg in 126.243441ms
success: successfully compiled /tmp/test.d2 to /tmp/test/2.svg in 113.501622ms
success: successfully compiled /tmp/test.d2 to /tmp/test/3.svg in 113.64756ms
```
if I try again with `--animate-interval 1200`  it seems to actually wipe out the previously generated svgs and generate no output at all (this looks like a bug):
```shell
$ d2 --animate-interval 1200 /tmp/test.d2 /tmp/test.svg
<no output again>

$ ls -l /tmp/test/* /tmp/test.svg
ls: /tmp/test.svg: No such file or directory
ls: /tmp/test/*: No such file or directory
```

Here is my version installed via homebrew on macOS:
```shell
$ d2 version
0.4.1
```

Is this a bug?

**Comment by alixander** [comment]
oh interesting, i think this is because the base has no content. that's a bug indeed, it should show 
- blank board
- step 1
- step 2
- step 3

it's probably not what you want though, you probably just want to make step 1 the base.

```d2
code
steps: {
  1: {
    code -> git commit
  }
  2: {
    git commit -> git push
  }
}
```

**Comment by HariSekhon** [comment]
Ah, that workaround does work... thanks!

**Comment by alixander** [comment]
this was fixed by https://github.com/terrastruct/d2/pull/1357
