### ISSUE TITLE
Feature Request: define theme in .d2 file programmatically

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#1286]
I've got a use case where using CLI `d2 --theme` or environment variable `D2_THEME` doesn't allow for variation in themes among different `.d2` files being generated via automation (in this case a [Makefile](https://github.com/HariSekhon/Diagrams-as-Code/blob/master/Makefile#L87) used by [GitHub Actions CI/CD](https://github.com/HariSekhon/Diagrams-as-Code/actions/workflows/generate-d2-images.yaml) in my [Diagrams-as-Code repo](https://github.com/HariSekhon/Diagrams-as-Code)).

I had intended to use the classic shebang trick applied to the top of my d2 files:

```
#!/usr/bin/env d2 --theme 200
```

which would allow each .d2 file to store it's preferred theme... but this comes at the expense of not being able to give a different image path argument or path type, for which I'll also raise a separate ticket.

Ideally all settings should be programmatic in code files and not just CLI / environment variables.

**Comment by HariSekhon** [comment]
I was just looking at the `--sketch` option too and realized that this ticket could become a more generic "Support All CLI options as declarative programmatic keywords in d2 files", which would also address #1287.

**Comment by HariSekhon** [comment]
Update: so I've improved my [Makefile code](https://github.com/HariSekhon/Diagrams-as-Code/blob/master/Makefile#L87) to extract the shebang from each d2 if available, and to just use a regular `d2 --theme 200` call if one is not found.

This is now allowing me to diversify the settings between d2 files using their shebang lines as a workaround until CLI settings are supported in the d2 code itself such that just a regular `d2 input.d2`in a for loop would suffice without any arguments... or using the shebang, just `./input.d2` if set executable.

This has allowed me to get one of my diagrams generated in the for loop to use `--sketch` for example, but not the others:

![test_in_production](https://user-images.githubusercontent.com/2211051/236029916-7109e128-2cab-4c0d-919b-676020c3c0e8.svg)

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/issues/410

**Comment by alixander** [comment]
(love the diagram, haha)
