### ISSUE TITLE
Feature Request: define image path and format in .d2 file programmatically

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#1287]
Related to #1286.

Feature Request to be able  to programmatically define the d2 image file path and output format inside the .d2 file itself.

This is possible in Python diagrams for example:

https://diagrams.mingrammer.com/docs/guides/diagram#options

This would allow for variations between diagrams to be stored in the code itself and be more self-contained.

This is useful from a Git perspective but especially when doing automation CI/CD or loops over a collection of .d2 files to generate their diagrams - in my case via a Makefile:

https://github.com/HariSekhon/Diagrams-as-Code/blob/master/Makefile#L87

used by my GitHub Actions CI/CD workflow to auto-regenerate the D2 diagrams upon any committed changes:

https://github.com/HariSekhon/Diagrams-as-Code/actions/workflows/generate-d2-images.yaml

**Comment by HariSekhon** [comment]
I was just looking at the `--sketch` option too and realized that this ticket could become a more generic "Support All CLI options as declarative programmatic keywords in d2 files", which would also address #1286.

**Comment by alixander** [comment]
indeed! will use the existing issue to track
https://github.com/terrastruct/d2/issues/410
