### ISSUE TITLE
Feature Request: d2 --output-dir and --output-format CLI options

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#1288]
It would also be convenient if `d2` CLI had `--output-dir` and `--output-format` CLI options.

This would make cases easier for people who just want to do simple for loops in shell over a bunch of d2 files.

This is a nice to have, but the more important related issue is: #1287

**Comment by alixander** [comment]
what would `output-format` do?

**Comment by HariSekhon** [comment]
`output-format` would be set to `png` or `svg`

**Comment by alixander** [comment]
ah, good suggestion. will close in favor of existing issue, but add your `out-format` suggestion! https://github.com/terrastruct/d2/issues/13
