### ISSUE TITLE
Feature Request: exit statement to ignore rest of file to make development easier

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#1289]
I have a large [Code Templates repo](https://github.com/HariSekhon/Templates) which I use to every new code file for all my languages and have created a d2 template full of examples from having read through the entire documentation:

https://github.com/HariSekhon/Templates/blob/master/template.d2

I've just realized that it would be convenient if d2 had an `exit` statement such that I could start coding at the top of this template and d2 could ignore the boilerplate below the exit statement as I step through the code and take bits and pieces from the template.

is this something that is easy to do to just ignore the rest of the file after adding an `exit` statement so that I don't have to comment out or delete the entire rest of the file while I'm still working my way through it?

**Comment by alixander** [comment]
I haven't seen that in any declarative languages, or usable in any programming languages (e.g. unreachable code after return statement is reported as n error). commenting will be the way to go
