### ISSUE TITLE
Mass setting attributes for objects via glob or regex

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#1291]
I've just realized in diagrams with lots of icons I am going around setting redundant `shape: image` on every single object.

Feature Request to add a glob or regex match functionality to apply an attribute like this to all objects of matching id or name, eg:

```d2
match * {
  shape: image
}
```
could set all objects to use their icon image, as this is often what you want with icon diagrams.

This functionality could also be used to set icons for select groups of object names or IDs:

```d2
match apache {
  icon: https://icons.terrastruct.com/dev%2Fapache.svg
  shape: image
}

Apache httpd1   # would inherit the settings from 'match apache' due to case insensitive glob or regex
Apache httpd2   # would inherit the settings from 'match apache' due to case insensitive glob or regex
...
```

Related to #1281.

Right now the closest thing would be using classes like this, which is a lot more needless boilerplate and doesn't scale well for diagrams of clusters because 2/3 of the lines for every object are completely redundant multiplied by the number of objects in the diagram.

So in this small example below nodes are 30 lines instead of 10... more if you consider that you have to declare the nodes separately to their connections to avoid syntax errors:

```d2
classes: {
  hbase: {
    icon: https://diagrams.mingrammer.com/img/resources/onprem/database/hbase.png
    shape: image
  }
}

hbase1: HBase node 1 {
  class: hbase
}
hbase2: HBase node2 {
  class: hbase
}
hbase3: HBase node3 {
  class: hbase
}
hbase4: HBase node4 {
  class: hbase
}
hbase5: HBase node5 {
  class: hbase
}
hbase6: HBase node6 {
  class: hbase
}
hbase7: HBase node7 {
  class: hbase
}
hbase8: HBase node8 {
  class: hbase
}
hbase9: HBase node9 {
  class: hbase
}
hbase10: HBase node10 {
  class: hbase
}
```

**Comment by gavin-ts** [comment]
#103
