### ISSUE TITLE
Feature Request: QR code

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1302]
i wish d2 can output QR-code. (using grid-gap:0)
https://pkg.go.dev/github.com/boombuler/barcode#section-readme

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=dNrBjhzFEoXh_TzFyA9gxYnKrMocr-5FSCBYIrE2CAGCBQskFpbfHXnAnrb6YxuqmunQ3ycy8-_8l_nr_3_7vy--eXr3_M9ff0D19PjD729__O3NP5XbT_n0WG_eP3x88fuvvv7uy89f_OuXX__86T9f_MTv6bHzcEv4pfDz2z-eHushladXr949_6un50_4_iHVqB2oDdQmaidq112tUuul-Nz1hwf3_csp1O4bqaTv_2DuO6lk4EG0ErSS-1aShRo6aXTS9500MFXXfXfVt6BeivftVd-ieimed8UWqwarBqvqW1gfHwSszv23rjrqBrAasKpz30z1La6X4n031bfAPhUb7YDYIWIHiB1I1oFkHUhWHcB1CNcBXHXUfYMHsnUoWweyVYd4HeB1iNcBXgfSdSBdB9JVB2AdgDUEawDWAKwBWEOwBmANwRqANZCtAVY1bmF9fBnZGpqDA6iGUA2gGkA1gGoI1QCqAVRTqCZQTaCaQDWFagLVFKoJVFNjcGIMTuRqAtUUqglUU6gmUE2gmkA1hWoC1QSqU6hOLVqnFq1Ti9apResErVO0TtA6QetEsE4NwRND8BStE7RO0Tq1Zp1as06tWafWrBPATgC7AOzCZvBCtC5E60K0LmwGL7G6wOpSsi4k6xKsC7AuwboA6wKsC7vBC8m6kKwLybqwG7zAqVbdz_haStZSspaStZSshWTVKnwblzYYCxuMWuBVC6vWwihc4rXAq1bUj9K1lK6ldC2layFdtRqEtrBtYdvAtpGw2qK2QW0rY1vQtqBtQNsK2da2cGtbuEVtg9pGzDZithGz2kC2kbONnKUALMXjMc_HPCDzhMwjMnKW4hlZh-TSKbmQsxSClgKzlM7JBWYpnZQLSUvprFzAlkLSUgIXgaPXCJKWYEAmiFqCqEVyI5_JjZei7Ib1hjqi3xA4Cw6Bs-Kg48CITASOmkOeIxIdaYFrJa6VOImOtBLXSlwLnFRHWuDkOtICJ9mRz2THy-uYIS1wLXCyHZHtSNNPCZx8R-Q7IuERGY8cAncInJxHDoGT84ikR2Q9cmhUynpE1iOHEncI3KFReQiczEcOgZP6yNColPvI0KgcGpVD4KQ_MpQ4-Y9IgGRgWxIZkAwlTg4kciAZAicJElmQDIGTB4k8SCRCIhOSqVEpFRK5kEiGZCpxsiGRDclU4qYSNwVuCpyMSGREMgVOSiRyIpEUydSonErcxDEg8iKRF4m8SORFIi8SeZFIjERiJKfASY3kFDi5kUiO5NQaJzsS2ZHIjkR2JKcSdwqc9EjkR3IJnAxJpEgiR5JL4GRJIkuSS-CkSXIJnDxJJEoiUZJLibsE7hK4S-BkSyJdEvmSLIGTL8kSuCVwS-DkS7IETr4kS2ucfEnkSyJhEhmTLCVOxiRLmxMZk8iYRMYkS-CWwG2BkzHJFjgpk2yBkzKJnEnkTCJnkq1RuQVO0iRb4LbASZpE1iRb4ORNspW4rc2JzEkXwHUBXBfWuC6scV1Y47r4gzXAtcxJF8B16SdrmZMugOsCuJY5aZmTljlpmZOWOWmZk5Y56cLmpHUhpGVOWldCWndCWpdCWrdCWuakdS2kI3DxXQN1JHAyJx0krmVOWuakI3AyJ637IS1z0gG4h78DAAD__w%3D%3D&

**Comment by bo-ku-ra** [comment]
API ERROR
https://play.d2lang.com/?l=&script=dJo9qyVVEEXz9ysuYz5U1fm-RiqCoqFgPIqoaGAgGAzz32Wuc7uexV7p5rxzX53Vu7tZ9Cfmb7_8_ouvvrvf3j9-_e1HVvfbT3---_mPz2__Ra__z_vNPrw8__LHb7794evyl__89vvfv-BffnYhvN_CX15DzuDXd3_db_bi5vfbmze394-fu98e_-eHF7fQcdNx1_HQ8dTxUrG57f_lj_P4uPzIXdx0LMc095Cbu5zT3Ltergd1PajLQd23jvWcoecMOWdoyhYmx7conDOX81sU0plPlQegDo06NGqLwvq5XLMOl5e0hcOsmnVo1hYuR7UotDOXs1oU3lceelgNvAHwpoE33eume910r61p2g1oN03bmskTaLrZDZrddLOtAe6mcTfA3TTuprvddLeb7rY1zbpp1h1Yd826a9Zds-7AumvWHVh3zbrrZneN2nph_dxFN7vDTbxr0h1Id026a9Jdk-5AumvSXZMeQHpo0kOTHpr0ANJDkx5AemjSA-7hQ9_Dh2710KQHkB6a9ADSQ5MemvTQpAeQHpr00KQnkJ7wwJ7wwJ7wwJ7wwJ4a9gTYU8OeGvbUtZ5wB5_6Dj4B9tSwJ8Ce8Lye8Lye8Lye8LyemvfUvJfmvfRr-NLFXrrYSxd76dfwBaiXRr2g10v3egHrpVkvYL0066VZL_0evnSvl-710r1e-j18acy2TT7BbEOvN_R6Q6839HrrXts2fbVveDfb-t3MtsZtWz-xt76Pb8C9NW7bDtNCtzd0e0O3N3R7627bDk33APUD1I-mfnS_7QD0o6EfaPgB5geYH838QMUPvJAfeCE_AP1o6EeX_OiSH11yO5r40S0_uuVumrcbWRXSKuRVSKyQWdEtdyO1Am7FQK6YbrmbrrmbRu4GesU0cjcQLKZ77gaKxTR1N91zN-BeZdqlh4B71Wm5HjSTLrpXo5Y5mCYD1URODaUazEtWDbijVgPuKNbIrOn7u1e3duUg18CuOeg1r3otc933qtcy1-dQ9Vqu19d_9Wu5HhwjcAfD5lWxXb8L3Ktiy330_a06tsw1d3BsDo7Nq2O79gHuYNkcLJuDZnPwbF5FW-6jzwFMm1fTlrk-B1BtDq7Nq2vLXHMH1-ZVtmUO88J9vuq2zPV1Xn1b5nreatye-4Nx86rcMtfnUKVb5vo-X61b5vocQLt59W7XerjPV_GWub7Owbx5VW-Zw7zQ9yrfcj3MC8930G8O_s2rf8tcnwMYOAcF51XBZa7PARycVwl35dD3auFyveYOHs7Bw3kVcZlr7mDiHFScVxd37QN9rzLuuR5snIONc7BxDjbOwcY52DgHHeeg47z6uCsH7tXI5XqYF7hXJZe5vs7ByTk4OQcn59XJXfsDd5ByDlbOq5Z7_i54OQcx52DmvKq53F9zBzfnVc5dOdznq53LHOYF7qDnvPq5zGFe4F4VXeaaO0g6B0vn1dJlrs-hWrpcr7lXS5e5Podq6XK9Podq6a71wB0snYOmc_B0Xj1d5pp79XS5XnMHT-fg6bx6umt_4F49Xeaae_V0uV6fQxV1mWvuYOocTJ2DqfNq6q59gDuoOq-qLveBeYE7uDqvsi7X6-d7tXVXDu914Oui-rrM5TlE9XWZ609Gqq_LHD6P0dwDfF1UX3fl8IEM-Lqovi5zyT3A1wX4ugBfF-DrAnxdgK8L8HVRfd0zh4_fAnxdwOdvAd-_BXwAF_AFXICvC_gELqqvu3L8MArmBe7g66L6utxHcwdfF9XX5XqYV_c9wNdF9XWf9vk3AAD__w%3D%3D&

**Comment by bo-ku-ra** [comment]
API ERROR 2
https://play.d2lang.com/?l=&script=dJo9qyVVEEXz9yuaMR-q6nxfIxVB0VAwVhEUDQWDYf67zHNu10yxV7o579xXZ_Xubhb9kfnbr3_86psfHte7119_-4HV4_r1719---vL6__o0__zcdn7l-df_vzd9z99W_7y3z_-_Od3_Mub4OMKf_niU8ivyZP047IXN39cb95c715_7nG9_p_vX9xCx03HXcdDx1PHS8Xmtj_LX8_jw_Ijd3HTsRzT3ENu7nJOc-96uR7U9aAuB3XfOtZzhp4z5JyhKVuYHN-icM5czm9RSGc-VR6AOjTq0KgtCuvncs06XF7SFg6zatahWVu4HNWi0M5czmpReN956GE18AbAmwbedK-b7nXTvbamaTeg3TRtayZPoOlmN2h20822Bribxt0Ad9O4m-52091uutvWNOumWXdg3TXrrll3zboD665Zd2DdNeuum901auuF9XMX3ewON_GuSXcg3TXprkl3TboD6a5Jd016AOmhSQ9NemjSA0gPTXoA6aFJD7iHD30PH7rVQ5MeQHpo0gNID016aNJDkx5AemjSQ5OeQHrCA3vCA3vCA3vCA3tq2BNgTw17athT13rCHXzqO_gE2FPDngB7wvN6wvN6wvN6wvN6at5T816a99Kv4UsXe-liL13spV_DF6BeGvWCXi_d6wWsl2a9gPXSrJdmvfR7-NK9XrrXS_d66ffwpTHbNvkEsw293tDrDb3e0Oute23b9NW-4d1s63cz2xq3bf3E3vo-vgH31rhtO0wL3d7Q7Q3d3tDtrbttOzTdA9QPUD-a-tH9tgPQj4Z-oOEHmB9gfjTzAxU_8EJ-4IX8APSjoR9d8qNLfnTJ7WjiR7f86Ja7ad5uZFVIq5BXIbFCZkW33I3UCrgVA7liuuVuuuZuGrkb6BXTyN1AsJjuuRsoFtPU3XTP3YB7lWm3HgLuVafletBMuuhejVrmYJoMVBM5NZRqMC9ZNeCOWg24o1gjs6bv717d2p2DXAO75qDXvOq1zHXfq17LXJ9D1Wu5Xl__1a_lenCMwB0Mm1fFdv8ucK-KLffR97fq2DLX3MGxOTg2r47t3ge4g2VzsGwOms3Bs3kVbbmPPgcwbV5NW-b6HEC1Obg2r64tc80dXJtX2ZY5zAv3-arbMtfXefVtmet5q3F77g_Gzatyy1yfQ5Vumev7fLVumetzAO3m1bvd6-E-X8Vb5vo6B_PmVb1lDvNC36t8y_UwLzzfQb85-Dev_i1zfQ5g4BwUnFcFl7k-B3BwXiXcnUPfq4XL9Zo7eDgHD-dVxGWuuYOJc1BxXl3cvQ_0vcq453qwcQ42zsHGOdg4BxvnYOMcdJyDjvPq4-4cuFcjl-thXuBelVzm-joHJ-fg5BycnFcnd-8P3EHKOVg5r1ru-bvg5RzEnIOZ86rmcn_NHdycVzl353Cfr3Yuc5gXuIOe8-rnMod5gXtVdJlr7iDpHCydV0uXuT6HaulyveZeLV3m-hyqpcv1-hyqpbvXA3ewdA6azsHTefV0mWvu1dPles0dPJ2Dp_Pq6e79gXv1dJlr7tXT5Xp9DlXUZa65g6lzMHUOps6rqbv3Ae6g6ryqutwH5gXu4Oq8yrpcr5_v1dbdObzXga-L6usyl-cQ1ddlrj8Zqb4uc_g8RnMP8HVRfd2dwwcy4Oui-rrMJfcAXxfg6wJ8XYCvC_B1Ab4uwNdF9XXPHD5-C_B1AZ-_BXz_FvABXMAXcAG-LuATuKi-7s7xwyiYF7iDr4vq63IfzR18XVRfl-thXt33AF8X1dd93Oe_AAAA__8%3D&

**Comment by bo-ku-ra** [comment]
good. 
"grid-gap: 0 ( &style.stroke-width: 0)" must use 'crispedges'.

**Comment by gavin-ts** [comment]
> good. "grid-gap: 0 ( &style.stroke-width: 0)" must use 'crispedges'.

I think it would have to be highly specific. rectangular shape, no border radius, stroke-width: 0, and grid-gap: 0, those could have the css style with `crispedges`

**Comment by bo-ku-ra** [comment]
and it applies only to straight lines.
