### ISSUE TITLE
Bug: 'd2 fmt' adds spaces after every comment # , breaking shebang header lines

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#1319]
As a workaround to #410, I'm using shebang lines to treat all my d2 scripts as executables containing the CLI --switches.

However, whenever I run `d2 fmt`, it inserts a space after every comment `#` symbol, breaking the shebang lines.

testfile.d2:
```d2
#!/usr/bin/env d2 --theme 200
someobject
```

```shell
$ chmod +x testfile.d2

$ ./testfile.d2
success: successfully compiled testfile.d2 to testfile.svg in 57.976548ms

$ d2 fmt testfile.d2

$ ./testfile.d2
./testfile.d2: line 2: someobject: command not found
```
in the file you can see the `#` and `!` characters are separated
```d2
# !/usr/bin/env d2 --theme 0
someobject
```

My real-world examples are here:

https://github.com/HariSekhon/Diagrams-as-Code

**Comment by alixander** [comment]
we should just skip all fmt aside from indentation when it's inside a code block

**Comment by berniexie** [comment]
@alixander maybe we just ignore the "#!" combo?

**Comment by HariSekhon** [comment]
FYI I've worked around this in my [Makefile](https://github.com/HariSekhon/Diagrams-as-Code/blob/master/Makefile) like so:

```Makefile
.PHONY: fmt
fmt:
    d2 fmt *.d2 custom/*.d2

    # put shebang header back to normal to work around this bug:
    #
    #   https://github.com/terrastruct/d2/issues/1319
    #
    sleep 1
    if uname -s | grep Darwin; then \
        sed(){ gsed "$$@"; }; \
    fi; \
    sed -i 's|# !/|#!/|' *.d2

    # revert typechange of template.d2 symlink
    git checkout $$(git status --porcelain | awk '/^.T/{print $$2}')
```

**Comment by alixander** [comment]
@berniexie that's not enough. what if they want to write `-->` for example, we don't want to shorten that to `->` in their code block.

**Comment by berniexie** [comment]
@alixander I'm not sure that's an issue right now? When I compile
```
Code: |js
  X ---> Y
|
```
it doesn't autoformat it to `X -> Y`

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/pull/1471#issuecomment-1646618203
