### ISSUE TITLE
Default shape and style

### ISSUE THREAD

**Issue by Emptyfruit** [terrastruct/d2#1327]
Is there a way to set the default shape and style for the diagram? I could not figure it out from the docs. If not, i think it is an important feature to be added.

Now, the default shape is a rectangle. If i need a simple diagram with ten connected circles, i'd have to add ten extra lines of code changing the shape of each one. And then the same with `style` to make them all green.

**Comment by alixander** [comment]
the way to do this in D2 will be with globs. it's being worked on.

```
*: {
  shape: circle
}
```

**Comment by artukn** [comment]
Just out of curiosity, how will we set defaults for connections?

**Comment by alixander** [comment]
```
* -> *: {
  style.stroke: red
}
```

**Comment by bo-ku-ra** [comment]
would this and "import" be a replacement for themes?
can i create my own theme? (https://github.com/terrastruct/d2/issues/875)

**Comment by alixander** [comment]
@nhooyr pretty interesting for globs: https://github.com/terrastruct/d2/issues/1327#issuecomment-1586910187

**Comment by alixander** [comment]
@the42 it'll be done like so:
```
* -> *: {
  &dst.class: sql_table
  &src.class: sql_table
  style.opacity: 0.4
}
```

**Comment by the42** [comment]
> @the42 it'll be done like so:
> 
> ```
> * -> *: {
>   &dst.class: sql_table
>   &src.class: sql_table
>   style.opacity: 0.4
> }
> ```

Maybe my intention and your draft fulfil a different purpose though?

* My use-case: If source and destination are of shape-type sql_table (I wrongly said class, but meant shape-type), then use the following styling information, enclosed in `{ ... }`.   Here `[...]` serves as s selector which only matches if source and destination are of shape type `sql_table`. In spirit as seen in https://d2lang.com/tour/classes#multiple-classes, `logo.class: [d2; sphere]` where it is used for assignment, whereas I was thinking of a selector.
* Your use-case seems to be: assign source and destination to shape type sql_table and style the link with opacity 0.4

I know this is WIP and I might as well misinterpret your intention.

**Comment by alixander** [comment]
> Your use-case seems to be: assign source and destination to shape type sql_table and style the link with opacity 0.4

@the42 the use-case is as you describe. `&` is basically, "for the glob to match, this also needs to be true". It's an idea from CSS preprocessors: https://css-tricks.com/the-sass-ampersand/

**Comment by bo-ku-ra** [comment]
does it work on v0.6.0?
https://github.com/terrastruct/d2/issues/1327#issuecomment-1588289466

**Comment by alixander** [comment]
@bo-ku-ra not quite yet, but it will in 0.6.1 which will come this week hopefully.

Right now, globs behavior only applies only to existing shapes.

```d2
a
b
*.shape: circle
c
```

`c` won't be a circle above.

We plan to change it so that globs are lazy-evaluated and applied to each shape as they come in, so you can define the glob at the top, and `a`, `b`, `c` will become circles as they come in

**Comment by bo-ku-ra** [comment]
i understand that d2 is not an interpreter language.
right?
