### ISSUE TITLE
multiple classes with arrowheads not behaving correctly

### ISSUE THREAD

**Issue by ddolan-lutron** [terrastruct/d2#1333]
The D2 documentation calls out support for applying [multiple classes](https://d2lang.com/tour/classes#multiple-classes) to a single element, which is a quite useful feature. I've noticed that it is not supported for connectors. I had created classes to make it easier to apply cardinality to connectors in a class diagram, and I also wanted to create classes to apply formatting as to the type of association (e.g. Aggregation, Composition, Inheritance), but the array syntax is not supported for connectors, and attempting to apply multiple classes results in only the last class being applied. Being able to compose classes to create consistent connectors would be helpful, especially in the class diagram context.

Thanks for the young, but still great alternative to the existing field of diagrams-as-code tools!

**Comment by alixander** [comment]
@ddolan-lutron thanks! it should work, can you paste what you're trying?

![Screen Shot 2023-05-17 at 10 09 39 AM](https://github.com/terrastruct/d2/assets/3120367/d995ff50-1532-41e6-8803-fccc1c8b1005)

https://play.d2lang.com/?script=gsa5lUI1l4JCUWoKhKGgAHaFHsRxViAJLgWFWi4FBbAtBYlFqXklqEqhYWelYKBnDFZby1WhoGunUAlRBrbHSiG6KDXFGtmQWK5aLkAAAAD__w%3D%3D&

**Comment by ddolan-lutron** [comment]
Thanks for the quick response! I must have either encountered the compiler error on an older version and have since updated, or I had a different syntax error and got confused by the error the compiler produced. I tried my use-case again and it does compile, but there are some cases where the settings don't compose as I might expect. In the example below, I have two classes that attempt to define different sub-properties of the `target-arrowhead` property, and the end result depends on the order in which the classes are specified.
![image](https://github.com/terrastruct/d2/assets/10943215/ff97612e-2c11-4ec5-b53f-7bc28ed433c1)
![image](https://github.com/terrastruct/d2/assets/10943215/e3f34e66-b534-4d9e-96ba-26b142544ab8)
This seemed a clean approach to what would otherwise be repetitive and verbose in a reasonably-sized diagram. The alternative is to create classes for all combinations of arrow shape and source and target cardinalities (which is my current solution).

**Comment by alixander** [comment]
indeed, this looks like a bug with arrowhead nested within classes
