### ISSUE TITLE
allow users to change the shape of an object using the diagram modifer

### ISSUE THREAD

**Issue by katwangy** [terrastruct/d2#1338]
currently you can only change the shape by editing the d2 code, but it would be faster to be able to change the shape through the diagram modifier. from a UI change, we would include a dropdown for the shape under the "style" section

<img width="699" alt="Screen Shot 2023-05-22 at 3 55 43 PM" src="https://github.com/terrastruct/d2/assets/102620103/28695e72-5c85-4ee2-a46b-eeaeeb66be62">

**Comment by gavin-ts** [comment]
moved to internal repo
