### ISSUE TITLE
layout=dagre: container labels are too close to the top edge of "multiple" style containers

### ISSUE THREAD

**Issue by emteelb** [terrastruct/d2#1339]
Compare the "Node" container label in this [Dagre rendered diagram](https://play.d2lang.com/?script=cs7PKynKz8lJLbJSqAZbrYfkUCsF01ouhBI9v_yUVHQ-mFBIzs_Lg6QTYs1B16cH0QWLFiuFkqJSTMuwKgIEAAD__w%3D%3D&layout=dagre&) with the same label in this [ELK rendered diagram](https://play.d2lang.com/?script=cs7PKynKz8lJLbJSqAZbrYfkUCsF01ouhBI9v_yUVHQ-mFBIzs_Lg6QTYs1B16cH0QWLFiuFkqJSTMuwKgIEAAD__w%3D%3D&layout=elk&).

I would just use the ELK layout engine for rendering my diagram but the above example is only a part of my diagram. My actual diagram has more connections and containers and I prefer the Dagre-rendered layout for that.

Is there a way to influence the padding of container labels that I might have missed in the documentation?

Thanks in advance for your time and help.

**Comment by emteelb** [comment]
Thanks for the fast response. I appreciate the acknowledgement and work. Enjoying using this tool so far!

**Comment by emteelb** [comment]
Thanks for the work here. I `git clone`-ed this repo, ran the `install.sh` script and renamed the resulting `d2` binary `d2-new` to avoid conflict w/ the `d2` binary installed by my system's package manager.

I used the `d2-new` binary to generate a diagram (Dagre layout) that I was seeing this issue with earlier. I still see the issue where a text label is too close to a "multiple" style object.

I ran `git log` locally to verify that I see gavin-ts's commit there. I do. `d2-new --version` shows v0.4.2.

Is there anything else I can do here to verify that I am indeed running the latest, "fixed" version. Or something I am not doing but should be as relates to generating my diagram?

Thanks in advance for your time and help.

![20230531-09:34:09_469x513_screengrab](https://github.com/terrastruct/d2/assets/106624800/4cc717f6-9191-46d2-a51b-93f05117a7a8)

**Comment by alixander** [comment]
@emteelb if you copy paste your code into playground, does it show correctly?

e.g.

https://play.d2lang.com/?script=qlDQtVOorOSqrNQDW6wHCxYrhZKi0lQuQAAAAP__&

**Comment by emteelb** [comment]
> if you copy paste your code into playground, does it show correctly?

It does indeed. Thanks for the hint. So... something going on with my local environment then? I'm on Arch Linux, just updated today. If you have another hint for me, would take it, otherwise, I can use the Playground to get by in the meantime.

![20230531-14:08:30_122x131_screengrab](https://github.com/terrastruct/d2/assets/106624800/07904218-d898-4e95-87ad-181b56a3b280)

**Comment by emteelb** [comment]
> hmm if something isn't working with the install script you can try `go build .` and `./d2 --version` in the d2 root directory

This worked perfectly and I see the text label looking nicely offset from the "multiple" object now after rendering my .d2 file with the Go-built binary.

Thanks to you both for the help and clarifications.
