### ISSUE TITLE
[Feature Request] Timeline Diagram

### ISSUE THREAD

**Issue by artemkovalyov** [terrastruct/d2#1344]
Timeline is an exceptionally useful diagram type.
It seems like D2 has all the means to render it.
Visually it most close to the sequence diagram where containers are attached to a "sequence" line

Mermaid has this diagram type although it's not so well implemented to my humble opinion.

**Comment by alixander** [comment]
@artemkovalyov do you have an example of an A+ timeline diagram? e.g. what Mermaid's is lacking
