### ISSUE TITLE
Simplify adding connection types

### ISSUE THREAD

**Issue by npupko** [terrastruct/d2#1351]
Hi d2lang team,

First of all, I want to express my appreciation for your work on the d2 lang project. The simplicity and ease-of-use of the language is fantastic.

I've been using Mermaid Lang for a while now and noticed that they have various connection types like `--|>`, `--o{` for ERD, and `--<>` for UML. 

Example for UML:
```
classA --|> classB : Inheritance
classC --* classD : Composition
classE --o classF : Aggregation
classG --> classH : Association
classI -- classJ : Link(Solid)
classK ..> classL : Dependency
classM ..|> classN : Realization
classO .. classP : Link(Dashed)
```

```mermaid

classDiagram
  classA --|> classB : Inheritance
  classC --* classD : Composition
  classE --o classF : Aggregation
  classG --> classH : Association
  classI -- classJ : Link(Solid)
  classK ..> classL : Dependency
  classM ..|> classN : Realization
  classO .. classP : Link(Dashed)
```

These connections are quite convenient and make it easy to create different types of diagrams.

For me, d2lang is simplicity and conciseness, but in the case of connections, this is not at all concise.
In d2 lang, achieving similar functionality requires using `target-arrowhead` and other attributes. While this works, I believe that adding a simplified way of creating these connections would greatly benefit the user experience.

I propose the following feature request:

- Introduce shorthand notations for common connection types, similar to those found in Mermaid Lang.

This addition would make it easier for users to quickly create different types of connections in their diagrams without having to rely on multiple attributes.

Please let me know if you require any further information or clarification. I'm excited to see how d2 lang continues to evolve and improve!

Thank you for your time and consideration.

**Comment by alixander** [comment]
thank you @npupko for the kind words and suggestion.

though this is a common ask, D2 won't be doing this.

1. i just don't believe ascii art should go into syntax. i think `x ..|> y` looks atrocious and stains the aesthetics of a d2 script.  If you add or remove one `.`, it breaks. why is `--o` produce diamond and not circle? If I do a symbol that doesn't exist, e.g. `--f`, the `f` just gets prepended to the target node label. big lack of consistency.
2. D2 also does not prescribe to any one paradigm like plantUML does. we have no intention of supporting the corpus of UML relations. instead, you should have the flexibility to construct any sort of diagramming paradigm you wish. giving special syntax to the set of UML relations would be prescriptive. 
3. It hinders readability. `->` is universally recognizable. `x .. y` looks like it may be specifying something else, like a for loop. 
4. `--*` will step on globs, which is a feature coming in the near future.

I think the shorthand is slightly faster prototyping for the author at the expense of readability for readers. They have to interpret, and nobody's read the UML specs.

You'll just need to define classes once. I think this is way cleaner and readable and the difference in prototyping speed is negligible. Maybe in the future there can even be downloadable libs of predefined classes, such that you can import a UML package!

```d2
classes: {
  aggregation: {
    target-arrowhead.shape: diamond
  }
}
classE -> classF: {class: aggregation}
```
