### ISSUE TITLE
connection from multiple shape using wrong box

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2#1355]
<img width="221" alt="Screen Shot 2023-05-31 at 11 16 53 AM" src="https://github.com/terrastruct/d2/assets/85081687/5d397c1c-477e-4a25-ae41-bcdca215e95a">

https://play.d2lang.com/?script=bJIxCsMwDEV3neJfIFq6echdClJNlqSospaSuxerbsngwcv_3_B46GiuVvAmIGpBdNeKakd7ZgiE_GPRx7Zv_RhGByQt_1wWuDWl0X1_8XQyWVwEFdxycVJ_J738bo5lReJyVA7hAbWs0F3oEwAA__8%3D&

**Comment by alixander** [comment]
ohh right, it should use whatever is outer

**Comment by gavin-ts** [comment]
yeah I have code to do that, but there must be a bug: 

https://github.com/terrastruct/d2/blob/ba3e43ad5dba4294f9d9c86bac9096431af237bd/d2layouts/d2dagrelayout/layout.go#L474
