### ISSUE TITLE
Markdown text in tooltips does not flow as expected.

### ISSUE THREAD

**Issue by ddolan-lutron** [terrastruct/d2#1367]
This may just be me running into undefined/unintended behavior, but when rendering a tooltip that is defined as markdown, newlines are inserted as-is from the plaintext. This differs from other markdown text blocks where single newlines in the plaintext are treated as a space.

This definition
```
box: {
  label: |md
    This is a label =)
    Its text flows as expected =D
  |
  tooltip: |md
    This is my tooltip =)
    But my text does not flow as you would expect =(
  |
}
```
Results in this output
![image](https://github.com/terrastruct/d2/assets/10943215/06cd615a-cc8f-4ccf-a9d7-11755915c0c6)

Example [here](https://play.d2lang.com/?script=ZNAxCsJAEEbhfk7xSr1CYBuxsfcC0V0xkDjC7JIE491lJ0llOz98D-amU8NHwD_VsAxRAK7PzuiMdh0IRz9fslFrPHodjdZI0zvdc4qEs8AisPX_rWHet507lezXKkZNxktXusqzFkYtfdwahIMXvvILAAD__w%3D%3D&theme=3&layout=elk&)

Thanks for great tool and your quick responses!

**Comment by alixander** [comment]
the tooltips use [title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) html feature, which is quite limited in its styling capabilities, so it's not markdown and just gets converted to plaintext. i'll document this better! (https://github.com/terrastruct/d2-docs/issues/148)
