### ISSUE TITLE
d2 0.5.0 new feauture 'import' does not work on windows.

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1388]
how did you test  on windows?

**Comment by alixander** [comment]
darn, sorry about that, we'll release a hotfix today on this

**Comment by bo-ku-ra** [comment]
occurs when included in file (and folder) names

https://play.d2lang.com/?l=&script=ZFIxT_MwEN3vV9xnKYoz1GrdTyi4gMpARxbK5iWyDaRSnCoJMFgZEvWf5o8g26FUoAxPuXu6e-_5zoGJxjuDz9J6TWJGaemhOBbWtAY_TNOWtc0ctF3dFK9GzEgf97unzMHzfrdYXTmYhlGQaRiZ5tLSZL1M_nOmeUaghx5UpQVRlWaqrogDdbxec0ECSEvbt_KlWxzKNiN_BuU8uV_GQdNw8p3TRSeucIBeRi5IAGmp5hjTDc2QtkBdq_fK2G4DiGHLdhpGaek2eVgn-SrJ_ajI9Zn2gD3E79s8i27ZNIy4uMNgyHvwBQC4_D8Fbh6oN7-5gqjCph2W1bFuOmnTs4IU_91iGl2nxIUHZz8HK7AxeoOxHC9jLgWZXwEAAP__&

**Comment by alixander** [comment]
@bo-ku-ra it's fixed on windows in latest release, can you try? https://github.com/terrastruct/d2/releases/tag/v0.5.1

as for your other comment, D2 currently doesn't support importing a UTF-16 file into a UTF-8 file. i'm not sure how conventional that is in other programs to be able to do that. theoretically we should be able to add such a feature into D2 without much hassle, but is this something you need?
