### ISSUE TITLE
Incorrect layout on rendering

### ISSUE THREAD

**Issue by fallback** [terrastruct/d2#139]
Hello! Thanks for awesome tool! Despite the issue below, it works pretty well. Thanks for making it available!
When I tried to get through the Docs, rendering a relatively simple example with Containers, Shapes and Text as seen in dedicated section. However, ran into issue below.
Feel free to ping me if you need more details. Thanks!

Incorrect layout discovered when rendering the example of [Text](https://d2lang.com/tour/text) section from Documentation.

**Environment:**
d2 version: v0.0.13
OS: macOS 12.6

**Source:**
```
aws: {
  load_balancer -> api
  api -> db
}
gcloud: {
  auth -> db
}

gcloud -> aws

explanation: |md
  # Why do we use AWS?
  - It has more uptime than GCloud
  - We have free credits
| {
  near: aws
}
```

**Actual:**
![Screenshot 2022-11-22 at 17 55 04](https://user-images.githubusercontent.com/5113782/203360712-06f66a03-311a-4227-b6a6-237dfad15319.png)

**Expected:**
<img width="558" alt="text-2-7ab187a103381abe68b2d0fa94ba6dab" src="https://user-images.githubusercontent.com/5113782/203360833-3777665c-78e5-436b-9434-ce44a1101b5d.png">

**Comment by alixander** [comment]
docs now make it clear of the rendering engine that was used
