### ISSUE TITLE
tooltip/link icons for some shapes appear floating

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1391]
original: https://github.com/terrastruct/d2/issues/1276

![Screen Shot 2023-06-09 at 2 15 22 PM](https://github.com/terrastruct/d2/assets/3120367/875e62d2-07d1-4e96-8819-689833d43c2d)

**Comment by alixander** [comment]
this case is especially bad, where it looks like the links are on the next object!

<img width="769" alt="Screen Shot 2023-06-28 at 2 31 17 PM" src="https://github.com/terrastruct/d2/assets/3120367/12dc3c1e-f68c-44ea-9a2e-4357262b0dd1">

**Comment by bo-ku-ra** [comment]
https://github.com/terrastruct/d2/issues/1211#issuecomment-1587302425

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=qrRSSMvPT0osUqjmUlAAudhKIaOkpMBKX7-8vFwvPT8_PSdVLzk_l0tBAWoeTAfX48YmrCgm73FjCzEIpLCNVARyp4ICONSsFEAeBvPxuxzT7QoKtVy1XIAAAAD__w%3D%3D&
