### ISSUE TITLE
imports: utf-16 file from utf-8

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1395]
original ask: https://github.com/terrastruct/d2/issues/1388#issuecomment-1585417858

<img width="591" alt="Screen Shot 2023-06-09 at 8 41 07 PM" src="https://github.com/terrastruct/d2/assets/3120367/a1b92a19-10bb-45ec-bde1-1159aa3912b6">

**Comment by alixander** [comment]
```
it's impossible to reliably detect utf-16 vs utf-8

there's no standard header you can look at

it'd be a bunch of unreliable hacks to try and tell
```

**Comment by bo-ku-ra** [comment]
i think just need a way to avoid it.
it should be possible to write hex numbers directly in the d2 source.

ex.

```perl```
printf ("\x82\xa0.d2"); #あ.d2 (cp932)

```d2```
"%82%a0.d2" # this file-name is not '%82%a0.d2'. it is 'あ.d2'

**Comment by bo-ku-ra** [comment]
you can ignore utf-16.
d2 works under 'cmd.com'. so it is cp932(s-jis).
d2 source is utf-8.
i am talking about this gap.

**Comment by alixander** [comment]
@bo-ku-ra i still don't understand unfortunately. here's what i understood you meant, but it works for me:

<img width="440" alt="Screen Shot 2023-06-09 at 11 23 27 PM" src="https://github.com/terrastruct/d2/assets/3120367/327df4b8-6723-44a8-9439-36549c12a1c5">

**Comment by bo-ku-ra** [comment]
i'm sorry. it seems that the upgrade failed.
v0.5.1 seems to work correctly.

**Comment by bo-ku-ra** [comment]
https://github.com/terrastruct/d2/issues/1064
