### ISSUE TITLE
Feature request: absolute import support

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1397]
when importing d2-file that define 'style' and 'classes', absolute path is better than relative path.

move "cccc.d2" "./bar/cccc.d2"

├─d2
│  │   bokura-config.d2
│  │ 
│  └─foo
│　　│   aaaaa.d2 (classes{ ...@../bokura-config.classes })
│　　│   bbbbb.d2 (classes{ ...@../bokura-config.classes })
│　　│  (ccccc.d2) <-OK
│　　│
│　　└─bar
│　　　ccccc.d2 (classes{ ...@```../```bokura-config.classes }) <- NG (```../../``` <-OK)

**Comment by bo-ku-ra** [comment]
i may want to put 'bokura-config.d2' on a network drive when i share it with my colleagues.

**Comment by bo-ku-ra** [comment]
doesn't it work on v0.6.0?

**Comment by alixander** [comment]
unfortunately not, didn't get to it

**Comment by tylerhartwig** [comment]
Just wanted to add a comment and say this is something I'd really appreciate from D2 as well, for similar reasons as the classes and style imports.

I'd also like to organize pieces of my diagrams in separate files, and then import them into the relevant diagram to avoid redundancies. Absolute imports would make this much easier and avoid the need to update relative paths if I were to change my directory structure

**Comment by alixander** [comment]
This will be in the next release, thank you all for patience

**Comment by bo-ku-ra** [comment]
is this not supported on 'windows'?

**Comment by alixander** [comment]
@bo-ku-ra it should, though I haven't tested it specifically. what are you seeing?

**Comment by bo-ku-ra** [comment]
@alixander am I wrong?
```
C:\
└─d2
　│ bokura-config.d2
　│
　└─foo
　　　 a.d2 ( ...@c:\d2\bokura-config ) # NG
　　　 b.d2 ( ...@c:/d2/bokura-config )  # NG
　　　 c.d2 ( ...@../bokura-config ) # OK
```

**Comment by bo-ku-ra** [comment]
please add this test pattern

```
C:\
└─d2
　│ bokura-config.d2
　│
　└─あ     <---( cp932 : windows japanese edition)
　　　 a.d2 <---( UTF-8/UTF-16 : d2 source file )
```
