### ISSUE TITLE
README: Switch to mp4

### ISSUE THREAD

**Issue by nhooyr** [terrastruct/d2#140]
See https://news.ycombinator.com/item?id=33705039

**Comment by nhooyr** [comment]
Maybe instead of a gif we use an mp4?

**Comment by alixander** [comment]
the mp4 UI in Github is ass though, and doesn't autoplay. maybe i'll just switch it back to full gif without the background like it was before

**Comment by nhooyr** [comment]
Def please revert.

**Comment by nhooyr** [comment]
I think the mp4 UI is fine and not autoplaying isn't a big deal and in fact good. It's nice to be able to press play and give it your attention.
