### ISSUE TITLE
grid doesn't obey styles

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1411]
```
DSL: {
  grid-columns: 2
  grid-gap: 0
  l: link :
  r: layers.x

  style: {
    opacity: 0.2
  }
}
```
<img width="1315" alt="Screen Shot 2023-06-15 at 2 30 30 PM" src="https://github.com/terrastruct/d2/assets/3120367/1db6b37d-3947-499d-b759-cdcb0cb659f2">

**Comment by gavin-ts** [comment]
children don't normally inherit parent styles, do we really want to make `grid` an exception?

![Screen Shot 2023-06-15 at 2 37 02 PM](https://github.com/terrastruct/d2/assets/85081687/cbed190c-c61b-4226-a7b8-838e1936530c)

```d2
DSL: {
  l: link:
  r: layers.x

  style: {
    opacity: 0.2
  }
}
```

**Comment by alixander** [comment]
oh ur right, oops
