### ISSUE TITLE
how do I define a "label" field in sql_table object?

### ISSUE THREAD

**Issue by imding** [terrastruct/d2#1419]
Hi, I'm trying to define the following SQL table:
```d2
TableName: {
    shape: sql_table
    id: String {constraint: primary_key}
    label: String
}
```
where `label` is an actual column, the D2 compiler is interpreting it as the label for the table in the graphical output:
![image](https://github.com/terrastruct/d2/assets/20434337/46308e63-ae48-4ebe-a3d8-b0ff17dbe607)

**Comment by alixander** [comment]
yeah sorry quotes should bypass the reserved nature of the keyword. it's an open wip

**Comment by imding** [comment]
thanks this is a good workaround!!
