### ISSUE TITLE
don't need 'root / (page num)'  for  pptx.

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1439]
\>d2 root.d2 root.```pptx```

i don't need 'root / (page num)'  for  pptx. i'd like its option.

![image](https://github.com/terrastruct/d2/assets/121328398/25b71c45-974a-4662-b441-d7e642f97853)

**Comment by alixander** [comment]
should add a flag to `--disable-nav`

**Comment by bo-ku-ra** [comment]
or reverse this action.
--force-nav
(--force-appendix)

**Comment by bo-ku-ra** [comment]
https://github.com/terrastruct/d2/issues/1440#issuecomment-1605952482

**Comment by alixander** [comment]
Let's roll this up into https://github.com/terrastruct/d2/issues/1644#issuecomment-1750120968

If the root label is empty, no nav should be added
