### ISSUE TITLE
how does it compare to mermaidjs?

### ISSUE THREAD

**Issue by ppwfx** [terrastruct/d2#145]
Hey,

I really enjoy mermaidjs. How is d2 different to it?

Best

**Comment by kquinsland** [comment]
Saw this on reddit this morning and came here to ask the same thing!

This looks a bit more full featured in that there's a binary that can be installed and an API whereas mermaid is just a spec and a JS library designed for integration with code blocks in MD.

There's a comparison tool linked in the readme: https://text-to-diagram.com/?b=mermaid

but if the readme had a image / table showing what https://text-to-diagram.com/ does but for all languages at the same time, that'd be a bit easier to see right away.

**Comment by alixander** [comment]
please refer to https://text-to-diagram.com for a comparison, including renders, syntax, features, license, everything
