### ISSUE TITLE
shape:person + multiple: true

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1458]
https://play.d2lang.com/?l=&script=srdSUHrc2KSkUM2loAB2ipVCQWpRcX4eiA-yQw_mBSuFkqLSVK5aLkAAAAD__w%3D%3D&

![image](https://github.com/terrastruct/d2/assets/121328398/d08d502c-000c-4447-b542-cecf97cbc896)

occurred again. @gavin-ts

**Comment by gavin-ts** [comment]
issue with corner is #1085

**Comment by bo-ku-ra** [comment]
oops.  #1085
