### ISSUE TITLE
Link in imported file results in incorrect html link

### ISSUE THREAD

**Issue by BarryNolte** [terrastruct/d2#1472]
Given files:

f1.d2
```d2
a: {
    link: f1.d2
}
```
main.d2
```d2
y: @f1

x -> y 
```
Run at command line:
```bash
d2 --watch main.d2
```
![image](https://github.com/terrastruct/d2/assets/4474173/9d41f042-e282-47fa-bbce-5d4bd6b1c2d0)

Link is:
http://127.0.0.1:41005/rootf1.d2

Should be:
http://127.0.0.1:41005/f1.d2

**Comment by alixander** [comment]
thx for the concrete example. will close in favor of this duplicate: https://github.com/terrastruct/d2/issues/1176
