### ISSUE TITLE
config vars

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1475]
- `d2-config` variables should be secondary to CLI flags and env vars, but used if not defined anywhere else
- `theme-colors` is an advanced feature that lets you override any theme variables, and can be used to design your own theme

```d2
vars: {
  d2-config: {
    theme: 123
    dark-theme: 123
    layout: elk
    sketch: false
    pad: 0
    theme-colors: {
      N1: "#FFF"
    }
  }
}
```

**Comment by soma-m** [comment]
Does this mean, I can have the config in a separate D2 file and import it into other files that contain only business logic?

**Comment by alixander** [comment]
yes.

configs.d2
```d2
theme: 123
dark-theme: 211
```

main.d2
```d2
vars: {
  d2-config: @configs
}
```
