### ISSUE TITLE
when/how did this test case become like this?

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1477]
<img width="798" alt="Screen Shot 2023-07-11 at 10 13 59 PM" src="https://github.com/terrastruct/d2/assets/3120367/6a2121b6-25df-4f74-a357-5789c3520655">

**Comment by gavin-ts** [comment]
https://github.com/terrastruct/d2/pull/1041/files#diff-abb1ddc7a0466134ef25b76175fb373d56bdc639c14c048adf083ce7ce0a9bf4

**Comment by alixander** [comment]
fixed now with gavin's pr
