### ISSUE TITLE
customize theme colors with d2-config var

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1487]
e.g. 

```d2
vars: {
  d2-config: {
    theme-colors: {
      N1: "#fff"
      AA1: blue
    }
  }
}
```

**Comment by soma-m** [comment]
Would we also be able to set the default `border-radius` for all elements in the `d2-config`?

**Comment by alixander** [comment]
no, that'll be [globs](https://github.com/terrastruct/d2/pull/1479)

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=SsvP50pKLOLi0rJSqOZSUAAbrYcS4lYKRgZctVxcafn5IJWAAAAA__8%3D&
