### ISSUE TITLE
generic links do not work in layers / imports

### ISSUE THREAD

**Issue by mkrinke24** [terrastruct/d2#1489]
```d2
# test.d2
x: I'm a Mac {
    link: /index.svg
}
```

```shell
d2 -l tala src/test.d2 out/test.svg
```

results in a svg with a link poiting to /index.svg

however

```d2
# test.d2
doh: {
    link: layers.test2
}

layers: {
    test2: @test2.d2
}
```

```d2
# test2.d2
x: I'm a Mac {
    link: /index.svg
   # link: http://example.com # doesnt work either
}
```

results in
> err: failed to compile: <path>/src/test2.d2:2:5: linked board not found

my expectation would be to use relative URIs (`../index.svg`), absolute URIs (`/index.svg`), absolute URLS (`http://example.com`, //example.com`) and d2-internal links in the same project as needed.

my current motivation is to place an "back to index" link on child diagrams, which doesnt work using layers, as layers cant handle cyclic imports (another bug or by design?)

any advice for a workaround would be appreciated ;)

**Comment by alixander** [comment]
Good catch, there was a bug here with imports where it was treating every nested link as another link to a D2 board.

By the way, there's a built-in feature for doing the "back to" you're referring to: https://d2lang.com/tour/linking/#parent-reference
