### ISSUE TITLE
tooltips are broken in the playground

### ISSUE THREAD

**Issue by freemansoft** [terrastruct/d2#1496]
The playground gives the first tooltip string to every item that has a tooltip.

The example on https://play.d2lang.com/?script=qlDQtVOo5AIEAAD__w%3D%3D& is broken when pasted into the editor on that page.  Both x and y get the same tooltip.

```
x: { tooltip: Total abstinence is easier than perfect moderation }
y: { tooltip: I can't make my satellite dish PAYMENTS! }
x -> y
```

Windows 11
Chrome

**Comment by alixander** [comment]
appreciate the report @freemansoft !

**Comment by freemansoft** [comment]
When will this get pushed to the playground?
