### ISSUE TITLE
Allow links and tooltips on connections

### ISSUE THREAD

**Issue by sontags** [terrastruct/d2#1497]
Currently, links and tooltips are ignored when placed on a connection:

```d2
a -> b: connects {
  link: "https://a-b.io/"
}
```
In my opinion there are a lot of use cases where additional info on a connection can be useful. Rather than adressing the issue by throwing errors (as described in https://github.com/terrastruct/d2/issues/1482) it would be beneficial to see these features being actually implemented.

An example: I use d2 to document systems and their dependencies. A systeme can refere to external system documetation via link. Connections are often a representation of a certain process. I would happily use links on connections to refer to process documentation.

**Comment by soma-m** [comment]
I would appreciate the ability to have links on connections as well.

For a system `A -> B` 

My use case is to show more details about the connection via tooltips and upon clicking the connection, I would like to link to a URL containing the data communicated between A and B

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=ggeaVRHId1wVCrq6CpkKunYKlVyZVgo1uSlcCgo2iQoZRalptkoZJSUFVvr65eXleun5-ek5qXrJ-blKdo9adr7f0W-jn2jHVcMFCAAA__8%3D&

**Comment by robinovitch61** [comment]
I would also really value a solution for this. PlantUML can do it as follows, but I want to use d2, not PlantUML:

```
@startuml
actor User
participant "Web Browser" as Browser
participant "Web Server" as Server

User -> Browser: Open Home Page [[https://example.com|hi]]
Browser -> Server: GET /home [[https://example.com/home|home link]]
Server --> Browser: 200 OK [[https://example.com/response|response link]]
Browser --> User: Display Home Page [[https://example.com/display|display link]]

@enduml
```

@bo-ku-ra those links seem broken - do you recall your workaround and could you share it in this thread?

**Comment by bo-ku-ra** [comment]
@robinovitch61 unfortunately, i don't remember.

for example
```d2
a -- url -> b

url: |md
  [connects](https://a-b.io/)
|
```

**Comment by huyz** [comment]
See current PR: https://github.com/terrastruct/d2/pull/1955
