### ISSUE TITLE
The examples of how to use d2 as a library in a go application do not work.

### ISSUE THREAD

**Issue by szehnder** [terrastruct/d2#1500]
The code examples for how to use D2 as a library do not work.  For example, the CompileOptions expect a different interface for Layout, not LayoutRenderer property.  The RenderOptions expect ints not int64.  

I'm digging through the source code to figure out a minimal example, but until I get unblocked I wanted to log this issue so you can hopefully take a look at it.

here's the import in my go.mod file

require oss.terrastruct.com/d2 v0.5.1

**Comment by alixander** [comment]
right sorry about that, it's undergone a bit of change for 0.6, and I haven't updated it yet. Will do shortly, thanks for flagging!

**Comment by alixander** [comment]
i just checked all of them and they do work. i did this by going into each directory in https://github.com/terrastruct/d2/tree/master/docs/examples/lib and running `go test .`.

Once we cut the release and you update to it (0.6), it should run smoothly
