### ISSUE TITLE
Person shape does not render label

### ISSUE THREAD

**Issue by activey** [terrastruct/d2#1520]
Hi,

Basically as title says ;) Label text is not included for node of shape "Person". Would it be possible to have it? :)

**Comment by alixander** [comment]
Hi @activey , can you give an example? 

https://play.d2lang.com/?script=SkwuySxLrdQDu8RKoSC1qDg_j4urwkqhmktBAVVUQQHsSSsFqCauWi5AAAAA__8%3D&

**Comment by alixander** [comment]
closing, will reopen if there's an example
