### ISSUE TITLE
Can't render images due to bug in d2 source

### ISSUE THREAD

**Issue by mark-summerfield** [terrastruct/d2#1524]
I'm using Go 1.20.7 on Debian 11.
I am using the example https://github.com/terrastruct/d2/tree/master/docs/examples/lib/1-d2lib
Here's the output when I try `go run .`:
```
/home/mark/opt/gows/pkg/mod/oss.terrastruct.com/d2@v0.6.0/lib/log/log.go:52:28: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Debug
/home/mark/opt/gows/pkg/mod/oss.terrastruct.com/d2@v0.6.0/lib/log/log.go:57:27: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Info
/home/mark/opt/gows/pkg/mod/oss.terrastruct.com/d2@v0.6.0/lib/log/log.go:62:27: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Warn
/home/mark/opt/gows/pkg/mod/oss.terrastruct.com/d2@v0.6.0/lib/log/log.go:67:28: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Error
/home/mark/opt/gows/pkg/mod/oss.terrastruct.com/d2@v0.6.0/lib/log/log.go:72:31: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Critical
/home/mark/opt/gows/pkg/mod/oss.terrastruct.com/d2@v0.6.0/lib/log/log.go:77:28: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Fatal
```

**Comment by mark-summerfield** [comment]
I tried adding these lines after `main() {`:
```go
	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))
	slog.SetDefault(logger)
```
but they didn't help.

But if I comment out the bodies of the functions `Debug, Info, Warn, Error, Critical, Fatal` in file `oss.terrastruct.com/d2@v0.6.0/lib/log/log.go`, then everything works fine. (Well apart from no logging of course!)

**Comment by alixander** [comment]
@mark-summerfield i think this is because slog made backward-incompatible changes without a major version bump. can you try changing your `go.mod`'s slog version to the one in D2? https://github.com/terrastruct/d2/blob/master/go.mod#L6

searching around, there's no way for us to lock onto that version =\. it's a todo to replace it

cc @nhooyr

**Comment by mark-summerfield** [comment]
I tried replacing
```
cdr.dev/slog v1.6.1
```
with 
```
cdr.dev/slog v1.4.2-0.20221206192828-e4803b10ae17
```
But as soon as I do `go run .` the `go.mod` file gets updated and the latter is replaced with the former and it doesn't work of course.

Is there any timeline for when this will be fixed in the D2 sources?

**Comment by alixander** [comment]
oh right you have to do `go mod tidy` after making that change.

And yes, it ought to be fixed, will use this issue to track -- ty!

**Comment by alixander** [comment]
it's been removed
