### ISSUE TITLE
release: chocolatey package for windows

### ISSUE THREAD

**Issue by nhooyr** [terrastruct/d2#154]
Related https://github.com/terrastruct/d2/issues/96

**Comment by iquiw** [comment]
I think they are not exclusive options as one might prefer some method over others.

Scoop is easy and suitable for portable packages, I setup it in [my bucket](https://github.com/iquiw/scoop-bucket/blob/master/bucket/d2.json).

I could submit PR to Scoop Main bucket if you want, maybe after `.exe` extension issue (https://github.com/terrastruct/d2/issues/388#issuecomment-1339780928) is solved.
Or feel free to use the above manifest JSON.

**Comment by iquiw** [comment]
Someone contributed to Scoop Main bucket and it's merged.
https://github.com/ScoopInstaller/Main/pull/4355

**Comment by TheCakeIsNaOH** [comment]
I've created a package: https://community.chocolatey.org/packages/d2
