### ISSUE TITLE
Invisible words when using Markdown explanation in a node

### ISSUE THREAD

**Issue by Necior** [terrastruct/d2#1540]
# Steps to reproduce

1. Open https://play.d2lang.com;
2. Paste the following snippet in the editor:
```d2
example: {
  explanation: |md
    *one* __two__ three!
  |
}
```
3. Compile the diagram.

# Observed behavior

The following image gets rendered:

![image](https://github.com/terrastruct/d2/assets/2404518/2e8408ec-9bd1-46d0-a0e8-8225feeab2bd)

Please note that the word "three" is not visible in the picture.

# Expected behavior

The word "three" _is_ visible in the picture.

# Additional comments

I've observed the same behavior in every available engine (Dagre, ELK, TALA). I've tried using D2 locally (with version `0.4.2`). The result is the same.

What is more, please note that changing "three" to a longer string (e.g. "threeeeeeee") will make the resulting node wider while the word is still invisible:

![image](https://github.com/terrastruct/d2/assets/2404518/af3ad634-5ba5-4aea-8ce2-bd58c36ee8d1)

**Comment by bo-ku-ra** [comment]
this is a strange specification for the D2 and has not been improved.
i add "\<br\/\>" to get around this.
i do not know why.

https://play.d2lang.com/?script=Sq1IzC3ISbVSqOZSUEitKMhJzEsEhaGVQk1uCpeCgoKCVn5eqpZCfHxJeX58vEJJRlFqqiJYwiapSN-OS0GhhquWCxAAAP__&

**Comment by alixander** [comment]
@Necior appreciate the 💯 bug report!
