### ISSUE TITLE
MathJax extensions can't be enabled

### ISSUE THREAD

**Issue by SV-97** [terrastruct/d2#1542]
# Description

I wanted to enable a mathjax extension (`ams`) due to running into a problem with unknown commands (`\substack` and `\mathclap`) however this currently seems to be impossible. In particular [the runtime import mechanism provided by MathJax in the form of `\require`](https://docs.mathjax.org/en/latest/input/tex/extensions.html)  does not work. (I also tried LaTeX's default `\usepackage` which usually works with mathjax and ran into the same problems).

# Reproducing the error

```d2
Linear program: {
  formula: |latex
    \\min_{ \\mathclap{\\substack{ x \\in \\mathbb{R}^n \\ x \geq 0 \\ Ax \leq b }}} c^T x
  |
}
```
yields `Undefined control sequence \substack`.

```d2
Linear program: {
  formula: |latex
    \\require(ams)
    \\min_{ \\mathclap{\\substack{ x \\in \\mathbb{R}^n \\ x \geq 0 \\ Ax \leq b }}} c^T x
  |
}
```
yields `Undefined control sequence \require`.

**Comment by alixander** [comment]
> In particular the runtime import mechanism provided by MathJax in the form of \require does not work.

Right, D2 packages Mathjax at compile-time, so the extensions cannot be dynamically imported. 

I'll make a note of this in the docs. In the meantime, ASM looks useful, I included it and used your equation as a test: https://github.com/terrastruct/d2/pull/1544

@SV-97

**Comment by SV-97** [comment]
Thanks for the quick fix! I just noticed that my example was a bit off as the `\\`s inside the substack should've really been `\\\\`s so that it renders something like this:

![substack_example](https://github.com/terrastruct/d2/assets/13320149/ecaa5c0b-9c9a-4ca9-a518-76991e37f6e1)

Although I guess the other variant also works as a basic test.
