### ISSUE TITLE
shape: geo

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1549]
`shape: geo` would set a background of a map with bounds defined by nodes. connections can just use direct lines? (which, mapped out on a map, turn into curves).

i suspect this should be a plugin.

```d2
map: {
  shape: geo
  r1: New York {
    top: 12.43
    left: -75.33
  }
  r2: SF {
    top: 11.32
    left: -742.2
  }

  r1 -> r2
}
```

![weathermap](https://github.com/terrastruct/d2/assets/3120367/2b23276f-044b-4c99-941d-bfab08559bc8)

**Comment by bo-ku-ra** [comment]
what are the advantages over Google Maps?
https://developers.google.com/maps/documentation/javascript/examples/polyline-simple

**Comment by alixander** [comment]
yeah should be a plugin at most
