### ISSUE TITLE
Flag to enable/disable wrapping in another SVG

### ISSUE THREAD

**Issue by vfosnar** [terrastruct/d2#1564]
Gecko (not sure abt. chromium) requires both width and height attributes on the root SVG element to render it to a canvas.

These are missing by default in the wrapping container to allow scaling AFAIK.

Add a flag that removes the wrapping SVG container to allow external programs to render the SVG to a canvas.

**Comment by gavin-ts** [comment]
I think this may be fixed by running d2 with `--scale=1` which should include the width and height on the outer SVG

**Comment by vfosnar** [comment]
Thank you<3 that works! Dunno why I missed the flag.
