### ISSUE TITLE
D2 is being built with Go 1.19.3 in the Docker image and binary release

### ISSUE THREAD

**Issue by fvichot** [terrastruct/d2#1566]
The Go version used to build the Linux Docker image of D2 is [hardcoded](https://github.com/terrastruct/d2/blob/c67098751655b7cec1b214ff421b59c8de5271c5/ci/release/build_in_docker.sh#L7) to use 1.19.3, which has a couple of critical CVEs, which means the latest (0.6.0) docker image and the binary release are getting flagged by our container scanning tools.

Could we remove or update the hardcoded version to 1.20 ?

**Comment by alixander** [comment]
thank you for surfacing this @fvichot
