### ISSUE TITLE
globs: "exists" filter

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1567]
e.g. target all shapes that have links, or all connections that have labels.

not sure how it'll be represented in the syntax

**Comment by alixander** [comment]
oh this can just use globs within.

this would filter for existence of link
```d2
*: {
  &link: *
}
```

i think we need a "not" operator too. maybe `!`? not sure. @nhooyr any thoughts?
```d2
*: {
  !&link: *
}
```

**Comment by asanjabi** [comment]
```!``` seems like a reasonable symbol for "not" operator.  What would the syntax look like for nulling all shapes that don't have a connection?  ```(** !-> *)[*]: null``` ?

**Comment by alixander** [comment]
we'd just introduce a keyword for that. something like

```d2
*: null {
  &connected: false
}
```

**Comment by nhooyr** [comment]
Seems reasonable to have `!&` to me.

**Comment by bo-ku-ra** [comment]
i prefer this one.
```d2
&connected: false {
  *: null
}
```

**Comment by XoL1507** [comment]
sorry

**Comment by gavin-ts** [comment]
Regarding globs for selecting all existing edges:

I tried `* -> *` but this creates edges between all shapes and does not apply to existing edges, interestingly `(* -> *)[*]` does apply only to existing edges. 

I think https://d2lang.com/tour/globs#glob-connections needs a note to clarify that *the parens + brackets syntax is needed to select existing edges*`(* -> *)[*]`. It is present in the example but a explicit note would make it clear.

<img width="1199" alt="Screenshot 2023-09-21 at 11 10 57 AM" src="https://github.com/terrastruct/d2/assets/85081687/011a0851-ac81-46de-941c-4e8c9954ab6d">


https://play.d2lang.com/?l=&script=ys9LtVKo5lJQSFTQtVNIAhHJICKFi0tBQQvE0oLIKyiAbdWDuMNKoSg1hUtBoZarlourpDwftxkaEEM0o7ViCRkECAAA__8%3D&

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/issues/1567#issuecomment-1693860826

https://github.com/terrastruct/d2/issues/2010
