### ISSUE TITLE
Nested Layer link limit

### ISSUE THREAD

**Issue by jlnrrg** [terrastruct/d2#1580]
Might be related to #1407, but as this example does not uses the spread operator, I thought it could be part of a different issue:

It seems that at a certain point layer links to other boards are not supported.
Expected Result: everything is rendert as intended. The components hold links to the other boards.
Real Result: `err: failed to compile: b/c/c.d2:1:1: linked board not found`

Folder Structure
```bash
.
├── a.d2
└── b/
    ├── b.d2
    └── c/
        ├── c.d2
        └── d/
            └── d.d2
```

a.d2
```d2
a.link: layers.b

layers {
    b: @b/b
}
```

b/b.d2
```d2
b.link: layers.c

layers {
    c: @c/c
}
```

b/c/c.d2
```d2
c.link: layers.d

layers {
    d: @d/d
}
```

b/c/d/d.d2
```d2
d
```

Example: 
[test.zip](https://github.com/terrastruct/d2/files/12574207/test.zip)

**Comment by gavin-ts** [comment]
@nhooyr for some reason it looks like the compiled IR link has `layers.c` duplicated. (In my example I made layer d a static `ok` to simplify but the issue still exists).

```
a: {
  link: root.layers.b
}
layers: {
  b: {
    b: {
      link: root.layers.b.layers.c
    }
    layers: {
      c: {
        c: {
          link: root.layers.b.layers.c.layers.c.layers.d
        }
        layers: {
          d: {
            ok
          }
        }
      }
    }
  }
}
```

**Comment by alixander** [comment]
i'll take this
