### ISSUE TITLE
how to make `shape: step` for Dagre/ELK like in Tala

### ISSUE THREAD

**Issue by italovieira** [terrastruct/d2#1585]
Is there any way to make `shape: step` works like intended for Dagre and ELK as is in Tala?

Example in Dagre:
![d2](https://github.com/terrastruct/d2/assets/8337230/757f2eb4-bfdf-4e11-9064-0cc0fd657b82)

Example in Tala:
![d2](https://github.com/terrastruct/d2/assets/8337230/ebd6de03-7c13-407a-adcc-8999290c6906)

Code used 
```
x -> y -> z
*.shape: step
```

**Comment by alixander** [comment]
unfortunately not. in this example, it would, but let's say you had

```d2
step1 -> step2

step*.shape: step

step1 -> a
step1 -> b
step2 -> b
```

Dagre and ELK place step1 and step2 in specific locations according to their graph algorithms. We cannot change their positions without layouts breaking.

**Comment by bo-ku-ra** [comment]
is this possible?
![image](https://github.com/terrastruct/d2/assets/121328398/d6d5889b-d09d-4a7f-9d8b-66b8ba47b397)
``` d2
s: "" {
  style.opacity: 0
  grid-rows: 1
  grid-gap: 0
  x: {shape: step}
  y: {shape: step}
  z: {shape: step}
}

s -> a
s -> b
s -> b
```

**Comment by alixander** [comment]
Yeah something like that would work. In general, I think using grids in parts of the diagram will help hack a lot of these situations: https://github.com/terrastruct/d2/pull/1586
