### ISSUE TITLE
Layers example only compiles once

### ISSUE THREAD

**Issue by huyz** [terrastruct/d2#1587]
If you take the example at https://d2lang.com/tour/layers and paste it into the [playground](https://play.d2lang.com/), the example will compile the first time.

But then if you click `Compile` again, you will get `cannot refer to root in link` errors:
![screenshot 2023-09-13T102924Z](https://github.com/terrastruct/d2/assets/128394/f5a9063a-c190-49c1-99ff-52e272d75721)

~~I get the same error in VS Code, except I can't get the example to compile even the first time there.~~ [Update: that was just because I had copied-and-pasted the rewritten and broken code. See next comment for the real cause of the issue]

**Comment by huyz** [comment]
Ah it looks like hitting "Compile" rewrites the code and breaks it.

**Comment by gavin-ts** [comment]
looks related to #1580

**Comment by alixander** [comment]
fixed

**Comment by huyz** [comment]
@alixander you're on a roll!. Thanks bro
