### ISSUE TITLE
failed to recompile: Diagram with path robots not found

### ISSUE THREAD

**Issue by rucciva** [terrastruct/d2#1588]
Hi, after upgrading to 0.6.0, watch feature failed with the following error when using chrome:

```
info: broadcasting update to 1 client
info: detected change in graph.d2: recompiling...
err: failed to recompile: Diagram with path robots not found
info: broadcasting update to 1 client
```

I see the following message on the websocket channel
```
{"svg":"","scale":null,"err":"failed to recompile: Diagram with path robots not found"}
```

Meanwhile when using firefox, the error message doesn't appear

**Comment by alixander** [comment]
There's not enough information, can you post your D2 file? @rucciva 

It's unlikely this is a browser-specific issue.

**Comment by rucciva** [comment]
a simple sequence diagram like this trigger the error

```
shape: sequence_diagram
a -> b
```

**Comment by rucciva** [comment]
i found the culprit, it was [this](https://chrome.google.com/webstore/detail/link-redirect-trace/nnpljppamoaalgkieeciijbcccohlpoh) chrome extension. disabling it remove the error.

Though this is not a problem in previous release
