### ISSUE TITLE
markdown: Background is black when system setting is dark mode

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#159]
force system preference to be dark mode and run this

```
cloud: {
    a1: AWS
    a2:{
        shape:sql_table
        blob
        tob
    }
}

cloud.a1--cloud.a2
explanation: |md
  # I can do headers
  - lists
  - lists

  And other normal markdown stuff
|
```

<img width="402" alt="Screen Shot 2022-11-22 at 2 18 25 PM" src="https://user-images.githubusercontent.com/3120367/203432880-02728952-baba-403b-8d2b-293338522ae4.png">

**Comment by nhooyr** [comment]
Should we have the output SVGs obey dark mode?

**Comment by alixander** [comment]
nah, i don't want exports changing depending on time of day
