### ISSUE TITLE
Error "null to object at" while compiling dagre layout, ELK and TALAworks

### ISSUE THREAD

**Issue by Palkers76** [terrastruct/d2#1595]
I got this error in vs code and playground
I'm foing ERD with 
Errors
err: failed to compile: failed to dagre layout: TypeError: Cannot convert undefined or null to object at :635:423(9)

error is not returning line so it was hard to debug, but finally I found that it was because of missing entities used in relationship, 
I found that ELK and TALA engines can create box even if missing.
I'm not expecting degre to do the same but it could at least point the line where the issue is , or return the object name so it's faster to find the root cause if you have big model if you don't know where to look at it's hard.

now I'm smarter so won't make same mistake again.

**Comment by alixander** [comment]
@Palkers76 are you able to share a script reproducing it? if private can email us (alex@terrastruct.com). if super private, no worries, appreciate the report

**Comment by alixander** [comment]
cannot reproduce
