### ISSUE TITLE
compiler: Validate reserved keyword value types

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1596]
```d2
foobar: {
  top
  bottom
  left
  right
}
```
https://play.d2lang.com/?l=&script=SsvPT0osslKo5lJQKMkv4FJQSMovKcnP5VJQAHmDS0GhCORrrlouQAAAAP__&

**Comment by alixander** [comment]
ah interesting, shoudl verify that reserved keywords need values
