### ISSUE TITLE
markdown: Tables

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#160]
Currently tables within markdown are not supported. Need to hand-measure these https://github.com/terrastruct/d2/blob/master/d2renderers/textmeasure/markdown.go

**Comment by alixander** [comment]
sql_table shape won't suffice because it doesn't support multiple columns

**Comment by alixander** [comment]
https://discord.com/channels/1039184639652265985/1039184640285610147/1054867819256361060

**Comment by alixander** [comment]
perhaps d2 should have a native shape type for this. `sql_table_data`

**Comment by jfudickar** [comment]
I would name it not sql_data_table because it could be handy to use it for multiple purpose.
But I would be happy to see something like this!!

**Comment by gavin-ts** [comment]
that could work but it might be tricky to fit it into other markdown elements. I wonder why it isn't currently working, we may just need to update the measurement logic to consider tables correctly

to be clear, for this issue I think we are talking about:

```
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
```

producing: 

| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |

**Comment by alixander** [comment]
no i was just talking about representing tables in general. if we have such an option natively in D2, there's no need or a much lower priority to support it in markdown

**Comment by gavin-ts** [comment]
oh okay that makes sense with the comment about having a native shape for tables

I think a `gap: 0` grid with rows and columns specified does indeed cover the table scenario

**Comment by jfudickar** [comment]
I want to draw diagrams similar to this:
[](https://github.com/jfudickar/json2puml/blob/main/documentation/images/rocket/rocket_5e9d0d95eda69973a809d1ec.default.svg)

Currently I'm using PlantUML but I'm thinking of having an additional option using D2.

https://github.com/jfudickar/json2puml

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=yk3NzbeqyU3hsilJTMpJteOyKSmysylJsUvLz09KLLLRL0mxs9EvKbLjstGHqqjh4gIEAAD__w%3D%3D&

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/pull/2221
