### ISSUE TITLE
Idea: possibility to setup default shape per diagram, 

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1600]
After a 1st round of testing I want to share my suggestions
this is the 1st one.

# setup a shape once 
shape: sql_table

  # and use indentation or {} to identify entities foling under this shape type
  my_table: {
    # This is defined using the shorthand syntax for labels discussed in the containers section.
    # But here it's for the type of a constraint.
    # The id field becomes a map that looks like {type: int; constraint: primary_key}
    id: int {constraint: primary_key}
    last_updated: timestamp with time zone
  }

or some other way.

**Comment by gavin-ts** [comment]
I think you can achieve this with `*.shape: sql_table` https://d2lang.com/tour/globs#scoped-globs

**Comment by ppalka-lingaro** [comment]
Thanks, it's adding grouping, but I presume that color can be changed to white or transparent to remove it.
I'm getting like this framework a lot

**Comment by alixander** [comment]
appreciate the kind words but please search issues/docs before creating issues @ppalka-lingaro , a search for "default" shows many results
