### ISSUE TITLE
Idea: simplify crow's foot relationship settings between sql tables

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1601]
instead of this  
customer.billing_address_id <-> address.id: has {
    source-arrowhead.shape: cf-one
    target-arrowhead.shape: cf-many
  }

could be something like:

customer.billing_address_id <-> address.id: has {
    cf-one <-> cf-many
  }

or even something like below using some aliases 
customer.billing_address_id <-> address.id: has {
    cfs:one
    cft:many
  }

I know it might be difficult because it's declaring shape for each arrowhead separately for each entity but want to know what do you thing about this and if more people will find this helpfull and will support idea :)

**Comment by gavin-ts** [comment]
interesting suggestion, this isn't built in, but I think classes or variables could achieve this:

```d2

classes: {
  cfs-one: {
    source-arrowhead.shape: cf-one
  }
  cft-many: {
    target-arrowhead.shape: cf-many
  }
}

a <-> b : {
  class: [cfs-one; cft-many]
}
```

or maybe variables

```d2

vars: {
  cfs-one: {
    source-arrowhead.shape: cf-one
  }
  cft-many: {
    target-arrowhead.shape: cf-many
  }
}

a <-> b : {
 ...${cfs-one}
 ...${cft-many}
}
```

**Comment by ppalka-lingaro** [comment]
> ```d2
>  ...${cfs-one}
>  ...${cft-many}
> ```

class works like a charm
variables are not, compile on playgroud is hanging

  category.parent_category_id <-> category.id: "parent_of" {
    ${cfs-one}
    ${cft-one}
  }
