### ISSUE TITLE
SQL_Schema column name same as tooltip, shape,top or other objects 

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1607]
what if I have column name in entity same as one of the following

- tooltip
- shape
- top

or other used by d2?

I tried the following and do not show column, please advice

  dim_address: {
    address_id: STRING {constraint: primary_key}
    city: STRING
    zip_code: STRING
    country: STRING
    state: STRING
    top: INT
    top: 222
    left: 0
  }

![image](https://github.com/terrastruct/d2/assets/134058357/317f62f6-8e6f-4b22-9afa-cf40908438d8)

**Comment by ppalka-lingaro** [comment]
Thanks

**Comment by alixander** [comment]
fixed in next release by quoting
