### ISSUE TITLE
how I can upload mine and my team icons ?

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1626]
how I can upload mine and my team icons to https://icons.terrastruct.com/?
according to this article and notes on icon page it should be possible, but can't find option to load it?
https://d2lang.com/tour/studio/#example

can someone advice ?

**Comment by mrsaiz** [comment]
To take advantage of the 'Uploads' feature in Terrastruct, you'll need a valid Terrastruct subscription

From the console, by clicking the next icon you will see `Uploads` button. Click on it to initiate the upload process.
<img width="2560" alt="image" src="https://github.com/terrastruct/d2/assets/38693330/392d477a-481a-4f52-b0b8-19b317d6bcf6">


**Keyboard Shortcut:**
If you prefer using keyboard shortcuts, you can press Ctrl (or Cmd on Mac) + I to trigger the 'Uploads' process.


Moreover, @alixander, has created an [issue](https://github.com/terrastruct/d2-studio-issue-tracker/issues/28) aimed at improving the discoverability of this feature within D2 Studio.

**Comment by alixander** [comment]
closed by https://github.com/terrastruct/d2-studio-issue-tracker/issues/28
