### ISSUE TITLE
is there a way to create rectangle shape with icon and text inside GCP style?

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1627]
I was thinking about something like used GCP but not only where you have a square or rectangle with icon in the middle or left and text
example:
![image](https://github.com/terrastruct/d2/assets/134058357/f75236d1-5cdd-4a91-b635-36c5a0d0aa04)

**Comment by alixander** [comment]
![Screen Shot 2023-09-27 at 3 26 13 PM](https://github.com/terrastruct/d2/assets/3120367/7b09e896-f239-44d4-99e7-37ab8e218908)

https://play.d2lang.com/?script=bFJRa8MgGHz_fsXRkpfATPDRh0EHKxQ2KOwXWCNGSIyoLd2W_vehXZM97OXwu09P7rjfJAW-CVDT6CenXbqPwN88BHjhilGBzYaAG92IalZExPqcapaD4QUF-pR8FE2Tp8iSDkHGFM4qMTWNjVG-4vtjmLqzSrHirXRdxduow8UqHSu-3x0W9l2q3jpd8fZNy-CsM4_9cZApG2fxYpb_S74CdpRGL-RqoGa5N8H63BqBeewI2OJlkD1Og-yL3-2dKOfTY7MCzURXPD3jM8MX0fV_0YMzOiYqejvv8eqMdZqAjxS0HK0zUL3Ml2imnwAAAP__&

```d2
classes: {
  component: {
    grid-columns: 2
    label: ""
  }
}

*.class: component
*.icon2.icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAI%20and%20Machine%20Learning%2FAI%20Platform.svg
*.icon2.shape: image
*.icon2.label: ""
*.description: |md
  # Blah blah
    ## Blah
    blah blah blah blah
|

x -> y -> z

x.description: |md
  # Ingest
  ## App Engine
  Streaming changes
|
```

**Comment by ppalka-lingaro** [comment]
Thanks that is very helpfull, but is there a way to have icon and default md defined in class, md is not so important but I want to have icon per class
I tried myself, but nothing seems to be working as expected
this one works so so, but icon is small and on the top, I like the bigger one :)
Thanks again for helping
![image](https://github.com/terrastruct/d2/assets/134058357/a058f97e-2352-4643-93bb-db9be4b821fd)

classes: {
  gml: {
    grid-columns: 2
    label: "google ML"
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAI%20and%20Machine%20Learning%2FAI%20Platform.svg
    *.icon2.shape: image
    *.icon2.label: ""
    *.description: ""
  }
}
*.class: gml

x -> y -> z

x.description: |md
  # Ingest
  ## App Engine
  Streaming changes
|

**Comment by alixander** [comment]
```d2
classes: {
  gml: {
    grid-columns: 2
    label: "google ML"
  }
  icon2: {
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAI%20and%20Machine%20Learning%2FAI%20Platform.svg
    shape: image
    label: ""
  }
}
*.class: gml
*.icon2.class: icon2

x -> y -> z

x.description: |md
  # Ingest
  ## App Engine
  Streaming changes
|
```

https://play.d2lang.com/?script=VFJBasMwELzvK4YEXwJVjI46FHJoIJBAoC8QslgLbNlISkjb5O9llbq0F7EzktiZYX6SNPgigMfhOQB_kzDQlasWDVY8TTx4nI4rAh4ESAp6-SnAoC9lzma7FZRV8SnZXNLFFeWmcctubvT-nKbu4kpudGtj1-g2-3QNzudG73eHX_ZkXR-ib3R79DbFEHm5Pw-2iFmVr1x31zwNwmjZ_5P8VPqgjaqGjViljarCF6oCohteXvEhxyfRTUmzUpilVwb3sSNgjUNkn4uMa-zmGW-RQ5SN7yV5O4bIcL2VR3Sn7wAAAP__&

**Comment by ppalka-lingaro** [comment]
Thanks,
could you explain how that works ?
I understand: *.class: gml

but not sure what is the *.icon2. means
*.icon2.class: icon2

I used other strings and also works
*.asdasdasd.class: icon2

**Comment by alixander** [comment]
`icon` is a reserved keyword, so I give another name to the object that you want looking like an icon but is actually a child image, thus `icon2`. Nothing special about the name

**Comment by ppalka-lingaro** [comment]
thanks, one more thing
is there a way to wrap text to i.e 2 lines? I have sometimes long names of icons
![image](https://github.com/terrastruct/d2/assets/134058357/56472b1f-e973-40df-bddb-a5d523346f0d)

**Comment by alixander** [comment]
yes just search docs first please: https://d2lang.com/tour/troubleshoot/#the-text-is-rendered-too-widelong

**Comment by ppalka-lingaro** [comment]
I tried to use same code in vs code and preview giving different result, no icon, any idea?

![image](https://github.com/terrastruct/d2/assets/134058357/80b421ee-4118-4a95-a36a-e9839b3a336d)

**Comment by alixander** [comment]
Maybe icons aren't showing up in vscode plugin for some reason. Can you post in https://github.com/terrastruct/d2-vscode
