### ISSUE TITLE
is there a way to include conditional formulas in code?

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1630]
in plantuml there is a way to do Preprocessing where we can use some boolean and if then else 

@startuml
!$a = 10
!$ijk = "foo"
Alice -> Bob : A
!if ($ijk == "foo") && ($a+10>=4)
Alice -> Bob : yes
!else
Alice -> Bob : This should not appear
!endif
Alice -> Bob : B
@enduml

**Comment by alixander** [comment]
correct, we will not be implementing a pseudo-scripting language, these will be done in embedded Go or Lua
