### ISSUE TITLE
Force Arrow direction

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1635]
Add arrow directions may help to render nicer ERD diagrams for star schema
or force direction of links
In combination with phantom edge will be great toolset to control location of elements.

![image](https://github.com/terrastruct/d2/assets/134058357/0074d5f9-edf3-4fdc-954a-bd895d3744b1)

Arrows -u-> Up 
Arrows -d-> Down
Arrows -l-> Left
Arrows -r-> Right

**Comment by alixander** [comment]
this type of control just isn't possible in current layout engines. except for TALA, which already has an issue: https://github.com/terrastruct/TALA/issues/35
