### ISSUE TITLE
element with multiple lines and icon in middle

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1639]
for few reasons I want to reproduce similar element
![image](https://github.com/terrastruct/d2/assets/134058357/ef3b1e9e-9529-49e2-bb66-946fed2edb2a)

I experimented with few options and almost got it, however code is too long,
also it would be hard imho to change it into class. 
maybe there is some way to pass  parameters like Title, Desc to class?
Please advice 
![image](https://github.com/terrastruct/d2/assets/134058357/7d4b0931-5a57-4435-910c-5b0fbb6df2fc)

link to playbook:
https://play.d2lang.com/?script=tFQ9T_MwEN79K543ryrBkoaE6TZExYwEG2IwrhUsmjTYTiWg-e_oLmnahooBwRTdnX3PR-48OEn4UMBCR_3knXkZYoD1EZ5jbALN5xyFNFrvdYi-NTE162qu31tvZ_nNVa1Xb9GZMMuzO-s3zthZnl2zwVztT2V7jDRsSgERFwiu0qWVhHhJSOTOAatEAZ3qlGraiutcwa1fGxuCq8sLJEKbh8G7hkeBsK2W0nPaS5LAv4fHs7-TB5wPOAsbjAK2apQbXlvtLauZyMh788e5IxS7sNQNIVPAvYsruxf3_5Q8xlqOifyUn8NfliGg49vdYGRxiDKq-Mq6-DXWR7R_wJpJslr-Jrs4lZ1JefsJsiWN9raOk3q_Zd-dGN8KwmWmOvUZAAD__w%3D%3D&layout=tala&

**Comment by gavin-ts** [comment]
hmm you can try to create a template with a `vars` declaration, then override specific values each time you use it with `...${var}`

```d2
Data Processing6: <<Databricks>> {
  ...${Reuse}

  title.label: |md # Sixth Stack |
}
```

<img width="514" alt="Screenshot 2023-10-04 at 6 01 21 PM" src="https://github.com/terrastruct/d2/assets/85081687/f9a06ae5-1361-4f18-8792-c5cb8bf94b34">


Here's an example: 
https://play.d2lang.com/?script=dJRhb9MwEIa_51e8aqgEEku7QtFkTUOIqV-HKH_ATa6J1SSu7EuhrPvvyOc0zaB8S-7O5_ee9-SepMJzAjxq1htn8l3_D4T5FCrmvVezWfjzGZNz2rPrcs5y28z0787RdLH60ur6yCb308V8Te5gcpou5l8D4JCNVfPLHZk_lHKJUFAwjS5JAsJSYSJnRqomCfCSvCRhkqjwO3WezmIHpxQ-XAKl3iss5hJgwzUpnJoCKf7ujlMcuSkzoaJGuSEj0rLgqILt2JsiLBqzbW5yapncUCkmZZclUyidPko6bKsz-7CrvZh0HENFjno1fRdTBx7p7e1qdXc3GWeu9Y-puJcK7DrqwSVhInxzNifvTVt-jOiyLHvzLCivFS3_LUqAFFwZD0_UeLDFhmAP5JwpCmqxOUZr8Pbzu_fYdBzRR3z4aZ0gTceGMHnGCaH3qPZs1simw1LYDG4oLJNXTEcnBUeKldlyJT2wH-ZKJHmDbUj23z-eHp_gzS8JnK7A-KRwf38R8_BwnU1t7c6jNjsCV-QJLVHRY6qNZyqgS21abK0LFZC3qi_IrQsv2RlEnPX1iP-htA7KsWad70T9nwAAAP__&layout=tala&sketch=1&

**Comment by ppalka-lingaro** [comment]
This is great, but the problem is that in every object people will have to include variable

The shortes I was able to achieve is , creating common variable with style :) [link](https://play.d2lang.com/?script=1FVfT9swEH_Pp_gpodImQWjDNiELMU1DlSZNIhps7256pBZJU9kXto72u0-2QwgQsYx1D3ur7y7n35_ztVFS4DYAziTLmVbZdXMGLD-BBfPKiMNDezIxk9bSsK4zjrOqPJQ_a02jZPphKYs1q8yMkvEF6RuV0SgZf7QC26yvGt_fEZubvL0kdvrFViqBqmaj5tZB5qo8yGjJpF2pE0xAlTInF3CfCYSufYdAGADbhhI-LZlyLe1s7J6YvWGUjKcy40or-le04C9YPyD2WV7TSxg5naShZxnZ5jsl00L2HLZBYEfS4_9aFk-nr316Akf3gVyuBJKxh1XmsRth0fG-zQzDayvdi4rvN4JAruXape1q0Wrlh2dTzhFF3RgWpAkbz9x3UYVlG00m0-nxcdjN9PX3Kb9EBFjX1Dhcl8WFzQ1XY5f3b4PA-ZXqKiNj1DJ_44HEcbx3e4etr-5tp-6BrdsgACLwQhkYotKAK8wI1Q1preZzWmK2xheqDeHV-9f7mNUMVlyQdxLfK-3cjXzU28FkGBvY3p3axir_TC7vtqJbAc6sdjweDU7H2U4jJ1SEqbrihW-5aum63AGubK75fXl-dg6jfrjApkeidwInJy52wZWWOZ2e9mn7x4z6nkI_I0Q4XzHOyGQdhA2av0DXfNGHyD39lwFKHiNKXgApeQ7U0HUxEHwYhsH__tfaUWovnbjQE3X30kmz-4bv2yESNivo9zOAMJ3gmyxqCveBME3aQ5geNb-DYOsM-RUAAP__&layout=dagre&theme=0&sketch=1&)
I tried to move   img.label.near: outside-bottom-center to class
as 
  icon.label.near: outside-bottom-center
generation is not failing but label is no properly justify 

```
Data Storage2: <<Data Storage2>> {
  ...${umlStyle}
  title.label: |md # Storage 2 |
  img.class: Data Lake
  img.label.near: outside-bottom-center
  description.label: |md # Opt Desc |
}
```
I think it would be very powerful to be able to create class or function which will get parameters as inputs
[Link to proposal](https://play.d2lang.com/?script=jJLLbvIwEIX3fooj_7D5RU0IG2QhpArEtkg8gWus1GouyJ4g0ZB3ryaBBLHq0nPGc_nm3ElqNALYGTKfwdvv-xvg_TS-iM5Rz-f8iopcCCZSqC0pWxVz81MHN03376XJr-RtnKbJ0YWLt26aJlsGzGqflYw9VLxkQxPV8VOMSqOqKfoTX5CoKt6sK8mFLrUDpuELk7n-b5GpbgeNSXNYtF2QPOWur6hxK04spS1uw4-_NWNTBX9mS70UW3IxAbSiFYK59rzqIj_yaR70ButoLMdAZs4aadLvw-mKPakh_y0W-_1qJZ-VwaMaWTDXJ6m3nQaF2j1G-a-UUpPmMUcrmDYOobIuRl9mGuv1S2izQSPHo8gZILe5MyWLcgb50QEwOXYuWtmK3wAAAP__&layout=tala&theme=0&sketch=1&)

**Comment by danielsitnik** [comment]
@ppalka-lingaro hello.
I'm also interested in having a layout more close to what is possible with PlantUML.

Sadly, all the playground links that you and the other guys shared here no longer work. 😢 

Do you still have a working example that you could share with me?
Thanks!
