### ISSUE TITLE
feat: `label` at board level

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1644]
Especially useful for root board.

Users should be able to rename this.

![Screen Shot 2023-10-05 at 11 43 11 AM](https://github.com/terrastruct/d2/assets/3120367/2bbf6439-bca1-4892-bd92-827175ab8670)

**Comment by bo-ku-ra** [comment]
and #1439

**Comment by alixander** [comment]
make sure to remove nav is root label is empty

https://github.com/terrastruct/d2/issues/1439#issuecomment-1751459357
