### ISSUE TITLE
default triangle arrowhead should also have `filled: false`

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1650]
we have it for diamond and circle, but triangle unfilled has meaning in uml too

https://d2lang.com/tour/connections/#arrowheads

**Comment by aakashdeepsil** [comment]
Hi team
I want to contribute to this story. I'm very new to open source. I think this looks like a good place to begin. Can I start working on this?

**Comment by alixander** [comment]
@aakashdeepsil All yours!

Perhaps @Paracelsus-Rose's PR on https://github.com/terrastruct/d2/pull/634 would be a good example starting point. His code adds a new arrowhead, which includes a `filled` version.

**Comment by aakashdeepsil** [comment]
I will go through the [PR](https://github.com/terrastruct/d2/pull/634) to understand the work well. Then start the work on this issue. Might take me a day to understand the PR well. I will start work from tomorrow.

**Comment by alixander** [comment]
@gavin-ts can you knock this out?

**Comment by hinogi** [comment]
I already tried `shape: triangle` `style.filled: false` but that didn't work for target arrowhead

**Comment by PackRuble** [comment]
Trying the v.0.6.2 release and it doesn't seem to work:
```d2
A1 -> A2: {
  target-arrowhead.shape: triangle
  style.filled: false
}

B1 -> B2: {
  target-arrowhead.shape: arrow
  style.filled: false
}

C1 -> C2: {
  target-arrowhead.shape: circle
  style.filled: true
}
```
![image](https://github.com/terrastruct/d2/assets/88033450/e300e22e-25fe-4147-b691-ad034a21c8ed)

**Comment by alixander** [comment]
@hinogi @PackRuble 

The style pertains to the arrowhead, not the connection.

```d2
A1 -> A2: {
  target-arrowhead.shape: triangle
  target-arrowhead.style.filled: false
}

C1 -> C2: {
  target-arrowhead.shape: circle
  target-arrowhead.style.filled: true
}
```

<img width="279" alt="Screen Shot 2023-12-07 at 4 08 46 AM" src="https://github.com/terrastruct/d2/assets/3120367/e0a6e438-25ac-4789-8e3e-37ef74b03c49">


https://play.d2lang.com/?script=cjRU0LVTcDSyUqjmUlAoSSxKTy3RTSwqyi_PSE1M0SvOSCxItVIoKcpMzEvPScWqpKQyJ1UvLTMnJzXFSiEtMac4lauWi8sZbLAzAYOTM4uSiTG2pKgUZCogAAD__w%3D%3D&

**Comment by PackRuble** [comment]
@alixander Thank you very much, I apologize for the inattention. Using `target-arrowhead.style.filled` helped)
