### ISSUE TITLE
rendering service, embeddable picture

### ISSUE THREAD

**Issue by setop** [terrastruct/d2#1651]
When writing a markdown document I'd like to embed diagrams as picture.

Like with plantuml I can type 

```markdown

* my wonderful diagram:

![](http://cdn-0.plantuml.com/plantuml/png/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vt98pKi1IW80)

```

and it will produce 

---

* my wonderful diagram:

![](http://cdn-0.plantuml.com/plantuml/png/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vt98pKi1IW80)

---
 It does not matter to me if I have to self-host.

I see the d2 playground is now using [bookmarkable url](https://play.d2lang.com/?script=HM_BrYMwEEXRPVW8BvgFsPhpIlI2SNFM_DCOjCexByF3H0EBR7r3KpjQ-N1ZXnyGJLHKNpxLxPgPNZ3wWMURjA3JsVHKXNygxMGcRwnvvTnDbVDT01x4wn0lRFNO3uGGT5YOrSlEwupcouUF0pAW-MqOg5WIsrH9Db8AAAD__w%3D%3D&). That is a start. Just add a way to output just the image and it will be perfect.

**Comment by alixander** [comment]
We haven't publicized it because D2 is not yet 1.0. And before 1.0, the compression dictionary may change which causes old links to no longer work. So use with caution for now! We don't have any new keywords planned that would change the compression dictionary, but pre-1.0, it's also not a guarantee.

**Comment by alixander** [comment]
We do use a standard compression. https://github.com/terrastruct/d2/blob/master/lib/urlenc/urlenc.go

The custom dictionary allows for shorter URLs

**Comment by alixander** [comment]
You're right. Not significant at all. With a medium/large example it's 1692 bytes with dictionary and 1716 without.

Opening a PR to remove using dict and be all standard zlib encoding.
