### ISSUE TITLE
containers on same level 

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1654]
is there a way to force engine to align all containers on same level ?
I have tried to use width: 200, height: 700 but only a little better
also lines / rel are not finishing at middle of icon
when line is connecting to element of target container like:
Transform and Store.lakehouse -> Consume.Power BI: DirectLake
Transform and Store.lakehouse -> Consume.Reports: TDS/SQL Endpoint

![image](https://github.com/terrastruct/d2/assets/134058357/184e7b64-dba5-4a49-8a79-d11bb023749e)

[diagram code with no icons but the problem is visable](https://play.d2lang.com/?script=jFQ7a_MwFN3vrzjk2z6ou2vo0LpDIJS0DnRW4lvbTSIZScaUkv9eZD3itBAySudxHz5yXpqA8eMRbYxU3gFS1aicNizwTcCMOfQEHOSeWz1YLqavIc4XBGxSHwS8aMdbrfeJl850InrSyg7HWGGtRzZ4XCZiOhPwxr02zmZENp3y8YAJgPcqpZOopmXaYFi10nAND1h2SXx5S8CKG7n7Qj22QQZEZgQm41GaPJ0ffsuHTHifYSffylI1bF1ws602bjfk8ulMwKfeWoHFIlZddz37D3UeM11MsG_j46DHhKZzLPoPZScbI48XiyjOw-HuAaGxwhe-pNmwlDosZUbN7c6kHv4bkyIHQERxWkQ2uV14jeVdYnCKlBGBcsrnSu75ZnFMlcCmrO6r1xWeVd3rTjmi_8X0yAr_uxAhzr00rFxGwoP8jV3TXVP-BAAA__8%3D&layout=elk&theme=0&sketch=1&)

**Comment by gavin-ts** [comment]
This can be done with grid-rows and grid-columns, although there are only straight edges across grids right now.

<img width="708" alt="Screenshot 2023-10-11 at 2 49 22 PM" src="https://github.com/terrastruct/d2/assets/85081687/9aebafc1-a7e8-44bc-9d73-0f5cb1c6b3ab">


https://play.d2lang.com/?script=jFSxTsMwEN3vK57KVgkjJCYPDBCGShUqpBKz25gktLUj21GEUP8dOY7dpKCq4_ndu7t395I5G2vmuKdp_ECUCSeQ90NaWqhSWkdrI5RvA6EK5E4bSc9a2fYg6R-M44eAdB-OtiFgL3ay0q2VrD8nPz0QsI5CCHjVTm603sW8GNORYtfQYaU7afC0iIkxJuBdNto4mxBR1sr7CyYAvtZYaCiYV8LIAh6w0kXy9JWApSzF9htFVwUaMGQOQF-4Eyap8-I3cp8SPkbY0Y8S1hyq2Uobt21T-xgT8KU3lmM2G7qen9K_repG-uufpMeHHvajfe51F9EYD4PcIKtFacRhshx2EozbR4RhmR9mmmbDooqwqFFqkjCievivdVgyBR_IcTmpyPXES1m-ymAmFn3DkfWeXYqdvJo8OI1jneV3-dsSL6podK0c0Zz1Xy7z_yAeLN4II5VLSPjKz7FLvEvM3wAAAP__&layout=elk&theme=0&sketch=1&
