### ISSUE TITLE
Plugins from andrinmeier are gone (Maven and Confluence)

### ISSUE THREAD

**Issue by landmaj** [terrastruct/d2#1656]
Two plugins listed in [community plugins](https://github.com/terrastruct/d2#community-plugins) from andrinmeier are no longer available, their links return 404. It seems like the GitHub account was removed.

- [Maven plugin](https://github.com/andrinmeier/unofficial-d2lang-maven-plugin)
- [Confluence plugin](https://github.com/andrinmeier/unofficial-d2lang-confluence-plugin)

**Comment by alixander** [comment]
fixed here: https://github.com/terrastruct/d2-docs/pull/190

thank you @landmaj
