### ISSUE TITLE
Global Setting for Font Sizes on Arrow/Connection Descriptions

### ISSUE THREAD

**Issue by rd-patrick-thaele** [terrastruct/d2#1657]
**CONTEXT**
I have a bunch of big and complex diagrams that are needed in a certification process. We successfully use D2 for our diagrams, with one exception: Due to the size of the diagrams the auditors have trouble to read the text on the arrow descriptions. So I wanted to increase the font-size.

**WORKS BUT INCONVENIENT**
```
A->B: Sample Text{
    style.font-size: 54
}

C->D: Styled with Classes {
    class: arrow
}

classes {
    arrow : {
        style.font-size: 54
    }
}
```

I figured out two working methods to increase the font size of arrow descriptions:
 * set style directly at the connection
 * set class directly at the connection

When I have to maintain 30 connections/arrows in each of the various diagrams it's rather painful to make the setting for each connection individually.

**GLOBALS**
I also tried globs but what works pretty well for components cannot simply applied to connections/arrows:
```
# works as expected
# sets font size of all components
**.style.font-size: 54

# sets font-size of all components and can even be imported
***.style.font-size: 54

# FAILS
# Also creates connections from everything to everything
*->* {
    style.font-size: 54
}

# Runs into endless loop while compiling
**->**: null {
    style.font-size: 54
}
```

❓ How can I style all connections/arrows globally? If it works via imports that would be even better.
❓ How can I style connections/arrows w/o creating new ones?

**Comment by alixander** [comment]
`(** -> **)[*].style.font-size: 54`

The syntax `(id1 -> id2)[index]` references a connection, so that line references all connections.

https://play.d2lang.com/?script=0tDSUtC1U9DS0ozWitUDG6wHDw4rBVMDLq4KkIJKK4WM1EquShC7ykohI5OLK9FKoZpLQaEKJJRkpZCUmc5Vy8WVqFcFVQMyhgsQAAD__w%3D%3D&

p.s., that's a cool use case. If you're open to letting us use that as a testimonial, please email me at alex@terrastruct.com.

**Comment by rd-patrick-thaele** [comment]
Thank you for the quick response!

That works like a charm 👍
