### ISSUE TITLE
Feature: Add support for images & 3d objects

### ISSUE THREAD

**Issue by elasticdotventures** [terrastruct/d2#166]
There are other issues/requests for 2d shapes.

I'd like to see the ability to add custom images & libraries (such as all the AWS network map Iconography)

While we're on the topic - do you know what would make that even cooler?   (while you're planning such an awesome feature)
Having 3d images which animate (spinning).  It's fairly straightforward to extrude 2d shapes into 3d images. 

Image objects that can be mapped with text, and hooked on an interactive canvas to display metrics.  (i.e.: Server is on fire), easy to hook by object id and write to that via GRPC or similar mechanism. 

This would would be useful in cases such as network maps & visualizing data as it moves through ML Pipelines.

**Comment by alixander** [comment]
>  It's fairly straightforward to extrude 2d shapes into 3d images.

like this?

<img width="531" alt="Screen Shot 2023-05-01 at 4 39 58 PM" src="https://user-images.githubusercontent.com/3120367/235549965-aa0e8402-b8ae-42a9-af1f-28af341df108.png">

**Comment by alixander** [comment]
or this: https://codepen.io/sungaila/pen/LzMgjE
