### ISSUE TITLE
`elk` layout engine sometimes doesn't manage to untangle lines, which causes some undesirable imagery to appear

### ISSUE THREAD

**Issue by SandaruKasa** [terrastruct/d2#1662]
```d2
direction: right
Block: {
  1
  2
  3
  4
  1 -> 4
  2 -> 3
}
```
Compile with `d2 -l elk`.
The result:
![卐](https://github.com/terrastruct/d2/assets/50824690/ddaf7d39-5266-41f6-84ec-f82d20ae8c94)
Yeah

**Comment by alixander** [comment]
this is desired behavior. ELK tries to maintain order top-down, so since `3` is defined before `4`, it appears on top. Switching `3` and `4` gets:

![Screen Shot 2023-10-12 at 3 02 24 PM](https://github.com/terrastruct/d2/assets/3120367/b74daae6-434c-4b65-8534-6070c5c444d8)
