### ISSUE TITLE
relationship lines are not draw properly between columns in ELK

### ISSUE THREAD

**Issue by ppalka-lingaro** [terrastruct/d2#1668]
Created diagram showing mapping between source and target
however it's not drawing lines properly between columns in ELK:
![image](https://github.com/terrastruct/d2/assets/134058357/f499f949-7c77-4922-a1fa-e87c1c4d1de3)

in TALA it's better however the direction: right do not work and lines are messy:

![image](https://github.com/terrastruct/d2/assets/134058357/20a54e48-a0d9-4a43-81e4-accd99f176af)

I tried the same for class = class but same
example of Data source to target mapping based on sql_table class: [link](https://play.d2lang.com/?script=rFbNbtswDL7nKYjuVmB-AB8GBNtaFNhaoM1lJ0OxlVSobTmSPNQr8u6DZMv6b-1shxxC8qPNj-RHz6TlwGR5mydS_8Ysh7cNgCKwkNiCCNyMRgBS5fC0e7y7v4U304IcOkYaxIbiBQ9nFTjiU-EHyjA5tia8Y7TqS1Hwl14jlP0khhzu7nfjwwVuio6REudw8-NhO1orwkvay6zGJtCr85cKVBvDeaMLXF0WF5RhqyxlLHsuaLOmXI45J7RdDqiQwDl82-6-xwoC4M-k60h7LBosnmm14k00sKTcobBDQ4NbsTqhxvn5vJbEurYndS1fBVUVw5xfUMRKpPx5zK2eiBY12JoGNVtqSv41E0DPauc_w0e1rZZpz1DrDiOjVHxFAh8pG-6W0-C2-7-wMO30-h3zNCDgJZAAfys_GJdypIdgnsPV9vFx-wsebrR1KEh19QFd583mltYTSwcpW6iWyd6m5VT6m8NObimgPRekxW2JgXDAiBPMQDyjFjrMDrgU0NAKMySVeIF0BnQpVbQ4g4pIlVTcZ5aummCbUF_oM-k0oZqUORxxTkudfnbPzyHVaBKSRvkic4RlN-m1vAdvcRJDXPKDSBNhAJ64BBjtNwijTkGwQK9WnCW8YaR0Wi2Madzo8cRwMgaivm6sx3CnuSmAmhEVr_pt4y3RWQLvWW2jHT1aglcAO4MrcktSjIjzhad4apV7X_1z6pDqOc3GLL2lTjbXZ5Kl7ugFR1JxNcVnf0hXlLTCl1_OZDopjNfZdaY-bXPgp7oQaF_jzeYT_ETqOXBgtPEXBwQ1Kjp9hWb-cllKBp-_gNTfbAZlWgRT6JMYUigpNQmU0ZYUeBSeBFzvfwo8y1ACL9BrCipFKYVSVyeFUxIV7Ue6CxmpIvn0mXJDtWZFANrlAqyNjWAsrwuTC5t8Kel0w1OkWMrr1WHvcqwY2-9C7c2NIG2395LRfs8XwyMgPVzu9XFhoXxEEoRBCXLezRKJCiZPzUR08sx1So6S0konvGexJs-HzQ1WpycZrrwuYDw0ScToDkqchCtapP5MM1-kqcXV31Ehg-41inMZuVjvNcy6U2E5zr2KVxWetHf2wH7Y3wAAAP__&layout=tala&)

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/issues/1429
