### ISSUE TITLE
How to position elements inside container?

### ISSUE THREAD

**Issue by f1nnix** [terrastruct/d2#1673]
Thanks for beautiful library!

I’m trying to make vertical stack inside container. That’s what I am trying to achieve:

```
+---------+
| Text    |
|         |
| +-----+ |
| |N1 N2| |
| +-----+ | 
+---------+
```

That’s my code:
```
SEARCH_RESULTS_MORE_ONE: "" {
  explanation: |md
    # SEARCH_RESULTS_MORE_ONE
    The Large Language Model (LLM) is a powerful AI\
      system that learns from vast amounts of text data.
  }
  |
  
  Intents: "" {
    CHOOSE_ITEM.shape: cloud 
    CHOOSE_RANDOM.shape: cloud
  }  
}
```

And that’s how it’s rendered:

<img width="853" alt="image" src="https://github.com/terrastruct/d2/assets/3099788/1b4fea7e-feea-428b-b6e7-8e3bc73d50d7">

Is there a way to achieve stacked alignment?

```
% d2 --version
0.6.1
```

**Comment by alixander** [comment]
You can make it a grid, though that comes with some limitations which you might run into as you grow this diagram. 

```d2
SEARCH_RESULTS_MORE_ONE: "" {
  grid-columns: 1
  explanation: |md
      # SEARCH_RESULTS_MORE_ONE
      The Large Language Model (LLM) is a powerful AI\
        system that learns from vast amounts of text data.
    }
  |

  Intents: "" {
    CHOOSE_ITEM.shape: cloud
    CHOOSE_RANDOM.shape: cloud
  }
}

```

![Screen Shot 2023-10-18 at 2 18 39 PM](https://github.com/terrastruct/d2/assets/3120367/60f81740-86df-4d75-95eb-311afec9337a)

https://play.d2lang.com/?script=dJFPa4NAEEfv-yke6aW9BHr1JulCBI2g9laQoa5JYd0N7to_NH73ooQSKJ3r4zfM702t02q3bytdP-dN3RZlpdvyoBM2G74V3BpJeFRgPs9WnCyiEy5Dp1jnjn9WXXlzMuTLyeTijpMcDYXvjOU-z4sH3gLC2X-YsZ8safZyjUH4CtEMxJNErJHRBfrRD7xLiMjgJxcDvmfpTydRtmt0VnBRCjIXjYvhtxHs9mVZ6zZrdLFdP5Dwav3U3cIqPTyVf_CsZvUTAAD__w%3D%3D&

**Comment by f1nnix** [comment]
That's nice, thank you!

However, there is major limitation:

> Connections for objects within grids are coming soon, but you can connect the grids themselves like regular objects in D2.

https://d2lang.com/tour/grid-diagrams#connections

What I need is to connection "CHOOSE_ITEM" node with some outer one, sorry for non-pointing it in the original message.

Without this feature I'm getting:

> failed to recompile: Schemes/main.d2:45:1: edges into grid diagrams are not supported yet

Is there PR or Github issue for this feature?

**Comment by alixander** [comment]
It's done, though the routing is rudimentary (no path finding, just straight edge). Live on Playground but will come in the next release for CLI: 

https://play.d2lang.com/?script=dJHNaoQwFIX3eYrDdNMuKnTroiDTwAhxAmp3BbnU61iIyWBif6i-e1GkBEqz_TgfOedWMiuPp6aU1bOqq6bQpWz0WaY4HPAtgHiRFA8C4M-rIUvr0CnmoRXY3g3-Ue287hlq_TIU2ctEF0bhWja4Vaq4w5sH4eo-eOwmgyx_2WOA__KBB4SeAgzTaD260Q14Jx9Ag5ts8HAd1v5oKVCyRRcBzEIAuQ1sg_9tBBxPWleyyWtZJNsFUrwaN7UxLLPzk_6Dl1XYszEuMieRD_ePO1_ETwAAAP__&

**Comment by f1nnix** [comment]
Yeah! I've discovered this in the playground, but you're definitely right: path finding is something to be improved as lines are crossing everything now.

Waiting for the release. Thank you very much for your help!
