### ISSUE TITLE
Standard library log output is overridden

### ISSUE THREAD

**Issue by hjr265** [terrastruct/d2#1680]
https://github.com/terrastruct/d2/blob/4cba5d27e691ed4f0172a77d45440a8acc1e6487/lib/log/log.go#L23

The `lib/log` package in this repository overrides the output writer of the standard Go `log` library.

Any project using `d2` will have its output logs look different from the default.

Can we not override the output writer of the standard Go `log` library?

I could prepare a PR to fix this if the team agrees.

**Comment by alixander** [comment]
hmm yeah I guess we should only run this in the init of the CLI main. cc @nhooyr for a gut check

**Comment by alixander** [comment]
Go for it @hjr265, thanks!
