### ISSUE TITLE
Class inheritance empty arrow head connections

### ISSUE THREAD

**Issue by hinogi** [terrastruct/d2#1706]
In reference to #1351 I don't ask for different ways but just to have a way for stuff like empty arrow heads like because that is quite important for modelling.

![image](https://github.com/terrastruct/d2/assets/4602609/e3e098c9-e9dc-451c-90cc-722fde11a5f0)

**Comment by alixander** [comment]
dupe of this: https://github.com/terrastruct/d2/issues/1650

Ack, will bump in priority
