### ISSUE TITLE
(feature request) Swim lane diagrams

### ISSUE THREAD

**Issue by victorwestmann** [terrastruct/d2#171]
Hi everyone, first of all thank you so much for this fantastic piece of software!

I was just wondering if it is possible to add a new feature to d2. If we could add the possibility to do swim-lane diagrams for a future version of d2. We would be able to hav a top band with the title of the diagram, a subheader so we could add the last date of the diagram update and the name of the person who edited the diagram.

Also if it is possible to add options to change horizontal and vertical swim lanes with the same content.
Thank you for your time and for sharing high-quality work publicly!

Victor

**Comment by ejulio-ts** [comment]
@victorwestmann can you add some image examples so that we get a good idea around your request?

**Comment by victorwestmann** [comment]
Sure thing! This should be a great example of a swim lane diagram (this one seems to be done in Microsoft Visio).

![httpatomoreillycomsourcemspimages1696588](https://user-images.githubusercontent.com/582569/203694230-7ed5dbce-77fa-4972-9f7d-094ca9116395.png)
