### ISSUE TITLE
grid: support custom label/icon positions for grid containers

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2#1710]
currently grid containers always have labels inside top center, but they should be able to be positioned with `label.near`

For example
```d2
grid: {
  label.near: outside-top-left
  grid-rows: 3
  a
  b
  c
}
```

**Comment by alixander** [comment]
note that if labels are set to outside, then there should be no box for them as part of the grid.

![Screen Shot 2023-11-07 at 3 09 42 PM](https://github.com/terrastruct/d2/assets/3120367/de5831d5-8c44-48d2-9272-840d2e4aa4cb)
