### ISSUE TITLE
FR: Allow grouping of elements in assignments

### ISSUE THREAD

**Issue by wpkelso** [terrastruct/d2#1747]
# Example

```
// Current method
A -> C
B -> C

// Proposed method
A, B -> C
```

The syntax is obviously only a suggestion, but I think it fits with the existing syntax (another option could be to group using braces, i.e. `{A, B} -> C`).

# Reasoning

As near as I can tell, we currently have no way to group elements in assignments. This means that if we have multiple elements going to one element or vice versa, the source file can get unwieldy with large amounts of similar lines. Collapsing them would make the source more legible.

**Comment by alixander** [comment]
Thank you for this. Folks have come to same conclusion, will aggregate in first issue: https://github.com/terrastruct/d2/issues/742
