### ISSUE TITLE
cli: Avoid opening browser when using `--watch`

### ISSUE THREAD

**Issue by DannyBen** [terrastruct/d2#175]
Is there a way to disable the browser opening when using `--watch`?
It is an annoyance when running in headless linux.

**Comment by alixander** [comment]
this should definitely be an option, ty, will work on it shortly

**Comment by nhooyr** [comment]
Let's make `BROWSER=0` and `BROWSER=false` disable.

**Comment by nhooyr** [comment]
And then I guess `BROWSER=1` and `BROWSER=true` should detect the browser automatically like `BROWSER=`,
