### ISSUE TITLE
Proposal for default styling using pseudo-classes.

### ISSUE THREAD

**Issue by flowchartsman** [terrastruct/d2#1754]
Despite the addition of glob semantics, default styling still doesn't really exist in D2. Currently there are two options to style multiple entities with globs, both of which have their drawbacks:

Given the following diagram:
```
classes: {
  decision: {
    shape: diamond
    style.fill: red
  }
  actor: {
    shape: person
  }
}
direction: right
u: {
  label: you
  class: actor
}
w: {
  label: which?
  class: decision
}
u -> w: want
w -> a: 1
w -> b: 2
```
<img width="711" alt="image" src="https://github.com/terrastruct/d2/assets/926884/7b9b6bb4-885b-459e-a379-4c8da7b1f40a">

If we want all nodes to default to be gray, we can place

```
**: {style.fill: grey}
```

At the top of the file, and indeed all nodes are grey now, but this has now overridden our class settings, and flattened every node to the same `style.fill` value:

<img width="712" alt="image" src="https://github.com/terrastruct/d2/assets/926884/ffeb2c34-8453-4d25-9af0-46c69e9cfb7d">

The other option is a glob class.

```
classes: {
  *: {
    style.fill: grey
  }
}
```

<img width="696" alt="image" src="https://github.com/terrastruct/d2/assets/926884/9b032d92-0e8b-42b3-b500-41091bd91886">

This _almost_ works as expected (`person` is now grey, while `decision` is not), however `a` and `b` are still "unstyled". This is because the glob is applying to the entities in the `classes` block. This makes sense, however its use is a bit limited, since entities without a class don't get the attributes.

The way I see it, there are two options here:

1. allow for special-pseudo classes such as `default`, which, when defined, will be applied at the top of the class stack for all entities within that block. I'd probably suggest adding three options: `all`, `shape` and `edge`.
2. make the meaning of `*` special in class blocks

Both of these approaches have their benefits and drawbacks. Option 1 has the potential to conflict with any existing diagrams that use these names as normal classes, however it's probably easier to implement and it makes a lot of sense. Option 2 changes existing glob semantics, and probably requires changes in both the glob handling layer and the later stages of the parser; however, it will likely cause less issues with backwards compatibility, since I imagine a lot of people don't know you can use globs like that, or they just don't find it useful enough.
 
There is probably a third option, which would be to use a sigil such as `!` to specify pesudo-classes. Ideally, this would be a currently-disallowed character; however the d2 syntax is very permissive since it doesn't have any expressions to account for, so pretty much anything other than `#` (comments), `@` (imports) and `*` (globs) is already allowed and could conflict with prior work.

Personally, I'd vote for `!`, and then disallow its usage outside of class blocks and disallow any class name that begins with this character, except for `!all` `!shape` or `!edge`. If you like, you could also introduce a flag or pragma to turn this behavior off to allow for older diagrams to be compatible.

<img width="715" alt="image" src="https://github.com/terrastruct/d2/assets/926884/68e9ed61-1e48-40eb-884d-7ed731959443">

The nice thing about this is it can be made to work by dividing it into two stages:

1. identifier exclusion in the parser, which would disallow other `!`-prefixed classes, while  transparently removing the prefix (e.g changing `!shape` to `shape`)
2. attaching the appropriate class to all items by default as whichever stage this needs to happen (i.e. everything gets class `all` while shapes additionally get `shape` and connection paths get `edge`)

This could also mean that items in a generated svg would have classes like

```xml
<g id="u" class="all shape actor"><path d="M 109 71 H 61..." />
```
as opposed to

```xml
<g id="u" class="actor"><g class="shape" ><path d="M 109 71 H 61..." />
```
which is how it's currently done.

This might actually end up being a good thing in terms of making svgs more selectable, though I don't know all of the implications. If `!shape` is a problem, you could always go with `!node`, which would make it

```xml
<g id="u" class="all node actor"><g class="shape" ><path d="M 109 71 H 61..." />
```

Which might also be more proper, depending on how hung up on graph terminology you are ;)

**Comment by alixander** [comment]
Oh good point with the first example. 
1. Classes should take priority over globs. 
2. `**` and `***` should not apply to class definitions.

The below should give red.

```d2
**.style.fill: green
classes: {
  x: {
    style.fill: red
  }
}

a.class: x
```

<img width="137" alt="Screen Shot 2023-12-06 at 6 16 57 PM" src="https://github.com/terrastruct/d2/assets/3120367/2c9bb273-3ad5-4d51-9c58-a1e7c05736b6">

https://play.d2lang.com/?script=0tLSKy6pzEnVS8vMybFSSC9KTc3jSs5JLC5OLbZSqOZSUKiAUAoKyOqKUlO4FBRquWq5uBL1wMqtFCq4AAEAAP__&

**Comment by alixander** [comment]
As for pseudo-classes, I don't see the need. You can just define multiple classes and apply multiple as needed.

```d2
classes: {
  all: ...
  shapes: ...
  connections: ...
}

a.class: [all; shapes]
a -> b: {
  class: [all; connections]
}
```

**Comment by flowchartsman** [comment]
> ** and *** should not apply to class definitions.
>  You can just define multiple classes and apply multiple as needed.

Except now there's still no default styling defined in one place, and you have to manually apply the `all` class to every otherwise un-classed entity and edge. That works, but it's a lot of boilerplate that's multiplied by every file you need to do it to, and that's easy to get wrong or omit by accident.

At its core, this issue is about default styles that are easily applied to multiple graphs, so it could also be solved by allowing user-defined themes and extending theme support to include default style attributes on nodes, edges or both. Concrete use cases might be someone who is writing a lengthy design proposal, academic paper, or someone like me who is writing a book, and wants all of the illustrations to look the same. So long as there is a convenient way to do default styles without a load of identical class definitions, I think that's a win.

Personally, I think the theme idea is probably the best solution, followed by pseudoclasses, which could be included from another file, and finally glob improvements, which are the least intuitive of the three, since the syntax and scope are a bit abstruse , and the glob syntax for "all edges" is kind of awkward to use right now.

**Comment by flowchartsman** [comment]
> This should do it, right? Or am I missing a case you have in mind.

As long as there is a fix that makes it so in [this diagram](https://play.d2lang.com/?script=0tLSKy6pzEnVS8vMybFSSC9KTc3jSs5JLC5OLbZSqOZSUKiAUAoKyOqKUlO4FBRquWq5uBL1wMqtFCq4EhV07RSSuAABAAD__w%3D%3D&) `a` is red and `b` is green, that meets the basic use case, but I think user themes would still be the better way to do this, since I could just put the style def in a config file and be done with it instead of needing to copy that code to every file or otherwise include it.  But, yes, if that works, that's definitely an improvement!

**Comment by alixander** [comment]
The plan to customize user themes is with `var`s. 

E.g.

```d2
vars: {
  d2-config: {
    theme: {
      # This would overwrite the color code for neutral in the theme
      N1: "#FFF"
    }
  }
}
```

So you'd have to define this in a file and import it everywhere anyway, same as the glob method.

**Comment by flowchartsman** [comment]
If it can be done in a single line, I think that's probably okay, though it would obviously be nicer if the `theme` flag could point to a file instead, or even if there were an `include` flag to allow processing and reprocessing many files at once using the same theme without needing to include it in the file.

**Comment by alixander** [comment]
separating this out into more dedicated issue: https://github.com/terrastruct/d2/issues/1766
