### ISSUE TITLE
exports: PNG exports have to wait for images to load

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#176]
otherwise:
![out](https://user-images.githubusercontent.com/3120367/203645943-033aec4c-3ed8-45cc-b0c9-e95e8e28c4d2.png)

**Comment by berniexie** [comment]
Yeah i don't think this is the waiting for images to load part since playwright does that automatically. This is the we have to encode images manually part

**Comment by alixander** [comment]
Are you sure? okay, we can encode then, whatever makes Playwright work.
