### ISSUE TITLE
markdown: support <details> tag

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1773]
https://play.d2lang.com/?script=VIuxCkIxDEX3fsUVZ-kupbN-gXMwAQtpI00FhX68WPDB2-49hyPvp1KjUaydMSsHADjiijs1sOEhxNJ94RO0-NjvACSWQUU9L5H8VSv1T76IqqX4v0verCsffk3cohm-AQAA__8%3D&

**Comment by bo-ku-ra** [comment]
is the box size ok?
https://play.d2lang.com/?script=VItBCgIxDEX3OcUX1zJ7KbPWE7iOJmAhbaSpMOJ4d7Gg4O7_93hnX56ky824cs9e91iLEABsccSFK8RxVRZtMfAOlqP_bwKSaOdsMQ-R4l4Kt8d8UDNP0_cOefJmsvk00y9a6UXvAAAA__8%3D&

**Comment by alixander** [comment]
Nah won't do. this is too extra
