### ISSUE TITLE
Official Atlassian Confluence app is missing

### ISSUE THREAD

**Issue by devsunb** [terrastruct/d2#1796]
When I tried to click the [Install Confluence app](https://marketplace.atlassian.com/apps/1222112/terrastruct) button on the [tour page](https://d2lang.com/tour/confluence) to go to the Atlassian Marketplace, I got the error message below.

```
Not Found. Redirecting to /apps/1222112/terrastruct?tab=overview&hosting=cloud
```

The app seems to have been deleted, is there another way to install the app in Confluence Cloud?

**Comment by alixander** [comment]
It's back
