### ISSUE TITLE
Sequence diagram: how to adjust the length of a span?

### ISSUE THREAD

**Issue by BruceXSK** [terrastruct/d2#1798]
the span example:
```d2
shape: sequence_diagram
alice.t1 -> bob
alice.t2 -> bob.a
alice.t2.a -> bob.a
alice.t2.a <- bob.a
alice.t2 <- bob.a
```
is it possible to adjust the length of a span, such as `alice.t1` or `bob.a`, to demonstrate the time of operation?

**Comment by alixander** [comment]
No. I think it would be strange to see a span longer by itself with no explanation. I'd just use notes or some explanation for the delay. https://play.d2lang.com/?script=Ks5ILEi1UihOLSxNzUtOjU_JTEwvSszlSszJTE7VKzFU0LVTSMpPQuHD2FYK5YmZJXikFHLzi1Jh8kZQo_QS4SJ6iVjFbHTRxBAigAAAAP__&
