### ISSUE TITLE
\n in grid destroys the grid lines.

### ISSUE THREAD

**Issue by jfudickar** [terrastruct/d2#1799]
When a \n is used in a grid column the horizontal lines are no longer correct:

https://play.d2lang.com/?script=dI7vSsQwEMS_5ymGfhQ8bALi7bMIJW32aiRNj-zmQMR3l4aT-u8ggdmdneH3Kmu2hK7DuwHmEsP97M-Eh69pWlNdshCcAe4Oom-JD-OaAuHkk7AxwNkXzvrD01LZAP3QEzp0BrC7dJvUl1JFh4ufal22Fq9a4liV_y-yhLGWPGhceBCe4CX8-c_5qq4PYXe_H3r8CkpoiJbAeY6ZpWFaQhxPG9zFp3oDzBH6R9vijnBswW335NzROvNhPgMAAP__&layout=elk&

```d2
json2: "" {
  grid-gap: 0
  grid-columns: 3
  *.style.bold: false

  parent.style.bold: true
  1_1: " "
  2_1: " "
  3_1: thrust_vacuum

  attribute.style.bold: true
  1_2: burn_time_sec asd asd asd asd asd \nasd asdasdasda dasd asd as asd asd asda sd asd asd asd sd
  2_2: engines
  3_2: ibf

  value.style.bold: true
  1_3: 162
  2_3: 9
  3_3: 1833923
}
```

**Comment by GavinNishizawa** [comment]
You just need to also specify `grid-rows: 4` if you want all the rows to have the same height. Grid columns can contain cells of different sizes. For example

https://play.d2lang.com/?script=dI7vSsQwEMS_5ymGfhQ8bCLi7bMIJW32aiRNj-zmRMR3l5Q7zr-QwGQmM_xeZM2W0HV4N8BcYrid_ZFwd3lNa6pLFoK7OGV9FcK9McDNTvQt8W5cUyAcfBJu9tEXzvot01LZAP3QEzp0BrBX6ZrU51JFh5Ofal3ailctcazKfw9ZwlhLHjQuPAhP8BJ-3ad8VueDcE2_fvT4UZSwIVoC5zlmlg3TEuJ4aHAnn-o_YI7QP9it7gj7rdi8R-f21pkP8xkAAP__&layout=elk&
