### ISSUE TITLE
dev: Ambiguous import

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#181]
https://github.com/terrastruct/d2/issues/180

Need to either remove slog entirely or patch upstream it seems. We should probably just remove.

**Comment by nhooyr** [comment]
Not sure how/why slog is being imported anyway anymore. Weird. I don't believe we use it anywhere actively at least. Maybe in some tests somewhere.

**Comment by alixander** [comment]
the bigger detachment is from TALA, and then D2 imports slog to discard slog lol

**Comment by nhooyr** [comment]
lmfao right. we should move that Discard into the TALA code instead of doing it here.
