### ISSUE TITLE
Certain characters breaking display

### ISSUE THREAD

**Issue by IlanCosman** [terrastruct/d2#1811]
The following code using [ascii 254](https://theasciicode.com.ar/extended-ascii-code/black-square-ascii-code-254.html) (■) doesn't display "bar".

```d2
legend: |md
  ■ foo bar
|
```

https://play.d2lang.com/?script=yklNT81LsVKoyU3hUlB4NG2BQlp-vkJSYhFXDRcgAAD__w%3D%3D&

![image](https://github.com/terrastruct/d2/assets/6318351/c544a7c7-9b66-4c51-86fc-08d0ce000d9a)

If we replace the square with a traditional character like "a", it works.

```d2
legend: |md
  a foo bar
|
```

https://play.d2lang.com/?script=yklNT81LsVKoyU3hUlBIVEjLz1dISiziquECBAAA__8%3D&

![image](https://github.com/terrastruct/d2/assets/6318351/bcd4bde1-f490-482e-9b35-59a8abd1581b)

**Comment by bo-ku-ra** [comment]
this is weird
https://play.d2lang.com/?script=ejRtgZVCTW4Kl4LCo2kLFNLy8xWSEou4argeTVuIkFiILDG9Hy4xvR9Fohsh0Y0i0YaQaEORaEdItKNYvglh-SYUic0Iic0oEnsQEntQJPYiJPYiSzTshks07EZxVR9E4tH0PiRhQAAAAP__&

**Comment by alixander** [comment]
thank you @IlanCosman for raising the issue and thanks @bo-ku-ra as always for the thorough test cases
