### ISSUE TITLE
Allow us to specify import sources within the diagram

### ISSUE THREAD

**Issue by dunkelziffer** [terrastruct/d2#1817]
A common use case for D2 is inline usage within Markdown. As we don't have real files here and only a single block of text, we can't use imports at all:
`````
```d2
# not a real file, no imports :(
```
`````

Allow us to define hidden nodes, that will be considered when resolving imports. Previously, we had to do:
```
# main.d2
container: @children
```
and
```
# children.d2
child_1 -> child_2
```

The following should be equivalent:
```
# main.d2
d2_imports: {
  children: {
    child_1 -> child_2
  }
}
container: @children
```

This would allow us to actually use imports within a single file and it would use the same syntax as the already existing imports. But wait, why would you even want that? Why import, if everything is in the same file already? Because imports allow to reuse a defined diagram part multiple times.

**Comment by alixander** [comment]
`vars` should cover this capability. 

```d2
vars: {
  x: {
    a
    b
    c
  }
}

hello: ${x}
```

https://play.d2lang.com/?script=KkssKrZSqOZSUKiAUAoKiWAyCUwmcyko1HLVcnFlpObk5FspqFRX1HIBAgAA__8%3D&

<img width="588" alt="Screenshot 2024-07-18 at 4 34 30 PM" src="https://github.com/user-attachments/assets/f67a0a73-7975-43cb-be2f-1f1624bbcf9b">
