### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by mdg-utility** [terrastruct/d2#1825]
One of the things that I've been using Mermaid for is making Gantt charts, but their tool is quite limited the customization options for Gantt charting at the moment.

Would it be possible to define a Gantt syntax to make building these charts? I've looked through the documentation examples and I might try to build something from scratch using the current functionality, but if there were a specified Gantt syntax, it'd make this a lot more straightforward.

**Comment by alixander** [comment]
I'm open to this being an external plugin to D2, but D2 core will focus on software architecture: https://d2lang.com/tour/design/#singular-use-case-documenting-software
