### ISSUE TITLE
support `link` on connections

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1827]
the text points to whatever the link is

**Comment by alixander** [comment]
In the compiler, the Link keyword is applied here. Just need to do that for Edges too.
https://github.com/terrastruct/d2/blob/master/d2graph/d2graph.go#L131

And then the exporter needs to take that value from the compiler and read it, like Shape does:
https://github.com/terrastruct/d2/blob/master/d2exporter/export.go#L198

And then rendered in the SVG with an <a> tag:
https://github.com/terrastruct/d2/blob/master/d2renderers/d2svg/d2svg.go#L909

**Comment by huyz** [comment]
Dup of https://github.com/terrastruct/d2/issues/1497
