### ISSUE TITLE
Is there a way to resolve the overlapping arrows?

### ISSUE THREAD

**Issue by peinan** [terrastruct/d2#1831]
I don't know why this happens, but I want the arrow coming from the right to work like the red line.

<img width="354" alt="image" src="https://github.com/terrastruct/d2/assets/5601012/03b073a4-b1fc-434e-8005-38084f730fd9">

**Comment by alixander** [comment]
This is probably just the layout engine's choice that we can't do anything about, but can you post the code so I can investigate?

**Comment by bo-ku-ra** [comment]
i think it is possible.

--japanese--
経験的に、その接続に問題がある各ノードが初めて出現する順番や、エッジの順番を変えると回避できます。
c.f.
```
a
b
c
d
a->b
c->d
b->a
```
↓
```
b ←ノードの順番を変えてみる
a
c
d
b->a ←エッジの順番を変えてみる
a->b
c->d
```

**Comment by peinan** [comment]
Thanks for your comment!
The original code has many (400+) lines which are not easy to debug as @bo-ku-ra said. It is also a bit difficult to share because it contains some personal information. Still, I'm very grateful for trying to help.
Personally, I prefer d2lang's syntax to mermaid's because it is intuitive and well designed. However, I am aware that the inflexibility of the layout is a common problem in code-to-diagram, and I hope there is a better solution.
