### ISSUE TITLE
Feature Request: Support for open ended edge

### ISSUE THREAD

**Issue by milon** [terrastruct/d2#1860]
Hello,
I am not sure whether this feature already exists, but I could find this example in the docs or searching online. I would love to have open ended edges like the orange edges in the diagram. This is required so many times in the diagram I draw. 

![tt](https://github.com/terrastruct/d2/assets/1138769/0b4c3c91-2ebf-4a3e-9f77-2df30b248bdc)

Finally, thanks for the wonderful product you made for the community.

**Comment by alixander** [comment]
Hey @milon thanks for the suggestion and kind words.

You can just use invisible objects (opacity 0). I don't think the language should simply that any further. I'll leave this issue up in case people search for it and have further arguments for why that's insufficient.

**Comment by bo-ku-ra** [comment]
if it's just straight lines, i might be able to do it with grid.

**Comment by milon** [comment]
Thanks @alixander 
I would really appreciate if you can add this somewhere in the document, so people like me who is searching for this can be benefited.

I am closing the issue.
