### ISSUE TITLE
Adjusting padding around diagram?

### ISSUE THREAD

**Issue by imJoshuaRice** [terrastruct/d2#1863]
Hi,

Is there a way to reduce or remove the padding around the diagram besides the command line argument pad=0 ?
![image](https://github.com/terrastruct/d2/assets/134961055/0d528561-633c-4cb4-bca1-37905abdfd9b)

For context, I use D2 embedded diagrams and the padding can result in a lot of space usage.

Many thanks

**Comment by bo-ku-ra** [comment]
as far as i know, it does not.

**Comment by bo-ku-ra** [comment]
```d2
vars{ d2-config.pad: 0 }
direction: right
a<->b
```
