### ISSUE TITLE
feature: layout direction

### ISSUE THREAD

**Issue by Melandel** [terrastruct/d2#1864]
Hello,

I know we can declare directions for connections.

Do you think it would be interesting to be able to declare a direction for the containers as well?

For instance, being able to write:

```
api {
  # 👇 something like that for container direction
  aim: right

  request {
    shape: class
    foo
    bar
  }
  response {
    shape: class
    foobar
    baz
  }
}
```

instead of:
```
api {
  request {
    shape: class
    foo
    bar
  }
  response {
    shape: class
    foobar
    baz
  }
}

# 👇 these can be tedious and repetitive
direction: right
request -> response { style.stroke: transparent }
```

in order to get the following:
![image](https://github.com/terrastruct/d2/assets/48007894/592cd13f-8ffc-47a7-a116-5c961c35bdbf)

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=XMw9CgIxFEXh_q7iJNZuIIV7yWRkDMJ7EALzI-5dYqVT3Ooevrm2e-nVLdHq8ujKmlSUud7IU0nEcxGlnHgJfp7ZV-OCeWf19qy2CDbBLjjGBrjtxx_49UIIUW99AgAA__8%3D&layout=tala&

**Comment by Melandel** [comment]
I'm sorry, I am having difficulties understanding.

Could you please elaborate?


I will also elaborate on my side: I would like to get [this result](https://play.d2lang.com/?l=&script=jM8xDsIwDAXQ3aewWDqB1IwZuEs-RFCBWpR6QVXujpTI7gCl2SL7yz_vOqR4kWEaPafhdhcKnhdi_pozh66vu_I89PZy64yP5zryvMzyfsbTLGl6RM-Swji_QoqjZGLO5aDTgz_qyt5anLU4bXGtLZr_n85E2LRjtcPsMDvUjlY7duwwO8wOtaPVjk7zu_ZQgvVPm0nK9AkAAP__&layout=tala&theme=0&) but **without** resorting to creating invisible arrows.

**Comment by Melandel** [comment]
grids definitely are great (I am so going to reuse them on certain diagrams, thanks for the tip!)

However my use case would imply a single configuration (or "profile") that would be used by default on most nodes in the diagram (think `css selectors & rules`) instead of having to declare it for each impacted node.

One example of such configuration ("css selector & rules") would declare something along the following lines:

```
For each root-child level node, // 👈 equivalent of css selector

// 👇 equivalent of css rule
  * if there are less than 2 children, apply `grid-rows: 1`
  * if there are less than 4 children, apply `grid-rows: 2` + `grid-columns: 2`
  * if there are less than 6 children, apply `grid-rows: 2` + `grid-columns: 3`
```

**Comment by alixander** [comment]
Sounds like another use case for scripting, related https://github.com/terrastruct/d2/issues/1599
