### ISSUE TITLE
style.stroke-dash doesn't work on shapes

### ISSUE THREAD

**Issue by tcsavage** [terrastruct/d2#188]
I can successfully set `stroke` on both a shape and a connection, but `stroke-dash` is apparently ignored on shapes.

Example:
```d2
a

b: {
    style: {
        stroke: "#ff0000"
        stroke-dash: 4
    }
}

a -> b: {
    style: {
        stroke: "#ff0000"
        stroke-dash: 4
    }
}
```

Generates the following output:

![Screen Shot 2022-11-24 at 08 51 27](https://user-images.githubusercontent.com/134930/203737033-5423aca1-d4eb-4776-87fe-ae1465aabae8.png)

But what I want is this (obtained by manually editing the generated SVG):

![Screen Shot 2022-11-24 at 08 51 18](https://user-images.githubusercontent.com/134930/203737085-a5a8b1f5-99e6-44b4-a14a-5764c34a19e1.png)

The [documentation](https://d2lang.com/tour/style) doesn't specify that `stroke-dash` only applies to connections so I'd expect this to work.

d2 version: v0.0.13 on macOS

**Comment by alixander** [comment]
ty for the report, this will be merged and included in the next release: https://github.com/terrastruct/d2/pull/189
