### ISSUE TITLE
Allow control over `sequence_diagram` direction

### ISSUE THREAD

**Issue by Didas-git** [terrastruct/d2#1883]
Sequence diagrams right now always flow from top to bottom but it would be nice if we could use `direction` to make them flow from bottom to top or even left to right.

**Comment by alixander** [comment]
Is there precedence to this? E.g., does another tool offer this capability? Trying to understand the benefits

**Comment by Didas-git** [comment]
Im unaware of other tool that provides this functionality but in my opinion it would be helpful when making some simpler control flow diagrams to use on documentation or a blog post.

**Comment by alixander** [comment]
> Sequence diagrams right now always flow from top to bottom

I think that's just what a sequence diagram is.

https://en.wikipedia.org/wiki/Sequence_diagram
<img width="731" alt="Screenshot 2024-04-17 at 10 26 21 PM" src="https://github.com/terrastruct/d2/assets/3120367/e855b25b-f905-48af-a20f-7392c7463789">

Adding this customization will be too niche for us.
