### ISSUE TITLE
glob null failing to target connections

### ISSUE THREAD

**Issue by Tyler-Hartwig-Pariveda** [terrastruct/d2#1885]
I created a sketch to demonstrate my problem [here](https://play.d2lang.com/?script=SsksSk0uyczPs1IoykzPKOHiqrBSqOZSUChOLSrLTE6FcBQUchKTUnOsFCIUgiHiXAoKtVy1XFyV-FRHoquu0IMqVNC1U6iEcbi4tPTgBuSV5uRwAQIAAP__&layout=elk&)

Here is the code:
```d2
direction: right

x: {
  service: {
    label: X Service
  }
}

y: {
  service: {
    label: Y Service
  }
}

x.service -> y.service

*.service: null
```

![d2](https://github.com/terrastruct/d2/assets/149527402/4a62d33d-a3b0-4c25-9d33-825820261098)

Essentially, I'm expecting this to remove both service boxes, and leave the X and Y containers. Instead, the glob pattern nulls out the existing services, but also creates new "service" boxes that are also linked together. I believe this is because the nulling isn't targeting the connection, which I expected to null from the documentation here: https://d2lang.com/tour/overrides#implicit-nulls

**Comment by alixander** [comment]
> I believe this is because the nulling isn't targeting the connection

Looks like it. Thanks for reporting

**Comment by alixander** [comment]
This actually works now though I don't remember fixing anything directly related. I guess something in the last update did it.
