### ISSUE TITLE
Variable Scoping not honored on imports

### ISSUE THREAD

**Issue by Tyler-Hartwig-Pariveda** [terrastruct/d2#1892]
Hi, I ran into an issue with importing diagrams and variable scoping:

template.d2
```
env: {
  label: ${env} Environment
  vm: {
    label: My Virtual machine!
  } 
}
```

environments.d2
```
dev: {
  vars: {
    env: Dev
  }
  ...@template.d2
}

qa: {
  vars: {
    env: Qa
  }
  ...@template.d2
}

```

I'd expect this to render with "Qa" and "Dev" in each respective environment, instead "Dev" is used on both diagrams!

**Comment by alixander** [comment]
@Tyler-Hartwig-Pariveda is this the full script? Do you mean to import `template.d2` in the `qa` scope too?

**Comment by Tyler-Hartwig-Pariveda** [comment]
> @Tyler-Hartwig-Pariveda is this the full script? Do you mean to import `template.d2` in the `qa` scope too?

That's correct, sorry, i missed that, I'll go update the original post!

**Comment by alixander** [comment]
ty for reporting this
