### ISSUE TITLE
investigate compile error

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1896]
from https://github.com/terrastruct/d2/issues/1891

```d2
classes: {
  dog: {
    shape: circle
  }
  male: {
    style.fill: brown
    style.fill: brown
    style.font-color: white
  }
  female: {
    style.fill: orange
  }
}

vars: {
  dog1: Frido {
    class: [dog; male]
  }
  dog2: Snoopy {
    class: [dog; male]
  }
  dog3: Paulette {
    class: [dog; female]
  }
}

vars: {
  my-house: {
    label: "Home"
  }
  friends-house: {
    label: "Friend's House"
  }
}

relations: {
  my-house: {
    ...${my-house}
    dog1 -- dog3: "Couple"
    dog1: {
      ...${dog1}
    }
  }
  friends-house: {
    dog2
  }
}

```

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=jJHBavMwEITvforB-eE_2ZD2pvZWCDkWeiw5KNbGEWy0YSU3hOB3L7bl9NCkrU5idrQzH2rYxkjR4FIATtrpAsS9PZJB47VhKoC-AA6W6TpPZ6Z655kNtiqn8LsqIVWNsKjBae_TvHVH9_aK2tBOtr4oPqx-1VwarNQ7ya9GCoN3J-3TWHOTlztpHwzegsjx_Afvo8Gr7ZhSolvuqerme6PDudpLF68UbLfEBuVaDlTOnOopuHjbuBqH_yPWw7TMCUpsk5dwJ6Wu63-XWexHaWAAsHiu7hz4EEnTbF6iqjJ4-SLdkakEFiBVUUjTdKrkruY5OEcP0hTb_8Q4_EEG-gwAAP__&
