### ISSUE TITLE
Documentation: Actually specify how to include a theme via CLI

### ISSUE THREAD

**Issue by knbknb** [terrastruct/d2#191]
The [themes/README.md](https://github.com/terrastruct/d2/blob/master/d2themes/README.md) currently specifies only that a theme can be included, but it does not specify how _exactly_ users can do that.

> `d2themes` defines themes for D2. You can add a new one in `./d2themescatalog`, give a unique ID, and specify it in the CLI or library to see it.

Should be extended to:

> `d2themes` defines themes for D2. You can add a new one in `./d2themescatalog`, give a unique ID, and specify it in the CLI or library to see it.
> Example: use the pink "Shirley temple" theme which has an ID of 102:
> d2 --theme 102 --watch example-twitter.d2 out-twitter.svg

This is a very simple issue but it helps users find their way around.

**Comment by alixander** [comment]
Thank you @knbknb !
