### ISSUE TITLE
[v0.6.5] stderr: bad usage: unrecognized command: routeedges

### ISSUE THREAD

**Issue by mauroexe** [terrastruct/d2#1917]
I'm using the latest tala release (v0.3.13)

When compiling with the latest D2 release (v0.6.5) on Windows the mentioned error is appearing:

stderr: bad usage: unrecognized command: routeedges

It's happening with any diagram.

Alixander pls help us 🥹

**Comment by alixander** [comment]
@mauroexe I've just released a new TALA, can you upgrade and try again?

**Comment by mauroexe** [comment]
> @mauroexe I've just released a new TALA, can you upgrade and try again?

Thanks!, it's working fine with the last TALA release.
