### ISSUE TITLE
Lack of base info about project flow

### ISSUE THREAD

**Issue by 403-html** [terrastruct/d2#192]
First of all - amazing project, I hope I'll be able to spend some time adding contributions to it.

To the point. I'm missing here CONTRIBUTIONS and VERSIONING docs, in commits I see chaos, it's not readable, not sure what was added where. Maybe we can tide this up, so from looking at the codebase we know what was happening, and "blaming" will be easier? Also it'd standardize repo.

**Comment by alixander** [comment]
there is a CONTRIBUTING docs. it could use a VERSIONING though, but we're still quite early =)

As for the commits, it's too tedious to garden it, and it slows down velocity. in fact, I alias `k` on my terminal to just git add and commit all changed fiiles with the date as the msg. it shouldn't effect `git blame`, which will always take you to the right PR.

what's the D2 logo look like deep fried?

**Comment by 403-html** [comment]
> there is a CONTRIBUTING docs

ah right... in `docs/`, usually it's located in root of the project

> As for the commits, it's too tedious to garden it, and it slows down velocity.

yes and no, I mean I understand it's a fresh project, and MVP speed is a *key*, but also some order is nice, and 10-15s more to write a descriptive commit, which was done, I think is not so bad (QA perspective, to know what has been done) - also I meant it not only for commits, but also for PR names, so for example later it might be much easier to wrap it in releases in changelogs

> what's the D2 logo look like deep fried?

depends on iteration when you run the script 😉

**Comment by alixander** [comment]
not the tradeoff for us right now, but thank you for the feedback!

I've opened an issue to track the versioning.md https://github.com/terrastruct/d2/issues/195
