### ISSUE TITLE
d2 playground - export to png missing texts in layout ELK

### ISSUE THREAD

**Issue by dimitre** [terrastruct/d2#1925]
Maybe it is something like font not found.
Dagra seems to work OK

![d2](https://github.com/terrastruct/d2/assets/58289/9dbe87d9-a70e-40d9-9d99-a0cd209981bd)

**Comment by alixander** [comment]
@dimitre can you share the playground link?

**Comment by dimitre** [comment]
https://play.d2lang.com/?script=jJJBT4QwEIXv_RVz3D0sibu3Hjx41h8xthMhDnTTGeIa4383pQIFMewJXvr6zeMxTB7eGEVMertiJE_GNJ0oMjoMFr4MgHw06moDgFE70pegIZJM-pn8QynOpbiU4nA7Tjg4PS55Fkhrih3phifN2DOc9wyXPcPhdiws38YIMuYOXGivvaIP0QAoMQ4Px-iDAWhDL5SY1HmKY5GTZvK55QUojU4kC7Vvmz9HA9NCL68bt4bB24eLDIPFnTYHrMKV1t9Pr1aWdGtambkpyVuin0yVaAzvZOGJe1pjcqQRMga8m7JMPy9plf_kTPof9BMAAP__&layout=elk&

**Comment by alixander** [comment]
Comes out normal for me.

![d2 (2)](https://github.com/terrastruct/d2/assets/3120367/747eed73-8c38-4a02-a0cb-9d268e2d12aa)

Can you share your browser and OS please? @dimitre

**Comment by dimitre** [comment]
confirmed normal on firefox
issue is on safari Version 17.4.1 (18618.1.15.111.8, 18618)
macOS 13.6.6 (22G630)

**Comment by alixander** [comment]
confirmed. Thanks for reporting this, filing this in the relevant github repo
https://github.com/terrastruct/d2-playground/issues/52
