### ISSUE TITLE
Canvas small

### ISSUE THREAD

**Issue by ATWp** [terrastruct/d2#1926]
What parameters should I write so that all my generated elements are increased to visible values?

I tested 
```
classes: {
  grid-block: {
    height: 500
    style: {
      font-size: 100
    }
  }
}
```

this is Zed editor...
[5.txt](https://github.com/terrastruct/d2/files/15179555/5.txt)

It's not a line!!! It's image ^_^
![f5](https://github.com/terrastruct/d2/assets/69421094/4fe7c73c-1c4c-418e-8e90-9014bbc7d73e)

How fix it?
d2-version: v0.6.5

**Comment by alixander** [comment]
this is 3500 lines? 

i think this is just an extreme example of the diagram growing horizontally and the aspect ratio making it imperceptible past a certain point.

like if you do `a -> b -> c -> d`, obviously it's rectangular and long, and if you keep going it just... approaches a line i guess. I'm not sure what we can there. There are ways to split it up, like putting them in different containers.

**Comment by ATWp** [comment]
> this is 3500 lines?
> 
> i think this is just an extreme example of the diagram growing horizontally and the aspect ratio making it imperceptible past a certain point.
> 
> like if you do `a -> b -> c -> d`, obviously it's rectangular and long, and if you keep going it just... approaches a line i guess. I'm not sure what we can there. There are ways to split it up, like putting them in different containers.

Good day!
The problem is not that there are 3500 lines. The problem is that it is impossible to specify the size of the elements on the canvas or at least the height of the canvas. If you generate an image in svg, the height of the element (box) is always 21. It turns out there is a problem with the algorithm! It does not use vertical scaling.
Is there any possibility to expand the canvas or increase the height value of the element? I looked through the documentation and didn't find any option...

**Comment by alixander** [comment]
There is height: https://d2lang.com/tour/dimensions (though has some limitations)

There is also a `pad` flag in the CLI.

**Comment by ATWp** [comment]
> There is height: https://d2lang.com/tour/dimensions (though has some limitations)
> 
> There is also a `pad` flag in the CLI, which will add padding around the image

Thanks! It's work!
