### ISSUE TITLE
Combining circle shape for arrowheads with sketch mode removes all arrowheads

### ISSUE THREAD

**Issue by ddolan-lutron** [terrastruct/d2#1937]
See [this playground](https://play.d2lang.com/?script=JMjBCcUgDAbge6b4F_ANII_uEjWiELAkLaUUdy_F68eUiPEPG1LEQ4CP07IENhtXEy5LAW-8S0TullWWHLfKr3ZVKRGV1T-fNOkNAAD__w%3D%3D&sketch=1&layout=tala&).

Setting the arrowhead shape for either source or target arrowheads to circle causes all arrowheads to be omitted from the diagram when Sketch Mode is used. Seems to be independent of other arrowhead properties.

**Comment by sossost** [comment]
Hi! @alixander  I am sossost, a new contributor. I would like to solve this problem. Could you allocate it for me?

**Comment by alixander** [comment]
Much appreciated @sossost !

See relevant starting tip here: https://github.com/terrastruct/d2/issues/1936#issuecomment-2103037590

**Comment by sossost** [comment]
@alixander 
hello. I tried this issue because it seemed interesting, but it was too difficult due to my lack of understanding of the Go language. Can I give someone else a chance?? sorry.

**Comment by alixander** [comment]
No worries @sossost , thanks for trying!

**Comment by bo-ku-ra** [comment]
maybe i'm looking in the wrong place, but...

sketch.go (func ArrowheadJS)
```case d2target.CircleArrowhead:```
and
```case d2target.FilledCircleArrowhead:```
are missing?

**Comment by 23danielsuh** [comment]
I'd like to take this issue if possible, I feel pretty comfortable in the D2 repo now.
