### ISSUE TITLE
Is the installation path fixed to $HOME/.local/?

### ISSUE THREAD

**Issue by lxwulf** [terrastruct/d2#1954]
I downloaded the Linux zip file and wanted to move the binary in the `/bin` folder of the zip file to `$HOME/.bin/d2/`. I recognized that this does not work. Then I looked at the installation script and saw that it want to install it to `$HOME/.local`. 

So I decided to copy the binary to `$HOME/.local/bin`, and the wizard of gondor decided that does now work.

So as my titled mentioned it, my question is: Is the installation path fixed to this specific location?

Greetings

LxWulf 

:penguin: :wolf:

**Comment by alixander** [comment]
What do you mean by "this does not work". What happens when you execute the path?

**Comment by lxwulf** [comment]
I would like to apologize for my lack of clarity. The binary works in any case, there is nothing wrong in that regard.

What I meant is that I can't call the binary if it's under `$HOME/.bin/d2/`, but if it's under `$HOME/.local/bin`.

So my goal is to have all external binaries or binaries I want to test “installed” under `$HOME/.bin/` to have an overview of them, but this somehow does not work with `d2`.


> [!NOTE]
> I have my path to my custom `bin` directory exported in my `.bashrc` file.
>
> ```bash
> export PATH=$PATH:$HOME/.bin/*
> ```
> And yes I also tried to point directly to the `d2` folder. 
> Other external binarys do work.

**Comment by alixander** [comment]
What do you mean you can't call the binary? The error is that it's not found? If so this is an environment path issue. It's impossible for a binary to hide itself or something unless at a specific folder.

**Comment by lxwulf** [comment]
Besides that, other binaries does work in my custom `$HOME/.bin/` folder, your answer is not really helpful. No matter if I'm wrong or not, you could explain what it could be or just be more kind.

Anyway, the question is more if your execution path is hard-coded in the binary. Because as mentioned above the binary works in one of the standard bin folder but :point_up: not in the `custom bin` folder of my own. 

Greetings,

LxWulf
:penguin::wolf:
