### ISSUE TITLE
TALA API error

### ISSUE THREAD

**Issue by GeorgesYCM** [terrastruct/d2#1958]
https://play.d2lang.com/?script=7Fzrbhs7kv7vpyB8MNgzC9iW5CS2hcECtuzkBBsnHssnObN_Fmzeu3lrXvo2yAPlOfJii5ZaluTLxHbSSnZyENhOU61ifcWqYpGs4jQ6MBWBjME_twAIxo7BcDAYbAEgCQ1j0P6vFDjwMdgfztp9qCXZpULKMdj-hY4oJvvbW1sA_AOpt8fT94RANRjO6QHgObRkDFAthcbEzdpeK8jIGGy_PZ5ud68BIJDRY8BDsH68t9c--d1AnIM-uIjCLjJqj3hPdBBQ-r3h8GAHwwAT6MmuL1hHpetOtD10TR33o-eHXQMngvEwBsMXo1nLx632ZwuAqbDQ-2mAQRi9v0Cw4PZxrAaC-B4mPgvGPoi_4f7gJn9dyzV_NVI75XA0eihnfn8n-p2S-LAz3IUKNkbD0nfsLdmNVhqICd6ZceX3RgcHBy-OXgxHe9Y0umINjcQg2Kgs5xWKMpa18ji4Xau_Cay53vw_U5ilVRzMX1u8tD883Jq_cjb94xrUms0QTDEdbs8-mVncXCALg5s9vH9z_BZcmUDU-BrxOpXBgBxRur3VffgPpF4RTbzwF45YZ_Bo-cW7VKUHdZG5T5luUOGUIY7LXBKRBJLliYkOrqjLPYK_U23uUp3lICz_LvGfkuKngz7TlFOO7CryG56aHh0NBtublUtDXePzusQcR9fkscFpkTjnBIsN4b3K5eOKIe0_v8-KKMUvINleSnICE6GJv9q8DmlW8hJDkTeWZo0UaYW5yR1KMlrlrn8d-kMkZn_jqFNf67zhnGWuCFySBmrnWFbmOcpYtgHLKc6hD8RtHLgvuCw4ZM5XdUIkr5TDLs8dpywn2cZM49ngPtMglNJ9tDCNteBo83NLgCRYz6jgNs-xkIY2mNfMF1UrxJ7VZEpcQaKbi-Bngr6qKO_PwVsSSuOy-xTm8JDgg2fXvnRyPiFM4JPT0x9sUkJB-VRIgamCKvqc8UJzo1kRy8aL_l3OmbMnGG9cjyCjNhBvUGTMeGei1TxXQpQ6cgtXYuJeYE_O35-dHZ8vV4Ybw50wm6e1QZo0TVITY3IoqkxXWakIqvse7sn5-8nZ26uzy--APDLYFLlkJTEJFL6w2lOYhMQ4lZpmN7U9K_rk8nuMN5G5yC3zec1LnQpoFGY6U3mmdMWyvvV8jnr086FufX07UQpENg4-j6qm3EOiCumQSRwXtpEktYVhUfWv6FPIyAWsNw8cuZQQWEUWkiqHzFe8aUINtdAGMdz_VHY8Od38PBZp1Jw3iJe09lVOce1K1LDAijqJ_WOeRzWvfzIln5y_FIgL4vy3jeaeunHX0-CewgCnBEUnQr3xES6oyjOUpYJiVeKS5yLJcpdBm_LG6P41-wK6TGj2-28vf7CIva6iYzmxMTS4SROkoiFEcp0h4TLev-rPTP4DSf5cyKyJ5fj0dnQHRk8yeNhER_Ze49bqQ_2X0aALJf4yGkyMNG7vGAVRtI-nwhEUjKv7X7Ecn47-zfFNprcBXnw47X3Tr4glwlXNnW5MGmkjjMwMJxmqGlf1pLjX-P77de-OHNVIxTY0qTJRO29ckulcNwKXCc02YZiTd4_X3K-GTVkgJcQNpI0Q3NS1SEjAeQw613wDsC8uX7cr7ekP5qYFqorS2gbVSAYGuZMNDLpyDRfWbuBw6PL8fPNbD7aqoXa2hAYGyUmTIiaSlFcKxgLtliSx_YI-IdxIfMe-PvhgHL5wxPveD3QQi8R6XmKHsIm-DgWPdQVhhWia9Ozllvh7duVcYZRkNoeNNbkSOWYiJbE0KeEF6yk0W4CcuBZLvwB5wQMJNAZsa0MaW4mKK1wQGK2loX_r_UCS8-iJ2fyZdkPzDDeNhCWOSWmltRGhLMHBZDXpP-hm0opHenLw6s1F75M7TKUUVeJhEYWsOVMmqXGdOKySRIqezXpiog4Xl1e9RzCccenKRpZpykoBK1oia3VkmFtb9m3WEAXR-4ap5lpBmlChY46CiLTMXC5SLGUecE_B9wLhVJmMXAjNej9lRs7GlKM0U2V0HFclyaq8coTYwtkNbZYdW_vTbQm_nh5fTjcfdslaIVvb3Ga0aYraG1GJ4GrljBCm_-H-H0I0NmhasM2fbwrFlMGJL512hKQEuqqkCvOGlWlSbkDVDcqsCJs_A4imCcYyi6qI6wKmQeIy1kplyOi8f9xvIRNm82kRsMikLaHKokCa1oVUSNRCkRKiqvH9w_6d00sC8XfIHGocp9AUvoGpzSByBReK1Hlqaqk16t-1nUQsEuhvn3aBk997X26khTMUy4QG7ynRwlsOcxsdjE2heg6-rj70HnYlPC8qr1JjvW4YkUpwl7UGDQWyfW-M9R9WpibReSoYIREjWKVNHWEpdOkyqEvTc1j50jgVJRSudws1LhCCyyyypMQuj4qKkipVprU3tOnfN73zVwJlZPNzEeN5VfrEF6FCzGPupNNOBtfQJsam_x3AP0RifrDdv--Y4Ppxmb03Gt2XtXdy9vL5WtbeYhd18zks33GjdEVUk3f3ygodoSN0sJIt_l5Cvfb-n1n313IcDlaTv26I5QC9QKtp913txgehsSn9FfHB_3kGfZcdD-4X6cHwMFkR6SUUOjHlB5JcBvQKBlLCzac0VCn2VNdVKgpUB5XRSjmbFga5SiOxKVU8GN6f5Y72D4YHa2LDIn6H5YzhQeSqLKQos8qTpJEsDWktVF2jjfm-4b0Wi48gpGtySvDUPbpK5u7TcaGpg3uD4f5OcFB7Slyvh9_z3-8oBb8eO8RFQfxf78K9Y2EIxOkxYA4K3X2-UrJ3o2gPACPx_yLCBPYswT-YA_uuO2LeFUeHg8HA_ymUtYA1gShK-IMJhYfMOFM1EIeIE1blWSkl4420EMdNxA__ubsowj0adNW0XYwQCNpY-XNV8arwBtW2CipDgtEiQ96ojPOiYd-k_Pnj1tZEmti5ivnQew6xKceAQunJdauKMggrybL92g_NfdDhvDq_K59uid4q1j84njx7OZmVDL8yhkkCXk0u7q5RPjpr_21vrRytta9uL7_Xm9ipR2mwTVP4IkadSxOLPEgDc-cMDw8S-5dqt29VXY-eDwaLevTjJjrS2uZCMrfefjEYrJaAHz4frZWAt0q7Irj9MdiemOicINL3JjVWca80bFzBnEFlo3gOK1JljhSaFV8ptU4GhzcmvaVAlwlGEyMlTIyb1Qn2hrZOvfAKKpfTouIkJ4Tw2gvuiFd5WHHb3wzt6NnBLbzPxmD7BKLMUCoQAcfW9ueLmlzyjMSc5Fp76dPSNTnN0kB0kid9DO-zF4e3AJ_p4OAYbM_-gtenvcGFNSx1zSJsSp5YnrhgYJXmwlVRy6wPuAfD57fgTv_-ptXo1peC0y4FvTfImibS2IaJyHOIGqZRgnLnqxoJh0UfkI-er05FAHSHd_e6vf01r7fQj6XXe7aZafnB53xfIajBPZ6u_fkAPUzEWhQy83xTGAvCoMPEg5nO9CaByGkmYWQBplynKJM2BKsrSKqSMtTTDDnoZsiPW1u_gDcQSOEDAS1YKYj2gOjgCJDEAz8vl_Zbi8uFds-mf-x21ea7a8XU4G87_wXufu1Gvfmk7SUAaaLDjyZ882afLxBbljrvrmQSgr_tgC93PAaXnz-haD9_mk-BcwkRFKIjHmACEHSB-C_2Oi8SnsGYKdPuSlhyAj3xQBGVtDT3wDRASoE10QH5H9DaxxNfDQe_HfUHiet9JMC3tCFo_Wt30cBKf-CfXVwcnMnIGBgHNSMfH8rGvQq2zsZxamIAe8BHax3xfj50IIGYEQ-mVwI_jY_ruuc1Rm7clbXqOqRBUM4N6_25fwz1-VAu3NMtd_RAkl3Z7j2WeZeIx-DUaP35U9vR5Tm4cAY_dcxmtbNf0_XnT_Yrul_UcT6NA9t-86nAuzypR_U8MUpFLdDM0cwlsNc22gAf1uHJ6ycibY3z5HVrIBIC9Igeu7KXp3U77-ipIj4-fZhSz6p-prVG3BlwfAr2wOnbafv7t8nFF81xceXFg3palpVNSR6NgN7QAFA3OX3-xIh7oLF-sbPVyziuuj3WAPCq8RTE-TVGnujvrkXwUAnM0gOXTFFndADdmorobzDqDxr0ybvbU_eavvtOJRaLn62H0AR3zd9ryvVAcstz2YfAWabozN0Bm08oQi3mNn9Tnlbo7C5pjkarfY822_nsWrPd21fbPcp9nCHeqooH59AJDf-Vi7zZ3ykp-upqncAiYePuoOmWRo_BvJKQdr4fTKfvvjKO_TZ9PDx0WPq-a6Hd9kZnlxePNvDVjeI1lucx178KlFbipELgz5_Ml2OllYTXVq5zytcL6RXSXVj36uz0MbHATYKX0FpnECeK6OABhd26Yq_1kgpq_ICVxWqJ-0N0YVn3f6yhrP3cmpWJRccFJoB27zxxflzebPqK-OtV0zuHiVNQ30F0ONy9PoL8kksag2OshBY-rKzIFmvU1X33zhlt_0Lps-dodvPZ6ic7i-3erY9P4qiF92Nwsv-8D0623rQRi8ZdXqgm0I1BYkIwagcRHWaXua7fJcycwDvOlH4M9hePyMiotB-D4aKFQdsdsV6eXgASwHT6G_h1f__wqH0Yjf564-7YQKqweqRhdNjxoiFjMBzcbEdGGreO7-MWANO_vwG_Dp_t738D2vNIpSP88uoC_DoafgOy7ZzZbcj8XwAAAP__&layout=tala&

**Comment by alixander** [comment]
dupe https://github.com/terrastruct/d2-studio-issue-tracker/issues/59
