### ISSUE TITLE
Please tell me there's a way to install this on windows without needing WSL

### ISSUE THREAD

**Issue by Pomax** [terrastruct/d2#197]
Cross-platform availability of tools is such a blessing, I hope there's just some instructions missing on how to install this for Windows users.

(without having to install a complete go build toolset, just a normal .exe or .msi installer downloaded from https://github.com/terrastruct/d2/releases, using a github action to create builds of course, a la https://blog.devgenius.io/write-your-github-actions-workflow-for-build-windows-application-94e5a989f477)

**Comment by alixander** [comment]
there is not, currently =( . same time next week, there will be =)

https://github.com/terrastruct/d2/issues/96

**Comment by Pomax** [comment]
As long as it's not "you need to use a different shell", because that's a great solution for linux devs who use windows, but a terrible experience for "real" windows users =)
