### ISSUE TITLE
support directory to directory compilation

### ISSUE THREAD

**Issue by sdykae** [terrastruct/d2#1973]
support directory to directory compilation

the simpler way i found to use the tool in the same directory and output svgs in the same directory is:

```bash
find src/d2 -name '*.d2' -exec sh -c 'd2 "$1" "${1%.d2}.svg"' _ {} \;
```

**Comment by alixander** [comment]
Thanks @sdykae , agreed. Dupe of https://github.com/terrastruct/d2/issues/13 .
