### ISSUE TITLE
Column name 'icon' in sql_table

### ISSUE THREAD

**Issue by bt** [terrastruct/d2#1980]
Hi all,

Just came across D2 and using it to draw some of my ERDs. I have a table that I use to store something that has to do with icons. One of the column names is `icon`, but I can't use it because it thinks that it is referring to an icon file.

The 'icon' column is a string that refers to a path, so in the D2 I use:

```
icon: string
```

This will throw the following error when rendering:

```
err: failed to bundle string: open string: no such file or directory
err: failed to compile app.d2: failed to bundle local images: [string]
```

**Comment by bo-ku-ra** [comment]
fyi
https://github.com/terrastruct/d2/issues/1419#issuecomment-1600442266

**Comment by bo-ku-ra** [comment]
@alixander will it be implemented?
https://github.com/terrastruct/d2/issues/1419#issuecomment-1601301953

**Comment by bt** [comment]
Thank you - that fixed it 👍
