### ISSUE TITLE
Icon is not visible in readme.MD

### ISSUE THREAD

**Issue by alakdam07** [terrastruct/d2#1983]
I have downloaded this [diagram](https://play.d2lang.com/?script=xFRNi9swEL37V-iSo5IlRx8K2cSBQgulWugxjOWpLaoPMxqlZEv_e1GyiTfdeC8m7dGS572nmfemMYSaTfClINN2XBRr9ExgzTM2CnUiw4dS_CqEiB30WArjoMVCCKNzUcfcx3KxyF9xzkgEkSlpnuvgFvAzzpbbVd9boyGzzJYPHz1jSy9f25WD5-BltUfPj2SaFudx3xa_i0J1QFkC7Y3G032K_0XJZ3Q10krrkDwf778mi_9Uym6dIgcnMR_JOsUdYQyJNMpMsrN5drJuz5I_gasbUBwINwcPLkxUuw6uT4xZ2zclT-jXXF9SbU3snoKq1B3JBhoL-scdiU5t2zxOpNgAQw0Rh6megS8-n96vozeQZsuHyrfQokPPA6EyrrcoKwfGypc8SVWpS0st8PdA7gnBTetqg_vZchszxnV27gJ9Y1EJ-UG8tzf4YHEO3jhgbErBlHB01WSsd5M_Ana7JqO9CWU-PNth-OF1ko4PuhhkhPE1xHU-hjf8PYERqLflY-64DfAnAAD__w%3D%3D&sketch=1&theme=4&) as SVG. 

I am trying to include an SVG icon in my Git README.md file, but despite having the correct relative path and confirming that the SVG displays correctly in local browsers, it does not render in the README.md file on Git. Here's how I've tried to include it:

```markdown
![Architecture](./infra/security-infra.svg)
```

I have verified that the path `./architecture/security-infra.svg` is correct relative to the location of the README.md file in my GitLab repository. 

**In my browser it looks like this:**

[![enter image description here][1]][1]

**In readme.MD it looks like this:**

[![enter image description here][2]][2]

Despite these efforts, the SVG icon still does not render in the GitLab README.md file. What could be causing this issue, and how can I resolve it?

Even it works in mozilla playgroud: 

[![enter image description here][3]][3]

**I suspect this image href does not load the svg:**

    <image href="https://icons.terrastruct.com/aws%2FApplication%20Integration%2FAmazon-EventBridge.svg" x="0.000000" y="250.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="64.000000" y="399.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">CentralizedSecurity</text></g><g id="SharedServiceEventBus"><g class="shape" ><image href="https://icons.terrastruct.com/aws%2FApplication%20Integration%2FAmazon-EventBridge.svg" x="228.000000" y="250.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="292.000000" y="399.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">SharedServiceEventBus</text></g><g id="MemberAccountEventRule"><g class="shape" ><image href="https://icons.terrastruct.com/aws%2FApplication%20Integration%2FAmazon-EventBridge_Custom-event-bus_resource-icon_light-bg.svg" x="456.000000" y="250.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="520.000000" y="399.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">MemberAccountEventRule</text></g><g id="LambdaStoreDynamo"><g class="shape" ><image href="https://icons.terrastruct.com/aws%2FCompute%2FAWS-Lambda.svg" x="684.000000" y="250.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="748.000000" y="399.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">LambdaStoreDynamo</text></g><g id="LambdaPublishToSES"><g class="shape" ><image href="https://icons.terrastruct.com/aws%2FCompute%2FAWS-Lambda.svg" x="1140.000000" y="0.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="1204.000000" y="149.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">LambdaPublishToSES</text></g><g id="PublishToSlack"><g class="shape" ><image href="https://icons.terrastruct.com/aws%2FCompute%2FAWS-Lambda.svg" x="1140.000000" y="344.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="1204.000000" y="493.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">PublishToSlack</text></g><g id="DynamoDB"><g class="shape" ><image href="https://icons.terrastruct.com/aws%2FDatabase%2FAmazon-DynamoDB.svg" x="912.000000" y="250.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="976.000000" y="399.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">DynamoDB</text></g><g id="SES"><g class="shape" ><image href="https://icons.terrastruct.com/aws%2FCustomer%20Engagement%2FAmazon-Simple-Email-Service-SES.svg" x="1368.000000" y="0.000000" width="128.000000" height="128.000000" class=" stroke-B1 fill-N7" style="stroke-width:2;" /></g><text x="1432.000000" y="149.000000" class="text-bold fill-N1" style="text-anchor:middle;font-size:16px">SES</text></g><g id="PlatformTeamSlack"><g class="shape" ><image href="https://icons.terrastruct.com/dev%2Fslack.svg"

Any help or insights would be greatly appreciated. 

Thank you!

  [1]: https://i.sstatic.net/ykoupfA0.png
  [2]: https://i.sstatic.net/l5Yb59F7.png
  [3]: https://i.sstatic.net/WQc964wX.png

**Comment by bo-ku-ra** [comment]
i think it is difficult because 'D2 Playground' does not have a bundle option.
https://d2lang.com/tour/man

**Comment by alakdam07** [comment]
@bo-ku-ra I found a way to do that. I have taken svg diagram's screen video then converted it into gif.

**Comment by lovette** [comment]
Try replacing the image reference to an `<object>` tag, that's what worked for me in https://github.com/terrastruct/d2/issues/1985#issuecomment-2315155112.

**Comment by alixander** [comment]
it's bundled now
