### ISSUE TITLE
Support for options, alternatives, loops in sequence diagrams

### ISSUE THREAD

**Issue by sanguineti** [terrastruct/d2#1986]
Hello,

I am here to discuss the need for alternatives, options, and loops in sequence diagrams. There was a discussion some time ago in #1688 where various points were raised regarding this need, but no one has commented on it since.

What do you all think? Do you see it feasible to add this to the roadmap? Currently, I believe it is a reason for many people to stay with other tools and not migrate to D2.

Thank you,

**Comment by alixander** [comment]
Replied there, let's continue there 
https://github.com/terrastruct/d2/discussions/1688#discussioncomment-9887350
