### ISSUE TITLE
Globs do not  affect arrows

### ISSUE THREAD

**Issue by FluxusMagna** [terrastruct/d2#1989]
Globs are not affecting arrows, even when they have the specified attribute. For example, changing the font-size for a diagram like

```
x -> y: z
**.style.font-size: 50
```
 results in a a diagram with large text in the boxes and small text on the  arrow.
 
 I expect the output from the above to be the same as for
 
 ```
x: {style.font-size: 50}
y: {style.font-size: 50}
x -> y: z {style.font-size: 50}
 ```
but it is not.

**Comment by terlar** [comment]
To target the connections you have to use something like:
```
(** -> **)[*].style.font-size: 50
```

**Comment by alixander** [comment]
Thank you @terlar 

related: https://d2lang.com/tour/globs/#glob-connections
