### ISSUE TITLE
`{near: bottom-center}` returns API error

### ISSUE THREAD

**Issue by MarvinJWendt** [terrastruct/d2#1991]
https://play.d2lang.com/?script=dJHBToNAEIbv8xTzAj0UbnMwETloGqIJqXcKEyXb3THs0MYY390siwu29sTMzz_D_B8y6pGV8Hl6AnTsjcoHYRkLsE1LWDVtIWIAzMkS7l4rrM-9tu_QSWt690ZYxgJrbbQXB2DFbQkrcb3KgFv8ctwMhAdRFbtp2SkP38GVLa7stitfXPkNFxj-PEgzdIS7uQIro-cwOnoGiGFxc4dzzJViTnb9PsZJPGYH4WNZPV2J5ct_UkC32kW4r4vNA_wyu1h5IYaV11LgH_oIdxpclGyyLH3-ZyT92H1dJG11GURW09cSx3M_8JG9T2jTMSHLPfwEAAD__w%3D%3D&layout=tala&sketch=0&

When only one monitor has `{near: bottom-center}` it works, if everyone has `{near: bottom-center}`, it returns an error.

**Comment by terlar** [comment]
FWIW it works with ELK and Dagre

**Comment by alixander** [comment]
I don't see an error, just that the last one wins, which is expected
