### ISSUE TITLE
Connections used in a Legend

### ISSUE THREAD

**Issue by amb007** [terrastruct/d2#1992]
I have trouble adding a Legend to describe various kinds of connections. The best so far that I've come up with (dagre does not allow for width, for example) is silly padding, like
```
  g1: "" {
    class: pad
    #width: 400
    grid-rows: 1
#    grid-gap: 0
    source.class: legend-node
    p0.class: pad; p1.class: pad; p2.class: pad; p3.class: pad; p4.class: pad; p5.class: pad; p6.class: pad
    target.class: legend-node
    source -> target: data processed {
      label.near: top-left #ignored on a connection label, only a shape label works
      style.stroke-width: 3
    }
  }
```
which gives (in Chrome):
![image](https://github.com/terrastruct/d2/assets/395676/152c92f0-a141-462e-9062-ace43c79f54f)
where the arrow is broken (I tried reducing grid-gap, but it does not seem related).
Is there a way to put the text above the horizontal line?
For completeness:
```
classes {
  pad {
    style {
      opacity: 0
      stroke-width: 0
      fill: transparent
    }
  }
  legend-node {
    shape: circle
    style {
      stroke-width: 0
      fill: transparent
    }
  }
}
```
EDIT: I found out that adding `label: ""` to the `pad` class, removes the breakages. Still, the general question is about connection support in legends.

**Comment by bo-ku-ra** [comment]
forced..
https://play.d2lang.com/?l=&script=lI7BasMwDIbvfoqfHgMuLuwwVNi7eLaWmBnbyCqtG_LuI3S5bxchJL6PLybhoKkWgqR5UTNLinb2jeBeu9R7J1zMA9biuY9BWLuOzOfafEg6CG7b_x8YxjwJp-jVo0kN3DvHE9Z7iroQ3py7IvtPzufCXgj1pj1FtlqbDVyU5YqXuqvUb7a_oDvOXylngoovvXnhopsx0zQR1oX3fsLlfTMPQq83CXyE_t02COplZv0_-hMAAP__&

```d2
direction: right
grid-gap: 0
grid-rows: 1
x -- z -- y: {style.opacity: 0}
x -> y

z: "data processed" {width: 400; label.near: outside-top-center; style.stroke-width: 0; style.fill: transparent}

***: {height: 18}
x: source {style.stroke-width: 0; style.fill: transparent}
y: target {style.stroke-width: 0; style.fill: transparent}
```
