### ISSUE TITLE
CLI Support for forward proxies 

### ISSUE THREAD

**Issue by damnhandy** [terrastruct/d2#1993]
I'm trying to use the D2 CLI and VSCode extension from behind a corporate proxy. Anytime a remote icon is referenced, it results in a `Bad Gateway` response. It would seem that the CLI doesn't honor the `http_proxy` or `HTTP_PROXY` environment variables and attempts to go directly to the internet, which ultimately fails. It would be great to add this support either by reading the environment variables or via a command flag such as `--http-proxy=myproxy.corp --no-proxy=127.0.0.0,*.corp`.

**Comment by alixander** [comment]
The CLI doesn't overwrite it in any way. If the remote icon uses https, you need `HTTPS_PROXY`.
