### ISSUE TITLE
slog type error on v0.6.5

### ISSUE THREAD

**Issue by Watt3r** [terrastruct/d2#2004]
I'm upgrading a package I'm using from v0.4.1 -> v0.6.5.

I'm struggling a bit with slog. Has anyone seen this issue before? What's the fix?

My code is https://github.com/Watt3r/d2-live

When I run `go run`, I get this error:
```
# oss.terrastruct.com/d2/lib/log
../../go/pkg/mod/oss.terrastruct.com/d2@v0.6.5/lib/log/log.go:52:28: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Debug
../../go/pkg/mod/oss.terrastruct.com/d2@v0.6.5/lib/log/log.go:57:27: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Info
../../go/pkg/mod/oss.terrastruct.com/d2@v0.6.5/lib/log/log.go:62:27: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Warn
../../go/pkg/mod/oss.terrastruct.com/d2@v0.6.5/lib/log/log.go:67:28: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Error
../../go/pkg/mod/oss.terrastruct.com/d2@v0.6.5/lib/log/log.go:72:31: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Critical
../../go/pkg/mod/oss.terrastruct.com/d2@v0.6.5/lib/log/log.go:77:28: cannot use fields (variable of type []slog.Field) as []any value in argument to from(ctx).Fatal
```

Any help would be appreciated.

**Comment by bo-ku-ra** [comment]
> My code is https://github.com/Watt3r/d2-live

c.f.  https://github.com/terrastruct/d2/issues/1213#issuecomment-1526883118

For example,
```
https://api.d2lang.com/render/svg?layout=dagre&theme=7&sketch=1&script=<encoded_string>
```
https://api.d2lang.com/render/svg?layout=dagre&theme=7&sketch=1&script=qlDQtVOo5AIEAAD__w%3D%3D

**Comment by bo-ku-ra** [comment]
i do not understand the golang issue. 
but i hope this will help you to improve your product.

here is my use case.

i can draw directly from 'D2 Playgraund' by the following bookmarklet.
```javascript
javascript:(function(){var url = location.href; var redirect_url = url.replace("https://play.d2lang.com/?l=&", "https://api.d2lang.com/render/svg?"); window.open(redirect_url,'_blank'); })()
```

**Comment by alixander** [comment]
@Watt3r indeed, this is a known thing. Slog made some backwards compatible changes that we don't agree with, so we version locked to our current. I have this line to projects that import d2

`replace cdr.dev/slog => cdr.dev/slog v1.4.2`

see https://go.dev/ref/mod#go-mod-file-replace for more
