### ISSUE TITLE
[markdown] support footnotes

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#2005]
[markdown] incorrect Explanatory notes.

```d2
md:|
# Explanatory notes
[^1]foo  
[^2]bar  

[^1]:foofoo
[^2]:barbar
|
```
https://play.d2lang.com/?l=&script=yk2xquFSVnCtKMhJzEssyS-qVMjLL0kt5oqOM4xNy89XUOCKjjOKTUosUlDgAgtapeXnp-Xng4WtkhKLkhKLuGq4AAEAAP__&

**Comment by alixander** [comment]
This won't be supported, it's too document-oriented instead of diagrams
