### ISSUE TITLE
[Bug] API error using all layout engines

### ISSUE THREAD

**Issue by pidgeon777** [terrastruct/d2#2007]
https://play.d2lang.com/?script=hFZdaxzLEX3fX3HQfbgS1grZSV4WkuBr-xITXzDIYEMmFrU9tTsV9ce4u0arRd7_Hqpn9ssO5EVoumu7Tp86daofKZcFnmdA-2ruUlzJevwEPG3ToHOOa4m8APuHuqwdB55Lu8Cfbm9nwG62m81-wR8kEZ9EPc_U_i7wPbQz4BfcaZa4xqeOU94u8DrifZy33GuHd0-9T5lUUpx9x3Nkygto6ueOo3KuB7-PmlM7OAuCpvPjZnKyOwIvHfW8QOFvA0fH963QOlOYAZ87Ukg5P-HvC1ycLVgE2S1TZhVHHqtMgTcpP0AiNp24zrbRJ4k69_LA6CmrOM8FaXX4QN9ti7gCyozMvSfHLZZbpMjzVgLHIimSR1r-h50WPMS0iaCCUvGUm4sZDBR-IzvnALTgUZaZlEGKVlYrzhwVqzxeWbhcg2JrIAtPsZJiQcvKOUjkil-3PZ_h1Y63BjRz4ag1--duC1H8Qaqcy09U2XLotVhdMrsUnXjGt4GiDgGBXUexMhBbrDlyJo_MnlQeRbfXSIbdziMMUVbCLVouLktfq51WIO-xGmJLgaNaLVJ2bMxUbfyTt3iTomPDIPEHbTzw9t5Nu2facJ5KmQEv3g7kRbcLXBjNUyy0O-O1SkG4wFGc4C1HBgsFqzLHFDhSJezF3dBzLtsQWE3tF6_RZ4lO-kowKfqc-lTYRLYPw5J1wxyxTMXqZHStrFIpjiJ48e5JM-HtXjQ_V6JPRawOHYOfpKhJ3_gLKde8sW6t0pBxkF7BxqJ7zmLhY6bfMkXG55R9W9EPUR45lwl8PbsgRRDC4FX-h5BxubQzrqwghE7WHeezsNJTzTb5hhkKjZ32e8ph8FWtGIpd7wN94i-zQNrdr46bYzX521C_Xi7w3ZPyU_WnO_wVzSqTe365e_5z00tDvu_o1x0aiYr266umyDoQmvIt6_O826H7-jwGNUtW2qGpLUH-flzFl69NGE5WLQpf7pswzIDvJ0henSFp_oXmY5HLRvlJn1PPcers3ZVhlKj3z_tD0dwZqB1e27GXX66O6XSf_9_7bE-9pzgRMbrs6BMryUUPYI6tPOqC3KGpRqGJm_BcY9NxZjSXd82V-d8x_BrN5UTgcWv8FXSsqIV0x01TtDiTyEnoxvRUOmYdram5rHdqrqo51kAThUqwNky5lUjK5aZeq5iztMd77XtwzCc2KU7uFnHCNDaiHQhrGtbGD3vLXTlurm4qn1WFbzrynuOax-Z7k0XFSQll5g47_2-8fCD3YAje1Y6a_Ordo7QWt8DFWy69KMP6lD2vKTq-PrcseHIPBa1k6yM-PYingw5D4QPFtjjqGR9zWnoOk4s9UlHEISw5V3dPpcjSM0rywzgGLl_efv3L7e0VAj1wMX83sxM3eDUj7zO34hSlZycrcdMcI_-D1Z117psUes9PRzOtrrn9tSCchrlDWOXZJpZkDnV8pTyZxalDmTzqoK2j1aWoHO0We_sw9_eDxc7c4d_D2-NsHz9wnTmQRDOz6pRVu6koVlScyc9Ct6w1aU5mgtanh2kgESG1nON-zt_gvRbQUmykGJE20raj7_40wer1p1EAgkvdfojv3xrGxxBbzkUptrXfOj7asRQMsads6vTc3uAfacOPnK_HtwlpZxA49JIr84_kpR37x1LTVArdV8oo2A_udSabz5ajqPj6AhrWnY7ddOyIm-OjbZlUUzh9t70dGwO_-7Q5e6Zh_jecjmb7_tHgbe2Yp34dC_nfAAAA__8%3D&layout=tala&

**Comment by pidgeon777** [comment]
When using this syntax, the error occurs:

```markdown
equation1: |latex
  S = \frac{1}{4\pi\alpha'} \int d^2\sigma \sqrt{-h} h^{\alpha\beta} \partial_\alpha X^\mu \partial_\beta X_\mu
|
equation2: |latex
  \[ \Psi(\text{open string}) = \int_{\partial \Sigma} A_\mu(X) \partial_t X^\mu \]
|
```

However, using the following syntax (`md` block type instead of `latex`) eliminates the error, but at the cost of losing LaTeX formatting:

```markdown
equation1: |md
  S = \frac{1}{4\pi\alpha'} \int d^2\sigma \sqrt{-h} h^{\alpha\beta} \partial_\alpha X^\mu \partial_\beta X_\mu
|
equation2: |md
  \[ \Psi(\text{open string}) = \int_{\partial \Sigma} A_\mu(X) \partial_t X^\mu \]
|
```

**Comment by alixander** [comment]
@pidgeon777 Please see the section on latex, unfortunately you have to escape twice to get the backwards slash command: https://d2lang.com/tour/text/#latex
