### ISSUE TITLE
icon render result seems weird with icon

### ISSUE THREAD

**Issue by FFengIll** [terrastruct/d2#201]
d2
```
# icon
09af4a91795841be981112f92b69cf7a: cluster1 {
05c03a172362482bb5165622c7d959a4: n1 {
    icon: https://cdn-icons-png.flaticon.com/512/6461/6461819.png
    shape: image
}
d68d42ba8dbb45a0bd8de63c5d974a2e: n2 {
}
05c03a172362482bb5165622c7d959a4 -> d68d42ba8dbb45a0bd8de63c5d974a2e: '' 
}
```

result (in mine: chrome, macos, d2 v0.0.13)

<img width="346" alt="d2" src="https://user-images.githubusercontent.com/7359555/203877611-45479b97-fdc3-4469-8d83-75f02188a6d2.png">

**Comment by alixander** [comment]
The label placement is rather naive right now for dagre and elk layouts. We have to add smarter label placements, which is built-in to TALA but has to happen post-layout for layout engines we don't control. So for example, in this example, `cluster` should've placed outside the container, to avoid collision. 

I've created an issue to track this, thank you for reporting it!
