### ISSUE TITLE
Not null constraint in SQL table does not work

### ISSUE THREAD

**Issue by i-am-the-slime** [terrastruct/d2#2019]
This would be very cool to have, but it either doesn't work or isn't documented.
Maybe it could be rendered as an asterisk or something.

**Comment by alixander** [comment]
<img width="777" alt="Screenshot 2024-07-27 at 10 14 33 AM" src="https://github.com/user-attachments/assets/1f40c1bf-3a67-4705-91fb-b7b51b793362">

What's missing? An asterisk is just mysterious

**Comment by i-am-the-slime** [comment]
Yeah, it's fine, I think I did something else wrong, sorry.
