### ISSUE TITLE
d2 --version does not work

### ISSUE THREAD

**Issue by FFengIll** [terrastruct/d2#202]
`d2 --version` print `????`.

**Comment by alixander** [comment]
You must've built from source. The version is not a static variable in source. 

It's read from Github releases at build time: 
https://github.com/terrastruct/d2/blob/5e001ddf5238c734e70ae9bb02066c5414f364eb/ci/release/_install.sh#L468

And then injected:
https://github.com/terrastruct/d2/blob/master/ci/release/_build.sh#L16

**Comment by gavin-ts** [comment]
1. `go install oss.terrastruct.com/d2/cmd/d2@latest`
2. `d2 -v` outputs `????`

**Comment by nhooyr** [comment]
To clarify, this is expected behaviour. I'll change it to instead be `HEAD` so it's more clear. See #288

**Comment by nhooyr** [comment]
Discussed with @gavin-ts and we decided we can fix this by having the release script update the version in `lib/version`.

**Comment by nhooyr** [comment]
For now we'll manually update. https://github.com/terrastruct/ci/issues/16 tracks automating this.

Thanks for reporting @FFengIll and for @gavin-ts for bring attention.

**Comment by gavin-ts** [comment]
tested with `@HEAD`

```
% rm $(which d2)                                 
% go install oss.terrastruct.com/d2/cmd/d2@HEAD  
go: downloading oss.terrastruct.com/d2 v0.0.14-0.20221130235807-5fa80861ff17
% d2 --version
v0.0.13-HEAD
```
