### ISSUE TITLE
cannot comment out on markdown

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#2026]
```
memo: |md
  # no problem
  <!--
  # foobar
  - foo
    - bar 
  -->
  ---
   ↑
  cause
|
```

API api error occurs.
```
memo:|
<!--
---
-->
|
```
https://play.d2lang.com/?script=yk3Nzbeq4bJR1NXl0gVjO64aLkAAAAD__w%3D%3D&

**Comment by alixander** [comment]
The API error is expected. `--` is not allowed in HTML comments
