### ISSUE TITLE
make connection `style.fill` more aesthetic

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#2030]
what we want

<img width="791" alt="Screenshot 2024-07-29 at 11 29 35 PM" src="https://github.com/user-attachments/assets/2de6a168-c588-4b69-93f4-91cf401033b6">

what it is currently

<img width="1650" alt="Screenshot 2024-07-29 at 11 30 47 PM" src="https://github.com/user-attachments/assets/531fc437-e06a-4c5a-ad2c-0bf2f9ed242e">

- More padding
- Rounded corners

**Comment by bo-ku-ra** [comment]
i want
- connection style and connection label style can be specified separately.
- markdown supports 'border'.


ex.1)
```d2
a->b:foobar{
   #for connection
   style{
   fill:red
   }

   #for connection label
   label.style{
   fill:orange

   double-border: true;
   border-radius: 20;
   stroke-dash: 2;
   stroke-width: 5;
   stroke: red;
   }
}
```

ex.2)
```d2
c->d:|
 foobar
|{ style.fill:orange }
```

ex.3)different outputs, why?
```d2
a -> b

memo: |md
  <div class="container">
    foobar
  </div>
  <style type="text/css">
  .container{
    background-color:orange;
    text-align: center;
    width: 100px;
    border-radius: 9999px;
  }
  </style>
|

y -> z: |md
  <div class="container">
    foobar
  </div>
  <style type="text/css">
  .container{
    background-color:orange;
    text-align: center;
    width: 100px;
    border-radius: 9999px;
  }
  </style>
|

```
https://play.d2lang.com/?script=3I9BTsMwEEX3I_kOo-xNyzIm9V0m9hAsEk81dksD4e7IXnCIbv__T_qP0HqcDRjYeBN3bNHAFNMdw0qlXIYguVLKrIM3gPguMpMamE4x3b2BqdR9Zaz7lS9D5Uc9hVLa9OUf_GncTOFzUbnlaIOsok6U8sJvrWuYpTUt2WHgXFl7_JVi_XD4ej5fHz2YRSOrVYrpVhyO4zj25rfd6T-8gaOp7NZ_P4EK_AUAAP__&

**Comment by i-am-the-slime** [comment]
No padding around connection labels often makes the text connect with the arrows when fill is the same as the background colour. I'd very much appreciate more padding and rounded corners!
