### ISSUE TITLE
Playground throws "D2 Encountered an API error"

### ISSUE THREAD

**Issue by chandra-gopalasamy** [terrastruct/d2#2053]
https://play.d2lang.com/?script=nJpPjiU1DMb3fYpW7RlV4thJEJu5QUtwgQGNxAJOgLg7GqaqXuXNLx27t9W2n-M_Xz47vX1-e0vbz6__vLy-br_-8efXv78k-fTbl9__-pq0bq-__HR-1u9fpW830XyI3gVPdQPBVu6Sl3qJyFaQ7fsga4dsJru1D7KHu6XdRffDwCh6fM3pLlrOaJG3zcBq3smBNDhwBbFDDkzIAZHB7PVZyYXkdqGwt1r9od3J3ZIwvTsKt4RnazkirOvCOdPmqLHrHNQPpaBsCgQNj5aa_2hN13avMktQZmOnHaLK5WDkbs4oWw2zJo6QLYQbFU8u6MVe6HSNT4ceJ6zgTlGrHLVKyRD2QdGHTC7UjjHLjpidtSPkg9qyLS40TGTV0CqhjnLSrODJiv9kky4ONDyC717ppkh7h7OZcTEg8mGNjf1-GRBo4poI0ydljknb-RqmTGTDjkAXGBvGYngXpFMZonDd-aOwPj4HrgpBkDSIr1K7pxFHTjxNAUgXxGmMAzpAvKHIOrhnbLufDmGbYXoR7yq3eiV8fgrW4wjrwJ71IczeEEIy-mDUZ4pmxTi5yPWeiMCtRiG-6pC9XTNAIjt2T8fukY5FRg0h2BA1UuUciExMq1W0q0iIsHhGDsmibPaKmTLiEEgbI2_1X5eGxS7ro92GInTXPyuN5Xv124Tt0cDY0trfy7GMfZyQ5FS029302Gzt7aIahMOb19WLYVjAWe4R4R3bTYk3KMJkRpqD6DDi-mk2NLoS_BqXmTVMRuFklMAOwT82doxZYlkLkIG0r4nZgzCCu3jFavYPxC0QMKFMFKZlvBuYsenmZhpIT9MTTJ52E46CzNJNcd7XdS5ugyfiZHWDFCZusnPI2HCz2uHlAO0B1YM7Z4qI7thkkVAjJNkC4MelpjwVqwTc2HF65O0Ar4twbsL5NZW6ll3RzxrZWZkfJXDQ43LXHkCU4m6NWtYQgal4rPPoYAhpiblyxq434uClRy6ByPiYxL_VKYFtEW_10a5hKvCmz1yQExIeAODs5rRGd0CdUFpaD9hkY4XcM-PObHfQX8VblqdCmS8IdMKixL8HU7cojhaTDQFucBHyevZbNf8IrTjzjwvcc4Rmjswlzk8V7IPg_qnSkt51X15AirO50bIKd4FPF1U73d0Dz3c4OwojNM0VZcLL_Fuo4bXxOINMOr35SRnOVkZ1U3A7wbDEm6IKD66Zq3Fw9vgt4SuKBraRCN32QQhKzV00wruJynbrmgmh3XfnH8uBV77knwLFv8vJkSmF9kl18pagEYbX_Hd66MHVT9uMBw9aTGigeQLXf3ZT-BZ5g_oW239fvv-XxSfYb_yv8_ntLV9_7afBvj3r3ebgqV7Zpr-mH_y1Hvm1x8j3o1I6Xxeazb2s73hZZK7XYnqPNcxUTUOHO5S-3Rgf0KohrWukzdOspXeyLTJXKxG1xxvYqSTX3-qhVCZK1udKadeJ1smBWMu2l_8CAAD__w%3D%3D&layout=elk&theme=0&sketch=0&

Please let me know if I can provide any additional information to debug this problem

**Comment by chandra-gopalasamy** [comment]
FYI, D2 Playground generates the diagram when I removed the last line from the input.

**Comment by bo-ku-ra** [comment]
no error occurred.
timeout? (https://github.com/terrastruct/d2/pull/1392)

**Comment by chandra-gopalasamy** [comment]
Agree.  I could be the timeout error. I am able to construct complicated diagrams using CLI with out any issues.  @bo-ku-ra, thanks for your quick response.
