### ISSUE TITLE
[markdown] can't comment out

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#2054]
```d2
ok: |md
  ok
  ***
  
  comment out
  <!--
  ***
  -->
|
```
https://play.d2lang.com/?script=4uXKz7aqAZG8XFpaWrxcvFzJ-bm5qXklCvmlJbxcNoq6ulAZXV07Xq4aXi5AAAAA__8%3D&

```d2
ng: |md
  ng
  ---
  
  can't comment out
  <!--
  ---
  -->
|
```
https://play.d2lang.com/?script=yku3UqjJTeHlUlDISweRurq6IAqEkxPz1EsUkvNzc1PzShTyS0tAgjaKEAW6MMqOl6uGCxAAAP__&

**Comment by stappersg** [comment]
```text
yeah: |md

  ---

  Double hyphens in markdown comment are tricky, avoid them.
  <!--
  - - -

  - ever more comment -

  - - -

  -->
|
```

https://play.d2lang.com/?script=PIxRCgIxEEP_5xTx3_EAIn55kboNtKzTkbGuFPbwsqKSn0Dy3mAqR6yWBRBAVUWAiz-vN6KMe2F7oDZYijn7q2FyM7aOFESPOs1jj7R4zeiFdhDgtFPdVFvkU7gwYB7809_h99CzrPIOAAD__w%3D%3D&
