### ISSUE TITLE
Imported classes with relative file paths fail

### ISSUE THREAD

**Issue by dzoeteman** [terrastruct/d2#2059]
#1924 (0.6.6) changed relative file paths to be relative to the file instead of working directory of CLI execution.
While I support this change, there is one issue introduced, where relative paths in classes do not work if they're imported.

This example I hope explains the use case. Assume you have a directory structure as such:
```
my-diagrams/
├─ diagrams/
│  ├─ subset/
│  │  ├─ test.d2
│  ├─ icons/
│  │  ├─ test.svg
│  ├─ models.d2
```

With `models.d2`:
```
classes: {
  myclass: {
    shape: image
    icon: ./diagrams/icons/test.svg
    width: 100
    height: 100
  }
}
```

And `test.d2`:
```
direction: right

...@../models

myobj {
  class: myclass
}
```

Before, I could make this work by executing the following, with the working directory being `my-diagrams`:
`d2 diagrams/subset/test.d2 output.svg`

However, now I get the following error if I do that:
```
err: failed to bundle ./diagrams/icons/test.svg: open /Users/myuser/workspace/my-diagrams/diagrams/subset/diagrams/icons/test.svg: no such file or directory
err: failed to compile diagrams/subset/test.d2: failed to bundle local images: [./diagrams/icons/test.svg]
```

Am I missing a way where this could still work, or is this something that might require a fix?

**Comment by alixander** [comment]
Was indeed a bug that's going to be fixed in the next release. Thank you for the report @dzoeteman
