### ISSUE TITLE
zed editor d2 extention support

### ISSUE THREAD

**Issue by yodatak** [terrastruct/d2#2060]
we have a issue here it could be awsome to support zed-editor we sould have tree siter and languaer server to support it 

https://github.com/zed-industries/extensions/issues/1084

**Comment by alixander** [comment]
The editor isn't mainstream enough for us to dedicate bandwidth to write an official extension ourselves. However, if there's generally applicable things that an extension author wants of us, they're welcome to create issues for those and we can help.
