### ISSUE TITLE
Theme flag does not work for GIF exports

### ISSUE THREAD

**Issue by atyner** [terrastruct/d2#2067]
Similar to https://github.com/terrastruct/d2/issues/1889, the `-t` or `--theme` flag does not change the theme for GIF exports. 

When I run 
```bash
d2 --theme 103 file.d2 out.gif --animate-interval 1200
```
the default theme is used. But the theme works for PNG or SVG exports.

**Comment by alixander** [comment]
thank you for reporting @atyner, will be fixed in next release
