### ISSUE TITLE
Scale flag (for disabling fit-to-screen) does not apply to animated SVG exports

### ISSUE THREAD

**Issue by atyner** [terrastruct/d2#2068]
When I run this
```bash
d2 file.d2 out.svg --scale 1 --animate-interval 1200
```
the resulting animated SVG does not respect the special `1` value for scale. The SVG always expands to fill the browser window. 

However, for a normal SVG export (without `--animate-interval`), even one with multiple boards, the resulting SVG file(s) do respect the `1` scale value and use a fixed size.

**Comment by alixander** [comment]
thank you for reporting @atyner, will be fixed in next release
