### ISSUE TITLE
Online playground

### ISSUE THREAD

**Issue by KevinZhang19870314** [terrastruct/d2#207]
Have a plan to build a online playground (in browser)? I think it will make more people happy to have a try this, but install it locally.

**Comment by alixander** [comment]
yes, this is in the works! thanks for the feedback

**Comment by BadgerHobbs** [comment]
I was looking for a way to do this so I put together a basic docker webapp with server side rendering and an API. Not perfect as no syntax highlighting, but has done the job for me for now.

https://github.com/BadgerHobbs/D2-Docker-Playground

**Comment by YashBhalodi** [comment]
Hi @KevinZhang19870314, I was also [hoping](https://github.com/terrastruct/d2/issues/153#issuecomment-1327113184) for the web playground. I just managed to host a simple API that serves up the svg from the D2 script. And I was able to build a very basic playground on top of that.

You can check it out here:- https://playground-d2-lang.netlify.app/

If you have any feedback, or you wish to collaborate on the project, feel free to raise an issue here https://github.com/YashBhalodi/d2-lang-playground.

**Comment by gavin-ts** [comment]
https://play.d2lang.com/ from #454
