### ISSUE TITLE
Partial imports do no work

### ISSUE THREAD

**Issue by BaronBonet** [terrastruct/d2#2080]
First and foremost thanks to everyone working on this project! D2 has been a game changer in my documentation workflow and I've loved working with it.

## Problem

In the docs there is a section on [Partial imports](https://d2lang.com/tour/imports/#partial-imports).

I've tried copying this example exactly i.e. in the same directory make 2 files:

>`donut-flowchart.d2`
>
>```d2
>...@imports-targeted-people.management
>joe -> donuts: loves
>jan -> donuts: brings
>```
>
>`people.d2`
>
>```d2
>management: {
>  joe: {
>    shape: person
>    label: Joe Donutlover
>  }
>  jan: {
>    shape: person
>    label: Jan Donutbaker
>  }
>}
># Notice how these do not appear in the rendered diagram
>employees: {
>  toby: {
>    shape: person
>    label: Toby Simonton
>  }
>}
>```

Then I use the cli command `d2 donut-flowchart.d2` and get the following error:

>```shell
>err: failed to compile donut-flowchart.d2: /<path>/donut-flowchart.d2:1:1: failed to import "<path>/imports-targeted-people.d2": open /<path>/imports-targeted-people.d2: no such file or directory
>make: *** [dev] Error 1
>```

If I modify the `donut-flowchart.svg` file to remove the targeted imports i.e.

>```d2
>...@people.management
>joe -> donuts: loves
>jan -> donuts: brings
>```

Then everything renders as expected. However, I'm hoping the partial imports functionally will work since it makes larger d2 projects more manageable.

<img width="762" alt="image" src="https://github.com/user-attachments/assets/0cd5eb73-7e04-46c0-b34c-86f196c3264f">

I am using d2 version 0.6.6 on a Mac M2 Pro.

**Comment by BaronBonet** [comment]
As far as I can tell [Model-view](https://d2lang.com/tour/model-view/) also doesn't work.

I signed up for [D2 Studio and tried it there](https://app.terrastruct.com/diagrams/706961023). I'm getting the same error as above.

<img width="408" alt="image" src="https://github.com/user-attachments/assets/a7de9515-efb7-4402-9838-73ccaf044aa2">

**Comment by alixander** [comment]
@BaronBonet Oops this is just a documentation mistake from a refactor. Thank you for this catch, it's been fixed.
