### ISSUE TITLE
d2sequence error

### ISSUE THREAD

**Issue by anuwat-th** [terrastruct/d2#2081]
https://play.d2lang.com/?script=jJLNbuJAEITvfoqSL7tIgMQerRUc9rB7WGl_OCYR6thtz4jxjDPTNkER7x4ZbIL5SXJsq_qrqmn_doW22GhR-OlcYTjBSwQERRUnCPxUs015lWkqPJUROhX-UC1qKjN8n-DA-EsFT2WW4H-7FKRXUpq62goyEppGVwiT-SUhVM4GvokY6K8A_tXst4i5JG3iMeJc-yCwVHI7GeqHe5t7V_Y2vrO96rBk37AfFNxrvsaec89BrcSt2cbjzvWm56jFH2ln6B-K03UfHDqAn3UQbQu4HNbJIgLIyOFIQHx3InmI-8_v8D2TMCxv0OY2b7m7xdPe39rjDnp3ZznvPPrAdckCbSkV3TCoIW3o0TBy51F5brSrw6fiTOb45Urezwk2igSZzrB1NRQ1B6CpbaoW-_Vd90ZsAl8-zvC3SSCK5EtAxT44S-ZI2EW76DUAAP__&theme=1&sketch=0&layout=dagre&

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?script=pJJPb9RADMXv8yme0gNU2mTVHiPUCnGAAxJ_egRUuYmTGXUyEzzOLhXqd0fZTdrd7hYQ5BSP7Pfzs_0-ti5g7dTibYyt5xI_DZAs9Vwi8feBQ8XXtaNWqDMGOMn_8RtrYVX7VC6X9bmn0BZV7JYaB1nOpHwipZMoNYsL7absdaVREtbOe1DfMwkaiR08N5przMW1VkEJtMDNAtUCdVEUBpMpfKBBrQG2dj9SywZ4Fzue_69YViz_Ze8JrdAzvMp3iIWelfg8-kw6Z1JVxSEoalIqjinkF4cKqY8h8bMSe_lHBD4NLHfIuCPnswWyxklSBOp4jDzNwdewGfGEkQl7lLCd3p7BTc7LTLgRTvZa4y2HbDFRn2WemoddHEq_sVzdzo3DJfAPl9SFFrFBiHppAPK6vWAg-7KT8i2bn3-jL0zKCLzG2Ld_7Hsq3PV9Pi53z_e0lqeeT_9AvWKFC1SpWzFoRc7TjWc0UdALr1wc0l-1k188HnSJtSVF7WrcxQGWVltBP4TKXm7K76cZsU98OJz9symhlvRFQs-SYiD_oHBv7s2vAAAA__8%3D&theme=1&sketch=0&layout=dagre&

**Comment by bo-ku-ra** [comment]
i don't know, why not accept both d2-sources?

**Comment by alixander** [comment]
Regardless, there should be better error messages so this is a bug

**Comment by alixander** [comment]
dupe https://github.com/terrastruct/d2/issues/2092
