### ISSUE TITLE
Bad SVG generation with markdown newlines

### ISSUE THREAD

**Issue by mrtryhard** [terrastruct/d2#209]
## Summary
**OS:** Ubuntu 22.04 
**Browser:** Firefox 107.0
**D2 cli version:** v0.0.13
**Error:** 
When compiling a node with markdown inside, it will create an invalid SVG file. See below. 
`XML Parsing Error: mismatched tag. Expected: </br>.` 
![image](https://user-images.githubusercontent.com/5321539/204010998-4649d79f-4652-4969-bbcd-7e800b4b983c.png)

## Expected result
1. Either a compiler error if new lines are not supported
2. Or the following image:
![image](https://user-images.githubusercontent.com/5321539/204012063-6bb1409b-1a4b-4e92-8e92-27f01ee1647a.png)

## Note
It requires 2 things to produce a working SVG: 
1. Replace `<br>` with `<br />` 
2. The `height` on the `foreignObject` should be adjusted (from 24 to 48 in my case) 

## Code to reproduce

`d2 file.d2 file.svg`

```
mainframe: Mainframe Banking System {
  explanation: |md 
  Stores all of the core banking information  
  about customers, accounts, transactions, etc.
  |
  style: {
    stroke: "#aaaaaa"
  }
} 
```

**Comment by alixander** [comment]
thank you for the 💯 bug report
