### ISSUE TITLE
Tooltips are not working

### ISSUE THREAD

**Issue by BaronBonet** [terrastruct/d2#2091]
First off thanks to everyone who is working on this project. D2 is awesome!

I think tooltips are broken.

In the below example that can be found [here](qrRSqC7Jz88pySywUihJLS6p5apQ0LVTqOQCBAAA__8) on play.d2lang.

```d2
y: {tooltip: test}
x -> y
```

I do not see the tooltip when I hover over y.

The [tooltip section of the docs](https://d2lang.com/tour/interactive/#tooltips) is also not showing the tooltop

**Comment by alixander** [comment]
@BaronBonet Thank you!

If you hover over the shapes here (leave your mouse for a few seconds), does a tooltip show up? 
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title

If not, you likely have some nonstandard accessibility settings in your browser/OS.

**Comment by BaronBonet** [comment]
@alixander I'm just crazy impatient sorry about this! The tooltip does show up after I wait with my mouse still for about 2 seconds.

I'm surprised how long it takes. I was expecting the implementation to act more like the tooltips I'm familiar with e.g. [this example on W3Schools](https://www.w3schools.com/css/css_tooltip.asp) which shows the tooltip instantly.

I assume there is a good reason they are not implemented this way?

**Comment by alixander** [comment]
Yeah it's not ideal but it's the most universal way with the least amount of intrusion from the standpoint of an external library adding extra DOM nodes.
