### ISSUE TITLE
d2sequence: slightly increase padding between long labels and end of messages

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#2095]
this looks a little squished

<img width="383" alt="Screenshot 2024-09-14 at 5 39 56 PM" src="https://github.com/user-attachments/assets/2e9ef49a-096c-46d4-880d-87f7b58fb36e">

**Comment by bo-ku-ra** [comment]
this is off topic.

i find it difficult to write the big d2 sequence diagrams.
why do i have to define the span names in the sequence diagram?
the span names don't appear in svg files. (mermaid is automatically uses + and -)

**Comment by alixander** [comment]
@bo-ku-ra I think it contributes logically.

Spans mean something logically, even if the labels don't appear. E.g. some process.

**Comment by bo-ku-ra** [comment]
i am annoyed by the many tasks of giving appropriate names that are not displayed.

**Comment by alixander** [comment]
I think Mermaid's is much less readable. I understand the annoyance at having to come up with names, but I will defer to our decision decisions: https://d2lang.com/tour/design/#readability--prototyping-speed

**Comment by bo-ku-ra** [comment]
@alixander thank you for your explanation.

i understand readable is a must.
but i feel the difficulty of writeable(easy to write).
the cause is span name is not displayed.
(the span name will be collision with another names.)
if d2 has span name display option, i am not annoyed. (e.g. tip help?)

``` mermaid
gitGraph TB:

    commit id:"tip help"
    commit id:" "
```

**Comment by alixander** [comment]
If the span name is displayed by default, it forces people to give them readable labels, which is different from readable variable names.

**Comment by bo-ku-ra** [comment]
ok, never mind...
