### ISSUE TITLE
content of NOTE is lost in sequence_diagram.

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#2102]
i can read the NOTE.
```d2
shape: sequence_diagram;

a
b

b{
NOTE:'foobar'
}
```

i can not read the NOTE.
```d2
shape: sequence_diagram;

a
b

b{
NOTE:'foobar'
}
a -> b.NOTE
```

expected
![image](https://github.com/user-attachments/assets/379ae050-6b3e-4a4c-b679-d7fed167f6ff)

**Comment by bo-ku-ra** [comment]
i believe this is due to the way SPAN is described
c.f. https://github.com/terrastruct/d2/issues/2095#issuecomment-2351236792

**Comment by alixander** [comment]
Notes are children with no connections. That's the rules. If you add a connection to it, it becomes a span.
