### ISSUE TITLE
Incorrect Linking with multiple d2 files

### ISSUE THREAD

**Issue by rutvora** [terrastruct/d2#2104]
**main.d2**
```
...@test
```

**test.d2**
```
elem: elem {
  link: https://google.com
}
```
I am running this as `d2 -w -p 8080 main.d2`

As you see in the bottom left of this image, the link is (incorrect) `localhost:8080/test1.svg` instead of (correct) `https://google.com` 
EDIT: Note that my mouse pointer is hovering over `elem` (which is not shown in the screenshot)
![image](https://github.com/user-attachments/assets/1c97e0d6-1522-456b-8314-cb655220d531)

**Comment by alixander** [comment]
ty @rutvora
