### ISSUE TITLE
Additional Duplicate element in the diagram

### ISSUE THREAD

**Issue by rutvora** [terrastruct/d2#2110]
**Note: This is an issue with the current master branch and not with the v0.6.6 release**

**main.d2**
```
...@second
```
**second.d2**
```
second: {
  elem: {
    ...@third
  }
}
```
**third.d2**
```
third: {
  elem
}
```

| master | v0.6.6 |
|---------|-------|
| ![image](https://github.com/user-attachments/assets/9d1452ac-9b08-40b0-a803-ea8e9c650100) | ![image](https://github.com/user-attachments/assets/4f7500e9-054c-4725-8cd5-5c5e94f0e12c) |

The extra `third` element in master is what I'm referring to.

Btw, I built the master branch by running the following commands (let me know if I did something wrong)
```bash
./make.sh
go build .
```
I then used the executable generated by the `go build .` to generate the images

**Comment by alixander** [comment]
@rutvora Very much appreciate this. Surprising lack of test case, we're lucky you caught it before the new release was cut 🙏
