### ISSUE TITLE
Feature idea: Node-local theme application

### ISSUE THREAD

**Issue by smheidrich** [terrastruct/d2#2124]
It would be nice if there was a way to specify that a [theme](https://d2lang.com/tour/themes) should only apply to a specific node (shape/container in D2 terminology, but I'll use "node" for the remainder of this issue) and its children, so that different nodes can have different themes applied.

Ideally, this should be possible for both pre-defined themes, which I realize might not always look great because they weren't designed with this usage in mind, but more importantly for [custom themes](https://d2lang.com/tour/themes#customizing-themes). In the latter case, there would have to be a way to either specify multiple custom themes for a single diagram globally that can then be referenced from the node, or to define a custom theme that is itself local to a node.

Another idea might be to make themes applicable to [classes](https://d2lang.com/tour/classes), which could then in turn be applied to nodes for the same effect. Or both of these ideas combined by making `theme` a `style` option, configurable in both classes and nodes.

This would enable users to more easily create diagrams with top-level components clearly visually differentiated from each other by color but with consistent internal coloring, e.g.:

<img src="https://github.com/user-attachments/assets/18cac26d-80df-4848-bfee-95b6d911e09e" height="600px" />

Which, AFAICT, is currently only possible by manually performing the nesting depth → theme color transformation that D2 does automatically when using themes (of course classes help here, but you still have to repeat the class names everywhere & change them whenever the nesting depth of something changes):

<details>
<summary>Code for the diagram above</summary>

```d2
aws: AWS {
  class: aws1

  eventbridge: EventBridge\nScheduler {class: aws2}

  lambda: Lambda {
    class: aws2
    app: Our app {class: aws3}
  }

  eventbridge -> lambda: Triggers\nperiodically {class: awsconn}
}

gitlab: GitLab {
  class: gitlab1

  repo: Repo {
    class: gitlab2

    app-code: Application code {class: gitlab3}

    diagrams: Diagrams {class: gitlab3}

    cicd: CI/CD config {class: gitlab3}
  }

  cicd: CI/CD Pipeline {class: gitlab2}

  repo.cicd -> cicd: Defines {class: gitlabconn}
  cicd -> repo.app-code: Checks out {class: gitlabconn}
}

d2lang: The D2 Language {
  node-local-themes: Node-local themes
}

gitlab.cicd -> aws.lambda: Deploys to {class: inter}
gitlab.repo.diagrams -> d2lang: Written in {class: inter}

aws.lambda.app -> d2lang.node-local-themes: "Adds another +1 comment to\nthe feature request about" {class: inter}

classes: {
  awsconn: {
    style: {
      stroke: "#20273E"
    }
  }
  aws1: {
    style: {
      stroke: "#20273E"
      fill: "#FFDD47"
    }
  }
  aws2: {
    style: {
      stroke: "#20273E"
      fill: "#FFE570"
    }
  }
  aws3: {
    style: {
      stroke: "#FFD20A"
    }
  }

  gitlabconn: {
    style: {
      stroke: "#E53B0C"
    }
  }
  gitlab1: {
    style: {
      stroke: "#E53B0C"
      fill: "#FFB35C"
    }
  }
  gitlab2: {
    style: {
      stroke: "#E53B0C"
      fill: "#FFC685"
    }
  }
  gitlab3: {
    style: {
      stroke: "#E53B0C"
    }
  }
  inter: {
    style: {
      stroke: black
    }
  }
}
```

</details>

## Related issues

- https://github.com/terrastruct/d2/issues/1165
  - I think this would solve the same issue but in a different way?
- https://github.com/terrastruct/d2/issues/887
  - From the title I thought this might be something that would go great with this feature (basically allow the user to specify only a single starting color for the node fill color and have the rest generated by automatically lightening/darkening) but I don't understand it enough to say for sure.

**Comment by alixander** [comment]
That's a good idea. 

Maybe the `d2-config` var can be re-defined.

```d2
x -> y

x: {
  vars: {
    d2-config: {
      theme-id: 2
    }
  }
}

y: {
  vars: {
    d2-config: {
      theme-id: 102
    }
  }
}
```

**Comment by smheidrich** [comment]
Sorry, I didn't realize [globs](https://d2lang.com/tour/globs/) were already powerful enough to solve the pain points I mentioned in the issue - all classes attached to containers and their children in the diagram above can be removed by simply adding this snippet instead:

```d2
aws {class: aws1}
aws.* {class: aws2}
aws.*.* {class: aws3}
(aws.** -> aws.**)[*] {class: awsconn}

gitlab {class: gitlab1}
gitlab.* {class: gitlab2}
gitlab.*.* {class: gitlab3}
(gitlab.** -> gitlab.**)[*] {class: gitlabconn}
```

I don't think sparing users from writing these few lines _once_ in their diagram is justification enough for this feature, so I don't think it should be implemented anymore.

It _would_ be nice if there was an example demonstrating this workaround somewhere in the docs, I'm just not sure where. Neither the [Themes](https://d2lang.com/tour/themes/) page nor the [Globs](https://d2lang.com/tour/globs) page seem like a good fit because they're about the actual features, not ways of using a feature to achieve a desired outcome. This is more like something you'd find in a "Cookbook" section.

Anyway, I'll close this, just reopen if you disagree.

**Comment by alixander** [comment]
Hah I didn't realize either. Nice
