### ISSUE TITLE
API Call Issue: Error Encountered While Using Playground

### ISSUE THREAD

**Issue by resatarikan** [terrastruct/d2#2127]
https://play.d2lang.com/?script=xJZRa9swEIDf8ysOvytpmnRleRisKR2DDtZl0Mdwli-xqC25JzkhjP73ISlu7DQr1GXbS-tT7u7T3Ul3UnrFaB3X0tVMM_g1ACgMZssUC9SSeAbJrcEMrvZyElQAlDR6BknuXGVno5EX7dARN96G0pSj4H10Nv4oNLmt4Yeh3ayTQXCwpXRpiTfEdgbJPaWwiFJDeBtjMhbRW0REB1hVLcbnqiqURKeMfsl6F-3ZR4lr0s7soTNIvsWFPa-Ne2MKp8LmpqqUXguJ7NpRtsFYVS1qK-Iu-o3RToU0GR0zn07ws7SFv0aHKVp6D_v8QmR7N3_mPx0qkKVLWdTWhew3G4B5XOqf_1e2UbEqkXcx9O9R-HehAzCFIkf-jyj8l9RLlDktC9yF3M9R5kqv4dbL_RN_NhXB7_EOmDJlQ8CZsu863BciNYV79XBTGfaQ-bPdfP9VZvMV__u_Ic-yMHUWmouS5KOf-4XQXPxCz94cvB72YiczSBYTuKrlA7me3XgikGWuNq26xVgKLNMMfTe-X8BtEPohpmMRfR0T7KPPzOJuAXc11dTP-_hCkN5QYaqjCEIdSqOVM6z02p-IZwF-GlP0qsLkTKTIQuad1l6xKcnlVNvQWRqhZ0k-RPeiUPpFVdaMK9S-LF_iV0_G5Z6BTC_qEo7ZFp3Mm4N774V-pPNLQbtTpek8XkB8OnpnXCvrWKW1I3CMq5WS3r6l4026z4Ybw1vkDJgea7LOeoOWxrA78719dxiH0Q80N2VJLKnjp6XZNuxO0StQ2hGjDHO8S_dWnZF3VxPvwPftE5rdDn1DTuawYlPGH04ZdBrOMLYGZ5hgpQoKIRypxDvpbeM9_Ko35oFgZRhoQ3of9uHK-HQXxeEaeS3eOT86ksHT4HcAAAD__w%3D%3D&layout=elk&

**Comment by alixander** [comment]
a lot of the images didn't exist. i've updated the playground to not error and just show the missing images, thank you.
