### ISSUE TITLE
accepting shape names are the same as mermaid.

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#2135]
mermaid became like d2 description.

> Expanded Node Shapes in Mermaid Flowcharts (v11.3.0+) 
> https://mermaid.js.org/syntax/flowchart.html#expanded-node-shapes-in-mermaid-flowcharts-v11-3-0

if the shape names are the same as mermaid, mermaid users can simply use d2.

ex.
```d2
d2{shape: document}
mermaid{shape:doc} #alias

d2 <-> mermaid
```
![image](https://github.com/user-attachments/assets/ce72ee50-45e3-41bc-ba96-06279f86efd9)

**Comment by alixander** [comment]
Thanks for calling this out. D2 has no interest in conforming to Mermaid, though Mermaid is free to become more D2-like =)

**Comment by bo-ku-ra** [comment]
i am interested in new shapes.
especialy 'Curly Brace'.

**Comment by bo-ku-ra** [comment]
the content is out of date.
https://text-to-diagram.com/?b=mermaid&example=shapes

**Comment by alixander** [comment]
It's not out of date, that's still their most popular and supported syntax.
