### ISSUE TITLE
Gif diagram loses dark --theme 200

### ISSUE THREAD

**Issue by HariSekhon** [terrastruct/d2#2138]
When generating a diagram as a gif to try to get it animated in a format that could upload to LinkedIn which doesn't accept SVG, I've found that the dark theme 200 gets lost and reverts to a white background

Reproduce:

```shell
git clone https://github.com/HariSekhon/Diagrams-as-Code diagrams

cd diagrams

d2 karl_marx_test_ideas_in_production.d2 karl_marx_test_ideas_in_production.svg --theme 200 --sketch

d2 karl_marx_test_ideas_in_production.d2 karl_marx_test_ideas_in_production.gif --theme 200 --sketch --animate-interval 500
```

Compare `karl_marx_test_ideas_in_production.svg` VS `karl_marx_test_ideas_in_production.gif`.

Open both images quickly on Mac:

```shell
open karl_marx_test_ideas_in_production.svg

open karl_marx_test_ideas_in_production.gif
```

ps. `--animate-interval` also doesn't work as per #1666

**Comment by alixander** [comment]
I can't reproduce. My d2 version is on master but it's not diverged much from the latest release (0.6.7). What version are you on?

<img width="889" alt="Screenshot 2024-10-05 at 10 31 59 AM" src="https://github.com/user-attachments/assets/34c998ff-4c56-4780-8c03-d08cb455820b">

<img width="1098" alt="Screenshot 2024-10-05 at 10 31 53 AM" src="https://github.com/user-attachments/assets/6ea8d29e-7385-4967-8118-098af812b5f3">

<img width="1100" alt="Screenshot 2024-10-05 at 10 31 46 AM" src="https://github.com/user-attachments/assets/769739aa-fe18-4e14-80f4-bbf0e7c3334d">

**Comment by HariSekhon** [comment]
I was using `0.6.5`.

I've just upgraded to `0.6.7` and that seems to have fixed it.

I should have checked my version and latest before raising this.

Thanks.

**Comment by alixander** [comment]
No worries, appreciate your bug reports!
