### ISSUE TITLE
Exported SVG's do not render correctly in LaTeX and Inkscape

### ISSUE THREAD

**Issue by Nathan-Rozendaal** [terrastruct/d2#2142]
### The problem
Opening SVG's exported by D2 in LaTeX or Inkscape results in a black box where the diagram should be

### How to reproduce
Create a simple D2 diagram:
"x->y" already does the trick

Open the svg in Inkscape

### Expected result
![image](https://github.com/user-attachments/assets/bfa1ce4d-2215-4752-bc3b-942be31ec733)

### Actual result
![image](https://github.com/user-attachments/assets/ff69e9ab-2915-4efe-9b1b-68799c05c239)

Tested in d2 v0.6.7

**Comment by alixander** [comment]
Ah so this is due to contexts where CSS doesn't get executed. D2 should inline the styles in addition to using css classes

**Comment by alixander** [comment]
actually if we do it by default, it will override the auto light/dark switching.

Maybe we do it only if --dark-theme is not supplied by default, and just caveat that passing in theme and dark-theme together will have this behavior
