### ISSUE TITLE
Additional space on grid layout

### ISSUE THREAD

**Issue by chrisirhc** [terrastruct/d2#2143]
Reproduction:
```
grid-columns: 1

a: "" {
  grid-gap: 0
  grid-columns: 2
  A
  B
}
b: "" {
  grid-gap: 0
  grid-columns: 2
  XYZ
  D
}
```

https://play.d2lang.com/?script=Si_KTNFNzs8pzc0rtlIw5OJKtFJQUlKo5lJQAEulJxZYKRjAeHCFRlwKCo5cCgpOXLVcSUTriIiM4lJQcOGq5QIEAAD__w%3D%3D&layout=dagre&

Expected two blocks containing two items each. But looks like the first one contains more items.

<img width="345" alt="image" src="https://github.com/user-attachments/assets/ef11f54c-3235-40f1-bc2b-89850b355b2c">

**Comment by alixander** [comment]
There's a section on the docs for this =)

https://d2lang.com/tour/grid-diagrams/#why-is-there-extra-padding-in-one-cell

**Comment by chrisirhc** [comment]
Hm now I understand why the extra padding exists, but it looks like another box. Perhaps that extra padding should be redistributed between A and B instead? 
Wonder if it'll take another pass in the d2grid/layout.
