### ISSUE TITLE
test absolute imports on windows

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#2149]
https://github.com/terrastruct/d2/issues/1397#issuecomment-2406544364

**Comment by bo-ku-ra** [comment]
please add this test pattern

```
C:\
└─d2
　│ bokura-config.d2
　│
　└─あ     <---( cp932 : windows japanese edition)
　　　 a.d2 <---( UTF-8/UTF-16 : d2 source file )
```

**Comment by bo-ku-ra** [comment]
success: successfully compiled
```
...@../bokura-config
```


unexpected text after import
```
...@file:///C:/d2/bokura-config
```

**Comment by bo-ku-ra** [comment]
v0.6.8 not yet?

**Comment by alixander** [comment]
@bo-ku-ra can you try

```d2
...@"C:/d2/bokura-config.d2"
```

**Comment by bo-ku-ra** [comment]
NG only below.
```d2
C:\
└─d2
　│
　└─あ
　　│bokura-config.d2
　　│
　　└foo
　　　a.d2
```
err: failed to compile a.d2: c:\d2\あ\foo\a.d2:1:1: failed to import "C:/d2/��/bokura-config.d2": open C:/d2/��/bokura-config.d2: The system cannot find the path specified.

c:\d2\あ\foo\a.d2 <- 'あ'
"C:/d2/��/bokura-config.d2": <- text garbling

**Comment by bo-ku-ra** [comment]
i've confirmed that it's fine on the windows japanese edition.

**Comment by alixander** [comment]
will add to the docs to be less confusing: https://github.com/terrastruct/d2-docs/issues/243
