### ISSUE TITLE
is it possible to build this topology in D2?

### ISSUE THREAD

**Issue by younes-io** [terrastruct/d2#2171]
I want to build the topology below using D2, but I don't know if it's possible. I checked the customization and Layout sections of the docs but found nothing related to this.

![image](https://github.com/user-attachments/assets/07bbbd5c-23f9-4942-ae8f-932160d100f4)

**Comment by bo-ku-ra** [comment]
e.g.

https://play.d2lang.com/?script=tJHNTsQgFIX3PAVp4maSMtDGDex9AOPSDQFsyTBAuLdWbfrupj8TTeNK4-4eyHf4ANIVb-uSRpC0VVsyKQzXCJKKfaHTWVKuCLF8-g6II9AeAMsFCzpjysTy5mtsb-NMiBV_6nyT1VO6uPgcH33sqgl6nZ00vpjgFOB7cAx6bdMoKZbBKTp6i70UDd93X1LEGvyHk7Rt1Hy0a_7hxidZVdN-ug9hMdMRsi4u4s0ZS7q4epOlfPE6sd-BZEX5aTfYOtZX8lfdOUW9SVH2iBnk-bwEYOhK0YBlMMhMup7Rmf6uedgaGLx286GU1jW1gq0_Mv1kcq9m8hkAAP__&

**Comment by younes-io** [comment]
Oh awesome, thank you @bo-ku-ra 
This technique you've used isn't mentioned in the docs, is it?

**Comment by bo-ku-ra** [comment]
i think it's the same as the html table tag.

example of how 'grid' can be used for a layout.
https://d2lang.com/tour/grid-diagrams/#like-this-map-of-japan

MARIO is lost and running :-p
https://github.com/terrastruct/d2/issues/1218#issuecomment-1512628007

**Comment by younes-io** [comment]
That's awesome! Thank you
