### ISSUE TITLE
[sequence_diagram] NOTE overlaps.

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#2194]
https://play.d2lang.com/?script=hI5BCgIxDEX3gX8HL1APMEJPMiA_Ne24sNEOsxLvLra4LgQCyX-Pv2982nLa7XVYTXa93VkaHxcIIQpJEEh2f0MYIpfsvlZlW2t2VzYIz5sX62-FKNssOuIaYurmCZGPQkjq8nGdtPkBA9IQCfn0-e9vAAAA__8%3D&
```d2
shape: sequence_diagram
a
b
c

foo: {
  a -> a: foo\nbar\nfoobar
  a.hoge
  a -> b
  bar: {
    a -> a: foo\nbar\nfoobar
    a.hogehoge
    b -> c
    foobar: {
      a -> a: foo\nbar\nfoobar
      a.fuga
      c -> b
      foobarfoo: {
        a -> a: foo\nbar\nfoobar
        a.fugafuga
        b -> a
      }
    }
  }
}
```
![image](https://github.com/user-attachments/assets/27c38dba-4d04-4d1d-9c3e-f174f3be4e61)

**Comment by jayjang0209** [comment]
Same issue
![image](https://github.com/user-attachments/assets/6818db10-22f3-46a1-9312-c527e902d1ad)
```
shape: sequence_diagram
alice -> bob
alice -> alice: "Self-messages"
alice -> alice: "Self-messages"
alice -> alice: "Self-messages"
alice -> alice: "Self-messages"

bob."In the eyes of my dog, I'm a man."
```
