### ISSUE TITLE
How can I combine styles,... with a markdown label

### ISSUE THREAD

**Issue by kirchsth** [terrastruct/d2#2206]
I tried to add a markdown based text to a styled ex. person, like below:

![image](https://github.com/user-attachments/assets/5c0bb065-5b5f-4847-b574-19f10579b4f1)

but if I combine it with styles I lost ex. stroke color, shape or it is not a rendered markdown label like below:   

https://play.d2lang.com/?script=ZI_NUsMgFIX39ynOxJ0zJMJOdmXyAL4CRmozJSEDaO2YvrsDpDHGFfdwf75zJuODGw8S1UuucKiIlk8u8U2A1a_GbgZ4Rbd1RtT7tlgPKIl5eCPgAUtTEcCgGF9eQfM6_JdWFrerPGsGxdmmFATMv37U6mdPFgUp7myxhT8Wdt-5UeIU4xRk0yQV6mi81yH6jy7WnRuafjx63TzxZzaaeHH-XIfP90wKJz0ZiWi-IuGuyv2k49WagknCu7ORGLR3uQsce2slrsZadyHgljK1xfy_MG2O0JYkIuX4CQAA__8%3D&layout=dagre&

![image](https://github.com/user-attachments/assets/44c25230-1c4b-4bf3-a644-9da7fdc36a2a)

How can I combine it?

Thank you and best regards
Helmut

**Comment by alixander** [comment]
As a grid

https://play.d2lang.com/?script=TI5BboMwEEX3PsVXugZCdp11DtArWDABK8a2xpPSqOHuFa5Ru_v_Wf7zEkuOgXA64dsAWZ-eqcS9SLxzs7pRZ8K5sJvznqBiQ05WOKgBNgNM4sZmiP6xhEzoDzLZ9Pvz707dnm1iqrgQN-zvs2rK1HV7y62yiM0qj0HbIS6dCzex3bl_bwLrGuXe5s-puv4TP9QJi5VY9w_3J3sf14K2Kq_8pYTXMhb6ho9ihWupDa59DZeLAV5mMz8BAAD__w%3D%3D&layout=dagre&

**Comment by kirchsth** [comment]
thank you for the fast answer.
BR Helmut

**Comment by bo-ku-ra** [comment]
there is a width problem.
https://play.d2lang.com/?script=lI5BboMwEEX3PsVXugZCd_U6B-gVLJiAFWNbM5PSqOHuFa6Rqu7q1f9PnpmXiSVFi9MJXwYQfQSyJe6F042a1Y86W5wLu_oQLJRdlOyYohpgM8DEfmyGFO5LFIv-IJPLP5N_7gAyu0y28kL8sH-YVbPYrtubtErMTpTvg7ZDWjofr-y6c__WRNI18a2Vj6nK_jI_3C0Wx6nuP-QfFEJaC9qqvdKnWjyXsdAXvBcrXEptcOlreP3nM8DTbOY7AAD__w%3D%3D&layout=dagre&
