### ISSUE TITLE
The grid cannot be rendered if there is duplicate data

### ISSUE THREAD

**Issue by xbpk3t** [terrastruct/d2#2215]
For reference [Grid Diagrams | D2 Documentation](https://d2lang.com/tour/grid-diagrams#or-a-table-of-data) , I want to use terrastruct/d2 to render a table, but I encounter a problem. If there is duplicate data, it will be automatically removed.

[D2 Playground](https://play.d2lang.com/?script=bIzBSvQwFEb39yk-8q9bkv7OoNmJCG5GBZ8gba6dSJoMNym1yLy7aF2N7u65h_P9w8uJh_Aa2KNk1KOryP0bD7XACWORUCsnhATJS-PzFJJLFVk8C40SfCN5KRbdBkOO85SKxdXGoztZaKIhulK4WHwQcGTnWbYbKHWN3M7Js8SQ2KLKzASc6Ux0H3niVNvv3v6UdFvzFAY8zlPP8rc7uFIuzIFjDWnEcw6_Fulh9ZJHTmRImVbra0Wq6XY3rdkrojsnfU60J2W6Vhuj6P9Oa6Kn9_Wrufx_BgAA__8%3D)

**Comment by bo-ku-ra** [comment]
it's in the specifications.

Workaround;
https://play.d2lang.com/?script=lJDNSgMxFIX3fYqQvZOkpUUlDYgIbqq-QjK5TAP5KXeuYKEPL2RwIkM3s8r5DpyPcMm6CM_slvyGMV2JuYIe8MgVZz3EOF5sH_Jw5HLii_W-8o6bOkKj6WzeIiTIpAWdK79QSaFnH9_JAS7bkx3HuTtBpJAH9lXC314QNrc371ePZYCsBflaqJY6KR9netjunzp1mHghebXoSlMcmmLbSdWMu72UdwWfP9f_f1ghEPWwNToU69_b5jcAAP__&

**Comment by xbpk3t** [comment]
Thx for your reply. I hope the solution can be explained in the documentation to avoid duplicate issues.
