### ISSUE TITLE
[feature request] box arrowhead and component shape

### ISSUE THREAD

**Issue by pmoura** [terrastruct/d2#2222]
I have a [`diagrams`](https://logtalk.org/manuals/devtools/diagrams.html) tool that generates diagrams using Graphviz (simple [example](https://logtalk.org/library/core_inheritance_diagram.svg)). I'm updating it to also support d2. It would be possible to add native d2 support for `box` arrowhead and the `component` node shape?

Thanks for your work in d2 and looking forward to some of the upcoming features being worked on (notably, links in edges).

**Comment by alixander** [comment]
Can you make these into separate issues that detail what each one is? Like requirements of what fulfills a "component" shape

**Comment by pmoura** [comment]
As requested:

https://github.com/terrastruct/d2/issues/2227
https://github.com/terrastruct/d2/issues/2228
