### ISSUE TITLE
diagrama de secuencia

### ISSUE THREAD

**Issue by Javimile** [terrastruct/d2#2235]
https://play.d2lang.com/?script=fJJdauswEIXfvYrZQDbgh_uQHy6By6W4dAET6cQMlTVmRg602-oSurGihjhtHPKs73B-RkVKQkvPCBNyEKYVdejFiylF0JSZTsiFm2aTBLlUVpMEKUx2BtloNI1TKOrNPhfYkd9ffGITbalDkAOuBMEDZ3BUb_5pL4H_o9dQ0SfTAGdKF881O7bYclFvaaPZp1SYvGh4pTfqJ7bIJPmoNnCQz4_c7IfR4Gq81oTC3tJfZBgTSIbRZAAdvl_mPrT6Q4vQ-9wb_FGxKruJv8snYaNY41JEmsW_e1bl3WJGUXzULAdJEjn-rH_HrkOFIxayx27dfLTzxgt6OeHl4HbZ7hapsvl77HIx9Ff4KwAA__8%3D&sketch=1&

**Comment by alixander** [comment]
please make higher effort to consult the docs or include more information in your posts

https://play.d2lang.com/?script=fJJBrhMxEET3PkVfIBeYBYv_f4QiIYQmYo06dmVo4XEP3Z5IgDgVR-BiyIRM-Jkoa7_qrqp2lZrR0R5xRonCtKEeg3g1pQSaC9MJpTL9CEQFbB1VnTYRpcLCzxD8M0_oyPG1DcCnJDwYjyE8Z2lQR3vNEqUy2XkwG02maY5VPezanCN__-gzm2hHPaIccCUIHrmAk3p4p4NEfo9BY0M_mEY4U_7nMTyx4wUvXNU7etbic65MXjV-oW80zGyJScpRbeQov3-VsBsng6vxk2ZU9o7eosCYQDJOJiPo8PdlyUObN7QyvSuDwR8Fa7Ib-9tyEjZKzS4l5EX8OmdT3g1mlMQnLXKQLInT__HvrOvR4ISV7PG2fjnaueMVva7wcnC7dHeLNNnyPbalGoYr_CcAAP__&sketch=1&
