### ISSUE TITLE
[feature request] recognize text editor URL schemes in links

### ISSUE THREAD

**Issue by pmoura** [terrastruct/d2#2237]
I provide a Logtalk "diagrams" tool that supports creating diagrams for applications with [links](https://logtalk3.readthedocs.io/en/latest/devtools/diagrams.html#linking-diagrams) that open source code locations in common text editors and IDEs. The links use the text editors and IDE URL schemes. For example:

```text
link: vscode://file//Users/pmoura/logtalk/examples/searching/hill_climbing1.lgt:35:0
```

But d2 (tested with version 0.6.8) doesn't recognize these URLs as valid and thus doesn't generate diagrams with links for nodes that contain them.

Common URL scheme prefixes include:

- VSCode: `vscode://file/`
- VSCodium: `vscodium://file/`
- Cursor: `cursor://file/`
- PearAI: `pearai://file/`
- Windsurf: `windsurf://file/`
- Zed: `zed://file/`
- BBEdit: `x-bbedit://open?url=file://`
- MacVim: `mvim://open?url=file://`
- TextMate: `txmt://open?url=file://`
- IDEA: `idea://open?file=`
- PyCharm: `pycharm://open?file=`

**Comment by jacobfriedman** [comment]
Watching this, ty- please add

**Comment by pmoura** [comment]
Thanks!
