### ISSUE TITLE
renders: styles not being applied to markdown/latex

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#231]
namely, stroke and fill.

**Comment by mrtryhard** [comment]
Hi, is this referring to behavior in the image below ? 
![image](https://user-images.githubusercontent.com/5321539/204577378-25133c13-deb2-4fb0-8c0f-5f06e2aa135f.png)

If so, it'd be very interesting for it to either be customizable or default the background to transparent !

**Comment by alixander** [comment]
oh that's a good idea. markdown fill should default be transparent. @gavin-ts wdyt?

**Comment by gavin-ts** [comment]
> oh that's a good idea. markdown fill should default be transparent. @gavin-ts wdyt?

I think having it transparent by default could make sense in a container, and outside of a container it is consistent with outside edge labels. Then you can still set it manually with `style.fill`.

On the other hand a transparent background may make it unclear that connections point to markdown in some cases. If there is multiline markdown with whitespace at points and a connection goes there it wouldn't be as clear as if there were a background and/or a border around the markdown.

**Comment by alixander** [comment]
i think it'd be clear the vast majority of times, and the user can specify border/fill in those other
