### ISSUE TITLE
Markdown is not fully displayed.

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#252]
# Example

```d2
test: |md
hello world
- foo
- bar
|
```

# Expected

```md
hello world
- foo
- bar
```

# Actual

```md
hello world
- foo
```

# Misc

```sh
$ d2 --version
0.0.13
```

**Comment by pleshevskiy** [comment]
If we add an extra paragraph to the example, the list is displayed correctly, but the paragraph is invisible!

**Comment by pleshevskiy** [comment]
Maybe this is related:

```md
[Source](https://www.gnu.org/software/make/manual/make.html\#Recipe-Syntax)
```

d2 will render link as `Sourc`. I think the problem is the size of the markdown box.

**Comment by alixander** [comment]
both of these work for me. what browser and OS are you using? Can you screenshot or include the PNG export you're getting? what's the command you're running? I suspect the fonts aren't loading for some reason, and the markdown box is measured in one font then displayed in another. 

![markdown](https://user-images.githubusercontent.com/3120367/204590092-7ae9d30e-a4b1-43b7-a808-f63e46419cd4.png)

![markdown](https://user-images.githubusercontent.com/3120367/204590226-634bea7d-dcdc-4c9e-97c3-eae87b4ab8e2.png)

**Comment by pleshevskiy** [comment]
> I suspect the fonts aren't loading for some reason, and the markdown box is measured in one font then displayed in another.

Thanks, It was really an issue! I use firefox. In watch mode my ublock extension blocks font.
