### ISSUE TITLE
Direction of nodes

### ISSUE THREAD

**Issue by John0x** [terrastruct/d2#253]
Hey, is it possible to define the direction of nodes, that are connected?
Example:
```
foo -> bar
```
Produces:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/5455173/204538878-15f70bd3-c85c-4c3f-9c8f-165130da9e1b.png">

But I would like them to be vertical and not horizontal.

**Comment by alixander** [comment]
yup this will be in the next release: https://github.com/terrastruct/d2/pull/251
