### ISSUE TITLE
The connections are stretched by the size of block that is at its level

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#254]
I want to use d2 as a mindmap to make it easy to structure documentation.

But I encountered a difficulty in perceiving the information that renders d2.

The connections are stretched by the size of the block that is at its level. It's the same story with blocks. It would be great if they didn't depend on other branches.

![image](https://user-images.githubusercontent.com/7839004/204545273-02b41109-704f-4552-ad45-133396222670.png)

I expect something like the following but with description for connections

![image](https://user-images.githubusercontent.com/7839004/204546752-3ad02ce1-8f37-4f5e-9108-56d2acdb49f4.png)

**Comment by pleshevskiy** [comment]
If you make `shape: none` then the connection is too far from the block.

![image](https://user-images.githubusercontent.com/7839004/204556135-2ae36253-e793-4cce-aeb0-71409f8ae25b.png)

**Comment by alixander** [comment]
i don't think the layout algorithms are good for mindmaps. Maybe TALA can handle it, but dagre and elk are by nature hierarchical whereas mindmaps are... idk, combination of radial and hierarchical, like it's got a specific structure. can you open a Github Discussion for a feature request on mind maps? If there's enough interest, we'll include a layout engine for it

**Comment by pleshevskiy** [comment]
https://github.com/terrastruct/d2/discussions/261

**Comment by pleshevskiy** [comment]
@alixander 
What about this?

```d2
a -> b: very long way to do something like that
```

![image](https://user-images.githubusercontent.com/7839004/204782509-c9590fd1-93cb-4411-b3e4-74e7a4f48198.png)

Can we stretch connection if text too long?

**Comment by pleshevskiy** [comment]
This is relevant for the horizontal direction. Considering that now we can change it manually.

**Comment by alixander** [comment]
@pleshevskiy i know it's been a while but do you still happen to have the script for that render in the original issue? 

the followup label bug has been fixed: https://play.d2lang.com/?script=ggeflUIRyPdciQq6dgpJVgplqUWVCjn5eekK5YmVCiX5Cin5CsX5uaklGZl56Qo5mdmpCiUZiSVcgAAAAP__&layout=dagre

**Comment by pleshevskiy** [comment]
@alixander Great! Thank you!
