### ISSUE TITLE
dagre: ensure sufficient space between shapes for large edge labels

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2#263]
```d2
a -> b: There\nonce\nwas\na\nvery\ntall\nedge\nlabel
```

![Screen Shot 2022-11-29 at 1 43 05 PM](https://user-images.githubusercontent.com/85081687/204654415-c76a868f-e3e2-47ca-9fe2-2ae795cdf163.png)

this can happen with some dagre layouts

**Comment by alixander** [comment]
a horizontal example: https://play.d2lang.com/?script=lJLNSsNAFIX39ynOyl1ELG6CFKKLdllIwaVMzDQzOMmE-bFU6bvL3LYxiGBnkU1y7pd7vplJXwmX2hM1UZv2dW_d-87YfYkvAthBCSP6phUFJ24PojdEwBi9OqWm3CZ6hWDRCz2gcWJ4U_yZ971kgUl8ifsHfnek9BCwWle_mCsd1rFBxcv6TFy9uMSun9lK58TOuj5_tHqp84eSRxTLP6pvne466f4tfTcDssKE-6l-pj2l0_P41CNu-KfSQ4c8dr3AY7GcK9pEY07QYNHK0djD3GHahK08KzF00iMoCaM_5PlOeTrSdwAAAP__&layout=dagre
