### ISSUE TITLE
Define config parameters in d2 file

### ISSUE THREAD

**Issue by rasmi** [terrastruct/d2#265]
It would be nice to be able to define certain config parameters such as the layout engine within a d2 file itself.

**Comment by alixander** [comment]
Oh interesting. Within a d2 file itself... hmm, i can't see the benefit, i think we should use standard config languages for configs. https://github.com/terrastruct/d2/issues/108

**Comment by alixander** [comment]
i totally misunderstood. i thought this was asking for using D2 as a separate configuration file. Upon revisiting, I now understand this to be defining D2 configs in the D2 script file itself. We'll combine into https://github.com/terrastruct/d2/issues/410, ty @rasmi

**Comment by rasmi** [comment]
Awesome, thank you!
