### ISSUE TITLE
Feature Request: Connections with labels inline

### ISSUE THREAD

**Issue by chrisirhc** [terrastruct/d2#276]
Wonder if there's a way to have connections declared inline with the arrow so something like:
```
a -( 1. a goes to b )-> b
```

It gets more valuable when declaring in a sequence like:
```
a -( 1. a goes to b )-> b -( 2. b goes to c )-> c
```
This does result in long lines, which leads to another suggestion, to support intentional line breaks?

Alternatively, to allow for continuing from the last right-most element (Doesn't work to well for LTR text accessibility)
```
a -> b: 1. a goes to b
-> c: 2. b goes to c
```

**Comment by alixander** [comment]
hi @chrisirhc, thank you for the proposal! we considered this in the initial designs, but it's especially hard to read in the multi-line scenario.

Imagine you want to write some latex label:

```
a -> b: |latex
  \\frac{1}{2}
|
```

vs

```
a -(|latex
  \\frac{1}{2}
| -> b
```

the second looks so much less clear to me. there were probably other reasons, but we debated all the methods we could think of and the current form has proven stable.
