### ISSUE TITLE
Near keyword does not work

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#279]
Seems like `near` keyword in text block does not work. And we have to reorder block manually, but reordering doesn't work too in complex examples. See below.

# Simple

If we want to render text near to a block or group

```d2
a; b; c; d;

foo: |txt
bar biz baz
| {
  near: b
}

```

## Expected
```
[a] [b] [c] [d]
   ↑ or↑
   `foo`
```

## Actual
![image](https://user-images.githubusercontent.com/7839004/204772907-db262ad5-393d-4e57-99ff-6598627a114f.png)

## Workaround

We can reorder the text block and now it works as expected without `near` keyword.

```d2
a; b;

foo: |txt
bar biz baz
|

c; d;
```

![image](https://user-images.githubusercontent.com/7839004/204773850-a9601a1c-d0eb-4aad-bd8b-f3f1d5f1c614.png)

# Complex

if we want to render text near to a connected block or group

```d2
a -> e; b -> f;

foo: |txt
bar biz baz
| {
  near: b
}

c -> g; d -> h;
```

## Expected
```
   `foo`
   ↓ or↓
[a] [b] [c] [d]
 ↓   ↓   ↓   ↓
[e] [f] [g] [h]
```

## Actual

![image](https://user-images.githubusercontent.com/7839004/204775961-12668022-d371-4b58-9939-d5c3514f8abb.png)

# Misc

Tested on d2 versions `0.0.13` and latest `e6c7d066164040098d294c00779a2248c402c864`

**Comment by murphyke** [comment]
Also, it seems `near` only "works" with top-level shapes.  Otherwise, it gives a "failed to recompile" error and a panic dump, for example:

```
dog.flea
comment: |md
    parasite
| {
    near: dog.flea
}
```

**Comment by alixander** [comment]
documented
