### ISSUE TITLE
ELK layout: Invalid order of shapes

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#282]
```d2
direction: down

queue: {
  shape: queue
  label: ''

  M0; M1; M2; M3; M4; M5; M6;
}

m0_desc: |
  Oldest message
|
m0_desc -> queue.M0

m2_desc: |
  Offset
|
m2_desc -> queue.M2

m5_desc: |
  Last message
|
m5_desc -> queue.M5

m6_desc: |
  Next message will be<br>
  inserted here
|
m6_desc -> queue.M6
```

# Expected

![image](https://user-images.githubusercontent.com/7839004/204844303-510607a4-3f81-4b88-8293-d59db3b3cc99.png)

Note: I use `dagre` layout to render expected behaviour

# Actual

![image](https://user-images.githubusercontent.com/7839004/204844006-7c1b3c38-5129-40cf-9775-dee304ab2842.png)

**Comment by alixander** [comment]
let me take a look how this can be specified in the layout engines
