### ISSUE TITLE
How to format d2 source files?

### ISSUE THREAD

**Issue by scsmithr** [terrastruct/d2#289]
I came across https://d2lang.com/tour/auto-formatter and it doesn't look like formatting is exposed through the `d2` command. At least I didn't see anything related to formatting when running `d2 --help`.

Is there currently a way to format d2 source files (preferably by passing it in on stdin)?

**Comment by nhooyr** [comment]
Yea it's implemented, just not exposed. Definitely an embarrasing omission haha.

**Comment by nhooyr** [comment]
Will be in next release see #292
