### ISSUE TITLE
Dagre: child containers are pushed to the end

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#307]
Inside the container the child containers are pushed to the end, but without container it render as expected from top. Can we change this behavior?

```d2
Example: {
  User1: {
    D1 -> D2 -> D3
  }

  User2: {
    D1 -> D2 -> D3 -> D4 -> D5
  }
}
```

# Expected

![image](https://user-images.githubusercontent.com/7839004/205098762-1d99dd37-2a5d-4233-98cb-724fa4508ffc.png)

# Actual
![image](https://user-images.githubusercontent.com/7839004/205098541-e3fd12b7-73e5-4803-84d5-6e5017e058aa.png)

**Comment by pleshevskiy** [comment]
Actually for ELK the same issue but it always by center :( I want to control this!

**Comment by pleshevskiy** [comment]
I found workaround for ELK

```d2
Examples: {
  U1: User 1 {shape: person}
  U1 -- D1 -> D2 -> D3

  U2: User 2 {shape: person}
  U2 -- D4 -> D5 -> D6 -> D7 -> D8
}
```

![image](https://user-images.githubusercontent.com/7839004/205101306-19f32e19-4214-4549-b703-890ee023802c.png)

But it doesn't work for `dagre`

**Comment by alixander** [comment]
dagre does have an `align` property, but it has no effect when nodes are contained =\

https://github.com/terrastruct/d2/compare/master...alixander:d2:dagre-align?expand=1

**Comment by bo-ku-ra** [comment]
I wish I could specify the length of the connector.(https://github.com/terrastruct/d2/issues/920#issuecomment-1447150133)

https://play.d2lang.com/?l=&script=dNAxCsJAEIXhfk7xk97grNpMwGo9ggeIsFZKJEYILLm7ZFa2UZtXfbu8eae5vz9uycgC12G49KPRNGS_w5jSPHU4NbSjzGfoUj2bI69nGrWNamTv1X4mMrbfMPyDAuf1o9IGoq5PYvDcCVQSfhPPvefB-SLvAAAA__8%3D&
