### ISSUE TITLE
d2layout-dagre: Compile fully statically with musl libc

### ISSUE THREAD

**Issue by nhooyr** [terrastruct/d2#31]
See https://honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/

**Comment by nhooyr** [comment]
https://xeiaso.net/blog/carcinization-golang

we could also compile v8 to wasm and execute in a pure go wasm runtime instead. then no cgo at all!

**Comment by Vaelatern** [comment]
This currently fully breaks build on musl, including of the d2 command itself (not just d2plugin-dagre).

Is there no easy way to cut this out and require e.g. a library to be present on the system, or something else like that?

**Comment by nhooyr** [comment]
d2 imports d2plugin-dagre by default. But the d2 command itself is pure Go. You can use `--tags nodagre` to build without dagre. See https://github.com/terrastruct/d2/blob/f64ed4981e911ef54d0b9ff6c204fc4c591b06fd/d2plugin/plugin_dagre.go#L1

or `CGO_ENABLED=0 go build ...`

The only pure Go layout engine we currently have is TALA which requires a license. See https://github.com/terrastruct/tala

**Comment by alixander** [comment]
https://github.com/rogchap/v8go/pull/350

**Comment by nhooyr** [comment]
@alixander damn nice how did you know that someone opened a PR fixing it?

**Comment by alixander** [comment]
i brieflyz considering calling React from Go for server side renders (probably won't go with that), and the potential extra reliance on v8go made me investigate its activity.

**Comment by nhooyr** [comment]
Can also try https://github.com/dop251/goja?

**Comment by nhooyr** [comment]
Also means it will be far easier to do #136 when there's no cgo involved.

**Comment by nhooyr** [comment]
Ok maybe not far given the dagre/elk javascript can just run in the browser lol.

**Comment by nhooyr** [comment]
omg what if we just embedded the node binary? code-server used to do this thing where they embedded the node binary/js into a single binary. they probably still do. we could do it too.

**Comment by alixander** [comment]
we can close this now that goja's worked.
