### ISSUE TITLE
Unexpectedly merging shapes

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#322]
Tested on dagre and elk layouts

```d2
a-
b-
c-
```

# Expected

![image](https://user-images.githubusercontent.com/7839004/205332558-07e6a4da-2664-4a1f-b138-546e79d01168.png)

# Actual

![image](https://user-images.githubusercontent.com/7839004/205332594-5feb0454-c360-4acd-961e-c38d2f53e421.png)

**Comment by nhooyr** [comment]
Can confirm this is a bug.
