### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#367]
### Discussed in https://github.com/terrastruct/d2/discussions/329

<div type='discussions-op-text'>

<sup>Originally posted by **azban** December  2, 2022</sup>
It would be nice to have tooltips for objects, so that by default the diagrams are concise, but more information can be encoded for someone looking to dig into specific elements.</div>

**Comment by AlexLloyd0** [comment]
Note that the screenshot example at https://d2lang.com/tour/intro already uses the field `Arcteryx.tooltip`, but that doesn't work in the current release

**Comment by alixander** [comment]
discussion on how tooltips should export is ongoing: https://github.com/terrastruct/d2/discussions/329#discussioncomment-4436573
