### ISSUE TITLE
release: msi installer for windows

### ISSUE THREAD

**Issue by nhooyr** [terrastruct/d2#379]
Continuation of https://github.com/terrastruct/d2/issues/96

**Comment by bo-ku-ra** [comment]
would this help?
https://stackoverflow.com/questions/19254772/how-do-i-use-insignia-exe-to-codesign-a-wix-bundle

**Comment by nhooyr** [comment]
What would code signing get us?

**Comment by bo-ku-ra** [comment]
I found a similar story done in English.
https://github.com/sbt/sbt/issues/4309

**Comment by bo-ku-ra** [comment]
https://stackoverflow.com/questions/58831544/how-can-i-generate-windows-certificate-so-my-msi-doesnt-shows-warning-to-users
