### ISSUE TITLE
Add Crows Feet to Arrowhead options

### ISSUE THREAD

**Issue by Rjvs** [terrastruct/d2#384]
Hi, although documentation claims D2 is useful for ERDs, it would be useful to have more options for the arrowheads, such as [crows feet](https://vertabelo.com/blog/crow-s-foot-notation/).

**Comment by suhr** [comment]
Crow's foot is a more compact and visual notation than labels.

**Comment by alixander** [comment]
closed by https://github.com/terrastruct/d2/pull/578

@suhr you had an opinion on rendering, how's it look to you?

**Comment by suhr** [comment]
Proportions are rather unusual. Compare with this images:

![entity-relationship-diagram-1536x781](https://user-images.githubusercontent.com/65870/210457549-c5421dbf-27d8-44b5-9f78-0cadb2f1635e.png)
![php7wjEYw](https://user-images.githubusercontent.com/65870/210457568-89a9a0c5-eb4c-4c1b-9785-17be66e3e72d.png)

The first picture is from a database design tool: https://www.datensen.com/blog/er-diagram/crows-foot-notation-in-erd/

**Comment by suhr** [comment]
There's an another example: ![schema](https://user-images.githubusercontent.com/65870/210458301-1ee13f69-0414-4bb1-99f8-e84dec1074d4.svg)

**Comment by martinjirku** [comment]
I was trying to replicate it from the [blog](https://vertabelo.com/blog/crow-s-foot-notation/) mentioned in the original post.
If there is a need, it can be definitely improved.

**Comment by alixander** [comment]
yeah i'm interested to see what it looks like in practice. 

i don't think the existing implementations out there are the gold standard by any means:

<img width="114" alt="Screen Shot 2023-01-04 at 11 27 40 AM" src="https://user-images.githubusercontent.com/3120367/210633934-182a4694-bfc5-42e1-bceb-68d7b15af240.png">
