### ISSUE TITLE
Constraint for regular shape works as label

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#415]
```d2
foo {
  label: bar
  constraint: BIZ
}
```

# Expected

ignoring `constraint` keyword as for example `direction`

![image](https://user-images.githubusercontent.com/7839004/206699497-ae7e7b3e-721b-45ec-8099-2b9033e69bb1.png)

or show an error as for example `3d` for `shape: oval`

![image](https://user-images.githubusercontent.com/7839004/206699771-f23586d6-1ea5-4007-ae32-bda3c19502db.png)

# Actual

![image](https://user-images.githubusercontent.com/7839004/206699662-4293c8d3-96c6-40d9-bf7e-f65b69e1c9ee.png)

**Comment by alixander** [comment]
good find, ty
