### ISSUE TITLE
External url link do not appear to work

### ISSUE THREAD

**Issue by mrtryhard** [terrastruct/d2#417]
## Summary 
**OS:** Ubuntu 22.04
**Browser:** Firefox 107.0
**D2 version:** 0.1.1
**Error summary:**
Adding a link to a shape do not appear to be working as expected. According to the docs https://d2lang.com/tour/style , a shape can be a link to an external URL. 

**Compiled via:** 
```
d2 --watch test.d2 test.svg --theme 105
```

**Sample code:**
```
test: "Deterministic diagrams" {
  shape: hexagon
  explanation: |
    All diagrams use the same  
    convention and style.
  |
  link: https://google.com/
  style: {
    link: https://www.google.com/
  }
}
```

## Actual result
Shape has no link whatsoever. Looking inside the SVG also shows there is no link. 

## Expected result
Shape can be clicked and redirects or opens a page to the determined link.

## Note
Adding the link manually around the node seems to be working, e.g. 
```xml
<a xlink:href="https://www.google.com" target="__blank">
    <g id="code_container.advantage_3">
        <g class="shape">
            <path d="M 572.5 546 L 504 619.9152 L 572.5 694 L 709.5 694 L 778 619.9152 L 709.5 546 Z" style="fill:#DFDCDC;stroke:#312102;opacity:1.000000;stroke-width:2;"></path>
        </g>
        <text class="text" x="641.000000" y="575.000000" style="text-anchor:middle;font-size:24px;fill:#170206">Deterministic diagrams</text>
    </g>
</a>
```

**Comment by veeral-patel** [comment]
Can confirm. Am facing the same issue.
