### ISSUE TITLE
text_block: Lazy Closing Check 

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#420]
I cannot create a text block with base rust language script

```d2
a: |rust
fn main () {
  let a = vec![1, 2, 3];
  a.iter().map(|a| a * 2).collect()
}
|
#               ^ text block closed here
```

![image](https://user-images.githubusercontent.com/7839004/206824059-57784b3a-c958-4c2a-8348-c4f92bf31154.png)

it fails with

![image](https://user-images.githubusercontent.com/7839004/206824505-fa341ca3-56f4-4243-b670-cad021024a00.png)

In tree-sitter-d2, I implemented an additional scanner that looks several steps ahead https://github.com/pleshevskiy/tree-sitter-d2/blob/main/src/scanner.c#L39. It works as a charm for any text blocks

**Comment by alixander** [comment]
you can also use double `||`: https://github.com/terrastruct/d2-docs/issues/25

**Comment by pleshevskiy** [comment]
Subscribed to the documentation update!

**Comment by pleshevskiy** [comment]
@alixander Note: for rust we cannot use `||` too :)

![image](https://user-images.githubusercontent.com/7839004/206826035-f7640cdf-4046-4e96-b2bf-399e1d076e6e.png)

![image](https://user-images.githubusercontent.com/7839004/206826128-c012e67a-58aa-40b9-8a11-7e1aba932295.png)

So, you need to document |` block

**Comment by pleshevskiy** [comment]
![image](https://user-images.githubusercontent.com/7839004/206826517-7b7189dc-9525-4603-81f8-772910a44ea2.png)
oh! we can use any character?
