### ISSUE TITLE
how to set direction ?

### ISSUE THREAD

**Issue by wangduanduan** [terrastruct/d2#421]
![image](https://user-images.githubusercontent.com/16631306/206839304-eabe0351-2632-4c8f-892c-76360a6b9c65.png)

after read the docs, i don't know how to set the direction,  could you give some examples ?

**Comment by Gnimuc** [comment]
The keyword is reserved here:
https://github.com/terrastruct/d2/blob/376e615f9394913183261ab82e695d67acf596b4/d2graph/d2graph.go#L1113

and looks like it shares the same attribute level of `shape`, `style`, etc.
https://github.com/terrastruct/d2/blob/376e615f9394913183261ab82e695d67acf596b4/d2graph/d2graph.go#L106

According to 
https://github.com/terrastruct/d2/blob/d5a1c9557365c326137e75a6299df9d73c9b3a69/d2compiler/compile.go#L266-L271

the `direction` key-value pair should be handled on root:

```
direction: right

x --> y
```

**Comment by wangduanduan** [comment]
@Gnimuc thank you
