### ISSUE TITLE
Feature Request: Change direction on container level

### ISSUE THREAD

**Issue by frederik-suerig** [terrastruct/d2#432]
It would be great if we could change the render direction on a container level

```d2
direction: right
Container 1{
 direction: down
 Child1
 Child2
}
```

**Comment by alixander** [comment]
this is possible currently in TALA: https://d2lang.com/tour/layouts#directions-per-container-tala-only

The other layout engines are limited here and fundamentally their algorithms don't allow for it. 

I have a plan to shim this though. Basically run layout separately for isolated containers (containers whose children do not have outside connections), and piece them into the main layout. Hopefully it works.

**Comment by alixander** [comment]
dupe #495
