### ISSUE TITLE
The connections on the right are not displayed correctly.

### ISSUE THREAD

**Issue by pleshevskiy** [terrastruct/d2#442]
```d2
# layout: elk

d2: D2 {
  description: |txt
    D2 is a modern diagram scripting
    language that turns text to diagrams. 
  |
}

d2 -> Comments
comments -> line_comment
comments -> block_comment

line_comment: Line Comment {
  example: |python
    x -> y
    # This is line comment
    y -> z # and this
  |
}

block_comment: Block Comment {
  example: |python
    x -> y
    """
    This is block comment
    """
    y -> z
  |
}

d2 -> $shape
$shape: Shape {
  syntax: |txt
    <shape_key>[: <label>][;]
  |
}

d2 -> container
container: Container {
  syntax: |%txt
    <container_key>[: <label>] {
      (<container_definition>)*
    }

    where
      container_definition:
        Shape | Connection | Attribute
  %|
}

d2 -> connection
connection: Connection {
  syntax: |%txt
    <shape_path> <arrow> <shape_path>[: <label>][connection_block]

    where
      arrow: -- | -> | <- | <->

      shape_path:
        (<container_key>.)*<shape_key>

      connection_block:
        { <connection_definition> }

      connection_definition:
        connection_attribute | style_attribute
  %|
}

d2 -> Text Block

```

# Exected

![image](https://user-images.githubusercontent.com/7839004/207436452-c44138eb-8278-44c8-804e-288e0e50a9a5.png)

# Actual

![image](https://user-images.githubusercontent.com/7839004/207436236-5b54df81-de26-4f42-a091-9df6a413829c.png)

**Comment by pleshevskiy** [comment]
Actually, dagre is affected too
![image](https://user-images.githubusercontent.com/7839004/207447221-6349719c-3132-4a25-afe9-6233ee458d41.png)

**Comment by VenkataBhaskarr** [comment]
@pleshevskiy can you please mention the operating system you are working on, the browser and its version because it's working perfectly fine in my device(Mac OS Ventura , safari latest version).


<img width="1348" alt="Screenshot 2022-12-15 at 10 39 30 PM" src="https://user-images.githubusercontent.com/111889155/207923914-48668a10-5a4a-4f0a-b72b-67afcafbde06.png">

**Comment by pleshevskiy** [comment]
@VenkataBhaskarr I don't think it matters. I had this code working fine up to a certain version. Unfortunately I missed the exact moment when it broke.
I have currently installed the latest version of d2
