### ISSUE TITLE
d2 fmt to stop modifying the file when there is no change

### ISSUE THREAD

**Issue by kamok** [terrastruct/d2#469]
I was trying to do some auto-reloading to run the formatter on change.

It turns out `d2 fmt` would keep modifying the input file (even when there's no change)!

This leads to an infinite loop of formatter running -> no change but modify -> auto-reload detects file is modified -> formatter running again.

Please advise.

Example:
nodemon --watch input.d2 --exec "d2 fmt" input.d2

```
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): input.d2
[nodemon] watching extensions: d2,json
[nodemon] starting `d2 fmt input.d2`
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `d2 fmt input.d2`
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `d2 fmt input.d2`
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
...
```

Mac Finder also shows Date Modified to change when running formatter without nodemon.

**Comment by alixander** [comment]
thanks @kamok , this will be in the next release" https://github.com/terrastruct/d2/pull/470

(you can install from source in the meantime)
