### ISSUE TITLE
compiler: escape reserved keywords

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#477]
E.g. width and height should be usable as sql table column keys.

https://play.d2lang.com/?script=AvnbSiE4sypVoZpLQQHsaiuF4sKc-JLEpJxULgUFJbA6JSuFvNLcpNQikAgkoBBCtVyAAAAA__8%3D

**Comment by alixander** [comment]
https://discord.com/channels/1039184639652265985/1039184640285610147/1074183026956836974

**Comment by alixander** [comment]
@nhooyr any ideas on how best to do this? Just prefix a backslash? e.g. `\shape: int`

**Comment by alixander** [comment]
this isn't an issue normally, because you can just relabel things, e.g.
```
x: { s: "shape" }
```

but for SQL tables this doesn't work

**Comment by alixander** [comment]
for now i should just make sure `label` works for sql table columns

```
x: {
  shape: sql_table
  s: int { label: shape }
}
```

**Comment by nhooyr** [comment]
Ooo I see, we should change the compiler to ensure that any reserved key is unquoted and without any backslashes.

Also need autofmt to preserve backslashes which I don't remember if it does right now. I know it doesn't preserve line continuations still.

**Comment by luistar15** [comment]
Adding a space inside quotes works for me, it seems to be trimmed afterwards:

```d2
my_table: {
	shape: sql_table
	icon: https://static.wikia.nocookie.net/tomandjerry/images/4/46/JerryJumbo3-1-.jpg
	width: 200
	height: 200
	"shape ": string
	"icon ": string
	"width ": int
	"height ": int
}
```
![{C1AF17D4-AF7C-4424-ADC0-8FACED1F5EDF}](https://github.com/user-attachments/assets/79c990ae-28dc-4ff3-8fd0-4c81ca375d6b)

I could not found an official list of reserved keywords for d2lang, specially for `sql_table`, here is some:
- `shape`
- `icon`
- `width`
- `height`
