### ISSUE TITLE
d2 process crashes when no connections in sequence diagram

### ISSUE THREAD

**Issue by judepayne** [terrastruct/d2#490]
The d2:

    conv: Silly conversation {
      shape: sequence_diagram
      alice: Alice
      bob: Bobby
    }

Will cause the d2 process to crash.

When a connection is added in, there's no problem.

**Comment by alixander** [comment]
@judepayne it works on latest:
https://play.d2lang.com/?script=Ss7PK7NSCM7MyalUALFTi4oTQaGpUM2loAD2g5VCcWphaWpecmp8SmZielFiLpeCAihgUq0UHEEUl4JCUn6SlYJTflJSJVctFyAAAP__

Can you try updating yours if you're on an earlier version? Thank you

**Comment by judepayne** [comment]
@alixander I upgraded and it does work now. thanks!

**Comment by alixander** [comment]
great! appreciate you making the issue, it'll help others on older versions that may run into this
