### ISSUE TITLE
sketch: Vary the texture blend mode based on brightness of fill

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#505]
Currently it's too subtle on lighter fills and too prominent on darker fills

<img width="498" alt="Screen Shot 2022-12-22 at 11 13 24 AM" src="https://user-images.githubusercontent.com/3120367/209214193-0cf3b7e8-b2fa-471d-9300-dba590072c2c.png">

**Comment by alixander** [comment]
we currently let shapes have a "blend" attribute which tells CSS to use a blending mode (used for sequence diagram spans): https://github.com/terrastruct/d2/blob/master/d2renderers/d2svg/d2svg.go#L665

we probably just need to change from a bool to a string

**Comment by vfosnar** [comment]
Okay so I have no experience with graphics and I have no idea what algorithm to use to calculate brightness of an image. I have a lot of time tomorrow so I will implement at least changing it based on given brightness. Could you provide some info about what method to use?

Continuing on this I also think that I could do some refactoring to support both light and dark themes based on media query and dynamically loading themes from a file if that would be something you are interested in.

I don't want to be that kind of guy who randomly starts adding things no-one cares about to the project and I am open to discussion. @alixander

**Comment by alixander** [comment]
Dark mode is a popular request, I wouldn't be surprised if the dark mode becomes one of the most used themes -- very much appreciated and not random! 

No graphics experience required: tldr; Blend modes determine how an overlapping element should blend into the colors behind it. The default is no blending, you only see the colors in the front.

In sketch mode, D2 overlays a rectangle over fills, where the rectangle has this streaky pattern to give it a paper look. The pattern is defined here: (https://github.com/terrastruct/d2/blob/6e8ffb529ff985d707e8212981e71f84c5425b7e/d2renderers/d2sketch/sketch.go#L56). 

This rectangle overlay has a class, which has a style with blend mode and fill of that streak pattern defined above: https://github.com/terrastruct/d2/blob/6e8ffb529ff985d707e8212981e71f84c5425b7e/d2renderers/d2svg/sketchstyle.css#L1

I think a rough outline of steps would be:
1. Instead of applying the same `sketch-overlay` to every rectangle overlay, you apply `sketch-overlay-bright`, `sketch-overlay-normal`, and `sketch-overlay-dark`. Give each one its own styles.
2. To choose which class, you determine the fill brightness. We want to do it with the builtin `image/color` instead of a third party lib. Looks like there's ways to (e.g. quick google search: https://www.socketloop.com/tutorials/golang-find-relative-luminance-or-color-brightness). 
3. Follow the guide in this issue.

Hopefully it works -- our designer made these in illustrator so not sure if it'll map 1:1 with CSS + SVG. Will be interested to see the results. @katwangy 

The media query idea is interesting. This came up in this issue: https://github.com/terrastruct/d2/issues/159. Basically I didn't want the time of day to effect exports. I think I'd still prefer it be entirely dependent on the specified theme.

**Comment by vfosnar** [comment]
One problem I encountered is that I have do define the sketch overlay 4 times - 1 for each shade. This is because you can't control the `fill` property when added through `defs` and `fill: url(...)`

**Comment by vfosnar** [comment]
Okay. I finally have some time now so I will do some things for our school project and then hopefully finish this issue.

**Comment by vfosnar** [comment]
It's finished. I feel bad for all that duplicate code but I couldn't find any other way to do that... Anyway both theme color and user-defined color are respected. And dark theme is ofc supported too :p

**Comment by vfosnar** [comment]
I will review all my changes tomorrow to make sure I didn't screw anything up. I will let you know when I'm done so others can check it as well.

**Comment by vfosnar** [comment]
related, this can be finally closed too @alixander :p

**Comment by alixander** [comment]
ohhh right, will changelog that too.
