### ISSUE TITLE
n is lack in svg

### ISSUE THREAD

**Issue by 1s22s1** [terrastruct/d2#507]
## Step to reproduce

1. Write below code as d2 file

```markdown
hello -> null
```

2. Run `d2 null.d2 null.svg`
3. Show null.svg

![null](https://user-images.githubusercontent.com/77497543/209246648-4f6f978b-2a47-4dc4-9a04-cf32e8305cca.svg)

## Expected behavior

null is displayed.

## Actual behavior

ull is displayed.

## System configuration

**d2**: v0.1.2

**Comment by alixander** [comment]
wow, baffling. ty. 

can reproduce on latest: https://play.d2lang.com/?script=ykjNyclX0LVTyCvNyeECBAAA__8%3D&layout=elk
