### ISSUE TITLE
The double byte character calculating is not correct so the diagram's width is not fitting.

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#513]
incorrect;
https://play.d2lang.com/?layout=dagre&script=SklKtlKoyU3hUlBQVnjc2PW4cf3jpo7HjW1cCgq6Cmn5-WA6KbGIq4YLEAAA__8%3D

adding single byte charactors(\x20);
https://play.d2lang.com/?layout=dagre&script=SklKtlKoyU3hUlBQVnjc2PW4cf3jpg4FKHjc2MaloKCrkJafD6aTEou4argAAQAA__8%3D

There are four double byte charactors.
I need to add four single byte charactors.

**Comment by alixander** [comment]
i believe this is because the font we use does not support Hans characters, so the measurement will be off.

I've created an issue for this:
https://github.com/terrastruct/d2/issues/517

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?layout=dagre&script=4lJQUFAIBjtLITgxr1ghoCgfWcwjMQ8sjk2dgq4dujKrjJKSgmIrff30zJKM0iS95Pxc_cSU_KRUXVAoF-tDAyAjMU-3ODGvWB9sLBcgAAD__w%3D%3D

**Comment by alixander** [comment]
actually i believe the core issue is that this is within markdown. for non-markdown, hans characters seem to render okay.

https://play.d2lang.com/?layout=dagre&script=erKj--XsFQq6dgpPZ897um4bF4QCCTzvW_lsx45nHf1IYk8bZz3ZO-fJjllWCs-mbni6dhkXIAAA__8%3D

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?layout=dagre&script=etzYNFBI1849tbgkMadEITk_JyexoDiVCxAAAP__&

**Comment by alixander** [comment]
touche

**Comment by bo-ku-ra** [comment]
i am not good about golang
is this possible? misdirected?

```
func controlRune

case unicode.Hiragana #japanese
case unicode.Katakana #japanese
case unicode.Han      #japanese and so on

dot.X += Face.Metrics().Ascent.Floor() + Face.Metrics().Descent.Floor()
```
