### ISSUE TITLE
elk: investigate panic

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#524]
This diagram looks really good on dagre but panics on ELK. 

![d2 (52)](https://user-images.githubusercontent.com/3120367/209481854-725f3d59-5edc-4f37-a117-5affe8f6eb04.png)

Found here: https://github.com/antoinevg/GSG/blob/d5edd32e59e2a6ba83218f4042913d6508c78d53/luna/design/structure/top_structure.d2

https://play.d2lang.com/?script=vFffb9s2EH7XX3Gwgb1ZnJ0oaLllgBM3bYYESOt4xZ4cWqIlLhIpkHQzL83_Poj6YSqmbLcumodAvPtIft8dyTv34RwiogksU_GEIV1xAufnnteHASRCFYGJKAyO_fO8ZjEMH4TSMGUR3Rh9IwXDsyUdQ_BiT3v2AJYkLI5KSOU8ZhpbYz9megvgL0j4SHmk5pkQvLTbk1DtRxu_n68PWmfOsrgkBWDOCIZez4xM6jGwjMTUGIojhSHROlcYIaWJZqH_xB4Z8bkIhXhk1OdUoyzNkZmlUICCIboVgs8n5W7Xk_k0eDcc-TmPPYCXgzjqfzWGr1lkWPT7cFOk96qZBhflFOOeUMm-UFhKkWF4aAcWI1fMYkmJboL24AF89TwAY15SXWaoOFFVbmyHXyR2XjixOWeo-DT_yvi7sXOnoLu1TgSHG7aQRK4dYurFSilmu9rUfNgKUrYw5kpBNapU2M6SWb42hkpINUK7oFs6LkWWER7BlEpGUvYfKV40KCz3knCVC6lb-q65prEkmmJ4sPlV6moOD-X68AtfqPw3I--lvNsR_cJC-kNut-dZi2GYmEF5vy1H5w1vTX62ojaQqgjcfMlk9kQkxbbnVTJeY_2oyL9U1Z3cB_NDkWUKQ21HlR0ZOzp4haPz-okuqaQ8pMCyotRQrs2UrTR3MHUkfBf5PCV6KWS2L0w1bhPWZv_ahZQIGzLfspb7Tk_FJdxRyfKESpLCpMS61RUPQ_utsaz-5vg0nF1uX4mwXGET20JSF9ZNuzr847vrfelsv0nNls27t1ILFKZEKdp-aMOOFNccY6JpdVsKLfUQuTCW5gb3WrON7U7V-wrl5NZ3rLZSi9c7F4pbUhIio1JK_YVcbt9dFJK1YiFJ4UMF26bmWouGeYDh5updMBsMR1eDs4v3o-Ds0oldqcXgnyGG2XAIs-nFycnpSTduhGH2Zj_sBMPs7U4Y1SGGnu_7vXZoG0CyzqmUJMPw-W1wNn5ze_H3-Oy6A6xytkzNU_x5FHw8Gf3513R6_bEDTLQiWYRhfD8d306Gw8nwdDy4nd3XRYVxTSUnKUiamnOuEpar76ovVsPo7-9z4PfBH5t21e9qNEx1KVu13PQMHkBdlszxaH4KYBidlr2c1XNjCCwbhkW6oqYVe7HZujd_xXBHE_FTSHbub3jaZfvQ0mnRXqnFcZxjSSmvSR9CZpu1-3m3SH5aKX0cSyEJj-m30Nyqfd2820_0z-Ltitp-ji1-vR70v4vkry2STwnTuznWu3fz29QPi984I5JwnRwXw3wl87Tm938AAAD__w%3D%3D&layout=dagre

**Comment by pleshevskiy** [comment]
![image](https://user-images.githubusercontent.com/7839004/209582926-b111e488-2f21-4199-ae5e-15305ec74c91.png)
it works without empty label
