### ISSUE TITLE
font-size doesn't work for markdown texts

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#529]

**Comment by mmatti** [comment]
I'd like to double-down on the importance of this. Markdown text is perfect for background, "near" positioned annotations on diagrams, except for one big gotcha: the hard-wired font size is _way_ too big for that purpose, and there's currently no way to tame it. Really frustrating ... wound up resorting to a document shape (page was another candidate), but having positioned, borderless markdown text — at a reasonable font size — would be the perfect approach for this use case.

**Comment by alixander** [comment]
done! deployed on playground and will be in next release @mmatti 

https://play.d2lang.com/?script=7JKxauNAEIb7fYofrjgwtsEuVRxccVddcVUg5UgeaYesdsXOrGwRR88eVgmBvEGKdMsw8_2zfON5aXAfLw74gT8z5wV9LmplREhxUFhCyyB0KbIDDvhdnyaxSBzQh3RF6jHRxBmi0NL30glHq5PvnQzz_Ll3Q_0PTMrIPJJEdBTGPcR-KmJCUUabzNeJomi5xvlFjXP9AMg2qNLIMBnfdnsQFVNQuNKiGGRmTDWjZG4gPWIypAjKWWYK-0qItVBJF54oW8mVtPvLajKLLfjHMwecdg0eU8kYCmtNyIzOk1ndikahNiy4inkwdR7JPOejc4CxGtZVLcsTm8-pDH5dt7K749kBm-_jx8k3OJ_di3O3by1fS8vpVLU4zwsOv3BzrwEAAP__&layout=elk&
