### ISSUE TITLE
arrowhead is broken.

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#534]
https://play.d2lang.com/?layout=dagre&script=cs7Py4OEX7GVQjWXgoIjTB-Eq6CQmGFopVBTkFqUA-YqKKB7wkpBC6oUKg_yuZVCSmZibn5eCrIEyLl6kJixUkhLzClOhcvWglk1XDArFWx07RQSM4ys4EbjtxaHpbitrIXS6MFlpaBFsrklRaWoxtbC_GGEGnQELCM67JAsRAQdiFXLBQgAAP__&sketch=1

**Comment by alixander** [comment]
indeed, this is only on sketch mode. thanks for the example, will close in favor of https://github.com/terrastruct/d2/issues/502

**Comment by bo-ku-ra** [comment]
i discovered
https://play.d2lang.com/?script=lJJBbsQgDEX3PsVXsh4OQKWeZDYJY4XRtHYUyAJF3L0Cpk0WaatBQl88sDH-rIEXu9Vi7cxLUMlUGC7v8DpxmcYr0_fCYiPAK1cFRo1Nh6YTF83PMzULl_hM1F9OB_Vwwxr41_1jHc-kKSUzrxZd9PeAwBJZHOMeEFXxoTKZq_y0oPCx9E7MVV6PEI0ID47O41NvbDpstfNm_0x24dsbGm02VZIJ_V_V66P7_9XDHrLD8Qy6A0wpWVSPyk3Nq1mrNZm-AgAA__8%3D

**Comment by alixander** [comment]
good find! ty @bo-ku-ra

**Comment by alixander** [comment]
we can close this one @gavin-ts , the sketch arrowhead is separately tracked: https://github.com/terrastruct/d2/issues/502
