### ISSUE TITLE
Tooling: d2 support for emacs org-mode code blocks

### ISSUE THREAD

**Issue by xcapaldi** [terrastruct/d2#535]
I've written a simple Emacs package for org-mode that provides d2 support for code blocks in a similar vein to [ob-ditaa](https://orgmode.org/worg//org-contrib/babel/languages/ob-doc-ditaa.html). You can find it here: [https://github.com/xcapaldi/ob-d2](https://github.com/xcapaldi/ob-d2)

If you think this is relevant or significant enough you can add to your [community plugins listing](https://github.com/terrastruct/d2#community-plugins).

**Comment by alixander** [comment]
awesome! https://github.com/terrastruct/d2/pull/536
