### ISSUE TITLE
width and height specification in svg-file

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#540]
The default output of d2.exe is specified as width and height.
If the svg file output by d2.exe is too wide or long, I would like to immediately display the entire figure in Edge (Chromium).
Is there such an option?

-----------------
Contents of *.svg
-----------------
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;svg
style="background: white;"
xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
width="**_```100%```_**" height="**_```100%```_**" viewBox="-10 -10 1048 5796"&gt;&lt;style type="text/css"&gt;
&lt;![CDATA[
.shape {
  shape-rendering: geometricPrecision;
  stroke-linejoin: round;
}
.connection {

&lt;snip&gt;

**Comment by alixander** [comment]
i think this is what you're suggesting: https://github.com/terrastruct/d2/issues/16.

But I'm not sure. Could you explain more if it's different?

**Comment by bo-ku-ra** [comment]
watch-mode; 
	I'm drawing a diagram now. no problem.

my suggestion;
	The diagram(svg-file) is a finished product .
	I email it.
	my colleagues will be able to view it easily.

**Comment by nhooyr** [comment]
So when you open the .svg, Edge isn't showing you the full svg and it's clipped until you zoom out/scroll?

I guess we could add a script in the .svg to take care of this.

**Comment by bo-ku-ra** [comment]
yes.

Edge/Chrome for Windows
CTRL + '-' : zoom out (min 25%)
CTRL + '+' : zoom in  (max 500%)
I looked for just the right magnification.

please add the script. I hope so.

**Comment by nhooyr** [comment]
@berniexie https://github.com/terrastruct/d2/pull/560#event-8128565401 doesn't fix this. The standalone svg needs to resize too and needs a simlar script embedded.

**Comment by berniexie** [comment]
> @berniexie https://github.com/terrastruct/d2/pull/560#event-8128565401 doesn't fix this. The standalone svg needs to resize too and needs a simlar script embedded.

@nhooyr but how would we know what to resize it to with no browser? Isn't the whole point of svg that it looks good at any size

**Comment by nhooyr** [comment]
@berniexie So you can embed a js script directly into the svg so that when the svg is opened, the js runs. The earliest version of d2 --watch used to use no html and just serve an svg with the js embedded directly.

**Comment by bo-ku-ra** [comment]
i am drawing the diagram when I execute watch-mode.
v0.1.4  changes to default magnification every reloading.
i suffer this specification. Especialy i draw big diagrams.
please keep the original magnification in watch-mode. (same v0.1.3)

**Comment by nhooyr** [comment]
Yea I guess we only want to zoom on the initial load and not for every one thereafter.

**Comment by bo-ku-ra** [comment]
i can't use v0.1.4 when i'm drawing the big diagrams because of this issue.
should i use v0.1.3?
how i can avoid it on v0.1.4?

**Comment by nhooyr** [comment]
I would suggest using v0.1.3 or building from master as @berniexie has fixed it.
See https://github.com/terrastruct/d2/blob/master/docs/INSTALL.md#source-release

And you can wait until the next release of course.

**Comment by alixander** [comment]
we'll cut 0.1.5 with this fix in the next few days
