### ISSUE TITLE
incorrect keys in style attribute maps are not error reported

### ISSUE THREAD

**Issue by judepayne** [terrastruct/d2#542]
Hi,

top level attribute keys in d2:

    c -> a {styleee: {stroke: red}}

are checked for errors:

    failed to recompile: 1:1: edge map keys must be reserved keywords

but errors in keys in nested style maps can either be ignored or produced funny errors in the diagram:

    c -> a {style: {strokeee: red}}

produces:

<img width="155" alt="image" src="https://user-images.githubusercontent.com/141360/209772176-70bce731-099c-49a0-8521-1b0a40254ba0.png">

nested style values are checked though:

    c -> a {style: {stroke: reddish}}

produces:

    failed to recompile: 1:25: expected "stroke" to be a valid named color ("orange") or a hex code ("#f0ff3a")

**Comment by alixander** [comment]
thanks @judepayne !

related: https://github.com/terrastruct/d2/issues/416 . I'll make error msgs clearer when I make that change

**Comment by alixander** [comment]
fixed in next release
