### ISSUE TITLE
Dagre layout bug

### ISSUE THREAD

**Issue by jbreitbart** [terrastruct/d2#546]
When layouting
```
en: {
  ha: {
    f
    bb
  }
}

en.ha.bb <-> en.ha: unify
```
using the Dagre layout, I get
![d2](https://user-images.githubusercontent.com/881727/209875932-ac009b6e-1acd-45d3-968f-7b24de949e79.png)
which looks wrong. The connection between en.ha.bb and en.ha.f seems to be wrong and it is not showing when using another layout engine on the playground.

**Comment by alixander** [comment]
thank you for reporting @jbreitbart . indeed, this is a known bug. will add this to examples but keep the existing issue to unify: https://github.com/terrastruct/d2/issues/71
