### ISSUE TITLE
Proposal: change font size/color on shape:class/sql_table. 

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#549]
I understand this isn’t the original purpose.
but I think this is good idea.

https://play.d2lang.com/?layout=dagre&script=UtJIrdBTKE4uyiwoUcgvLSkoLSnWVNIrSi0uzSmxUqjmUlAA-8RKobgwJ74kMSknFSQEslgPFMZWCkWpKXARiAutFHJAAZlelFiJUAsPdyuF_KLEvPRUVClQ-FspGBlwKSgo1VAINIwMTCw0lawU3EvzUhJzFYIidM0tsBmsYWpoBFJXmV8Kk9YwNAJrzU3lquUCBAAA__8%3D

my script (I like perl :-) outputs a result as d2 format.
I hope to change font-size, font-color and so on.

**Comment by bo-ku-ra** [comment]
Thank you.
I was made aware that markdown supports html, so you can ignore this suggestion.  #551

**Comment by spinscale** [comment]
Great tool! Thanks for that!

Regardless of the above issue solved with tables, I guess changing the style of the sql_table columns still makes sense - just ran into this as well.
