### ISSUE TITLE
Proposal: shape:table (inspire html<table>tag)

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#551]
Proposal; 
ex:{
shape:table  ```<- new```
#Like MS Excel/LibreOffice Calc
	=A1:{	  #Reserved-word: /\=[a-z]+[0-9]+/i )
		value: "date";
		style.fill:pink;
	}
	=B1:{	#Like Exce1
		value: "count";
		style.fill:pink;
	}
	=A2:{value:'2022/12/31'}
	=B2:{value:10; align:right}
	=A3:{value:'2023/1/1'}
	=B3:{value:100}
	=A4:{value:'total'; align:center}
	=B4:{value:110; style-font-color:red}
}

Expected; (view it as html)
&lt;table border="1" cellspacing="0" cellpadding="0"&gt;
&lt;tr&gt;&lt;td bgcolor=pink&gt;date&lt;/td&gt;&lt;td bgcolor=pink&gt;count&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;2022/12/31&lt;/td&gt;&lt;td align=right&gt;10&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td&gt;2023/1/1&lt;/td&gt;&lt;td&gt;100&lt;/td&gt;&lt;/tr&gt;
&lt;tr&gt;&lt;td align=center&gt;total&lt;/td&gt;&lt;td&gt;&lt;font color="red"&gt;110&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;

<table border="1" cellspacing="0" cellpadding="0">
<tr><td bgcolor=pink>date</td><td bgcolor=pink>count</td></tr>
<tr><td>2022/12/31</td><td align=right>10</td></tr>
<tr><td>2023/1/1</td><td>100</td></tr>
<tr><td align=center>total</td><td><font color="red">110</font></td></tr>
</table>

**Comment by alixander** [comment]
we plan to support markdown tables, which should cover your use case: https://github.com/terrastruct/d2/issues/160

**Comment by bo-ku-ra** [comment]
Oh!

forced sample;
https://play.d2lang.com/?layout=dagre&script=nJJNbsMgEIX3PsWUC_DjXQVzhZ4Be5BrFWOLjheRfPgI41iJkmzCiuHxPeAxP79f37BN1ABY9l0MULN2QgvoQ4z_5WlpcELVevFER407lNEyQTfsobplTH9InoOVTM9KP6-JqyQ53xmgUcZIbWSrT9LHcUgul09Brd5RrdTyZFCrlxsPrz4kDhl5Zh9PxJYGgHpJkQMJ1OW0soqPXnJPCJvbAKB1mi4AH8y25hoAAP__&

**Comment by bo-ku-ra** [comment]
i want to eliminate 'dummy' lines. please improve d2!

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/pull/2221
