### ISSUE TITLE
[feature]Add the ability of modular d2 files

### ISSUE THREAD

**Issue by KevinZhang19870314** [terrastruct/d2#554]
If the diagram is more complicated, can we split it by module. For example:
I have a whole d2 file, which maybe contains A, B, C part of module, and each of the part are complicated. So I want to split up.
``` all.d2
A
B
C
```
I want to split it in a.d2, b.d2, c.d2, and then in all.d2, it maybe looks like:
```new-all.d2
include 'a.d2'
include 'b.d2'
include 'c.d2'

a -> b
b -> c
```

**Comment by alixander** [comment]
in the works! i don't think there's an issue yet so we'll use this to track. Thanks

**Comment by KevinZhang19870314** [comment]
Any feedback or progress for this?

**Comment by alixander** [comment]
@iAdanos kind of! import statements are not in yet, but you'll be able to compose multiple d2 boards in the next release

docs https://github.com/terrastruct/d2-docs/pull/94
example output: https://github.com/terrastruct/d2/pull/1088

**Comment by iAdanos** [comment]
@alixander, any news? :)

**Comment by alixander** [comment]
imports still haven't been worked on, but the concept of modular building blocks has an implementation in the form of https://d2lang.com/tour/composition/ .

appreciate the bumps though @iAdanos , helps us prioritize knowing there's demand for this feature

**Comment by bassmake** [comment]
another useful outcome of this feature is possibility to easilty share common styles via classes across multiple diagrams:

```
classes: {
  basic-service: {
    style: {
      ...
    }
  ...
}
```

```
include './styles.d2`

service-A: {
  class: basic-service
}
```

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/pull/1371

**Comment by mjbright** [comment]
Duplicate comment I just added to #1371

I don't think it is possible to import a set of class definitions using this syntax - please prove me wrong !

It would be really useful to be able to specify classes as a separate imported file.

If this is already possible then can we give an example of this (true modular import) in the documentation?
Otherwise, I could open an issue for this
