### ISSUE TITLE
d2 v 0.1.4 crashes on start

### ISSUE THREAD

**Issue by Vaelatern** [terrastruct/d2#590]
```
$ d2
panic:  flag redefined: dagre-nodesep

goroutine 8 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000136100, 0xc000133720)
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x626
github.com/spf13/pflag.(*FlagSet).VarPF(0xc000780000?, {0x19d85f0, 0xc000860188}, {0xc00051c140, 0xd}, {0x0, 0x0}, {0xc00003e340, 0x32})
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x151
github.com/spf13/pflag.(*FlagSet).VarP(...)
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).Int64VarP(0x0?, 0x1042fae?, {0xc00051c140?, 0xc000527480?}, {0x0?, 0x1042fae?}, 0x51?, {0xc00003e340?, 0xd?})
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/int64.go:46 +0x45
github.com/spf13/pflag.(*FlagSet).Int64P(...)
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/int64.go:71
oss.terrastruct.com/util-go/xmain.(*Opts).Int64(0xc0004e6680, {0x0, 0x0}, {0xc00051c140, 0xd}, {0x0, 0x0}, 0x1026ada, {0xc00003e340, 0x32})
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20221226181616-c04ce7d1b79f/xmain/opts.go:138 +0x1a5
oss.terrastruct.com/d2/d2plugin.(*PluginSpecificFlag).AddToOpts(0xc000136100?, 0xffd638?)
        /builddir/d2-0.1.4/d2plugin/plugin.go:46 +0xd1
main.populateLayoutOpts({0x19d9920?, 0xc0000a21e0?}, 0xc000274000)
        /builddir/d2-0.1.4/main.go:309 +0xc9
main.run({0x19d9878?, 0xc0004e66c0?}, 0xc000274000)
        /builddir/d2-0.1.4/main.go:78 +0x4a5
oss.terrastruct.com/util-go/xmain.(*State).Main.func1()
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20221226181616-c04ce7d1b79f/xmain/xmain.go:91 +0x71
created by oss.terrastruct.com/util-go/xmain.(*State).Main
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20221226181616-c04ce7d1b79f/xmain/xmain.go:89 +0x155
```

**Comment by alixander** [comment]
huh, can't reproduce on mine. will test on other machines, ty

**Comment by Vaelatern** [comment]
Just did so in a clean clone of the `v0.1.4` tag, running `go install -x oss.terrastruct.com/d2 oss.terrastruct.com/d2/cmd/d2plugin-dagre` and then `~/go/bin/d2`

**Comment by Vaelatern** [comment]
Ok, can only replicate when `d2plugin-dagre` is in `$PATH`

**Comment by Vaelatern** [comment]
is it just recommended not to build d2plugin-dagre separately?

**Comment by Vaelatern** [comment]
I think `d2` calls `d2plugin-dagre` if it's present, and with this code change: https://github.com/terrastruct/d2/compare/v0.1.3...v0.1.4#diff-2110f9f0c85550382324dd3be09fd535f7374a228ddf005d3f8adc4e92a05044R25-R42
my guess is d2 ends up somehow having the flags be present in both? I didn't think pflags shared between subprocesses... but for some weird reason that function is the only place where the flag is defined.

**Comment by Vaelatern** [comment]
```
// FindPlugin finds the plugin with the given name.
// 1. It first searches the bundled plugins in the global plugins slice.
// 2. If not found, it then searches each directory in $PATH for a binary with the name
//    d2plugin-<name>.
//    **NOTE** When D2 upgrades to go 1.19, remember to ignore exec.ErrDot
// 3. If such a binary is found, it builds an execPlugin in exec.go
//    to get a plugin implementation around the binary and returns it.
func FindPlugin(ctx context.Context, name string) (Plugin, string, error) {
        for _, p := range plugins {
                info, err := p.Info(ctx)
                if err != nil {
                        return nil, "", err
                }
                if info.Name == name {
                        return p, "", nil
                }
        }

        path, err := exec.LookPath(binaryPrefix + name)
        if err != nil {
                return nil, "", err
        }

        return &execPlugin{path: path}, path, nil
}
```

The comment and the code suggests the plugins must not be in the slice. Yet `d2 layout` finds the plugin.

I think the simple answer is "Stop building the dagre plugin separately" and the problem will go away.

**Comment by alixander** [comment]
i'm pretty sure we no longer need the `d2dagre-plugin`. it's bundled with d2 already. the use case i can think of would be like, if you want a trimmed down D2, you can build with `nodagre` build tag, and then still use dagre as a binary plugin. seems unnecessary though and safe to remove. @nhooyr

**Comment by nhooyr** [comment]
I'm ok with removing it but we should look into why this is happening still. There's a bug somewhere.

**Comment by nhooyr** [comment]
So I just installed `d2plugin-dagre` on the latest version of master and I'm unable to reproduce.

<img width="802" alt="Screenshot 2023-01-03 at 2 11 34 PM" src="https://user-images.githubusercontent.com/10180857/210449757-c2a15f81-5baf-46a0-a813-33af930edf5e.png">

Both the bundled dagre and the external dagre are picked up correctly.

**Comment by nhooyr** [comment]
Still not sure why I can't reproduce the issue though.

**Comment by alixander** [comment]
it's happening because i made a change for each plugin to declare their flags. and then `main` will register each one. if dagre is included twice, it'll try registering twice.

https://github.com/terrastruct/d2/pull/563

**Comment by nhooyr** [comment]
I'm fixin.

**Comment by nhooyr** [comment]
<img width="802" alt="Screenshot 2023-01-03 at 2 25 17 PM" src="https://user-images.githubusercontent.com/10180857/210451437-77099da4-77f0-4470-a8cd-194e3a7e512f.png">

darn we get two TALA warnings too.

Also I was able to reproduce @Vaelatern. My homebrew installation of d2 was taking precedence.

**Comment by nhooyr** [comment]
Or actually hold on that's related to my fix lol

**Comment by Vaelatern** [comment]
Huzzah! Thanks all!
