### ISSUE TITLE
border-radius has no effect

### ISSUE THREAD

**Issue by JakobTSutton** [terrastruct/d2#592]
The docs only provides this information:
```
# Only applicable to shapes, except ovals
# Integer betwen 0 and 20
border-radius: 4
```
I'm guessing it works like the CSS counterpart ["_border-radius CSS property rounds the corners of an element's outer border edge_"](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius)
However when applying this style to any shape (except the circle) nothing happens.
Example:
```
foo.shape: "square"
foo.style.border-radius: 20
```
[Edit] This was tested on the D2 Playground

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/pull/688

**Comment by exolab** [comment]
That still doesn't work for me in v0.1.16
```
dang: {
  style.border-radius: 20
}
```

**Comment by alixander** [comment]
@exolab does it not look like this?

https://play.d2lang.com/?script=SknMS7dSqOZSUAAbpocSB1YKRgZctVyAAAAA__8%3D&

when you run `d2 version` it shows 0.1.6? (not 16)

**Comment by exolab** [comment]
I was surprised to see it working on my mobile phone when I read your message. Went back and checked in Chromium: works fine. But it doesn't round the corners in Firefox 109.0.1 (64-bit) on my Arch Linux laptop.

**Comment by alixander** [comment]
oh interesting! Looks like it's a firefox-specific thing then. thank you for reporting this, will track here: https://github.com/terrastruct/d2/issues/777
