### ISSUE TITLE
Mouse Pointer overlaps tooltip

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#593]
I use a larger mouse pointer. (win10)
I can not read any tips.

x: {tooltip: "overlap"}

![image](https://user-images.githubusercontent.com/121328398/210257155-b19c9c5f-bd63-4da9-9878-d3897afc7ecd.png)

**Comment by alixander** [comment]
we just use svg `<title>`, which is implemented by the browser. it's a browser issue if they don't increase tooltip size to account for system mouse size. i don't really want to complicate by adding a javascript library for tooltips

if you hover over the date on github, will it also overlap?

<img width="598" alt="Screen Shot 2023-01-03 at 1 50 22 PM" src="https://user-images.githubusercontent.com/3120367/210447209-8227437b-b696-47c7-bd96-18e1e4b9ba2b.png">

**Comment by bo-ku-ra** [comment]
You were right.
i understood  it's a browser issue.

my solution;
x: {tooltip: "\noverlap\n\n"}
