### ISSUE TITLE
svg: update text rendering

### ISSUE THREAD

**Issue by ejulio-ts** [terrastruct/d2#596]
Why d2 uses `svg:foreignObject` instead of `text` for text objects?

From https://github.com/terrastruct/TALA/issues/15#issuecomment-1369159559
> I am on Linux (kernel 6.0) Just tested with firefox and chrome. It works indeed but fails with Inkscape, and applications that render svg with librsvg. Looking at the XML code, I notice that the Title text is implemented as svg:foreignObject rather than a standard text object https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

**Comment by alixander** [comment]
Because it's Markdown, and markdown uses HTML.

**Comment by alixander** [comment]
it'll continue to be in html. if you use markdown, that's a reasonable expectation. one day we can write a general markdown to svg converter for Goldmark, but not soon

**Comment by ejulio-ts** [comment]
yeah, makes sense.
Completely forgot of markdown support.
thanks

**Comment by uliw** [comment]
OK, it appears that at present HTML rendering will only work in browser windows, but virtually all other SVG applications (including Adobe Illustrator ) will ignore it. Maybe add a note in the docs. Thx

**Comment by alixander** [comment]
https://github.com/terrastruct/d2-docs/issues/52
