### ISSUE TITLE
Configurable per shape padding

### ISSUE THREAD

**Issue by hsuominen** [terrastruct/d2#599]
It would be convenient for large/complex diagrams to adjust the default padding per shape (ie. that labels just fit).

This was previously mentioned but not lifted to an issue:

> @alixander Hello, this looks pad on whole rending graph, is there a way to change padding of each box from the text label inside?
> 
> _Originally posted by @jinfagang in https://github.com/terrastruct/d2/issues/431#issuecomment-1346070758_

**Comment by jinfagang** [comment]
Yes, yes, I would definitely hoping for such feature, currently large graphs unable to clearly see if not scale it.

**Comment by gavin-ts** [comment]
related #692

**Comment by alixander** [comment]
i think this is no longer an issue after we decreased padding significantly in d2 0.2
