### ISSUE TITLE
As a user, I would like Links to open on a new tab so that I can interact with my diagrams better

### ISSUE THREAD

**Issue by kamok** [terrastruct/d2#600]
In the current behavior, my diagram exits and goes to the link rather than open a new tab.

I believe it's this bit of code https://github.com/terrastruct/d2/blob/master/d2renderers/d2svg/d2svg.go#L638

Here's an example:
https://stackoverflow.com/a/15551842/6174577

**Comment by alixander** [comment]
it's the default behavior on the web. there are widely known options for opening in a new tab (e.g. right click and open as tab, cmd + click), and this isn't true vice versa. if we make the default open in new tab, someone would open this issue in the other direction, but with no easy way to alleviate. 

that's my case for the current behavior, but i'll leave this open in case anyone wants to argue the flip side

**Comment by bo-ku-ra** [comment]
Expected the default behavior (in Windows)

target="_self"
- [protocol (I would use)]
  - mailto:
  - ms-word:
  - ms-powerpoint:
  - ms-excel:
  - im:
  - sip:
  - ftp:

target="_blank"
- [protocol]
  - http:
  - https:

Oh, they are a minority. but i hope so.

**Comment by exapsy** [comment]
I think it's better for links to stay the way they are for the reason of **links are used for presentation mode**. Presentation as in "Powerpoint" like presentation. So, from my understanding when the links feature was created, the thought behind was that it would be used for presentational reasons.

In the development mode though I haven't found links working at all. And at **development mode I would love links to open a new tab**.

**Comment by alixander** [comment]
won't do
