### ISSUE TITLE
Errors dont come with an timestamp/id or something useful

### ISSUE THREAD

**Issue by exapsy** [terrastruct/d2#608]
As a user I expect (at least) an error to come with a timestamped id so I can report the error to the devs in some way they can have a lead on.

As a developer of d2, I would expect to have a timestamped ID with information about the user inside to know when this error was thrown and from which user and potentially other meta information about the id.

Potentially, even include some information about the internal server error _if and whenever possible_.

### What the user sees

![image](https://user-images.githubusercontent.com/9019120/210996389-aa9a25ac-8ad8-4eb3-bef9-75d3a8266e8f.png)

### What the developer debugging this sees

![image](https://user-images.githubusercontent.com/9019120/210996866-1789318b-23d9-404a-998a-45c419f4171c.png)

![image](https://user-images.githubusercontent.com/9019120/210997051-22cc5fb9-cc28-4b96-92f9-4eb0d10d5ce0.png)

**Comment by alixander** [comment]
thank you @exapsy , we get pinged for these and it's historically been solveable without an explicit report. or just the rough timestamp is enough, e.g. "this afternoon".

please report Terrastruct app issues on Discord or through the app, this repo should only track open-source D2 issues. so will close this, but I do appreciate the continued reports 🙏
