### ISSUE TITLE
label overlap on arrows

### ISSUE THREAD

**Issue by sherlant** [terrastruct/d2#611]
Hi,
i have a problem with labels on arrows.
This is my code :
`k8s: Kubernetes                                                                              
 k8s.m1: k8s-master1                                                             
 k8s.m2: k8s-master2                                                             
 k8s.m3: k8s-master3                                                             
 k8s.w1: k8s-worker1                                                             
 k8s.w2: k8s-worker2                                                             
 k8s.w3: k8s-worker3                                                             
                                                                                 
osvc: opensvc                                                                   
osvc.vm1: VM1                                                                   
osvc.vm2: VM2                                                                   
                                                                                 
k8s -> osvc: keycloak                                                           
k8s -> osvc: heptapod                                                                                                                                                 
k8s -> osvc: harbor                                                             
k8s -> osvc: vault`

![image](https://user-images.githubusercontent.com/63449800/211057119-c420d0a3-dcd1-4fd4-a4ce-224dd57bd627.png)

there is a way to fix it ?
thx

**Comment by alixander** [comment]
thank you @sherlant , this will be fixed in the next release
