### ISSUE TITLE
option to disable sketching the background - opinions?

### ISSUE THREAD

**Issue by vfosnar** [terrastruct/d2#622]
Sketched diagrams look cool because they look like drawn on paper, but this does not apply to dark themes. I propose adding a new option that gives user the choice to disable it without giving up other things.

```
-s, --sketch    $D2_SKETCH  render the diagram to look like it was sketched by hand (default false)
    --sketch_bg $D2_SKT_BG  make the background look like it was sketched too (default true)
```

I had to trim `D2_SKETCH_BG` because of padding error but I don't think `$D2_SKT_BG` would be hard to understand

# with background (default)
![sketch](https://user-images.githubusercontent.com/13472046/211143980-6f198019-b11d-47c4-90b9-927b39c6c339.svg)

# without (new)
![sketch-no-bg](https://user-images.githubusercontent.com/13472046/211144014-2f7f7b55-8399-4515-907c-839c67134898.svg)

**Comment by alixander** [comment]
we actually have a plan to tackle darker fills: https://github.com/terrastruct/d2/issues/505

can you take a look and see if that'd work? @vfosnar

**Comment by vfosnar** [comment]
> we actually have a plan to tackle darker fills: #505
> 
> can you take a look and see if that'd work? @vfosnar

Oh, I didn't notice that. Thanks for pointing out, will look into it when I'll have time in about hour or two.

**Comment by vfosnar** [comment]
closing this as not required due to #505
