### ISSUE TITLE
render: respect prefer-color-scheme

### ISSUE THREAD

**Issue by vfosnar** [terrastruct/d2#623]
Using themes is one of the main "selling points" of this project. Most websites use `prefers-color-scheme` media query to determine what theme to show to the user, but this project doesn't support it.

We could achieve this by changing the rendering process so it sets classes to objects instead of writing colors from the theme directly. Then we can apply themes using CSS.

This will also make the codebase more readable because all theming will be on a single point. No more passing theme colors to render functions.

I have some free time so I can try to implement this, but I would like to get some feedback.

**Comment by alixander** [comment]
my concern is SVGs in non-browser contexts. If the SVG depends on CSS but there are SVG viewers/editors that don't implement a CSS engine, D2 would effectively be producing impure SVG files that are less portable. That's why I've kept the use of CSS classes to a minimum, and nonessential, and opted to use SVG attributes instead. 

Whether this is a real concern, I haven't actually investigated. E.g. if you apply fill and stroke with CSS, will it render the same on Adobe Illustrator, or other SVG viewers?

**Comment by vfosnar** [comment]
Okay I did some research @alixander

- CSS is an optional feature for SVG
- CSS must be supported in viewers that support CSS for other purpose. e.g. browsers
- CSS is required by SVG 2.0 but that is not something we care about because it's still a draft
- we already depend on CSS styling...

When rendering, the theme is applied using the `style` attribute instead of, for example, `fill` attribute for filling.

As the specification states:
> The ‘style’ attribute allows per-element style rules to be specified directly on a given element. When CSS styling is used, CSS inline style is specified by including semicolon-separated property declarations of the form "name : value" within the ‘style’ attribute.

([link](https://www.w3.org/TR/SVG11/styling.html#StyleAttribute))

**This means current SVGs do not render properly in viewers without CSS support.**

And because
> SVG implementations that support CSS are required to support the following
> - External CSS style sheets
> - Internal CSS style sheets
> - Inline style

([link](https://www.w3.org/TR/SVG11/styling.html#StylingWithCSS))

We know that every viewer that could render our SVG until today will be able to render it with additional internal CSS style sheet.

## Should this program depend on CSS?
Well, this is not something I should decide, but I can share my opinion.

Yes, it should. The primary use of SVGs is now in browser context and most other viewers render it properly AFAIK.

**Comment by vfosnar** [comment]
## How to implement multiple themes
There are two ways this can be achieved:
- user can specify what theme should be used for light preference and what theme should be used for the dark one
- every theme has colors for both light and dark themes

I personally prefer the former one because it allows us more flexibility.

We could split the options to
- primary theme (required) `--theme`
- dark theme (optional) `--theme_dark`

Implemented as something like

```css

selector {
    fill: ${primaryThemeColor};
}
```

And if user specifies the dark theme we could just add
```css
@media (prefers-color-scheme: dark) {
    selector {
        fill: ${darkThemeColor};
    }
}
```

This allows us to:
- render only light theme SVG - set primary theme to a light one
- render both light and dark theme SVG - set primary theme to a light one and dark theme to a dark one
- render only dark theme SVG - set primary theme to dark one
- not break export

> The media query idea is interesting. This came up in this issue: #159. Basically I didn't want the time of day to effect exports.

Export will not be affected as it will take only one theme as an argument. The CLI could throw an error if the dark theme was specified too.

**Comment by vfosnar** [comment]
btw I was talking about the export to PNG.

If you meant the `d2exporter.Export` function it will also not be a problem.
The current definition of the function is
`Export(ctx context.Context, g *d2graph.Graph, themeID int64, fontFamily *d2fonts.FontFamily) (*d2target.Diagram, error)`

but after the refactoring the themeID can be totally removed. At least I hope.

**Comment by alixander** [comment]
oh that's quite interesting. so D2's SVGs can potentially adapt to both light and dark preferences, and the preference of the author doesn't actually matter. 

i'm +1 to this proposal.

applying classes and then styling once should also cut down on overall file size.

**Comment by vfosnar** [comment]
Damn, I'm so happy you approved it. My undiagnosed ADHD forced me to not do anything but to refactor all day :D

- [ ] `d2exporter`
  - [x] remove all references to theme values
  - [ ] allow user-defined colors
- [ ] `d2svg` theming using classes
  - [x] Shapes
  - [ ] Connections
- [ ] `sketch`

Think I can finish it around tomorrow but I can't promise anything.

**Comment by vfosnar** [comment]
Damn, almost done.

Everything looks the same... that's a good thing!

The theme is still hardcoded but now in an internal style sheet in one place. This is because I will change the way it's being loaded to support the primary and dark theme model.

I will finish and polish my code tomorrow and will do a review of my changes. Next thing that's on my radar is fixing #505.

Also frick, it's around midnight and I have a math test tomorrow... wish me luck :D

![arrowheads](https://user-images.githubusercontent.com/13472046/211223993-f97c0365-34c1-4b63-bf01-12fd13734f38.svg)
![class](https://user-images.githubusercontent.com/13472046/211223996-42ef5d43-f59e-4918-9d70-dcd86159a88d.svg)
![color](https://user-images.githubusercontent.com/13472046/211223997-8c8e8039-335a-4d36-bcce-729d5330efba.svg)
![containers](https://user-images.githubusercontent.com/13472046/211223998-33a565bf-2fa7-4453-926a-d50fec082ad0.svg)
![latex](https://user-images.githubusercontent.com/13472046/211223999-2c302ee6-fd91-4ca5-83ec-b9b92e9d11f5.svg)
![sequence](https://user-images.githubusercontent.com/13472046/211224000-d798faed-cdce-465f-9628-7bdb07f1938f.svg)
![sql](https://user-images.githubusercontent.com/13472046/211224003-5475c515-1fea-4fd5-b251-29ef1edbe234.svg)

**Comment by vfosnar** [comment]
provided base to build on, will continue this in #613

**Comment by alixander** [comment]
@vfosnar awesome!

> I have a math test tomorrow

One of the main authors of D2 just [did open-source](https://github.com/nhooyr/websocket) in high school and skipped the whole college thing and he's a beast. Math tests are overrated! 😉
