### ISSUE TITLE
label both ends of a connector (feature)

### ISSUE THREAD

**Issue by bbrendon** [terrastruct/d2#626]
Would be great to be able to label both ends of a connector. Also the middle as well would be a bonus.

**Comment by alixander** [comment]
i'm not sure what you mean. is it different from https://d2lang.com/tour/connections#arrowheads ?

**Comment by bbrendon** [comment]
Like this

![image](https://user-images.githubusercontent.com/6364477/211180584-15bb4d22-4604-4b51-85c1-e030a5a468f5.png)

**Comment by alixander** [comment]
https://play.d2lang.com/?script=SlTQtVNIslKo5lJQQHedlYIPyO8KYK8oOCoUZ6akcikooFuAqswJoqyWCxAAAP__

**Comment by bbrendon** [comment]
I clicked on the link and I see the image below. Not like the image above.

![image](https://user-images.githubusercontent.com/6364477/211186790-b6c3faaf-30e9-4e65-97c0-862dc15cbbde.png)

**Comment by alixander** [comment]
weird, it looks like Github left out part the URL for some reason. sorry about that, can you try this?

[https://play.d2lang.com/?script=SlTQtVNIslKo5lJQQHedlYIPyO8KYK8oOCoUZ6akcikooFuAqswJoqyWCxAAAP__](https://play.d2lang.com/?script=SlTQtVNIslKo5lJQQHedlYIPyO8KYK8oOCoUZ6akcikooFuAqswJoqyWCxAAAP__)

**Comment by bbrendon** [comment]
Sorry I missed that! THANKS!
