### ISSUE TITLE
feature request: add support for inline latex within a markdown block

### ISSUE THREAD

**Issue by TSSlade** [terrastruct/d2#643]
Sometimes it's preferable to use lighter-weight markdown for a block, but still slip in a bit of latex (e.g. `$t_1$` -->  $t_1$ and `$t_2$` --> $t_2$ for two time periods in an experimental design). If such an inline use of latex currently supported, it's not very clear how to make it happen.

If it's _not_ (yet) supported, it would be lovely to have it added.

**Comment by alixander** [comment]
Not and won't support, as it's quite unconventional expectation (e.g. GitHub doesn't support it)
