### ISSUE TITLE
the initial display to fit the window size

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#645]
I appriciate for your providing v0.1.5.
I use it everyday :-)

recently, i think the following are good choices.
because almost all PC's screen height is shorter than its width.

*.svg
-----
>//  if (width > height) {
>//    if (width > window.innerWidth) {
>      ratio = window.innerWidth / width;
>//    }
>//  } else if (height > window.innerHeight) {
>//    ratio = window.innerHeight / height;
>//  }
>  if (ratio) {
>    svgEl.setAttribute("width", width * ratio - 16);
>    svgEl.setAttribute("height", height * ratio - 16);
>  }

Could i choice these options? 
(fitting size: height only/ width only/ both)

**Comment by alixander** [comment]
can you say what the issue is that you're proposing the solution to?

**Comment by bo-ku-ra** [comment]
- initial display is often too small. (vertical and horizontal large diagrams)
- my colleagues are used to vertical scrolling.
  -  many laptop users (narrow screen)
  - scrolling horizontally is difficult.

both       : small and medium size
width only : large size (direction:up/down)
height only: large size (direction:left/right)

**Comment by bo-ku-ra** [comment]
could i get alternatives?

**Comment by bo-ku-ra** [comment]
i'm still editing the output SVG file before sending it to my colleague. (v0.2.1)
```
ratio = window.innerWidth / width;  
svgEl.setAttribute("width", width * ratio - 16);
svgEl.setAttribute("height", height * ratio - 16);
```
