### ISSUE TITLE
Darge layout shows line child to child instead parent to parent

### ISSUE THREAD

**Issue by PKasman** [terrastruct/d2#646]
Snippet:
Chocolate.Chip.Cookies
Chocolate -> Chocolate: groups

expecting the line from Chocolate to Chocolate, but Darge shows line Cookies to Cookies

![image](https://user-images.githubusercontent.com/27642971/211817029-f3aa3ae4-161f-4421-ab9b-d737e3e61023.png)

ELK is correct:

![image](https://user-images.githubusercontent.com/27642971/211817219-82389704-d3d1-477b-bf95-641970ed612b.png)

**Comment by alixander** [comment]
ty for reporting another instance. we'll use an existing issue to track: https://github.com/terrastruct/d2/issues/71
