### ISSUE TITLE
nested lists in markdown render slightly mismeasured

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#647]
probably some padding/margin we aren't factoring in when a nested list appears. 

https://play.d2lang.com/?script=4qqwUqjJTeFSUFBWyEit5FJQ0FUogTAUFAz1IOwaLkAAAAD__w%3D%3D&

also, only with headers? weird

notice the "y"

![Screen Shot 2023-01-11 at 11 05 47 AM](https://user-images.githubusercontent.com/3120367/211895657-06354446-3745-42d6-b960-a225b63609e1.png)

**Comment by vfosnar** [comment]
[looks like it's broken again?](https://github.com/terrastruct/d2/blob/master/e2etests/testdata/stable/li3/dagre/sketch.exp.svg)

**Comment by alixander** [comment]
@vfosnar where's the breakage? can you screenshot what you're seeing?

**Comment by vfosnar** [comment]
Oh, looks like it's broken in FF but works in chromium.

## Firefox (110.0 64-bit)
![image](https://user-images.githubusercontent.com/13472046/219957028-53a7e023-a187-45c4-83cb-c038d116ea7e.png)

Also connections are for some reason not showing on the screenshot but are in fact rendered.

## Chromium (Brave Version 1.48.164 Chromium: 110.0.5481.100 64-bit)
![20230219_16h12m48s_grim](https://user-images.githubusercontent.com/13472046/219956934-8756f242-93d2-4b25-8701-468d28db4573.png)
