### ISSUE TITLE
self-messages between different spans in Sequence diagram is broken.

### ISSUE THREAD

**Issue by balazshq** [terrastruct/d2#657]
Hello,

I'm trying to create a self-message, but between different spans, here's an example:

  ```
  shape: sequence_diagram
  a: A
  b: B
  
  a.sp1 -> b: foo
  a.sp1 -> a.sp2: redirect
  a.sp2 -> b: bar
  ```

On the playground some strange output was generated, on my local machine got the following error message:

  ```
  err: failed to compile: TypeError: Cannot read property 'type' of undefined at n (<eval>:48:12(2))
  error Command failed with exit code 1.
  ````

I would like something like this, but the redirect would point from sp1 -> sp2

  ```
  shape: sequence_diagram
  a: A
  b: B
  
  a.sp1 -> b: foo
  a -> a: redirect
  a.sp2 -> b: bar
  ```

Regards
Balazs

**Comment by alixander** [comment]
thank you @balazshq, this is fixed and will be included in next release
