### ISSUE TITLE
Edge overlaps node

### ISSUE THREAD

**Issue by BarryNolte** [terrastruct/d2#662]
Linux version 5.15.0-57-generic (buildd@lcy02-amd64-110) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) SMP Thu Nov 24 13:43:17 UTC 2022

D2 v0.1.5
---
Run D2 on file containing the following:

```code
f -> g -> h -> g -> f - h

g: { t -> n }

```
It renders like this:
![image](https://user-images.githubusercontent.com/4474173/212434602-e8ff3cd0-7faf-4cac-90ff-b284696bc89b.png)

I'm not sure how much of a bug this is, or if it's by design, but I like my edges to go around my nodes.

**Comment by MariusAlbrecht** [comment]
seems to be an engine related issue:
dagre [playground](https://play.d2lang.com/?script=SlPQtVNIBxEZcFaagq5CBhdXupVCdQmIn1fLBQgAAP__&layout=dagre&theme=0&sketch=0&)
![image](https://user-images.githubusercontent.com/64852250/212927968-facd54cd-ae90-4d1f-a095-c04636cc38e5.png)
elk [playground](https://play.d2lang.com/?script=SlPQtVNIBxEZcFaagq5CBhdXupVCdQmIn1fLBQgAAP__&layout=elk&theme=0&sketch=0&)
![image](https://user-images.githubusercontent.com/64852250/212928022-908f7e56-13ab-4f3a-bdac-993fc6aa6028.png)
tala [playground](https://play.d2lang.com/?script=SlPQtVNIBxEZcFaagq5CBhdXupVCdQmIn1fLBQgAAP__&layout=tala&theme=0&sketch=0&)
![image](https://user-images.githubusercontent.com/64852250/212928086-fc135c98-df70-45f4-ad79-67c8aa810b92.png)

**Comment by BarryNolte** [comment]
![image](https://github.com/user-attachments/assets/4d7cca48-717a-4ff6-ad91-b4e064e7fa70)

The 'g' label is now outside it's node, and the fill is incomplete around the arrow from 't' to 'n'.

**Comment by alixander** [comment]
That `g` label position is intentional. the fill incomplete is weird, but not reproducible on my side
![d2 (17)](https://github.com/user-attachments/assets/7ef2f509-5cf5-44ce-b941-3afa8ab25d29)
