### ISSUE TITLE
Feature: ability to import d2 files and reuse common components

### ISSUE THREAD

**Issue by shikharid** [terrastruct/d2#670]
Ability to import d2 files inside another and ways to inherit styling will be a very useful feature for large scale projects.

Something like this should make:

- maintaining these diagrams easier
- teams will be able build a base set of components with custom styling, common lingo and shapes and reuse them

Also conforms to how software teams operate, in a declarative way. 
Some leads create a set of guidelines on how to document stuff and the team _follows_ it.

We will need some syntax for defining shape styling (which are not to be rendered) and ability to inherit/override them in nodes

Something like:

microservice-base.d2
```
d2-templates: {
  microservice-server: {
    shape: rectangle
    style: {
      stroke: "#53C0D8"
      stroke-width: 5
      shadow: true
    }
  }
  
  microservice-db: {
    shape: cylinder
    style: {
      stroke: "#53C0D8"
      stroke-width: 5
      shadow: true
    }
  }
}

```

my-monolith.d2
```
import: ./microservice-base.d2

my-monolith: {
  shape: microservice-server
  my-monolith-db {
    shape: shape-microservice-db
  }
}

```

**Comment by iAdanos** [comment]
+1, since it's the painkiller for complex diagrams

**Comment by iAdanos** [comment]
I think it's related to https://github.com/terrastruct/d2/issues/554
