### ISSUE TITLE
idea: rounded connections?

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#673]
maybe border-radius can be set for connections too, and determines the rounding of bend corners.

<img width="217" alt="Screen Shot 2023-01-16 at 1 26 49 PM" src="https://user-images.githubusercontent.com/3120367/212768040-0aee3f8b-1090-4a12-ba58-bcce9d98a5c8.png">

**Comment by donglixiaoche** [comment]
@alixander i'd love to try working on this issue

**Comment by alixander** [comment]
@donglixiaoche awesome!

I'd probably start by adding a test:

https://github.com/terrastruct/d2/blob/a41f5c9cfb3981f5374e77568cc2c24530c8ce69/e2etests/stable_test.go#L2039

Get a delta: `./ci/e2ereport.sh -delta -test-case=border-radius`

And then keep making changes to https://github.com/terrastruct/d2/blob/master/d2renderers/d2svg/d2svg.go, rerunning the above to see what's changed, until the connections look good.

**Comment by donglixiaoche** [comment]
@alixander 
after reading some codes, altough the description above is quite concise, there are lots of details i want to confirm with you.
so, for drawing connection between shapes, basiclly there are those steps:
1. use the input script to calc layout(by darge/elk layout engine), then we can get route path(points) of those connections
2. convert these points to the actual points used by a curve
3. construct the svg path string of these curves(bezier curve)

and below are my questions:
1. in which condition, could a connection not be a curve?
2. should i consider ELK graph as well?
3. suppose our user set `border-radius: 3px` to a connection, how can we apply this to a bezier curve? by set an offset to those points that draw the curve?

**Comment by donglixiaoche** [comment]
@alixander cool, i will just look at ELK tests then, thx!
