### ISSUE TITLE
API error - ELK layout - self-referencing container inside container

### ISSUE THREAD

**Issue by eremef** [terrastruct/d2#675]
How to reproduce (on ELK):
https://play.d2lang.com/?script=qrBSqOZSUEjkUlBI4qrl4qrQS1TQtVOo0EvkAgQAAP__&sketch=1&layout=elk&theme=104&

Works for Dagre and TALA

**Comment by alixander** [comment]
thank you @eremef , this has been fixed. it's deployed on playground and will be in the next release of D2.
