### ISSUE TITLE
bug: snapshot tests broken in Go 1.19

### ISSUE THREAD

**Issue by a-h** [terrastruct/d2#678]
Go 1.19 added a new field called `OmitHost` into the `url.URL` type - https://github.com/golang/go/issues/46059

The snapshots on disk don't include the `OmitHost` field, because they were generated with Go 1.18, so if you run the tests on Go >= 1.19, the tests will fail due to the `OmitHost` field appearing.

If I update the snapshots, then it will fail for everyone using Go < 1.19.

Since the `OmitHost` field isn't important for this use case, maybe the comparison could be updated to ignore the field.

```
       --- FAIL: TestE2E/regression/elk_img_empty_label_panic (0.09s)
            e2e_test.go:175: unexpected error: diff (rerun with $TESTDATA_ACCEPT=1 or $TA=1 to accept):
                --- a/testdata/regression/elk_img_empty_label_panic/dagre/board.exp.json
                +++ b/testdata/regression/elk_img_empty_label_panic/dagre/board.got.json
                @@ -29,6 +29,7 @@
                         "Host": "icons.terrastruct.com",
                         "Path": "/infra/019-network.svg",
                         "RawPath": "",
                +        "OmitHost": false,
                         "ForceQuery": false,
                         "RawQuery": "",
                         "Fragment": "",
                @@ -79,6 +80,7 @@
                         "Host": "icons.terrastruct.com",
                         "Path": "/infra/019-network.svg",
                         "RawPath": "",
                +        "OmitHost": false,
                         "ForceQuery": false,
                         "RawQuery": "",
                         "Fragment": "",
```

**Comment by alixander** [comment]
yeahh there's some discussion here: https://github.com/terrastruct/d2/pull/577

basically, go 1.19 has a new fmt that breaks a bunch of our ascii art comments, so we haven't been upgrading. being 2 minor versions behind is harder to swallow though so it's a TODO to convert all our ascii art to use block comments to preserve. we'll use this issue to track, thank you.

**Comment by alixander** [comment]
task is to fix ascii arts
