### ISSUE TITLE
render: border-radius should work with class and sql-table

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#689]
currently it's implemented for rectangles, but class and sql-table are rectangular in shape, so should apply to those too

**Comment by donglixiaoche** [comment]
@alixander  i'd love to work on this issue

**Comment by alixander** [comment]
@donglixiaoche go for it! i think the only trickiness here is that the header will need to have border-radius on one side (the top). which is kind of hard in SVG. https://stackoverflow.com/questions/34923888/rounded-corner-only-on-one-side-of-svg-rect

it'll be an annoying task for sure. feel free to look into it and if you decide it's too annoying, can grab a different one

**Comment by donglixiaoche** [comment]
copy, glad to take this challenge
