### ISSUE TITLE
Images: width and height are not taken into account (when set under 128px)

### ISSUE THREAD

**Issue by mrtryhard** [terrastruct/d2#699]
**D2 compiler version:** v0.1.6
**Browser:** Firefox 109.0
**Summary**:
When creating a diagram with a shape of type `image`, the parameter `width` for instance is not taken into account. 
**Workaround**: 
Use a container shape instead

## Demo code
```
not_working: "Not working" {
    shape: image
    icon: ./my_svg.svg
    width: 25
}

failing_too: "Failing too" {
    shape: image
    icon: ./my_png.png
    width: 20
}

failing: "Failing" {
    shape: image
    icon: ./my_ico.ico
    width: 50
}
```
I unfortunately cannot provide icons. 

## Actual result (code)

```html
<g class="shape">
  <image href="data:image/png;base64,<SOME_BASE64>" x="2" y="0" width="128" height="128" style="fill:#FFFFFF;stroke:#0D32B2;stroke-width:2;"></image>
</g>
<text class="text-bold" x="66.000000" y="149.000000" style="text-anchor:middle;font-size:16px;fill:#0A0F25">Failing too</text>
```

Notice that `width` and `height` just match the image's default sizes, `128x128`. If I replace the sizes and adjust the label position, it works fine.

**Comment by alixander** [comment]
oh we have a default size of 128 pixels
https://github.com/terrastruct/d2/blob/13d202b84b10468f2a4748dbed3c498592287a59/d2graph/d2graph.go#L728

and it uses the max of the default with what was provided
https://github.com/terrastruct/d2/blob/13d202b84b10468f2a4748dbed3c498592287a59/d2graph/d2graph.go#L1135

I think this is a mistake though, you should be allowed to go below the default. Thank you, will file this as a bug but hopefully this comment lets people workaround for now
