### ISSUE TITLE
winget package release

### ISSUE THREAD

**Issue by MariusAlbrecht** [terrastruct/d2#700]
somewhat related #154 

The (easiest) way to add a package to winget is to pr a valid manifest to the main microsoft/winget-pkgs repo.
I have set up a fork on my github [here](https://github.com/MariusAlbrecht/winget-pkgs/tree/master/manifests/t/Terrastruct/D2) which also contains manifests for the 0.1.5 and 0.1.6 releases (which _should_ work)

I think having d2 as a package in winget has no downsides, 2(or 3) things still need to be sorted out imo:

1. I have basically no idea of how installers on windows work and whether the configs I have made are any good. I used [wingetcreate](https://github.com/microsoft/winget-create) to generate the manifests. They are valid, and actually do install fine on my system however I'd like to have someone
    - confirm the other metadata I entered
    - take a look at the installer, because while the install works, I get a security warning saying the installer is of an unknown publisher and potentially malicious (which oft isnt nice to see). Note for testing: a package can be installed from a local manifest and not the remote repo like [so](https://github.com/microsoft/winget-pkgs#locally)
2. how the latests releases can be released there as well. Doing it manually wouldnt actually be too much of a hassle. I think using wingetcreate as part of your normal release script is still something to consider because its just so easy. wingecreate's update command can basically do all the work. More specifically `wingetcreate.exe update Terrastruct.D2 --urls https://github.com/terrastruct/d2/releases/download/v<version>/d2-v<version>-windows-amd64.msi --version <version> --submit --token <token>` would automatically create the manifests of the .msi windows installer from the github releases (and also do the pr to the main repo).
here \<version> would need to be substituted with e.g. `0.1.6` for the latest realease 
and \<token> for a github acces token, so that the tool can automatically create a pr to the main repo
3. What installers actually get put on there. Up until now I've only added the amd64 installer because that has an executable in the github releases. Could the arm64 one also get an executable? Can the tag.gz file also be added as an installer? idk

**Comment by MariusAlbrecht** [comment]
note: while I also added the new 0.1.6 into my repo I really dont know if things are set up correctly (and if winget upgrade would work). Doing it locally doesnt work but im not sure if thats because something is configured incorrectly or because winget searches the remote repo for a new release (and naturally doesnt find one becasause d2 isnt added at all)

**Comment by MariusAlbrecht** [comment]
added 0.2.0 to my fork of the package repo
ps: no new on this?

**Comment by alixander** [comment]
sorry for the delay @MariusAlbrecht. it seems like a nontrivial investigation and we only just learned enough about windows installs to get the installer build automated. once the backlog of higher priority things clears up more, we'll get to this!

**Comment by MariusAlbrecht** [comment]
npnp. Just a heads up as well because I just noticed (and yall apparently havent as well): Someone else did push some versions (0.1.6 and 0.2.1) into the main repo https://github.com/microsoft/winget-pkgs/commits/master/manifests/t/Terrastruct/D2

**Comment by alixander** [comment]
oh, hah awesome! i had not noticed. i think this can be closed then. appreciate your efforts anyway, ty @MariusAlbrecht 🙂
