### ISSUE TITLE
Question: replacing PlantUML with D2, limitations?

### ISSUE THREAD

**Issue by rogeralsing** [terrastruct/d2#703]
I am building a tool for OpenTelemetry observability.
I'm using PlantUML to visualize trace data.
There are however some pretty bad limitations there, e.g. PlantUML cannot handle large sequence diagrams.
And for component diagrams, the lines/arrows often look strange.

D2 looks like a very nice alternative, so I thought I'd ask before I start building anything.
Are there any limitations in the size of the diagrams for D2?
and maybe someone can give a hint if it would be possible to generate diagrams similar to the ones attached here?:

<img width="1440" alt="Skärmavbild 2023-01-21 kl  13 51 28" src="https://user-images.githubusercontent.com/647031/213867890-f6798de4-b2de-4fd2-afaf-c263f5d11bdc.png">
<img width="1440" alt="Skärmavbild 2023-01-21 kl  13 51 38" src="https://user-images.githubusercontent.com/647031/213867896-8aab26c3-cb3f-44cb-b1ce-f2f5caa5a8d5.png">

**Comment by MariusAlbrecht** [comment]
the component diagram should be quite easy: Take a look e.g. at my try to replicate your screenshot in the playground [here](https://play.d2lang.com/?script=lFTBauswELz7K_QDT_B6NMEQkh56M6H01MuiLo1AkVxpnZK_Lys3ckTqSD4Za2dmZ3aR0vha4Tl9Ewg8yei-Fe4MpnnFQFK509CKzYa_zqKlrnu3O7AHDAN82zftaQSzVeR8mBlyCTG1Ef86UYFVZgyEvhW9d-TkbvqVzAzXotQfaEnThU0CE9lgD540p3v5rUbJO47cKtJnYOABv0YMlCCDAYUntPS3bm_gMtVz5UR7II3q6DLVZ3V0uQxDZK_tZ36y19hUhODx1hgqruBW6MHMVunM0dbTYv5IizdAZs9DK_4_3WiWEQtdF5lXK6V6mlQJOO-mhIzpq_vebWiFk_XctNA65F7jIvAnAAD__w%3D%3D&layout=elk&)
![image](https://user-images.githubusercontent.com/64852250/213883874-87550718-07f6-40ea-ab5c-c45a9a800b64.png)
dark themes and more options in terms of theming _should_ also come quite soon

with the sequence diagram I'm not sure. I dont really use them so I cant give you an opinion there

**Comment by alixander** [comment]
> Are there any limitations in the size of the diagrams for D2?

yes. it's not tested past the hundreds of nodes, so it depends on what you mean by large. 

With sequence diagrams, it's rule based instead of search, so that has no limitations on size and will run fast. We're tuning the padding/font-sizes to make it more legible for this next release.
