### ISSUE TITLE
style.font-opacity

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#704]
i can see '+' and '=' on 0.1.5
i can't see them on 0.1.6

ex.
https://play.d2lang.com/?layout=dagre&script=jJBNisMwDIX3PoXIdhjbyWQxUZg5RC9QQmJUl_iH2ATSkrsXpW3orl1JPJ70-N5eH8LE9OJQwfc_LAjFVwHXLUE-8BB0C3dl7wyh_l0F29nNzAjWdWRa4CIRTjnHhEoN1dh5kn1wyjpSY6Ago6dVXN7fbmKSXUomp8GMdjbTsr3qg4vWUzrOlSKTa2_yc5aNLl93_dPoRp4jrWJhRM79-xzxFgAA__8%3D&

**Comment by alixander** [comment]
that's intended. the label of an opacity 0 shape should adopt its opacity. you can achieve the effect this way:

https://play.d2lang.com/?layout=dagre&script=hJDNqoMwEIX38xSDW7lJ9N6NudiH6AsU0TBNMT-YIFXJu5eILV0UujkznGFm-M4rPolTpodzjT8nLLMsWdosq8QNEPd_7ICVKCBBeUwyrcSo7hEStJ9MWCQWBW6Hq01H6h9z2hKvMfogOR_qsbPEeme4NsRHR455SwnW77u7GVgXgophUKOe1bTsp3pnvLYULnPNScU_q-KzVo2o3nvx24iG3TwleAQAAP__&

does that work?
