### ISSUE TITLE
API error in playground

### ISSUE THREAD

**Issue by MariusAlbrecht** [terrastruct/d2#705]
https://play.d2lang.com/?script=hJJBSsAwEEX3OcW_gD1AFkIpLtyVIm5lSAcbSJOaTJUivbskTW1Xusv8_Jn3E2Ym6zW-FVACayT-WNkbfhstvUeaFSCcROOFk_wWueGvFiByWujLa3Tkh-P8aqOs5FojISYF7Aowbk3CMWn0MUhoulo3FXfd_4-0I3uxsmn0FMXmpXiuUmEW0-LI8Mxebq7e0XaIl4_NFDSezBQu7QTg4fE-pzViPykPGnKsknuvX5Wt5xvUrn4CAAD__w%3D%3D&layout=tala&sketch=1&

error only happens with sketch toggled.
Even without sketch on there's some pretty wonky behaviour (could also be just me doing forbidden stuff somehow, I'm dont know d2 sequence diagrams very well)

**Comment by alixander** [comment]
ah, yeah the compiler should prevent nested  sequence diagrams. is it deliberate for a use case you have or just inducing edge cases? either way, ty for finding and reporting this! @MariusAlbrecht

**Comment by MariusAlbrecht** [comment]
I was trying to replicate the screenshot given in #703 :)
