### ISSUE TITLE
Self connection on shape with markdown child is rendered incorrectly

### ISSUE THREAD

**Issue by Barabas5532** [terrastruct/d2#708]
I was trying to create some basic state machine diagrams with mardown in the states to describe side effects, and came across this bug:

```
x -> x

x.text: |md
  text
|

y -> y

y.text: |md
  text
|

y.shape: circle
```
![d2](https://user-images.githubusercontent.com/28671465/213922761-eef3c594-9ab6-4dd9-b435-a90d276a9516.svg)

**Comment by alixander** [comment]
Thanks! 

This looks to be the same issue as https://github.com/terrastruct/d2/issues/707, so will close in favor of that. 

In the meantime, a different layout engine works: https://play.d2lang.com/?script=qlDQtVOo4OKq0CtJrSixUqjJTeFSUACxuWq4uCpBspVcXJXYZfXAnrRSSM4sSs5J5QIEAAD__w%3D%3D&layout=elk&
