### ISSUE TITLE
d2 fmt: Accept multiple files to be formatted

### ISSUE THREAD

**Issue by nhooyr** [terrastruct/d2#718]

**Comment by alixander** [comment]
probably can group with this (https://github.com/terrastruct/d2/issues/13). if u can allow multiple files to be formatted, we should allow multiple files to be rendered too

**Comment by nhooyr** [comment]
Nah this is way simpler/quicker. Just a simple for loop and we're good.

**Comment by bo-ku-ra** [comment]
FYI. i run the following on Windows now

[file exists]
 c:\d2\test.d2
 c:\d2\aaa\test2.d2

[cmd.exe]
 c:\d2> ```for /r %i in (*.d2) do d2.exe fmt "%i"```
