### ISSUE TITLE
Issue processing d2 with tala

### ISSUE THREAD

**Issue by judepayne** [terrastruct/d2#720]
Hi,
this piece of d2:

````
Securities:   {
  app8664: Globe-X
  app8665: Ark Crypto
  app8669: Risk Sheet
  app8670: Credit guard
  app8672: Flame
}
Finance:   {
  app8666: Booking Flash
}
Corporate:   {
  app8667: Attunity
  app8673: Trade Aid
}
Funds:   {
  app8668: Flame
}
Equities:   {
  app8671: Acmaze
}
Corporate.app8673 -> Funds.app8668
Securities.app8672 -> Securities.app8664
Securities.app8672 -> Corporate.app8673
Funds.app8668 -> Securities.app8664
Securities.app8670 -> Funds.app8668
Finance.app8666 -> Funds.app8668
Corporate.app8673 -> Funds.app8668
Equities.app8671 -> Securities.app8672
Funds.app8668 -> Corporate.app8667
Securities.app8670 -> Securities.app8669
Securities.app8664 -> Securities.app8672
Corporate.app8667 -> Equities.app8671
Securities.app8664 -> Securities.app8665
Securities.app8672 -> Funds.app8668
Securities.app8669 -> Securities.app8664
Corporate.app8673 -> Funds.app8668
Funds.app8668 -> Securities.app8670
Funds.app8668 -> Corporate.app8673
Corporate.app8673 -> Securities.app8665
Securities.app8669 -> Securities.app8670
````

causes a crash with the Tala layout engine, but not with the default (Dagre) engine.

**Comment by alixander** [comment]
ty @judepayne, it's fixed now. pretty interesting graph that surfaces some other improvements too. live on playground (cutting new TALA release now)

https://play.d2lang.com/?script=jFHNboJAEL7vU8wLaFBxV-bQhJLae-2h1y1MdIOydFkOtvHdG5oVhYXKcb58-f5mR2ltlFVUIfwwAFmWG85DhNej_qTZRwutEWKTQ2LOpdUtGiG8qSqH3YHIXlERICSGMmVhX0uTtfgSYXuUJ2IXtlWFLFK6N-UIz1rnqtg3rOrALizRptRG2g5PIMTW1oWy51Z5hfBuZEYQq6xRr4usU2hzc375qvt9xQIhTk_ym-49504aZk_wJzh3Wuw2muMsG04f5eEI0XNgHfmpWoEfzK3qbu4TJpS77uMYi6E4YulH7klzMZLYqxZ5RB6OmHoeDa8feKIcX4-85_9f82jkPxOmffhmETzcVayGnSbUG44uAvYbAAD__w%3D%3D&layout=tala&

**Comment by judepayne** [comment]
Great!
