### ISSUE TITLE
How the org convert to d2

### ISSUE THREAD

**Issue by arstum** [terrastruct/d2#727]
How the .org and .md file code convert to d2 code.
I usually write note with org-roam, when I hope to understand the relation between the node, I must rewrite all the note.

**Comment by alixander** [comment]
I'm not 100% sure what you're asking, but perhaps you could try this? https://github.com/xcapaldi/ob-d2

**Comment by arstum** [comment]
> I'm not 100% sure what you're asking, but perhaps you could try this? https://github.com/xcapaldi/ob-d2

Org-roam file convert to d2 format, not d2-compile. I's before compile.

**Comment by alixander** [comment]
sorry I still don't understand. I looked at your profile and if you're more comfortable writing Chinese, that's fine too.

**Comment by amb007** [comment]
Perhaps the OP meant, use `|org` like you use `|md`?
