### ISSUE TITLE
proposal: set background color

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#734]
background:#000000
 or
background:black

-------------
.svc (default)
-------------
&lt;?xml version="1.0" encoding="utf-8"?>
&lt;svg
id="d2-svg"
style="background: ```white```;"
xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
width="138" height="376" viewBox="-12 -12 138 376">&lt;style type="text/css">
&lt;![CDATA[
.shape {
  shape-rendering: geometricPrecision;
  stroke-linejoin: round;
}

----------------------
background:#000000
 or
background:black
----------------------
&lt;?xml version="1.0" encoding="utf-8"?>
&lt;svg
id="d2-svg"
style="background: ```#000000 ``` ;"
xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
width="138" height="376" viewBox="-12 -12 138 376">&lt;style type="text/css">
&lt;![CDATA[
.shape {
  shape-rendering: geometricPrecision;
  stroke-linejoin: round;
}

**Comment by bo-ku-ra** [comment]
---------
matrix.d2
---------
background:```black```
x{ style.stroke:lightgreen; style.font-color:lightgreen; style.fill:black; }
y{ style.stroke:lightgreen; style.font-color:lightgreen; style.fill:black; }
x -> y{style.stroke:lightgreen}

![image](https://user-images.githubusercontent.com/121328398/215252108-4af23a37-44ed-4df2-83c6-024a9a773445.png)

**Comment by alixander** [comment]
for the background color issue, i'm going to close in favor of: https://github.com/terrastruct/d2/issues/663

for the changing other elements, I believe you're just looking for a dark theme, which is being worked on: https://github.com/terrastruct/d2/pull/613
