### ISSUE TITLE
panic: layout-flags(dagre) 

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#738]
d2 0.1.6 on Windows

d2.exe layout dagre ```--dagre-nodesep``` 50 file.d2
-> panic:  flag redefined: dagre-```nodesep```

d2.exe layout dagre ```--dagre-edgesep``` 50 file.d2
->panic:  flag redefined: dagre-```nodesep```

**Comment by bo-ku-ra** [comment]
ok
d2.exe --layout dagre --dagre-nodesep 50
d2.exe --layout dagre --dagre-edgesep 50

**Comment by alixander** [comment]
ah. still a bug that you got a panic though, thanks
