### ISSUE TITLE
Rendering PNG with CLI fails because of playwright

### ISSUE THREAD

**Issue by iAdanos** [terrastruct/d2#744]
After an installation with the official script I try to convert a d2 file to png:

```
d2 -l elk cp.d2 cp.png
```

and it doesn't work because of

```
err: failed to launch Chromium: could not send message: could not send message to server: Executable doesn't exist at /home/user/.cache/ms-playwright/chromium-978106/chrome-linux/chrome
err: ╔═════════════════════════════════════════════════════════════════════════╗
err: ║ Looks like Playwright Test or Playwright was just installed or updated. ║
err: ║ Please run the following command to download new browsers:              ║
err: ║                                                                         ║
err: ║     npx playwright install                                              ║
err: ║                                                                         ║
err: ║ <3 Playwright Team                                                      ║
err: ╚═════════════════════════════════════════════════════════════════════════╝

```

At the same time I already executed `npx playwright install` in different directory.

Meanwhile, playwright dependency is not mentioned in any of the installation docs.

If this is an expected behavior and is not a bug, then please update docs with an instruction on how to properly install playwright dependency and if this should be done globally or per project / directory, etc.

// OS Linux Ubuntu 20.04
// D2 CLI v0.1.6
// Node v18.13.0

**Comment by alixander** [comment]
playwright's behavior is to install dependencies upon first usage if it detects it's needed. Perhaps you can source or restart your terminal and try again and it'll find the dependencies if it was installed in another session?

**Comment by iAdanos** [comment]
@alixander, I managed to test the thing and here are my findings:

Inputs:
- Ubuntu Linux (20.04)
- node v18.14.2
- npm 9.5.0
- d2 CLI v0.2.1

When trying to run the thing from https://github.com/terrastruct/d2/issues/744#issue-1566020459 `d2 -l elk cp.d2 cp.png` I still do get the message about playwright install need.

Then I do:

```
npm install @playwright/test # Installs fine
npx playwright install # Downloads Chrome driver fine as well
```

After this I do get playwright installed in the current folder (PWD), so it won't be available in other dirs.

Let's say it's ok, and I would like to run it again:
```
$ d2 --layout elk cp.d2 cp.png
err: failed to install Playwright: could not install driver: could not install driver: could not check if driver is up2date: could not run driver: exit status 1
```

After re-opening the terminal (to refresh the env) it still doesn't work and gives the error.

Ok, that's fine, I thought. What if I do install the thing globally?

```
rm -rf node_modules/
sudo npm install -g @playwright/test
npx playwright install
d2 --layout elk cp.d2 cp.png
Downloading Playwright build of chromium v978106 - 130.7 Mb [====================] 100% 0.0s
Playwright build of chromium v978106 downloaded to /home/user/.cache/ms-playwright/chromium-978106
Downloading Playwright build of ffmpeg v1007 - 2.6 Mb [====================] 100% 0.0s
Playwright build of ffmpeg v1007 downloaded to /home/user/.cache/ms-playwright/ffmpeg-1007
Downloading Playwright build of firefox v1319 - 75.5 Mb [====================] 100% 0.0s
Playwright build of firefox v1319 downloaded to /home/user/.cache/ms-playwright/firefox-1319
Downloading Playwright build of webkit v1616 - 78.8 Mb [====================] 100% 0.0s
Playwright build of webkit v1616 downloaded to /home/user/.cache/ms-playwright/webkit-1616
success: successfully compiled cicd.d2 to cicd.png in 2m58.292017032s
```

And this gives me the proper png.

After re-opening the terminal it still works and it works even inside another directory.

Taking all of that in consideration, would you kindly:

1. Describe in the docs the need and the way to install playwright?
2. Consider adding any kind of progress bar or in-progress message for PNG rendering, since while it's working I was unable to determine if something good is happening (my diagram took long to render.)

Thanks for your support.

**Comment by alixander** [comment]
1. https://github.com/terrastruct/d2-docs/pull/78
2. tracking here: https://github.com/terrastruct/d2/issues/915

@iAdanos thank you for the detailed logs!

**Comment by sanabel-al-firdaws** [comment]
i went on circles to fix this the only thing i had to do is " npm install -g @playwright/test" 

i think D2 script is downloading playwright but it didn't download the test package?
