### ISSUE TITLE
IntelliJ plugin

### ISSUE THREAD

**Issue by userbradley** [terrastruct/d2#747]
Hey,

Fond of this project, was wondering if you have in your project road map to develop a plugin for IntelliJ?

\-b

**Comment by andrinmeier** [comment]
I'd like to take a look at this. But from what I understand, IntelliJ plugins have to be developed in Java? What's the preferred way of interacting with d2lang from a different language?

**Comment by alixander** [comment]
It'll have to be calling into the command line, I'm pretty sure. Google shows some results for calling Go from Java, but I suspect it'll be a lot of work.

**Comment by andrinmeier** [comment]
1. What about using a REST/gRPC interface for talking to d2? That would allow all languages to easily communicate with d2. Or are there any downsides to this approach?
2. Where would you like the plugin code to live? separate repo or this one?

**Comment by alixander** [comment]
1. Do you mean like a hosted, online API endpoint for that?
2. Separate, e.g. https://github.com/terrastruct/d2-vscode

**Comment by andrinmeier** [comment]
I meant something like implementing the language server protocol (LSP): https://microsoft.github.io/language-server-protocol/. From what I understand it uses JSON-RPC for communicating locally between a language server (d2) and a client (e.g. VSCode, IntelliJ, Confluence or whatever).

**Comment by alixander** [comment]
yeah we have a long-standing task to kick off that project (https://github.com/terrastruct/d2/issues/104). Not prioritized currently though. From what I understand (and it's not much, regarding LSPs), an LSP is just adding additional features though right? Being able to syntax highlight, autoformat, display compiler errors on line numbers, these would compose a very usable plugin and don't benefit from an LSP

**Comment by andrinmeier** [comment]
Ah my bad, I've never done anything with LSP myself.

But the possibility still stands, some sort of diagram server protocol that uses a similar protocol to compile diagrams maybe? Too complicated?

**Comment by alixander** [comment]
i think the one place structured data would be helpful is for compilation errors: which line is the error at? Currently, https://play.d2lang.com just parses the strings: https://github.com/terrastruct/d2-playground/blob/master/src/js/modules/editor.js#L302

It'd be annoying to implement for all languages that want to integrate with it for sure, but, not too bad as you can see from the code, so I'd say it's acceptable for now until LSP project is underway.

**Comment by userbradley** [comment]
I'm really late to this but yes, Java annoyingly.

A few plugins eg: tfsec and trivy just use the command line operator to render it.

Easiest way imo is to make use of the inbuilt intellij browser and just render what ever there. 

Happy to test and provide feedback, sadly I know no programming languages :(

**Comment by shirohoo** [comment]
Is there a roadmap or progress update available for this issue? While Visual Studio Code has a D2 extension, there doesn't seem to be a plugin for D2 in the JetBrains plugin market.

**Comment by alixander** [comment]
There is not. Just limited bandwidth. The VSCode extension took a lot of effort, and even then, it would've fallen behind in maintenance if it weren't for someone in the community helping out.

**Comment by develar** [comment]
The D2 for IntelliJ Platform based IDEs will be available in 1-2 weeks. 

The D2 IntelliJ plugin will primarily focus on the editor features, and not on the preview (that is handled by D2 studio). However, a preview is provided through an embedded browser (JBCEF) for a server created by D2 `--watch`.

The preview support for D2 files, as part of the [Writerside](https://www.jetbrains.com/writerside/) plugin, [is already completed](https://youtrack.jetbrains.com/issue/WRS-3636/Add-support-for-D2-diagrams). A new version of the [Writerside plugin](https://plugins.jetbrains.com/plugin/20158-writerside) will be released around January 15th.

![D2 Diagram](https://github.com/terrastruct/d2/assets/350686/c27160ec-8955-4d02-845d-b904a46dd95f)

**Comment by develar** [comment]
Could you please assist me in finding the official and free-to-use D2 logo assets? In particular, I need a plugin logo icon that like the one available here: https://github.com/terrastruct/d2-vscode/blob/master/d2-icon.png but in SVG format instead of PNG.

**Comment by alixander** [comment]
Oh good point [will](https://github.com/terrastruct/d2-docs/issues/200) put up a page for design assets. Ty.

in the meantime:
![d2-logo](https://github.com/terrastruct/d2/assets/3120367/bbd309b0-9270-4ef5-a856-044f191a6ebc)

**Comment by bo-ku-ra** [comment]
https://d2lang.com/img/d2_graphic.svg

**Comment by develar** [comment]
The D2 plugin for IntelliJ will be available in the marketplace in 2 days. Meanwhile, you can [download zip](https://github.com/develar/d2-intellij-plugin/releases/tag/v1.0.0) and use [Install from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk).

### Light
<img width="1525" alt="Screenshot 2023-12-31 at 13 13 42" src="https://github.com/terrastruct/d2/assets/350686/c33a7de4-22d2-4e67-bdf0-d488c49c0a83">

### Dark (yes, we should instruct D2 to [use a dark theme](https://github.com/develar/d2-intellij-plugin/issues/1) :)
<img width="1525" alt="Screenshot 2023-12-31 at 13 13 59" src="https://github.com/terrastruct/d2/assets/350686/9f67c54c-63fc-44e3-b32e-e9ee92e8d1f3">

Known issues:
* smart completion for shapes is not implemented (resolve and navigation works).
* FQN for shapes is not considered (if you have two shapes `foo` in different containers, resolve and navigation will use the first defined one).
* editor color style settings are not finished (well, in most cases, default generic is enough, so it will be not finished anytime soon without request)
* Formatting is file-level only — we delegate the work to D2 (to avoid reinventing the wheel). Still, basic spacing is respected according to the official D2 code style to avoid tedious space coding (for example, "Enter" after `{` is handled correctly).
