### ISSUE TITLE
Styles: shapes and containers transparent fill

### ISSUE THREAD

**Issue by iAdanos** [terrastruct/d2#753]
Currently, it seems to be impossible to create a transparent fill for a shape or container.

```
x {
  style: {
    fill: none
  }
}
```

doesn't work.

```
x {
  style: {
    fill-opacity: 0
  }
}
```

neither.

It would be good to have such a capability.

**Comment by alixander** [comment]
https://play.d2lang.com/?script=SrRSqOZSUKhQ0LVTqOQCsfTApuqBAtBKoaQoMa-4ILEoNa8EJJmcWFIMUpmSn17MpaAAFYHqgAaClYIBVy0XIAAA__8%3D&

**Comment by iAdanos** [comment]
Thanks!

Just to keep and answer in the same place:

A bit more representative version of @alixander, reply: https://play.d2lang.com/?script=SrRSqOZSUACbBGEqKIDCzkqhKDWFS0GhlotLQaFCQddOoRLM0gOr1IMoKSlKzCsuSCxKzSsBSSYnlhSDVKbkpxfD-FD10ACyUjDQM-Wq5QIEAAD__w%3D%3D&

```
a: {
  style: {
    fill: red
  }

  x -> y

  x.style.fill: transparent

  cats -> dogs

  cats.style.opacity: 0.5
}
```

so `  x.style.fill: transparent` does the thing.

**Comment by alixander** [comment]
Thanks @iAdanos , you're right, it's easy to mistake for css properties of "none", and "hidden". Adding this to the docs

https://github.com/terrastruct/d2-docs/pull/62
