### ISSUE TITLE
cli: command to list icons

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#758]
`d2 list-icons` to open up https://icons.terrastruct.com

**Comment by bo-ku-ra** [comment]
Is the command necessary?

c:\>d2 ```-help```
Usage:
 d2 [--watch=false] [--theme=0] file.d2 [file.svg | file.png]
&lt;snip>

See more:
docs and the source code at https://oss.terrastruct.com/d2
```list icons at https://icons.terrastruct.com```
```D2 Tour at https://d2lang.com/tour/intro/```

**Comment by alixander** [comment]
yeah i like it. appreciate the input @bo-ku-ra
