### ISSUE TITLE
cli: allow passing ttf paths for fonts

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#765]
`--regular-font=./comic_sans-regular.ttf --bold-font=./comic_sans-bold.ttf`

**Comment by alixander** [comment]
maybe also accept google fonts. `--google-font=https://fonts.google.com/specimen/Architects+Daughter`

**Comment by alixander** [comment]
the blocker here is that

- To embed fonts in SVG, you need WOFF format. (ttf way too big. woff is compressed)
- Most fonts are given as TTF
- I can't find a golang ttf to woff converter

cc @nhooyr

**Comment by nhooyr** [comment]
I'm not aware of anything. Will have to write it ourselves then.
