### ISSUE TITLE
fix markdown measurement with tables

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2#771]
Oh!

forced sample;
https://play.d2lang.com/?layout=dagre&script=nJJNbsMgEIX3PsWUC_DjXQVzhZ4Be5BrFWOLjheRfPgI41iJkmzCiuHxPeAxP79f37BN1ABY9l0MULN2QgvoQ4z_5WlpcELVevFER407lNEyQTfsobplTH9InoOVTM9KP6-JqyQ53xmgUcZIbWSrT9LHcUgul09Brd5RrdTyZFCrlxsPrz4kDhl5Zh9PxJYGgHpJkQMJ1OW0soqPXnJPCJvbAKB1mi4AH8y25hoAAP__&

_Originally posted by @bo-ku-ra in https://github.com/terrastruct/d2/issues/551#issuecomment-1367083541_

![Screen Shot 2023-02-06 at 1 24 05 PM](https://user-images.githubusercontent.com/85081687/217091280-80a2b866-06e2-4586-a8d0-47ab31170fde.png)

**Comment by bo-ku-ra** [comment]
this issue is about vertical.
the horizontal issues are #517, #513, and #749.

**Comment by bth8939** [comment]
Hello,

Any news for this issue please ? 
Thanks

**Comment by bo-ku-ra** [comment]
Scale multi-width unicodes #817

**Comment by alixander** [comment]
@bo-ku-ra is that related to this?

**Comment by bo-ku-ra** [comment]
d2 tends to be correct in height, provided the width is correct, as I have experienced.
but you say so.
i was wrong.

**Comment by alixander** [comment]
https://github.com/terrastruct/d2/pull/2221
