### ISSUE TITLE
Will d2 output diagram with a title/name?

### ISSUE THREAD

**Issue by FFengIll** [terrastruct/d2#773]
Like bellow with a title/name on the bottom.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/7359555/217131113-c8b52e7e-398e-4f10-897e-c5433605bf8a.png">

**Comment by bo-ku-ra** [comment]
uncool, but..

https://play.d2lang.com/?script=hJDBCsJADETv-YqhnhU34CUHf6UUXMWDe5AeFsr-u8ymYoqIPaXJZDZvck2GRYDudWBshmF37d8gQEnYn1GU5ZgMQ0m9PSpr9do1bC3uEwgMpyYCXO7T7Tk9KGE0hjnXuXFduR3G3WGN1HBs_tw_UZNc1Vk-MgHeaH5ShAvDb-4t7hY4IvvvGtJPfoAHvgIAAP__&layout=dagre&

**Comment by bo-ku-ra** [comment]
fyi. https://d2lang.com/tour/text/#near-another-shape
