### ISSUE TITLE
"&" Character causes improper SVG export

### ISSUE THREAD

**Issue by 10Nates** [terrastruct/d2#775]
# Issue
When exporting, using the "&" character (which has special use in HTML & SVG) will cause an error on some SVG parsers who don't have a fallback, thus rendering the file incompletely

# Replication
Use the "&" character as a title or a tooltip

# Solution
Use HTML encoding for better compatibility, and other characters that may present an issue in rendering for full compatibility.
- "&" -> \&amp; (most significant)
- "∈" -> \&isin; / \&#8712;
- "∑" -> \&sum; / \&#8721;
- ...

**Comment by alixander** [comment]
tried reproducing but unsuccessful

https://play.d2lang.com/?script=qsy3UlBTU6jmUlCAKrRSSEpNzCtWUFMoykxO5arlylCrBKl51NEBVgbytpVCSX6BbnJqXklqEZeCAtivVgolqRUlXLVcgAAAAP__&

Can you reproduce with a playground link please? @10Nates

**Comment by bo-ku-ra** [comment]
'&' disappeared
https://play.d2lang.com/?script=UkvLz-dSU0tKLOJKy89PSiyyUlBSg7CUuEBCCrp2CmBpQAAAAP__&

**Comment by 10Nates** [comment]
> tried reproducing but unsuccessful
> 
> https://play.d2lang.com/?script=qsy3UlBTU6jmUlCAKrRSSEpNzCtWUFMoykxO5arlylCrBKl51NEBVgbytpVCSX6BbnJqXklqEZeCAtivVgolqRUlXLVcgAAAAP__&
> 
> Can you reproduce with a playground link please? @10Nates

I clicked that link and exported it as SVG, and it had the error when I opened it in Brave, Safari, and Firefox.
It is not an issue with the inbuilt display, it is an issue with the export.

**Comment by alixander** [comment]
@nhooyr do you remember why the parser has ampersand as a special char?

https://github.com/alixander/d2/blob/2ab9f434e16cf6128289ae71bc82b5c9dae6cf67/d2parser/parse.go#L610

**Comment by nhooyr** [comment]
The idea was you could target fields by using ampersand instead of setting them.

I don't remember exactly how it was used, I'll keep it in the back of my mind and it'll come back to me.

**Comment by alixander** [comment]
it was for globs: https://github.com/terrastruct/d2/issues/103
