### ISSUE TITLE
fdopendir /usr/local/bin/docker: not a directory

### ISSUE THREAD

**Issue by ShonStewart** [terrastruct/d2#794]
I tried different ways to install `d2` (`brew` and download from release). I always get the following error:

```
err: fdopendir /usr/local/bin/docker: not a directory
```

FYI, I do have docker installed on my M1 mac (macOS Ventura 13.2).

**Comment by alixander** [comment]
cc @nhooyr

**Comment by nhooyr** [comment]
This isn't related to our docker image right? If so, I have no idea where that's coming from. Very bizarre 🤔

**Comment by nhooyr** [comment]
> @nhooyr To clarify, I didn't run it in a docker. Instead, I tried to run it natively on my M1 mac.

I understand but that's why it doesn't make any sense. There is no code in the d2 binary for docker.

Try `strings -v $(command -v d2)` and see if the output of that contains `/usr/local/bin/docker`. If not, then that confirms that it's definitely not the `d2` binary that's trying this on its own and it's something else on your system somehow.

**Comment by nhooyr** [comment]
Also the `d2` binary has no cgo but `fdopendir` is a C function. I wonder if `d2` is trying to execute some other binary and that's what's causing this. Though you'd see a proper error message then of what `d2` tried to execute and it failing.

Try uninstalling docker and reporting this to the docker devs as well.

**Comment by ramon-san** [comment]
I got a similar issue, whenever I try to run a d2 command I get:

```txt
err: fdopendir /usr/local/bin/gnuplot: not a directory
```

I'm using MacOS with Ventura 13.0.1 and my chip is Intel. I installed `d2` via Homebrew, but I remember using it a while back and it used to work correctly. I already checked `whereis gnuplot` and it does appear in the appropriate directory as a symbolic link to `gnuplot`'s Homebrew installation. Here is the result of running `ls -la /usr/local/bin/gnuplot`:

```txt
lrwxr-xr-x  1 my_user  admin  35 Oct  7 11:43 /usr/local/bin/gnuplot -> ../Cellar/gnuplot/5.4.5/bin/gnuplot
```

**Comment by nhooyr** [comment]
Very weird. I don't believe we use that binary either lol.

Could one of you guys screenshot the output you're seeing so that I can confirm it really is coming from the d2 binary?

**Comment by ramon-san** [comment]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/65260209/218854351-b2192806-5041-4102-ab7d-24fc9c3fa56a.png">

**Comment by ramon-san** [comment]
I tried running the command in `--verbose`, but that didn't change the output, if you have any way in which you'd like me to run the command let me know. I also tried uninstalling `d2` and installing it back on.

**Comment by nhooyr** [comment]
Yup that's definitely the d2 binary as `err` is colored red. Try installing go and compiling from source. See docs/install.md for how to compile after installing.

**Comment by alixander** [comment]
@ShonStewart just to make sure your local install is not shadowed by your brew install, can you run `which d2` again?

**Comment by Morriz** [comment]
I am fairly sure errors like `err: fdopendir x: not a directory` is happening because PATH is contaminated with files. If you fix your PATH to only container folders the error goes away.

**Comment by nhooyr** [comment]
Similar report at https://github.com/terrastruct/d2/issues/907#issuecomment-1445308645

Can you post your `$PATH`?

**Comment by alixander** [comment]
it's gotta be path
