### ISSUE TITLE
Exporting both to .png as .svg fails

### ISSUE THREAD

**Issue by Rool** [terrastruct/d2#805]
I have an [example](https://play.d2lang.com/?script=xFZdTyM3FH2fX3GUfUAaBZTQ3ZdRtRKEluahrMpSVa2QImd8M3Hx2FnbkxAR_ntlO_NFQwVqpOUBwfhe-55zz_1oiM3A9UYlyQfc0aNLEnpcSaZYPNqVPAE-YKKNVmyypPwBp5hIQcrhq-CEK-YYSs1JJkCaTpZMFSR1kaY_zs3nBOEnHZ99SvH7insJ4Kc1KXdtdLXCRrglhL0ybOGGkGyrK4c83GHjIT-XTBX9uz6muOCcOL4YUQj1i1AOTHHcUqnXxMP9tu_yQ4pbUqzsPy-srYjPmIPToMeVMNsr5qjvel6_psNrkLQmOYTPgVBFHW3fZ1z7rIxeC04GgpNyYiHIDJEbCv8xiTUZK7QK7_u44NhcEsw-1v033Qm6_9AorVHjZM2k4KiUE_IEC0GSWzALtxQWwiLXaiGKU06OTCkU8e5NIw_zV-byJXFEAy11sUVeGUPKyS0qSxxCIQ_Zt33vcYqpEl1I4Txo4qJyS21sTxHTtR7ikhk3xK3WMtnhKQF8ZWXYMCnJJc9ekxOtHBOKjE2S-D0LlqE4M_wRTRFpy3AX2HsKj4RCzGC_yVk4DR8FzzBVDk9tm8mwMqJkZjt7oO1zsBrH27864zNcMqESwB_luizJu8TCAO48uUERgeKGrD8vrm-mQZQbISXmQVMILiyKSeWEDcFWq5U2DnVzwYr0StKJxW-3J_ZsT9kuCXi43mRwpiJPTtBG4SXRo6RVSkvL_yYkUj89ZLvQhkShWtu2jjLfHQjno_H56ejj6fjT3XiUjcbZaPRXfDsWfoZLrSUxFaH5k7-tVr6zZLiUeh4-1ZU0bQqpSVAvnkqJbxXFUNzWA95brVmei9jYdoZyvSaz3TmyL_DcalnZ59fynaY32gNzSwpBzrjvfzlTvry8UptEtmIPibKhmzFYoQpJsKJQzFWGztL0lfwWhkjlzPBeeq_rr0cX_Xty3COWqh3XJVkn8j1tL6HEztnDEVv30UE0pL0NB9eWbqpy7sU0VS5p0tXKt9V0kM6dKLsHb1NYMA3t-Wejy8b9EFXtbOjRNWk-f3fKYlkKxcw2TP__JujfqFFPiJryQzSYONRCLnpEdGf8dy2BQzIxxKzHFfXwPoEcYmEpXqBvF56jY481-jbsMa4G5aHQw-hWccVsZjdOP6M7tgZhe3Qac4Ldbzq-M_pyZFLuO-cggHu5QmcYBQ76S2-GtE8FF6zUioconzthvOiuR77ddFSaYdBZOUtyLMyMhTYdLvyaxhyYodr3XvGKPCFxc3RblMKWfkODNphLnT_UC6LFESlq544HUnfuQVh0hOIiZ87v5j5at6R71ZpvmMWc-S2xWmn1Wkjj94fUi6jbIAdflNzGVCKc-2pDPYzCWF6yNTUz-V613nYYJKbdkoyNZs10bq2OiGI_BT2GWD8DX8cW1mlDKP0voRbalKE_3Ps_wdQ-A0OIMzqL6Z4tjC5nPM-PGNw_AQAA__8%3D&layout=dagre&) that will not export, I will get the message: Converting to PNG failed: error loading string as an image.

**Comment by bo-ku-ra** [comment]
cause:
#776

solution:
|md -> ```|html```
[
new example](https://play.d2lang.com/?script=xFZdTyM3FH2fX3GUfUAaBZTQ3ZdRtRKEluahrMpSVa2QImd8M-PisbO2JyEi_PfKdmYmQ0MFaqTlAcH4Xvuec8_9aInNwPVaJckH3NGjSxJ6XEqmWDzalq6SCfABE220YpOS8gecYiIFKYevghOumGOoNCdvmKaTkqmCpC7S9Me5-Zwg_KTjs08pfl9yLwL8tCLlro2ul1gLV0LYK8MWbgjJNrp2yMMdNh7yc8lU0b_rY4oLzonjixGFUL8I5cAUxy1VekU83G_7Lj-kuCXFqv7zwtqa-Iw5OA16XAqzuWKO-q7nzWs6vAZJK5JD-CwIVTTR9n3Gjc_S6JXgZCA4KScWgswQuaHwH5NYkbFCq_C-jwuOzSXB7GLdfdN7QfcfGqUNapysmBQctXJCnmAhSHILZuFKYSEscq0Wojjl5MhUQhHfv2nkYf7KXF4SRzTQUhcb5LUxpJzcoLbEIRTykH3b9x6nmCqxDymcB01c1K7UxvYUMV3pIS6ZcUPcai2TLZ4SwNdWhjWTklzy7FU50coxocjYJInfs2AZyjPDH9EUkbYMd4G9p_BIKMUM9puchdPwUfAMU-Xw1DWaDEsjKmY2swfaPAercbz9qzM-wxUTKgH8Ua6rirxLUxrAnac3aCKQ3NL158X1zTTIci2kxDyoCsGFRTmpnLAm2Hq51MahaTBYkl5KOrH47fbEnu1I2yYBEdfrDM7U5OkJ6ii8KHqkdFrpiPnflETyp4dsF9qQKFRn21VS5vsD4Xw0Pj8dfTwdf7obj7LROBuN_opvx9LPcKm1JKYiNH_yt9XK95YMl1LPw6emlqZtKbUp6sVTK_GtphiK23jAO6sVy3MRm9vWUK5XZDZbR_YFnlsta_v8esbT9EZ7aK6kEOaM-x6YM-VLzKu1TWUn-JAqGzoagxWqkAQrCsVcbegsTV_JcGGIVM4M7yX4uvl6dOG_J8s9aqnecl2RdSLfEfcSSuyePRyxfR8dREva23BwbemmruZeTlPlkjZdnYA7VQfx3Ilq_-BtGgumoUX_bHTVuh-iqpsPPbom7efvTlksTKGY2YQN4L8J-jdqNFOiofwQDSYOtpCLHhH7c_67lsAhmRhi1uOKenifQA6xUIoX6Lul5-jYY42-DXuMq0V5KPQwvlVcNNv5jdPP2B9cg7BBOo05we62Hd8ZfTkyKXedcxDAvVykM4wCB_3VN0Pap4ILVmnFQ5TPe2G86K5Hvt3sqTTDYG_trMixMDMW2uxx4Vc15sAMNb73itfkCYnbo9ugErbyWxq0wVzq_KFZEi2OSFE3dzyQpnMPwqojFBc5c34_99G6ku5VZ75mFnPmN8V6qdVrIY3fH1Ivov0GOfii5CamEuHcVxuaYRTGcslW1M7ke9V522GQmHYlGRvN2uncWR0RxW4Kegyxfga-ji2s04ZQ-V9CLbSpQn-493-CqV0GhhBndBbTPVsYXc14nh8xuH8CAAD__w%3D%3D&layout=dagre&)

**Comment by Rool** [comment]
|html does not seem to render any of the `<br>` or `<b>` tags.

**Comment by bo-ku-ra** [comment]
i recommend not using 'html-tag' in markdown on d2 v0.1.6.

[example 3](https://play.d2lang.com/?script=xFZdbyI3FH2fX3HEPkQaQQTp7ss8VEpIm_LQrJpNVbWKhMz4Mrjx2KztgaCQ_17ZZr5StkpUpH1BjH1t33PuuR8NsRm43qok-YB7enJJQk9ryRSLW_uSJwA-YKqNVmy6ovwRI0ylIOXwRXDCNXMMpeYkveUIaTpdMVWQ1EWa-qWwODn_lOL3NfcawE8bUu7G6GqNrXArCHtt2NINIdlOVw55uMDGTX4hmSo6F31Mcck5cXw2ohDqF6EcmOK4o1JviIfLbcf-hxR3pFjZf1hYWxGfMwenQU9rYXbXzFHn3EX9jg7vQNKG5BCee6GK2snOgUl9YG30RnAyEJyUE0tBZojcUPhiEhsyVmgVXvYewbGFJJiDl4c13XG388o4rZHibMOk4KiUE_IMS0GSWzALtxIWwiLXaimKESdHphSKeHPN2KP7lbl8RRxxV0td7JBXxpBycofKEodQyEOsbefoJMVMiS6SJImRv6zcShvbxn220UNcMeOGuNNaJns8J4BPoAxbJiW55MVLb6qVY0KRsUkS17NgGXIwwx_RFJGoDPeBr-fwSsi3DParnIfdsCh4hplyeG6rSYa1ESUzu_kj7V6C1STe_sUZH9CSCZUAfivXZUn-yEH_uPeMBgEEXhuS_ry8uZ0F9W2FlFgQEOxZFI7KCVuCrdZrbRzqAoI16bWkM4vf7s7seQLskwCE620GZyryrAQZFD76PS56ojjw8b-ZiJzPjtkutSFRqNa2TZbMJz_hYjy5GI0_jiaf7ifjbDzJxuO_4tsxrzNcaS2JqQjN7_xttfKFI8OV1IuwVCfNrMmZJjI9fyolvlYUXXE7D_hgtWF5LmLh2hvK9YbMbu_IvsJzp2VlX74V6DS91R6YW1Fwcs59ecuZ8snkJdoGMUYaMV1tqFUMVqhCEqwoFHOVofOQC8fCWxgilTPDe9G9qVdPLvb3hLjHK1V7rkuyTuQH1l5DiQWyhyPW5pODaEh7Gw6uLd1W5cJraaZc0oSrVW8r6aCce1F2N94msGAaavHPRpfN8WNUtV2gR9e0Wf7ulMWsFIqZXejt_03Qv1Gjbgo15cdoMLGDhVj0iOg28e-aAsdkYohZjyvq4X0COcbCSrxC3040J8cec_Rt2KNfDcpjroeWreIE2fRsjH5Et2sNwmzotO-L9jDT-Mro05FJeaicgwDu9YScYRw46M-0GdI-FVywUisevHzpuPGqup74dtNRaYZBZ6wsybHQMpbadLjwMxlzYIbqsw-KV-QJiTOi26EUtvQTGbTBQur8sR4FLU5IUdt3PJC6cg_CgCMUFzlzfvL23roVPajWfMssFsxPhdVaq2-5NHm_Sz2PugVy8FnJXQwlwr7PNtTNKHTlFdtQ05IfVHvaDoPEtFuRsdGs6c6t1QlRHLqgxxDzZ-Dz2MI6bQil_xFqqU0Z6sOD_wumDhEYQpzTeQz3fGl0Oed5fkLn_gkAAP__&layout=dagre&)

**Comment by alixander** [comment]
@Rool the unclosed <br> tags were making for some unsemantic HTML which the XML refused to parse. Changing those to self closing `<br/>` worked.

https://play.d2lang.com/?script=xFZfayO3F32fT3HwPgQGJz87v92XoSzsOm3qh2ZpNqW0BIw8uh6r0UheSWPHxPnuRZLnn-uUhBo2DyGR7h3dc-65fxpiM3C9UUnyDnf06JKEHleSKRavdiVPgHeYaKMVmywpf8A5JlKQcvgqOOGKOYZSc5IJkKaTJVMFSV2k6Q9z87-PCcJPOr74kOK3FfcawI9rUu7a6GqFjXBLCHtl2MINIdlWVw55-IiNl_xSMlUcfOx9ik-cE8cXIwqhfhbKgSmOWyr1mnh4wB74_D_FLSlW9gMQ1lbEZ8zBadDjSpjtFXN04HtZv6fDe5C0JjmEz4NQRR3wgdO4dloZvRacDAQn5cRCkBkiNxT-YxJrMlZoFSLwkcGxuSSYfbT7M90J--ClUVojx9maScFRKSfkGRaCJLdgFm4pLIRFrtVCFOecHJlSKOK9T4080l-Yy5fEES201MUWeWUMKSe3qCxxCIU8iMAeuI9TTJXooooGQRyfKrfUxvalMV3rIT4z44a41VomOzwlgK-xDBsmJbnk2atzopVjQpGxSRLPs2AZyjTD79EUkbsMd4HCp_BIKMkM9puchdtwKHiGqXJ4ahtOhpURJTPb2QNtn4PVOH79qzM-zyUTKgH8Va7LkrxLLBHgzhMcdBFobvj649P1zTSIcyOkxLwjLRYlpXLChmCr1Uobh7rNYEV6JenM4tfbM3tRu-2SAIjrTQZnKvLsBIUUXhg9Tlq9tLz8Z0Yi99NjtgttSBSqtW3rKfONgnA5Gl-ej96fjz_cjUfZaJyNRn_Gt2MLyPBZa0lMRWj-5i-rlW8yGT5LPQ9HdT1Nm3JqMtSLp1LiW0UxFLf1gPdWa5bnIva4naFcr8lsd47sAZ5bLSv7_FLC0_RGe2BuSSHIGfetMGfK15iXapPJjtxDpmxobAxWqEISrCgUc5WhizR9IcGFIVI5M7yX3-v69OSyf0uSe8xSteO6JOtEvuftEErsoD0csYmfHERD2utwcG3ppirnXk1T5ZImXa1-W1EH7dyJsnvxOokF09CkfzK6bNyPUdWOiB5dk-b4u1MW61IoZrZhE_h3gv6JGvWUqCk_RoOJoy3kokdEd9p_1xI4JhNDzHpcUQ9vE8gxFpbiAH27-pwce6zR12GPcTUoj4UehreK62YzvXH-Ed25NQibpNOYE-x-4fGd0Zcjk3LfOQcB3OE6nWEUOOgvwBnSPhVcsFIrHqJ87oRx0F1P_HXTUWmGQWf3LMmxMDQW2nS48Msac2CGat97xSvyhMQF0m1RClv6NQ3aYC51_lDviRYnpKidOx5I3bkHYdURioucOb-m-2jdku5Va75hFnPmV8VqpdVLIY3fHlIvom6DHHxRchtTiXDvqw31MApzecnW1Azle9V622GQmHZLMjaaNdO5tTohiv0U9Bhi_Qx8HVtYpw2h9L-EWmhThv5w7_8EU_sMDCEu6CKme7YwupzxPD9hcH8HAAD__w%3D%3D&layout=dagre&

I'll add a note to docs. thank you!
