### ISSUE TITLE
Style.fill Doesn't Work

### ISSUE THREAD

**Issue by epshetsky** [terrastruct/d2#809]
The [examples ](https://d2lang.com/tour/style#fill)of "style.fill" don't work.
Any references to "...style.fill" result in "D2 encountered an API error." message.

e.g.

x: {
  y
  y.style.fill: transparent
}
x.style.fill: PapayaWhip

**Comment by alixander** [comment]
@epshetsky can you screenshot what you're seeing?

https://play.d2lang.com/?script=qrBSqOZSUKgEYT2weXqg4LRSKClKzCsuSCxKzSvhUlCo5VJQqECRD0gsSKxMDM_ILOACBAAA__8%3D&

**Comment by epshetsky** [comment]
![image](https://user-images.githubusercontent.com/13578087/218585000-28ef42d7-dbc9-4109-9b8f-6463115a425d.png)

**Comment by epshetsky** [comment]
@alixander see above

**Comment by alixander** [comment]
@epshetsky i think the cache just hasn't been cleared on your browser. can you try it in incognito mode or such?

**Comment by epshetsky** [comment]
You're right! 
Thank you for such a prompt response!
