### ISSUE TITLE
http://play.d2lang.com crashes firefox on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by BarryNolte** [terrastruct/d2#811]
Open https://play.d2lang.com will crash firefox within about 5 seconds.

The only output I could capture is:

```code
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. web-client-content-script.js:1:340202
XHRGEThttps://play.d2lang.com/d2.wasm
[HTTP/2 304 Not Modified 25ms]

XHRPOSThttps://play.d2lang.com/api/event
[HTTP/2 202 Accepted 432ms]

XHRGEThttps://play.d2lang.com/js/vendor/onig.wasm
[HTTP/2 304 Not Modified 27ms]

XHRGEThttps://api.d2lang.com/render/svg?script=qlDQtVOo5AIEAAD__w==&layout=dagre&theme=0&sketch=0
[HTTP/2 200 OK 41ms]

Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq out.js:11:37523
You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker out.js:11:37716
```

**Comment by alixander** [comment]
weird, can't reproduce. maybe monaco is using too much CPU though?

**Comment by BarryNolte** [comment]
monaco using too much memory or CPU, inconceivable.  It doesn't say it OOM's or is consuming too many resources.  I have an update pending, so I'll see what happens after the reboot.

**Comment by pattmax00** [comment]
Also having it give me an API error for something that was working a couple hours ago

**Comment by pattmax00** [comment]
> that API error is likely just a browser caching issue. we update the WASM on the frontend and the build on the backend, and this release had some encoding changes, so previous playground links won't work anymore unfortunately. Do you have a link @pattmax00 ?

Yes, the solution was just clearing my cache 😂 thank you

**Comment by BarryNolte** [comment]
Clear Cache/upgrade all/reboot - all good.
