### ISSUE TITLE
Language Anomoly

### ISSUE THREAD

**Issue by BarryNolte** [terrastruct/d2#812]
I can't find it documented anywhere, but I found that:

```code
x: {
...
}
```
is equivalent to:
```code
x {
...
}
```
Is the colon meant to be optional?

**Comment by alixander** [comment]
no, the autoformatter will add the colon for you. just like how 0.2.0 we had a breaking change where `obj.fill` was no longer supported since it was illegal (the correct usage was always `obj.style.fill`), it's likely that one day we'll also patch this and maps without colon will stop working
