### ISSUE TITLE
container title 

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#813]
v0.1.6 -> no problem
v0.2.0 -> degrade 😢

https://play.d2lang.com/?l=&script=HMq7CYAwFEDRPlvfxyOIneCHLKBi4wY6zF1ETHngyCi3MUgtPyKlySuXLJJFQiZ5ZJO9J-SQU6rMskr20MoXAAD__w%3D%3D&

**Comment by alixander** [comment]
i don't understand, what's the issue?

**Comment by bo-ku-ra** [comment]
v0.1.6
![1](https://user-images.githubusercontent.com/121328398/218628885-04d3b4e2-e060-4cf0-8331-6cea69f9a8c0.png)

v0.2.0
![2](https://user-images.githubusercontent.com/121328398/218628924-d661dda8-81af-42db-ad9f-93b03ecea10f.png)

you say v0.2.0 is much more legible. are you sure?

**Comment by alixander** [comment]
this is just this issue though, right? https://github.com/terrastruct/d2/issues/513

i got you @bo-ku-ra , I'll fix this tomorrow =)

**Comment by alixander** [comment]
@bo-ku-ra https://github.com/terrastruct/d2/pull/817
