### ISSUE TITLE
'Connections' Demo Snippet from Playground Errors w/ 500

### ISSUE THREAD

**Issue by matthenry87** [terrastruct/d2#814]
dogs -> cats -> mice: chase
replica 1 <-> replica 2
a -> b: To err is human, to moo bovine {
  source-arrowhead: 1
  target-arrowhead: * {
    shape: diamond
  }
}

https://play.d2lang.com/?script=XJCxCsIwFEX3QP7hzGKHOgbpV_gDr0mwAZMnSXWR_ruk4tLp8Q5nuPcGvTeGCS_rfnPy0eEXadGaGp-P5IWR6zDx_y7WSFdnx02JtZIayytLObMqWZVZ36lEPtbAsbNj7PgY03H6-bBP5whJspbQ2WbNZs03AAD__w%3D%3D&

**Comment by pattmax00** [comment]
This is the correct demo:
```
dogs -> cats -> mice: chase
replica 1 <-> replica 2
a -> b: To err is human, to moo bovine {
  source-arrowhead: 1
  target-arrowhead: * {
    shape: diamond
  }
}
```
the one you linked to is syntactically incorrect, but the one you copy pasted into the issue *is* correct.

**Comment by matthenry87** [comment]
> This is the correct demo:
> 
> ```
> dogs -> cats -> mice: chase
> replica 1 <-> replica 2
> a -> b: To err is human, to moo bovine {
>   source-arrowhead: 1
>   target-arrowhead: * {
>     shape: diamond
>   }
> }
> ```
> 
> the one you linked to is syntactically incorrect, but the one you copy pasted into the issue _is_ correct.

Steps to reproduce:
1. Open playground site.
2. Click the 'copy' button on above snippet.
3. Paste into the textbox.
4. Ctrl S/compile
5. Observe error.

![image](https://user-images.githubusercontent.com/3778394/218633235-d0f8ac57-e0c9-47dc-a733-14f65805e377.png)

**Comment by pattmax00** [comment]
That API error is a little different. I had that a few hours ago and clearing by browser cache fixed it. You probably have an old WASM binary cached.

**Comment by matthenry87** [comment]
Fixed after clearing cache.
