### ISSUE TITLE
dagre: not connected

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#818]
https://play.d2lang.com/?script=ZI9RysIwEITf5xRzgQ78vz5IlJ6kIKWa2hYjNPahhtxdNkUQfBp2d_ZjpmUCOenJqqbXANKrt-GsqICMyTGZKPJU1Vz0wE13RfO08uoBk5HlGDViKczuA3mpQwYQXdkHJpbg2vo4ztcLSNKDzGaNCva8anZM396tu-Ph-IvIWDVvoXoNjn9N-G_Crgl74B0AAP__&

**Comment by bo-ku-ra** [comment]
because i use d2 every day, i want to get the new version soon :-)

**Comment by alixander** [comment]
@bo-ku-ra i just want to get these in before another small release (0.2.1)!

- https://github.com/terrastruct/d2/issues/823
- https://github.com/terrastruct/d2/pull/613
- https://github.com/terrastruct/d2/issues/856

**Comment by gavin-ts** [comment]
Is this what the link had before? If not this seems like a weird bug

![Screen Shot 2023-02-27 at 11 51 46 AM](https://user-images.githubusercontent.com/85081687/221668499-48edfaa7-db8a-43f4-b963-6166797a4136.png)

**Comment by alixander** [comment]
the original one is an e2e test in d2

**Comment by gavin-ts** [comment]
hmm ok I wonder if we should add a version param, to avoid breaking old links

**Comment by alixander** [comment]
yeah we should. i considered it. but pre 1.0, w/e
