### ISSUE TITLE
make `~~` strikethrough work for markdown

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#819]
https://d2lang.com/tour/style/#bold-italic-underline

style.strike-through: true
```html: <s>foobar</s>```

**Comment by alixander** [comment]
i'm going to say no to this being a keyword because those are for labels, and i don't think it makes sense for a whole label to be strikethrough'd.

however, it should work for markdown: https://play.d2lang.com/?script=qrBSqMlN4VJQ0NIqycgs1tJSqKsrLinKzE4tySjKL03PqKvjquECBAAA__8%3D&

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?script=dJFBysIwFIT3OcV3gf67f5NFT-EFYn3owzQpfa1ttebsEkFw424GPoYZRhNdMAFlCWliysg6xKAJnai23-hyjBLOs0DUqxA4SswLTcvqVpoGq3rzPN6t_r42eP6flWm5ew4XNdTo8livJuXFmWfvTw5KGUa5aZ4tbh-iFLe737mvAAAA__8%3D&

**Comment by bo-ku-ra** [comment]
https://github.com/terrastruct/d2/issues/819#issuecomment-1457639489
> however, it should work for markdown: https://play.d2lang.com/?script=qrBSqMlN4VJQ0NIqycgs1tJSqKsrLinKzE4tySjKL03PqKvjquECBAAA__8%3D&

not working.. (Windows only?)

**Comment by alixander** [comment]
sorry for the confusion, i meant "it should" as in, this is the TODO (we should make it work!)
