### ISSUE TITLE
investigate Powerpoint export

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#821]
pure Go method?

**Comment by ejulio-ts** [comment]
Anything specific? Like, report the diagrams as images and put it in power point, or check how to export it using native objects? Maybe, export the SVG inside the ppt/pptx file?

**Comment by alixander** [comment]
SVG into ppt best. PNG into ppt second best.

**Comment by ejulio-ts** [comment]
Some references:
- Pure go library to handle Office files and PDFs https://unidoc.io, paid license
- Go library to work with XLSX (Excel) https://github.com/qax-os/excelize
- Another library to handle xlsx https://github.com/plandem/xlsx
- Here is the library used by xlsx to handle OOXML (Office Open XML) https://github.com/plandem/ooxml

- here are the specs for presentations in OOXML http://officeopenxml.com/anatomyofOOXML-pptx.php
- the specification of OOXML https://www.ecma-international.org/publications-and-standards/standards/ecma-376/

I'll check http://officeopenxml.com/anatomyofOOXML-pptx.php and see if we can use ooxml to handle the low level stuff. Meaning, we might only need to write a high level API for slides/presentations and then leave the low level OOXML stuff to that library

**Comment by alixander** [comment]
why mention Excel stuff?

**Comment by ejulio-ts** [comment]
Just notes, as there's no implementation of `pptx`, `xlsx` could be a guideline to use `ooxml`

**Comment by bo-ku-ra** [comment]
I'm done? 🤔

https://play.d2lang.com/?l=&script=hJGxboQwEER7f8WINFxxFEhprCh9_oEGbIMcHV7LNlykE_8erblAjkS6CjEa786bfcFWt0TgToSuJW4C4G_RE1W6LnDLUBKa1DQalxYBxHm4O-I8_G_RNc7vq1HR6O3FiEUIT1cTPFmXJIoxgvreKlPu8qnICbo2SBRdGyrv09eqAYc1q_Y8CkAk76sap0N7tW5oHHWfRm1DOC3bFLnZhIREGK0KFKlPx7fYni4MpWvejbczdo6Ks6_ZPlzkgXEeGlduzAyar1j9urnE60NJPIWD-UB6UvlXIpg4XZIQD-Khq79N7RXghyJDNK6kYAfrJJ-MpuSnZDSnPYlFfAcAAP__&

**Comment by bo-ku-ra** [comment]
i had recognized that ms office(latest) could handle svg files & convert them to office objects.
i think  d2 could concentrate to output svgfiles.
does anything useful happen?

**Comment by alixander** [comment]
@bo-ku-ra yes, D2 will soon support multi-board diagrams. So you'll be able to generate PDFs and PPTs like the following, which is harder to do manually. 

(this one is produced in terrastruct)

[Fields_ VR for Chinchillas (1).pdf](https://github.com/terrastruct/d2/files/10750799/Fields_.VR.for.Chinchillas.1.pdf)

**Comment by bo-ku-ra** [comment]
oh! but
i think the best solution is outputting html(w/javascript/css)+svg files. (or it's archived as mhtml file.)
