### ISSUE TITLE
renderer: icon size

### ISSUE THREAD

**Issue by ejulio-ts** [terrastruct/d2#827]
D2 computes the icon size after receiving the layout back from the underlying engine. This works if the engine doesn't consider the icon size when setting its position.
We should change D2 to either:
- Send the icon size to the layout engine and it should not change it
- Get the icon size back from the layout engine and, if there's none, compute in D2

The reason is that TALA computes the icon size internally and could benefit from returning the best size for the given layout, or make the layout work with the given icon size.

Related to https://github.com/terrastruct/d2/pull/826

**Comment by alixander** [comment]
> D2 computes the icon size after receiving the layout back from the underlying engine.

No it doesn't. https://github.com/alixander/d2/blob/758446783426613df61a84b70e685fb64282f9ea/d2layouts/d2dagrelayout/layout.go#L123

TALA can call this function too. I don't see any TODO here
