### ISSUE TITLE
upgrading to latest elkjs-0.8.2 release

### ISSUE THREAD

**Issue by ymolists** [terrastruct/d2#863]
Hi

I really like how this project is coming along. I learned a lot going though the code base. Specially around the elk layout algorithms.

1) what is the version of the library that you are using now ? would it make sense to add a readme on the actual version of the lib you are suing ?
2) where did you get it or how did you build it from source ? i dont see bin release on the elkjs repo 
3) which version of the jdk are you using to build the elkjs lib ? I tried building with jdk 17 but got errors
4) when i upgraded the lib to 0.8.2 i am not getting any errors. i am not sure if the error is with goja or the way i built the elkjs file. i am not getting any errors. i am only getting an empty graph as an output. I attached a small patch file to show the minimal changes i made. also running the code below works fine in node

```js
node ./main.js

--- main.js
const ELK = require('./elkjs.0.8.2.js')

async function main() {
  const elk = new ELK()

  elk.layout(loadGraph(), {
    logging: true,
  })
    .then(console.log)
    .catch(console.error)
}

function loadGraph() {
  return {
    id: "root",
    children: [
      { id: "n1", width: 30, height: 30 },
      { id: "n2", width: 30, height: 30 },
      { id: "n3", width: 30, height: 30 }
    ],
    edges: [
      { id: "e1", sources: ["n1"], targets: ["n2"] },
      { id: "e2", sources: ["n1"], targets: ["n3"] }
    ]
  }
}

if (require.main === module) {
  main();
}

```

[upgrade.patch.tar.gz](https://github.com/terrastruct/d2/files/10798215/upgrade.tar.gz)

**Comment by alixander** [comment]
hey @ymolists , thanks for the kind words! 

1. We are using elk 0.8.2
2. We used a minified dist, slightly modified to be runnable headless and in context of goja (basically just run, fix error, run, fix error, until it works)
3. We didn't build from source, see 3.
4. N/A, given 1.

Is there something specific you're trying to do in D2? Or is this exploration for your own project in Javascript? Happy to answer any other questions either way.

btw if you're interested in layout engines and want to get involved, one of our todo's is to write a force-directed layout engine =): https://github.com/terrastruct/d2/issues/641

**Comment by ymolists** [comment]
Thank you so much for your detailed answer and your follow up. I am so sorry i was not able to reply in time !

I am trying to use elkjs as it is now for my own project. Ultimately i would like to convert all of elk to pure go but not sure when i will get to do that :-(
