### ISSUE TITLE
3d on hexagon shape

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#869]
<img width="455" alt="220769755-8f1bda9d-ff20-459f-bb5a-7fae11a90aae" src="https://user-images.githubusercontent.com/3120367/220771571-96efebb7-dea0-45bc-909a-48dd88ffbce5.png">

related: https://github.com/terrastruct/d2/issues/868

**Comment by JettChenT** [comment]
Hi! I'm willing to work on this issue.
Is there an API for drawing dotted lines in the SVG library to create the 3D perspective effect, or should I write a loop to achieve this?
Thanks!

**Comment by JettChenT** [comment]
Here's my current progress:
<img width="1442" alt="CleanShot 2023-02-25 at 00 02 15@2x" src="https://user-images.githubusercontent.com/45888395/221226822-61e5d8c2-c62f-498f-8e43-e21346e884e1.png">

**Comment by alixander** [comment]
awesome! no documentation unfortunately.

> API for drawing dotted lines in the SVG library to create the 3D perspective effect.

ohh very interesting. there isn't. i'm guessing you'll want to split it up into multiple paths or lines, and the ones behind will get lower opacity and dashed properties. 

i wonder if this exact image will be the best rendering of 3d for hexagon. it doesn't look like a lot of space for a label/icon. i'll let our designer @katwangy take a look this morning and chime in

**Comment by alixander** [comment]
<img width="617" alt="Screen Shot 2023-02-24 at 10 41 14 AM" src="https://user-images.githubusercontent.com/3120367/221264057-8728ae73-f9b4-45a7-9ff0-b809bbb4b4b7.png">

I would agree with that, the different perspective could look weird. can you change to doing this please? Sorry for that, I know you already started @JettChenT

**Comment by JettChenT** [comment]
Thanks a lot! I'll change this to the new design right away.
