### ISSUE TITLE
Is there documentation on sizing and positioning icons within containers?

### ISSUE THREAD

**Issue by zachcp** [terrastruct/d2#877]
In the [0.2 release docs](https://d2lang.com/releases/0.2.0) you have a really nice architectural diagram featuring nested components. 2 of the 3 icons in this image are tucked into the upper left corner. I'd like to replicate this but can find no documentation on how to do this.  Does this exist and if not, can it be added, perhaps to the Docs and playground? 

thank you,
zcp

![image](https://user-images.githubusercontent.com/1260667/221002399-ff66f63c-d3e6-4d45-8c5d-1df1c330153b.png)

**Comment by alixander** [comment]
it's just automatic: https://play.d2lang.com/?script=lJJPb5wwEMXvfIpRKnozf5ymlXxb0dDmUkWttIdekGFHxKrXRmYMSiq-e2XKAon20J5g3ozm8X7D0DUCjo8F5JBnSZ5kSZak-Uf4HQEEOgKeiLpepGmo-oTQOdmT8w0ljT2ncuxjXlZfnPVdzLOHMBTz8qgcealZ59QgCVmjrT-x42NR6cCd1W3SD20EMEcQs10oQkABrUM0s7Kd8JWqtBYwPinCCGCKAOSLgMMglZa10oqe4ac1CId1785ks6m1x0Xa--zk3SEE3F5mX7n_9Q-qw1GGTrm8wQ9fG6T1K_4H6Dek0bpfyrQxz97HPCusITQU8-wzajWge455eTjLF2vYd-sJ2d1t9dX2hCcWsr_lfAXDBqLzrtO4ynsYb1tz9pt3mJ_u8NPNok_LExsu4L7g8GB6kqbBnde_Zy_sufOE4be67Nmy3he8Kj6wS-NazGm9yhRN0Z8AAAD__w%3D%3D&layout=elk&

I'm thinking about some keywords for label and icon positioning. Basically the set of `near` keywords (e.g. top-center, top-left, etc). Not sure how important it is though

**Comment by zachcp** [comment]
Beautiful. Thank you.

**Comment by alixander** [comment]
that's a good point that i should always include a playground link to examples in release notes. thank you!

**Comment by alixander** [comment]
https://github.com/terrastruct/d2-docs/pull/72
