### ISSUE TITLE
show link url by tooltip

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#888]
the linking container must show the tooltip of the link url on mouse over. (ignore 'tooltip:')
this is a security issue.

https://play.d2lang.com/?script=Ss7JTM5WtFKoBnnZSiGjpKTASl8_JTEvPbUovjw1Kb44syTVWgFqDlxBeXm5Xnp-fnpOql5yfm4tFyAAAP__&

**Comment by alixander** [comment]
yeah that's a good consideration. when link and tooltip both defined, make the link the tooltip.

**Comment by alankan886** [comment]
Hello! I would like to work on this issue if possible. Thanks in advance!
