### ISSUE TITLE
Issue with local icons in 2.1

### ISSUE THREAD

**Issue by zachcp** [terrastruct/d2#889]
Local images using both `icon` and `shape` work with D2 v.02 but break with D2 v0.2.1. See below.

```d2
my network: {
    icon: https://icons.terrastruct.com/infra/019-network.svg
}

my network2: {
    shape: image
    icon: https://icons.terrastruct.com/infra/019-network.svg
}

my network3: {
    #wget https://icons.terrastruct.com/infra/019-network.svg
    shape: image
    icon: 019-network.svg
}
my network4: {
    #wget https://icons.terrastruct.com/infra/019-network.svg
    #shape: image
    icon: "./019-network.svg"
}
```

![image](https://user-images.githubusercontent.com/1260667/221210253-d5ae84f5-59ba-4ad8-b7f3-494ebdb43009.png)

**Comment by alixander** [comment]
wait `wget` was working before?

**Comment by zachcp** [comment]
> wait `wget` was working before?

No I'm just showing you that I'm trying to use the exact same icon but locally

**Comment by alixander** [comment]
can reproduce, we'll get this fixed today, ty for repoting @zachcp
