### ISSUE TITLE
overlay links on PDFs

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#891]
we can create a clickable region over an object when it's linked, where clicking on it goes to either another page of the PDF or external link

**Comment by berniexie** [comment]
What about the legend?

**Comment by alixander** [comment]
what legend

**Comment by berniexie** [comment]
@alixander sorry, the "appendix" 
![Screenshot 2023-02-27 at 10 24 03 AM](https://user-images.githubusercontent.com/6413609/221650651-0260fadd-ae82-408e-83eb-29ce2173cbb2.png)
