### ISSUE TITLE
Monospaced font in SVG

### ISSUE THREAD

**Issue by Baldomo** [terrastruct/d2#898]
Monospaced fonts are broken when exporting to SVG on Linux because `font-mono` or `font-mono-bold` are not a valid CSS font family. I found instances of this in the following files (and likewise for `font-mono-bold`):

- [`github-markdown.css#L15`](https://github.com/terrastruct/d2/blob/f9befba278d99b749bf651fe38952ef4500f7f63/d2renderers/d2svg/github-markdown.css#L15)
- [`d2svg.go`](https://github.com/terrastruct/d2/blob/f9befba278d99b749bf651fe38952ef4500f7f63/d2renderers/d2svg/d2svg.go#L1305-L1308)

As an example, rendering the following code to SVG

```
code: |go
import "fmt"

func main() {
	fmt.Println("Hello world!")
}
|
```

yields the following (using Inkscape):

![image](https://user-images.githubusercontent.com/17025402/221362035-a2efd0ec-883a-481f-8937-42fecded86fd.png)

Sorry in advance for the low quality of the issue as I don't have much time for additional research.

**Comment by alixander** [comment]
ah i think this is this issue: https://d2lang.com/tour/troubleshoot/#markdown-svgs-wont-render-in-certain-svg-viewers

if you open it the document in your browser, it should work. sorry about that. is there something you're trying to do in Inkscape that D2 can do for you? @Baldomo

**Comment by Baldomo** [comment]
Thank you for the swift response. I'm using D2's output in a Markdown document rendered via Quarto, which internally uses Pandoc. I guess Pandoc just converts SVG to PDF when rendering using `rsvg-convert` or `Inkscape`, which in turn breaks the fonts. Rendering to PNG and using that is quite cumbersome because of all the dependencies that are downloaded for rendering, but I can make do with that since it works fine after all. Feel free to close this issue and thank you again.
