### ISSUE TITLE
Add tagging for entities and tag filter for parser (CLI)

### ISSUE THREAD

**Issue by iAdanos** [terrastruct/d2#914]
An idea coming as an addition for https://github.com/terrastruct/d2/issues/670, https://github.com/terrastruct/d2/issues/133 and https://github.com/terrastruct/d2/issues/102.

When drawing large diagrams and describing complex cases, it would be also useful to specify tags for shapes and connections, so some of them could be filtered on rendering.

_The approach below is very similar to the one used by https://github.com/structurizr/ when from a single definition a user is able to render different views based on a filter._

-----

For example:

```
platform_part1 {
  microservice1 // service
  microservice2 // service
  microservice1 -> microservice2 : API calls // API
}
platform_part2 {
  microservice3 // service
  microservice4 // service
  microservice3 -> microservice4 : API calls // API
}

platform_part1.microservice1 -> platform_part2.microservice3 : API calls // API
platform_part1 -> platform_part2 : Network connectivity // Network
```

Let's say that things like `// API` are tags for the entities defined on the string.

And I would like to render code like this:

```
d2 --filter-tags='service' file.d2
```

Which would give me only service composition.
The same file I would be able to render with 

```
d2 --filter-tags='service,API' file.d2
```

so API tagged connections would also be rendered, and I would get microservice connections also displayed from the same file.

or, I would run it like this:

```
d2 --filter-tags='API, Network' file.d2
```

And this would give me HLD for platform level, showing cross-part connections.

This feature combined with classes support and imports would allow big teams to support different parts of the architectural docs and to be able to get from a single repo all the info needed by all users.

**Comment by alixander** [comment]
we have a better way of doing this. it's implemented already but not documented, will get to it soon! 

my main issue with this method: you need to define everything in one and selectively hide and show. this makes the base very confusing.

D2 will allow inheritence.

```
platform_part1
platform_part2

scenarios: {
  service: {
    platform_part1: {
      microservice1
      microservice2
    }
    platform_part2: {
      microservice3
      microservice4
    }
  }
  api: {
    platform_part1: {
      microservice1 -> microservice2 : API calls
    }
    platform_part2: {
      microservice3 -> microservice4 : API calls
    }

    platform_part1.microservice1 -> platform_part2.microservice3 : API calls // API
  }
}
```

and if I run `d2 example.d2 example.pdf`, I get: (excuse the shitty resolution, temporary thing)

[example.pdf](https://github.com/terrastruct/d2/files/10842812/example.pdf)

**Comment by iAdanos** [comment]
Is the example above the target solution you have on your mind?

I would say that the thing you posted is almost the same thing as describing multiple diagrams separately.

And the thing I am talking about (the way structurizr does it) allows you to describe a single big diagram (which will be much prettier if you will implement imports / includes) and display only needed things.

Maybe, a better way would be to implement a construct similar to structurizr's views. 

To get an idea on what I do mean, you can take a look on https://github.com/structurizr/examples/blob/main/dsl/microservices/workspace.dsl#L108

**Comment by iAdanos** [comment]
I think the issue is related to https://github.com/terrastruct/d2/issues/711

**Comment by alixander** [comment]
>  and display only needed things.

but this "and display" part means "and create separate diagrams" right?

**Comment by iAdanos** [comment]
Possibly, or to create a diagram only with corresponding data.

So, there can be two different behaviors:
1. Some variation of views description as in [structurizr DSL](https://github.com/structurizr/examples/blob/main/dsl/microservices/workspace.dsl#L108), so a user will be able to describe (almost "select") data for different views.
2. The way described in this thread initially. It is the same idea as in https://github.com/terrastruct/d2/issues/711, so [last message](https://github.com/terrastruct/d2/issues/711#issuecomment-1433289786) by @kmindi also describes the same idea - when you query diagram file from CLI and get exactly one diagram. Something similar to SQL:)

**Comment by ppalka-lingaro** [comment]
will tag be visable in shape below or above icon for example ?

**Comment by alixander** [comment]
this is done with classes
