### ISSUE TITLE
todo: recreate this diagram

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#920]
just a note for self. D2 needs to be able to create diagrams as pretty as this one on Stripe's website:

<img width="827" alt="Screen Shot 2023-02-27 at 11 51 25 AM" src="https://user-images.githubusercontent.com/3120367/221668401-62646303-3cae-4ad4-b97d-3f9b7da419eb.png">

**Comment by alixander** [comment]
@katwangy anything you can see that we need for D2 aesthetics to get here?

**Comment by katwangy** [comment]
from a glance:

- increase border-radius values (right now only goes to 20) so the rectangles can be a "pill shape"
- increase padding of labels on connections (our's is so close it pretty much looks like it touches the text)
- they have a gap between the arrowhead and the shape altho I'm not sure I like that actually
- allow svg icons to be colored to match the text (like "customers"). icon fonts?
- softer drop shadows. our's is pretty harsh. don't think we need to make it complicated to the point where users have to specify X, Y, blur, spread, and opacity, but maybe we have varying intensity options set on a slider.
- I like that their text changes color with the light colored background (like the yellow orange and pink shapes). we can kiiiiind of achieve this by putting text at #000000 with 0.8 opacity and setting a color burn effect on it so the text will adjust itself based on the BG color. but, it won't work (as in, it'll work but the text won't be legible) for certain colors like yellow green and cyan (see vid).


https://user-images.githubusercontent.com/102620103/221680262-4326fd7f-53e3-4ebe-b750-ab343b7cedb1.mov

**Comment by bo-ku-ra** [comment]
i think the following 2 implementations would significantly increase the range of designs.
- we can specify connections' length. ( 0 -> max)
- 'direction:' is individually valid within the containers.

**Comment by bo-ku-ra** [comment]
> * we can specify connections' length. ( 0 -> max)

https://github.com/terrastruct/d2/issues/932#issuecomment-1448200828

**Comment by alixander** [comment]
pretty close

![d2 (33)](https://user-images.githubusercontent.com/3120367/221978247-d441606a-7193-48ba-b819-150a8fc52f46.svg)

https://play.d2lang.com/?script=xJRPbts8EMX3PMWD8wH5mqaFrcRSpUWBWhHhwJugadCNN6xCOQIq0hDlwkbTQ_QE3fSAPUJB0hatP0lRwEk3hjFDzu-9oWbqnkcodWMI-fXj-0_EK1XJgpd49RY314hlsWRiE-H4v2NS59j24n1xS4CTXVzh02qD_OpOCo6UKa7mBMhKWaC647pcasudkHt8JYDubIQGl3wjxHG1iqkUC8z0Ty3mvdywz1XOFV5iWeYpnwvIzCJJ53zbSqyPnULx8kuecnU6F2DiFpdXGqz_TWdth066tqgsab8EwbaGtes09Dq-FKksOP6_uX7R9Zusl1workzaNr55YO-2Te8FdP4DW3eTXUO7iku2Me9UsTVXkEL3KjeXHhXd22anfTrb8nvPfWQLrh7J71h1suXUxWvD7aPkCHpQcrGAqlZZRoiZm8g40vsjwuCI-jSk8YAAdsp0LJ5c-MnQxezkRfAI0NhhEUZe8_lsccN5vUNkWTaog82Kwzrequu7C2a1RKjKFXel6y2nAX4QeMl40Psm_1pQY7T7xCR-MqGjv9bjDR9gj70xDahht-aoy6Y0GdLx4dhBeBa-e2PY2-_7WZmt2XtWdt-89gmgYRweTkB4cXY-ShoCHnzqJyO7bdvb8SCeHBCbeKNz32H_1O6nov8OAAD__w%3D%3D&layout=tala&theme=1&sketch=0&

**Comment by xvrdm** [comment]
Thanks for this amazing library!

Are these play.d2lang examples accessible somewhere? When I click on the link above (or any other links in the other "Recreate this diagram" issues), I end up in an empty d2 sandbox.

**Comment by alixander** [comment]
@xvrdm they used to be, but the encoding changed due to adding new keywords (the encoding takes the keywords as a compression dictionary), so the link with previous encoding sadly doesn't work anymore.

D2 is quite near 1.0 now though and once that happens there will be full backward compat with all encoded links.

(also a dedicated site for examples is being built)

**Comment by i-am-the-slime** [comment]
Why is this closed? 
The edge labels aren't on the edges (and don't have padding, I guess), and the shadow is way off (would probably need to be some fancy `<feDropShadow>`, right?) or is there a way to do this now and there's just no image of the latest state?

**Comment by alixander** [comment]
The goal isn't to reproduce identically, but to get the same effect.

https://play.d2lang.com/?script=xJTfbtMwFMbv_RRHHdJgrKjN1pTkAolmsTr1ZmJM3PTGS5zWorEr22GNGA_BE3DDA_IIyEkbN382hNRtN9N6zvH3-77jujGTNNJMcB8kWyw1Qn9-_fwNQaa0SKmE_ge4uYZApGvCcx-OXx2jqke2B-_TGAGc7OoKbrMc2NVScAoRUVTNEUAiRQp6SY1cVMqdoHv4jgA4JdKHGhf9QMhyjYup4AuYmT-VmU8iJyvNqIK3sJYsonMOIimRqDXfjBKYsVNQVH5jEVWncw6Ex3B5ZcDmv-msmdBaNxFVSdqXQLDVKONaD52JL3kkUgqvb67ftPOGmzXliqqiXS6-PrB3umzvFUz_M9m0m-1AO8U1yYt70mRDFQhudsWKQ4-a7lyz9T6dbfmdc1_IgqpH-jtW1WwktfUqcHMUHYHS-YrxBSidJQlC5iP1i0QJW6186B1hF3s46CEApaX4Sk0tmFy44cDW-ncs1ksfHARwK2RMZV-SmGXKh6FTv75SvOC82yGSJOlVxbrioKo3dF17YEliceeDlhm10oLrfiRWQhqAOx474ajXeScvbaj2tLvMhG44wcP_9uMMHmCPnBEe44LdeEdtNsbhAI8Oxx57Z97H9wV7-_1-Vmbj7T0ru-u9dhnAXuAdzoB3cXY-DGsGHrzqJyPbX9vOjY-DyQGxoTM8dy32X-t-KvrfAAAA__8%3D&layout=tala&

<img width="592" alt="Screenshot 2024-07-02 at 1 17 17 PM" src="https://github.com/terrastruct/d2/assets/3120367/e4bfa19c-3d8a-4f9a-934b-ae6324bf0f26">
