### ISSUE TITLE
dagre container label padding with direction:right

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2#925]
https://play.d2lang.com/?script=goe5lUIRKGC48jLzUksqFUCUlUI1l4IC2B49ePhZKVhagkQzK0oqFdLyS4sgqrCoMzMBi5dkZBaVVCqUlOfDVGJRa2wEk8msKElNzUMoxaLY0AwuB45MZMVYlFvAJWu5kGkQWctVywUIAAD__w%3D%3D&

<img width="626" alt="Screen Shot 2023-02-27 at 2 28 12 PM" src="https://user-images.githubusercontent.com/85081687/221700462-e6e53f64-1b54-4010-9cd3-b8ecef31605a.png">

**Comment by bo-ku-ra** [comment]
unbeautiful..

https://play.d2lang.com/?script=goe5lUJKfnkeV15mXmpJpQKIslKo5lJQAFujBw8-KwVLS5BoZkVJpUJafmkRRBUudQoKJRmZRSWVCiXl-TCVuNVCzE1NzUMoxadYQQEcl8iKsSi3gEvWciHTILKWq5YLEAAA__8%3D&

**Comment by bo-ku-ra** [comment]
at first glance, it can be difficult to tell which "Fake title" is the title of the container.
https://play.d2lang.com/?script=dJFBCgIxDEX3OcWn3bsScXIAL-AJFCMGhxbGSKcMc3dpR7rqLD6B5CWB_5vnjEdMgTyCBrFcC2MhD9RPh-YgYxjI46OzZTzjdypYj7GXTpZhKTLcVQR3GWNyWKhz83gqXZ1NJDDc5fYWmNooG7-3AdQ8-Q91sHMdrFS0ksemXwAAAP__&


so I prefer the 1.0.6 rendering.
https://github.com/terrastruct/d2/issues/823#issuecomment-1443163885
