### ISSUE TITLE
`pattern` keyword

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#928]
dotted, lined, etc. some are more applicable to backgrounds, some to nodes. 

should work the same way it works in terrastruct:

<img width="314" alt="Screen Shot 2023-02-27 at 2 57 19 PM" src="https://user-images.githubusercontent.com/3120367/221707379-3c3949ad-b671-47ed-bb32-7ea989c4b8f2.png">

**Comment by alixander** [comment]
i'm going to call it `fill-pattern` to make it unambiguous and avoid reserving another common english word

**Comment by bo-ku-ra** [comment]
https://rhodiapads.com/brand.php
Rhodia Pad Rulings : Blank / Graph / Dot Grid / Lined  ( / Lined w/margin)
