### ISSUE TITLE
"person shape" aspect ratio too wide, shape too large.

### ISSUE THREAD

**Issue by katwangy** [terrastruct/d2#932]
<img width="912" alt="Screen Shot 2023-02-27 at 6 55 42 PM" src="https://user-images.githubusercontent.com/102620103/221741839-939cb0e7-3901-46c7-87bc-53d4a94e22b1.png">

the head of the person shape should be a perfect circle for it to look "right" and we should lock that aspect ratio. it's currently super wide to fit the text inside but we can put the text on the bottom of the person shape.

**Comment by bo-ku-ra** [comment]
https://play.d2lang.com/?l=&script=VJJLCsIwEED3c4pH95WoKDLFw9gQtFhSaboQSi7gCdx5RY8gSSHYWc3i8eZ7CXRBmQWe_6HMeRLl4cYw-ChRpoHWLaxVqu_n_aoKZrvR9q4hW5WTacgdbsrmlf0xCrRKtaqVJBld_YayMw3LuVJuint7MMljqesk887e6Z2_TjfOGInyCwAA__8%3D&
