### ISSUE TITLE
left margin not needed(svg file)

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#945]
0. download
https://user-images.githubusercontent.com/121328398/222019129-ddd51c66-91c5-4a60-b28c-42a8ff01c98c.svg

1.please open ```222019129-ddd51c66-91c5-4a60-b28c-42a8ff01c98c.svg``` (outputed by v0.2.2) on browser.
2.text is too small.
3.zoom(500%) by browser
4.left margin not needed!

**Comment by gavin-ts** [comment]
right this is the issue where zooming is better if we keep it on the top left instead of center @alixander
see https://github.com/terrastruct/d2/commit/b43e2a44

can we adjust this value separately for the docs?

**Comment by alixander** [comment]
yeah we debated this. the left margin is not needed indeed, but i think it's nicer. this is a very odd example that normal usage wouldn't result in. i maintain it's nicer to be horizontally centered.

but i will leave this open, and if there's others who feel the same way, we can reconsider

**Comment by bo-ku-ra** [comment]
i am using v0.2.1 now. (downgrade version)
i hope to fix the zoom issues soon. (v0.2.2b?)

**Comment by gavin-ts** [comment]
I think it is mainly when zooming in where having it in the top left makes more sense. The zoom logic also zooms the padding which is the issue. Without zooming, anchoring in top left is also pretty standard, but centering makes sense too.

**Comment by bo-ku-ra** [comment]
okay, but i have no options.

when i send my svg file to my colleagues, they cannot see it well.
this matter is critical for me.
i will spend with v0.2.1 as my best pertner.
so long.  :_( 😢😢😢😢😢

**Comment by gavin-ts** [comment]
@bo-ku-ra if you really need to you can change `preserveAspectRatio="xMidYMid meet"` to `preserveAspectRatio="xMinYMin meet"` on the outer svg if you open it in a text editor.

Maybe we can add a flag or config for this, what do you think @nhooyr?

**Comment by bo-ku-ra** [comment]
long time no see :-p

style{
fill:pink;
```align:center; #default: xMidYMid ```
}

style{
fill:pink;
```align:left; #my proposal : xMinYMin ```
}

**Comment by gavin-ts** [comment]
> style{ fill:pink; `align:center; #default: xMidYMid ` }
> 
> style{ fill:pink; `align:left; #my proposal : xMinYMin ` }

oh interesting, are you suggesting having this as an `align` keyword at the root level in d2 text?
I was thinking it would make more sense as a command line flag or env var e.g. `TL=1 d2 in.d2 out.svg` or `d2 --no-center in.d2 out.svg`

**Comment by bo-ku-ra** [comment]
> oh interesting, are you suggesting having this as an `align` keyword at the root level in d2 text?

rectangles to be filled with "style.fill" are targeted

**Comment by bo-ku-ra** [comment]
> I was thinking of having it as a command line flag or env var e.g. `TL=1 d2 in.d2 out.svg` or `d2 --no-center in.d2 out.svg`

everything is OK.
it is important that I have a choice.

**Comment by pangloss** [comment]
@alixander asked me to chime in here, I think based on the screenshot I posted in #952. 

I think being left aligned is generally better because when you zoom in browser with large documents, the browser seems to shift everything right proportional to the left margin of the document. Diagrams with a large margin might be bumped right out of the display frame as you zoom further in, which would be frustrating.

**Comment by alixander** [comment]
okay that's like 3 votes for left-aligned, i'll defer, let's revert to left-aligned. thanks for the feedback @pangloss

**Comment by gavin-ts** [comment]
With fitting to top left as default, we can add a flag/env var to center (that we can use for the svg in docs or by preference). also worth noting #721 would enable remove the fitting entirely (which also puts it in top left).
