### ISSUE TITLE
use 0-1 decimal value as percentages for border-radius

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#947]
border-radius people may want either percentage (namely, 50% for the "pill" shape), or a px value. 

https://github.com/terrastruct/d2/pull/913#discussion_r1121144213

**Comment by Poivey** [comment]
Hello, I would like to start contributing and this issue looks like a good first step. Would you mind assigning the issue to me?

To make sure I understand, [0,1[ values would be considered a percentage value, and [1, infinity] a pixel value ? Do we need to accept value like `50%` also ?

**Comment by alixander** [comment]
closed per discussion in https://github.com/terrastruct/d2/pull/1006
