### ISSUE TITLE
Diagrams may no longer be zoomed in/out in browser

### ISSUE THREAD

**Issue by pangloss** [terrastruct/d2#952]
Hi there,

I use D2 to analyze some moderately large networks, sometimes with 2k nodes or more. Prior to the latest update it worked very well, but now that it's locked to 100% zoom, even 100 node diagrams are hard to read, and larger diagrams are rendered illegibly small.

A few versions ago, diagrams were not scaled to the viewport size. That was by far the best configuration for my purposes, but at least prior to v0.2.2, I could zoom my browser in and out of diagrams and was able to get things the scale I needed. In the latest version that is no longer possible. 

Could you please provide a way to specify fixed scaling of diagrams? This is the solution I'd prefer, but if there is a reason that's not possible, not locking the browser to a fixed zoom level would work for me. 

The diagrams that I get from the system are sometimes very large like the one I've included below. The bigger ones like this one sometimes take 2-3 minutes to render, but that's no problem because they can be extremely useful and are worth waiting for!

Thanks for a super useful tool!
Darrick

<img width="411" alt="image" src="https://user-images.githubusercontent.com/10115/222296395-ce7ea6b7-b9cf-43c7-adfb-c132afcc7faf.png">

**Comment by alixander** [comment]
hey @pangloss sorry about that. it's a regression that's in the next release (aim to be tmr or friday latest): https://github.com/terrastruct/d2/blob/master/ci/release/changelogs/next.md#bugfixes-%EF%B8%8F

btw while we're on the subject, would you care to chime in on https://github.com/terrastruct/d2/issues/945 ? it was also something that changed recently and we just wanted to hear what other zoom-users prefer

**Comment by alixander** [comment]
this should be fixed in 0.2.3
