### ISSUE TITLE
Add line return to avoid deforming shapes

### ISSUE THREAD

**Issue by angela-aura** [terrastruct/d2#956]
Some shapes such as `circle` or `person` are made a lot bigger than they need or deformed by too long a label.
Adding automatically one or more line returns in the label text would avoid this and would avoid users needing to know the code `"\n"` to add it manually.
![d2 long labels](https://user-images.githubusercontent.com/126801929/222483289-14df12a7-ee5e-47e4-ba2b-70207acd639d.png)

This might also help with #932 in some cases.

**Comment by gavin-ts** [comment]
> i think we should just change the default label position to be bottom of person shape, and let it overflow by 30% or something. @gavin-ts wdyt?

yeah default bottom for the person shape makes sense. I don't know about overflowing though.

**Comment by alixander** [comment]
i guess the bottom portion is the most width anyway. kk no overflowing

**Comment by alixander** [comment]
i consider this done, as the main issue here was the person shape
