### ISSUE TITLE
specify rows/cols

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#983]
we should be able to specify arrangement of shapes per container, which could work no matter the layout engine.

e.g. a `rows` and `columns` keyword. we make these in a step before the main layout engines, replace it with a placeholder node of given dimensions, and then swap back in the real nodes after

<img width="788" alt="Screen Shot 2023-03-06 at 7 48 11 AM" src="https://user-images.githubusercontent.com/3120367/223160389-ba5fd6a9-9510-4c98-92a8-e4c753dd3b71.png">

> source: https://github.com/gravitational/teleport

the only thing is that it wouldn't work if something in that container was connected (unless it's TALA). we have to make it a constraint that anything using these keywords are just composed of unconnected children

**Comment by bo-ku-ra** [comment]
It's nice (https://github.com/terrastruct/d2/issues/920#issuecomment-1447150133)

ex. (v0.2.3)
- can't use "watch-mode"
   (failed to fully compile (rendering partial svg): failed to bundle local images: [b.svg a.svg])
- want (https://github.com/terrastruct/d2/issues/945#issuecomment-1449275710) for a.svg 

```
x->y
x->z

y:""{
 #x
  shape:image
  icon:a.svg
}

z:""{
 #x
  shape:image
  icon:b.svg
}

layers{
 a{
 style{
 stroke:red
 stroke-width:2
 }
 direction:down
 y->z
 }
 b{
 style{
 stroke:red
 stroke-width:2
 }
 direction:right
 y->z
 }
}
```
![image](https://user-images.githubusercontent.com/121328398/223220202-d0aa397b-4a85-43f9-aca7-913260662085.png)

**Comment by alixander** [comment]
another example of what can be done with this

<img width="600" alt="Screen Shot 2023-03-31 at 4 01 14 PM" src="https://user-images.githubusercontent.com/3120367/229247332-eb74e0ad-4c46-4352-9aa7-75463be65ac9.png">

**Comment by gavin-ts** [comment]
so it is just the inner grids here and not the outer deployment rows right? no recursive grids (at least for now) right?

**Comment by alixander** [comment]
ooo what if the children of grid containers can specify how many cols/rows they occupy. allowing for diagrams like

<img width="1277" alt="Screen Shot 2023-04-01 at 3 15 01 PM" src="https://user-images.githubusercontent.com/3120367/229316380-aed0e9e4-e619-400a-8ee0-21e0a4d48821.png">

https://twitter.com/solomonstre/status/1641938062816210944

e.g.

```
container: {
  cols: 3
  # This would take up 100% width
  hey: { cols: 3 }
  # These three would take up 33% of width
  one; two; three
}
```
