### ISSUE TITLE
err: fdopendir /Library/TeX/texbin/latexmk: not a directory

### ISSUE THREAD

**Issue by dfucci** [terrastruct/d2#991]
After installing d2 using brew and running the minimal example,  I got the following error:
`err: fdopendir /Library/TeX/texbin/latexmk: not a directory`

my PATH contains `/Library/TeX/texbin/latexmk`
I am on a Apple M1, OSX 13.2.1

**Comment by nhooyr** [comment]
If `/Library/TeX/texbin/latexmk` isn't a directory try removing it and seeing if that fixes.

**Comment by nhooyr** [comment]
Oh actually, homebrew compiles D2 on the latest version and so it could be that the latest version of Go has changed os/exec to complain if `$PATH` is screwed up in some way.

**Comment by dfucci** [comment]
Indeed, I did not realize latexmk was a file and ended up in the PATH.
Removing it from PATH fixes the issue.
