### ISSUE TITLE
Documentation: Add/Create Documentation of boards, layers, sencarios and steps

### ISSUE THREAD

**Issue by kmindi** [terrastruct/d2#998]
There appears to be support for the generation of multiple renderings from the same d2 file to allow for different views.
E.g. https://github.com/terrastruct/d2/blob/dc6e819dac224125fada7f62ec4d35e6fdabd58a/e2etests/stable_test.go#LL2253-L2302C2 

Yet I think documentation is missing on how to use this (correctly).
I especially want to find out if it would be sufficient for #711 , currently I am not sure, e.g. because it seems that edges are not handled between these layers, scenarios and steps?

**Comment by alixander** [comment]
@kmindi thank you for bumping this! I will get to this later this week, as well as some more quality of life features for it.

The gist: layers, scenarios, and steps are keywords for **inheritance**

Layers: New tree, no inheritance from previous.
Scenario: Each scenario inherits from layer. (e.g. show a different version of something)
Steps: Each step inherits from previous step. (e.g. show deltas in a multi-step process).
