### ISSUE TITLE
Feature Request: interactive should work on special objects

### ISSUE THREAD

**Issue by johannes-z** [terrastruct/d2#999]
Support `tooltip` should also work on special objects, such as `sql_table`. `link` works, but there is no visual indicator that there is a link, unless you hover over the element.

```d2
Entity: {
  tooltip: Total abstinence is easier than perfect moderation
  link: https://microsoft.com
}

SQL_Entity: {
  shape: sql_table
  
  ID: int { constraint: primary_key }

  tooltip: Total abstinence is easier than perfect moderation
  link: https://microsoft.com
}
```
![image](https://user-images.githubusercontent.com/9069888/223666723-fc3a9b33-0aab-42af-b05c-0426bffdce3d.png)

**Comment by alixander** [comment]
you must be on an old version, it works on latest: https://play.d2lang.com/?script=tJKxysJAEIT7fYp5gj_91r-FYCPah825IYu5u3i3zRHy7hIR9AXsB2b45jskN2-MlYB3mHHNLjNkqG5JU1BYhUo1LfBJEhYtowZHzDctsj9JwM6MMbkvlbsuWii55tH_Qo60EV3Op_677MWJUR9z7zLMSgABx3-GJceKjzKMpViU0vq7Nmz046XPAAAA__8%3D&

**Comment by johannes-z** [comment]
Weird, I took the screenshot from the playground as well. Well thanks anyway!
